### ISSUE TITLE
save the image jpg format not working!

### ISSUE THREAD

**Issue by daeehamid** [Intervention/image#1001]
hi
this is my code for Upload image from any format to jpg
```
$filename = Carbon::now()->timestamp;
$path = "images/".$filename;
$image = Image::make($file);
$image->save($path , 80 , 'jpg' );
```

but it's not working!!
file uploaded without extension!!
why ?

**Comment by davidmartinezfl** [comment]
I use this code with "intervention/image": "^2.5" and it's works.

```
$file = $request->file('photo');
$name = $file->getClientOriginalName();
$source = Image::make($file->getRealPath())->save($file, 60, 'jpg');
```

**Comment by tinkeshwar** [comment]
Hi, If you are looking for something like [Laravel Imager](https://github.com/tinkeshwar/laravel-image) Happy to help.
