### ISSUE TITLE
fit doesn't resize images

### ISSUE THREAD

**Issue by anadimisra** [Intervention/image#1010]
- OS: Mac OS/X 10.15.3
- PHP Version: 7.4.2
- Laravel Version: 6.11.0
- gd version: 2.2.5 (installed via home-brew )

After configuring as per the documentation, I call the fit method like so in my controller 
```
$thumbnail = Image::make(Storage::disk('public')->path('images/thumbnail-' . $name));
$thumbnail->fit(256, 192);
```
this is to generate the thumbnail, when in Check the directory `public/storage/images/` original and thumbnail have have sizes.

**Comment by mfn** [comment]
Did you also save it somewhere?

`fit` only performs the transformation, does not externally persist anything.

**Comment by anadimisra** [comment]
nope I hadn't, went by the documentation a bit too literally :-)
