### ISSUE TITLE
iOS / Orientation - if iOS edits file before uploading, it alters exif orientation

### ISSUE THREAD

**Issue by sparkwatson** [Intervention/image#1014]
I'm using Intervention to handle file uploads in Laravel.

I have a photo that has an exif orientation of 8 ([sideways](https://www.impulseadventure.com/photo/exif-orientation.html))

In my web app, if I upload an un-touched/un-resized/unedited photo then 
```
$img = Image::make($file);
$img->orientate();

```
works fine, and correctly rotates the photo.

However, if you "choose image size" to resize the photo before uploading, the exif data reports it as EXIF orientation =1, and the image shows up sideways whether you use orientate() on it or not.

This is not necessarily a bug in Intervention, I realize, but I would love to hear how others handle this iOS eccentricity.

**Comment by lukasjuhas** [comment]
I would be very much interested in this too! Thanks!

**Comment by olivervogel** [comment]
Might be related to a bug in an older iOS version. See https://github.com/Intervention/image/issues/868#issuecomment-555077334
