### ISSUE TITLE
PSR-2 Deprecated

### ISSUE THREAD

**Issue by AshotN** [Intervention/image#1015]
On top of the PSR-2 page linked in the README, it states `Deprecated - As of 2019-08-10 PSR-2 has been marked as deprecated. PSR-12 is now recommended as an alternative.`

[PSR-12](https://www.php-fig.org/psr/psr-12/)

**Comment by olivervogel** [comment]
[Version 3](https://image.intervention.io/v3/) is PSR-12 compatible.
