### ISSUE TITLE
Method to remove backups and free up memory

### ISSUE THREAD

**Issue by zZeepo** [Intervention/image#1017]
Hey guys,

in my storage process I temporarily store different `backup($name)` of the image under different names. 
Once I `reset($name)` the image, I no longer need the backup.
In the process a bunch of unnecessary backups pile up and eat up my memory.
I would love to have a `clear($name)` method, to clear old backups and free up some memory.

If you've got some time to kill, I would appreciate this function implementation :)

Have a nice day
zZeepo

**Comment by halilcakar** [comment]
Hi @zZeepo, Laravel File Facade has a delete method, 

`File::delete('your image path');`

should delete file if it exists =)

**Comment by zZeepo** [comment]
Hey @halilcakar,

I think we have a misunderstanding here. I’m not storing the backup on my disk. I’m using the `Intervention\Image\Image::backup()` method to back up the state of my Intervention image. 

I have a workflow where I have one main image which is passed to different subtasks in a row for different manipulation tasks. Each subtasks first creates a `Image::backup()`, then does it’s job and `Image:: reset()’s the image back to the original state before returning to the main task. 

During this process the subtasks create a big list of backups in the main Intervention\Image and build up memory usage. 

Because of this, I would love to have a `Image::clear()` method, which would allow me to clear existing backups stored in an image.

Cheers, 
zZeepo

**Comment by halilcakar** [comment]
Ohh, Yea sorry for that but atleast now your question has a better explanation 😃

**Comment by olivervogel** [comment]
This issue refers to version 2. I would like to point out that there is now a new major version. The `backup()` method no longer exists and is handled differently. 

See: https://github.com/Intervention/image/issues/1274#issuecomment-1898019101
