### ISSUE TITLE
Create folder on save

### ISSUE THREAD

**Issue by DrCod3r** [Intervention/image#1020]
i just want you guys to implement this feature would be soo great when i trigger save() on unexisting folder it should be automatically create it

**Comment by davidmartinezfl** [comment]
I use this code with "intervention/image": "^2.5".

```
$file = $request->file('photo');
$name = $file->getClientOriginalName();
$source = Image::make($file->getRealPath())->save($file, 60, 'jpg');
Storage::disk('ftp')->put('/directory/subdirectory/' . $name, $source);
```

With this line you can create a directory in Laravel
```Storage::disk('storage_name')->put('/directory/subdirectory/' . $name, $source);```

**Comment by olivervogel** [comment]
I can understand that automatically creating directories would be very convenient. However, I see the danger of unintentional creation of folders and that the file system becomes cluttered as a result. I prefer to create the folder structure manually.

Alternatively, packages that are specifically created for managing file systems can be used for this task.
