### ISSUE TITLE
My Image Upload saving file name/imagename to Database

### ISSUE THREAD

**Issue by naysw** [Intervention/image#1022]
Hi, 
Any one help me explain , I use as below , After I upload image , Image has saved to correct file but in the database , it saved   => "filename/image_name.jpg" , Please check me anything i make wrong

Thanks

`if (request()->hasFile('cover_image')) {
            $company->update([
                'cover_image' => request()->cover_image->store('company_cover_images', 'public'),
            ]);
            $cover_image = Image::make(public_path('storage/' . $company->cover_image))->fit(1903, 350);
            $cover_image->save();
}`

**Comment by diosby** [comment]
Have all saved files same names in the database or cannot you get a file?
Use `$request->cover_image->storeAs('images', 'my_custom_name.jpg', 'public');` to set a custom file name.
Check your config.
Use `Storage::get($company->cover_image)` or ``Storage::disk('public')->get($company->cover_image)`` to get a saved file.
