### ISSUE TITLE
Images lose their saturation in thumbnails

### ISSUE THREAD

**Issue by motosha** [Intervention/image#1029]
I have a problem and am getting stuck. The pictures are in RGB colors and in jpg format. When I upload the images the saturation in the thumbnails is reduced and I don't know what it could be. I hope you can help me!

Example:

Original Pic

![test - 4928x3075](https://user-images.githubusercontent.com/49786988/87473565-f4b5d880-c621-11ea-8044-1bb68da3d167.jpg)

thumb
![test - 640x399](https://user-images.githubusercontent.com/49786988/87473591-00090400-c622-11ea-9d7b-8a5285934764.jpg)

**Comment by motosha** [comment]
I found out that it has to do with the ICC color profiles, but still no idea how to solve that.

**Comment by nam-co** [comment]
Hi, did you ever found a solution for this? Thanks

**Comment by allaniftrue** [comment]
There is somehow a great article regarding this issue. I am experiencing the same issue with our site.

https://stackoverflow.com/questions/5773032/how-to-stop-gd2-from-washing-away-the-colors-upon-resizing-images

**Comment by nam-co** [comment]
Hi, thanks for the suggestion, what I ended up doing is uploading to cloudinary and letting them do the process

**Comment by olivervogel** [comment]
This seems to be an issue with Version 2 of Intervention Image ignoring color profiles.

Version 3 of Intervention Image [supports color profiles](https://image.intervention.io/v3/basics/colors#color-profiles). But only with the Imagick driver. Unfortunately, it is still not possible to interpret color profiles with the GD library and therefore also not with Intervention Image and the driver for this library.

See https://github.com/Intervention/image/issues/707#issuecomment-1870271306
