### ISSUE TITLE
Convert AI, EPS, PDF Files to Image?

### ISSUE THREAD

**Issue by reasecret** [Intervention/image#1032]
On Laravel, is this possible to convert vector files (Like ai, eps or pdf) to image files (jpg or png)?

**Comment by olivervogel** [comment]
Officially, Intervention Image supports a [fixed number of image formats](https://image.intervention.io/v3/introduction/formats#image-formats) that do not include the ones mentioned above. However, it is possible to read other formats with the Imagick driver. The driver uses `Imagick::readImageBlob()` and can therefore read all formats supported by the Imagick installation. Writing is limited to the official formats.
