### ISSUE TITLE
Unexpected image size with AspectRatio constraint

### ISSUE THREAD

**Issue by maxgrundnig** [Intervention/image#1036]
There are some edge cases where `Image::resize()` with the AspectRatio constraint produces unexpected image sizes.

Basically one would expect that for landscape images and a specific $width parameter, the resized image is always the same size, regardless of the value of the $height parameter (as long as `$height > ($width / $aspect_ratio)`). But sometimes this is not the case.

I have created a test script here which demonstrates this bug:
https://github.com/maxgrundnig/intervention-image-resize-aspect-ratio-bug

**Comment by olivervogel** [comment]
This issue should no longer occur in version 3.
