### ISSUE TITLE
how to append image to the bottom of the other one 

### ISSUE THREAD

**Issue by jonny77** [Intervention/image#1039]
![未标题-1](https://user-images.githubusercontent.com/1962170/91679229-4555a680-eb7a-11ea-814b-2b63833a5757.png)

as you can see , i want to put the image2 below the image1(not inside the image1) .  i tried many times ,  but failed . so  i need a demo

**Comment by BenOvermyer** [comment]
Create a new canvas that has the combined height of the two images, then insert the top image, then insert the bottom image.

```
$image1 = Image::make('image1.png');
$image2 = Image::make('image2.png');
$width = $image1->width();
$height = $image1->height() + $image2->height();
$newImage = Image::canvas($width, $height)->insert($image1, 'top')->insert($image2, 'bottom');
```

**Comment by jonny77** [comment]
thanks for your help . but i get something wrong , the result image is just a part of my image , is it a bug?? here is my demo:
public function actionCombine(){
        $top = 'https://image.eunoin.com/common/20200828/5f488642b6681.png';
        $bottom = 'https://image.eunoin.com/common/20200702/5efda269e221d.png';


        $image1 = Image::make($top);
        $image2 = Image::make($bottom);
        $width = $image1->width();
        $height = $image1->height() + $image2->height();
        $newImage = Image::canvas($width, $height)->insert($image1, 'top')->insert($image2, 'bottom');
        echo $newImage->response('png');
    }

**Comment by BenOvermyer** [comment]
The code you wrote works for me. I'm seeing the correct result.
