### ISSUE TITLE
I can not get the intact  image when using canvas,bug??

### ISSUE THREAD

**Issue by jonny77** [Intervention/image#1040]
https://image.eunoin.com/common/20200702/5efda269e221d.png
here is the long image. (witdh:594 height:2310)

```php
$imageFile = 'https://image.eunoin.com/common/20200702/5efda269e221d.png';
$ImageManager = new ImageManager(array('driver' => 'gd'));
$img = $ImageManager->canvas(594, 2420,'#ff0000');
$img->insert($imageFile);
echo $img->response('png');
```
here is the result :
![image](https://user-images.githubusercontent.com/1962170/91679610-6ec30200-eb7b-11ea-8f9b-1c027afce8cc.png)

as you can see , it is just a part of my image , where is the rest content of my image?? 
i tried another image ((witdh:594 height:500)), everything  is ok !! so  is that a bug??

**Comment by olivervogel** [comment]
The integration of the option to read data directly via URLs was a mistake. The task of this library is image manipulation. Reading data via HTTP should be done by a corresponding client. For this reason, Intervention Image Version 3 does not support reading URLs.
