### ISSUE TITLE
Get quality of image ?

### ISSUE THREAD

**Issue by neoteknic** [Intervention/image#1043]
I use this lib to transform and convert to webp if possible, but on low quality jpeg it output high quality webp, sometime heavier.

Is it possible to add a **getQuality()** method on jpeg/webp, and the ability to save to webp from jpeg with the same quality (in order to have always a lighter file) ?

**Comment by olivervogel** [comment]
I would love to integrate this but according to my research, the coding quality is sometimes but not always stored in the image. At least for Jpeg.

Unfortunately, there are also further hurdles with GD, which unfortunately does not offer any functions for reading out the quality. Imagick does have identifyImage() and getCompressionQuality(), but these do not always deliver the desired result.
