### ISSUE TITLE
How to add text in image from database

### ISSUE THREAD

**Issue by RahulMachhiC** [Intervention/image#1064]
![image](https://user-images.githubusercontent.com/64777899/101977883-d870a300-3c76-11eb-9274-c2d2135c160c.png)

like this

![153b5_512](https://user-images.githubusercontent.com/64777899/101975616-e5d06200-3c63-11eb-9869-979462d88d62.jpg)

I have added the query but its return me printed query in image

![image](https://user-images.githubusercontent.com/64777899/101977930-38ffe000-3c77-11eb-8950-681e7431cac3.png)

**Comment by Sublan** [comment]
Use Html CANVAS , u Can easily do it using ajax and canvas.If intervention is not mendatory.
