### ISSUE TITLE
Resize and Crop in same time

### ISSUE THREAD

**Issue by p3yman** [Intervention/image#107]
I want to create thumbnail from my image. for example 200 \* 300. i know crop don't resize and also resize don't crop. how should i do that?

**Comment by mindplay-dk** [comment]
This does not let me specify my own cropping coordinates, is that correct?

For that, I would have to do `crop()` then `resize()`?

My problem is, that's extremely inefficient - if I'm loading a large image, then cropping a few pixels off the edges first, then resizing, that's like 2 x memory overhead and 4 x CPU time compared with a resampling crop-operation, e.g. `imagecopyresampled()` with GD.

What I need is a single operation that resamples an area of the image.

If this is not currently possible, would you accept a PR for this?

**Comment by olivervogel** [comment]
The intention of Intervention Image is to provide a collection of simple single tasks like crop() and resize() and run them after another, if necessary.

In your case, It's always possible to access the GD resource of the image object with [getCore()](http://image.intervention.io/api/getCore) and run functions like `imagecopyresampled()` this way.

**Comment by mindplay-dk** [comment]
> The intention of Intervention Image is to provide a collection of simple single tasks like crop() and resize() and run them after another, if necessary.

Understood, but crop-and-resize is probably the most frequent operation in any CMS or media management system - basically every image we deliver has been cropped and resized.

Ideally, operations like `crop()`, `resize()` etc. should operate on a simple model (coordinates) only, e.g. defer and apply the net operation on the physical bitmap as late as possible. I know that this approach doesn't fit with your existing architecture/design at all, but at least we could address the very common crop/resize-scenario with a single optimized operation a'la `imagecopyresampled()`, so someone using this library can implement their own logical model and achieve the same thing. Currently, the framework kind of gets in the way of doing this the optimal way, the way anyone would have implemented it if they were just using GD. That's hardly ideal.

> In your case, It's always possible to access the GD resource of the image object with getCore() and run functions like imagecopyresampled() this way.

Yes, but that breaks the ability to use Imagick, which defeats the purpose of using this abstraction (besides convenience) in the first place.

So I will be implementing this as a command either way.

For the Imagick implementation of the command, I think we can use [`Imagick::transformImage()`](http://php.net/manual/en/imagick.transformimage.php), which is described as a "convenience" method, but [does appear](https://github.com/mkoppanen/imagick/blob/3acc635fe321bde7e2154f0cd01e6aa7d970bc3f/imagick_class.c#L754) to execute as a single operation internally, so this should have comparable performance characteristics with GD's `imagecopyresampled()`.

I think it makes sense to have this as a built-in command, but let me know if you really don't want a PR for this and I'll just build it as a separate package.
