### ISSUE TITLE
ImageNotWritableException

### ISSUE THREAD

**Issue by DharaBhut** [Intervention/image#108]
Hello,

I m trying to upload an image using intervention, but it gives me error 

Intervention \ Image \ Exception \ ImageNotWritableException

Here is my code 
$fileName = Input::file('logo')->getClientOriginalName();
$path = public_path().'/images/'. Auth::user()->id .'/';
$image=Image::make(Input::file('logo')->getRealPath())->save($path . $fileName);

On, line 3rd I m getting error.

Thanks.

**Comment by cyberkiko** [comment]
Hi im having the same issue, but in my case the directory is writable. 
```php 
        $parentDir = public_path() . '/pois/images/';
        $fileName = $input->getClientOriginalName();
        $saveDir = $parentDir;

        File::exists($saveDir) or File::makeDirectory($saveDir, 0777);

        if (is_writable($saveDir)) {
            $image = Image::make($input->getRealPath())
                ->save($saveDir);
        } else {
            echo "dir not writable";
        }
```

If i just do the ```$input->move($saveDir) ``` it works. Im using version 2.2.0

**Comment by cyberkiko** [comment]
Was my bad, I forgot to include the image name in the save function parameter. 
```->save($saveDir . '/' . $fileName) ``` 
Thanks anyways ;)
