### ISSUE TITLE
Why Image source not readable 

### ISSUE THREAD

**Issue by AlvinQinwen** [Intervention/image#1080]
{
    "message": "Image source not readable",
    "exception": "Intervention\\Image\\Exception\\NotReadableException",
    "file": "/var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php",
    "line": 346
    ...

}

I gave 777 access

**Comment by AlvinQinwen** [comment]
and i try use `move()` `store()` `storeAs()` methods to store image to different folders

**Comment by AlvinQinwen** [comment]
this is my code 
```php
  //压缩图片上传
    public function compressionUpload($path)
    {
        $full_path = storage_path().'/public/Image'.$path;
        dd($full_path);  ///var/www/html/storage/public/Imagepublic/Images/test.jpg
        $img = Image::make($full_path);
        //todo ....

        $img->resize(300, null, function ($constraint) {
            $constraint->aspectRatio();
        });
        //将图片保存到新的路径下
        $img->save(storage_path().'/Thumbnails/new_avatar.jpg');
        //保存后的路径，用于上传删除
        dd($img->basePath());

    }

**Comment by AlvinQinwen** [comment]
and can you tell me this path ,absolute path or relative path, or something else

**Comment by AlvinQinwen** [comment]
now i use `file_get_contents()` and use absolute path to open the image

**Comment by Denisbeder** [comment]
The same happens here. I'm using PHP 8.0.2 with Laravel 8.12. 

This exception doesn't happen when i use PHP 7.4.12

**Comment by mitmelon** [comment]
This must be a bug that should be corrected for PHP 8 because i too face same issue..

Getting... error on

Image::make(__DIR__.'/asset/logo/logo.png')->opacity(50);

Fatal error:  Uncaught Intervention\Image\Exception\NotReadableException: Image source not readable in...

**Comment by ohbuvik** [comment]
me too

**Comment by somato-tomato** [comment]
me too

**Comment by HanifullahJamalzai** [comment]
Same here, faceed with similar problem in laravel 9, any solution?
