### ISSUE TITLE
Backup() & Reset() not working

### ISSUE THREAD

**Issue by rajjanorkar** [Intervention/image#1083]
```
/ create an image
$img = Image::make('public/foo.jpg');

// backup status
$img->backup();

// reset image (return to backup state)
$img->reset();
```

throwing an error, i am using version 2.5.1

```
{message: "Backup not available. Call backup() before reset().",…}
exception: "Intervention\Image\Exception\RuntimeException"
file: "/Users/rajdeepjanorkar/Data/Websites/flymetoyou.com/vendor/intervention/image/src/Intervention/Image/Gd/Commands/ResetCommand.php"
line: 34
message: "Backup not available. Call backup() before reset()."

```

**Comment by nitrogenium** [comment]
confirmed 

It doesn't work

**Comment by nitrogenium** [comment]
See: https://php.watch/versions/8.0/gdimage

Quote: “Note that all functions in GD extension now returns and expects \GdImage objects instead of resource objects.”

**Comment by FullWebService** [comment]
Thanks @asdrubalini. I hope this gets picked up soon.

**Comment by neylsongularte** [comment]
will this be fixed?

**Comment by Ashraam** [comment]
I still have this issue.

I'm using Intervention/Image version 2.6.1 and PHP 8.0.10

**Comment by AlexDanault** [comment]
I too still have this issue.

**Comment by olivervogel** [comment]
This issue refers to version 2. I would like to point out that there is now a new major version. The `backup()` method no longer exists and is handled differently. 

See: https://github.com/Intervention/image/issues/1274#issuecomment-1898019101
