### ISSUE TITLE
Performance issue?

### ISSUE THREAD

**Issue by ProteanCode** [Intervention/image#1098]
I have created a code that should be quite good at reproducing the performance issue

```
    private static function createMultipleImages(UploadedFile &$uploadedFile, string $outputFormat='webp') {
        $filename = 'myOutputImage';
        for($i = 1; $i< 6; $i++) {
            $width = 200 * $i;
            $image = Image::make($uploadedFile->getRealPath())->encode($outputFormat);
            if($image->width() >= $width) {
                $image->resize($width, null, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
                $image->save(__DIR__.'/'.$filename.'_'.$width.'.'.$outputFormat);
            }
            $image->destroy();
            $image = null;
        }
    }
```

Didn't run it, but the concept is the same.

The input on which I do test that function is some image from unsplashd with 6000x4000 dimension and around 3MB in size;

Execution time is calculated in like half a minute, maybe more, it is just highlt noticeable and I may just do something wrong there.

Maybe the webp is the reason why, or I should compile my alpine docker image with some extra settings

![desert](https://user-images.githubusercontent.com/43477801/125213348-5307ac80-e2b2-11eb-9041-2ae7afbd3da4.jpg)

**Comment by olivervogel** [comment]
I think this is not related to this library but to the performance of GD or Imagick in general.
