### ISSUE TITLE
Instantiating image with auto-orientation throws exif_read_data error. 

### ISSUE THREAD

**Issue by cliffHarry** [Intervention/image#1112]
ERROR: E_WARNING exif_read_data(example.png): File not supported in Intervention/image/src/Intervention/Image/Commands/ExifCommand.php 

While trying to use ` $image->orientate()`; it throws `exif_read_data` error.
`
ERROR:	20210913-164246: E_WARNING exif_read_data(example.png): File not supported in intervention/image/src/Intervention/Image/Commands/ExifCommand.php `

**Comment by olivervogel** [comment]
This issue should be resolved as of version 3.
