### ISSUE TITLE
Image source not readable Intervention???

### ISSUE THREAD

**Issue by Harhukam** [Intervention/image#1115]
local.ERROR: Image source not readable {"userId":1,"exception":"[object] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Image source not readable at D:\\Development\\deal\\vendor\\intervention\\image\\src\\Intervention\\Image\\AbstractDecoder.php:351)

laravel

i was try both     'driver' => 'gd' and    'driver' => 'imagick' but not working for me.

**Comment by popovdk** [comment]
i same issue

**Comment by Harhukam** [comment]
Image source not readable Intervention solved.


 if($request->hasFile('image')){

               $image = $request->image;
                $Path = public_path('images/');
                $extension = $image->getClientOriginalExtension();
                //$fileName =  generateRandomName('8') . '.' . $extension;
                $Img = Image::make($image->getRealPath())->fit(800, 400);
               // $Img->insert(public_path('images/logo.png'), 'bottom-right',20,20);
                $Img->save($Path . '/' . $fileName, 50);
    }

I'm using image stemp on image // my logo.png is missing  , so i put  logo.png in images folder my issue now solved.
now my code 100% woork fine.
thanks to all.

**Comment by popovdk** [comment]
> $image = $request->image;
>             $Path = public_path('images/');
>             $extension = $image->getClientOriginalExtension();
>             //$fileName =  generateRandomName('8') . '.' . $extension;
>             $Img = Image::make($image->getRealPath())->fit(800, 400);
>            // $Img->insert(public_path('images/logo.png'), 'bottom-right',20,20);
>             $Img->save($Path . '/' . $fileName, 50);

use php 8?

**Comment by Harhukam** [comment]
yes


*HARHUKAM SINGH*
Founder of
*My Web Deal*
*+91 9463710716 *
*Jalpot,*
*Jalandhar, Punjab, INDIA, 144104*
*www.mywebdeal.in <http://www.mywebdeal.in/>*

**Comment by Harhukam** [comment]
laravel 8 and php 7.4


*HARHUKAM SINGH*
Founder of
*My Web Deal*
*+91 9463710716 *
*Jalpot,*
*Jalandhar, Punjab, INDIA, 144104*
*www.mywebdeal.in <http://www.mywebdeal.in/>*
