### ISSUE TITLE
Create lossless or lossy webp images? 

### ISSUE THREAD

**Issue by jcogs-design** [Intervention/image#1121]
Is this degree of control possible using Intervention/Image? 
The documentation does not make it clear which version of webp image is produced when an image is encoded with webp - does anyone know (or know how to find out?)?
It would be great if there was an option in the encode method to control which type of webp is being produced.

**Comment by jcogs-design** [comment]
As of PHP8.1 php will support lossless webp:

> In PHP 8.1, the GD extension supports lossless encoding, and declares a new PHP constant IMG_WEBP_LOSSLESS which can be passed to imagewebp function to enable lossless encoding of a GdImage object.

More [here](https://php.watch/versions/8.1/gd-webp-lossless).

**Comment by gbrock** [comment]
Looks like it doesn't do this yet, it would be in [src/Intervention/Image/Gd/Encoder.php](https://github.com/Intervention/image/blob/04be355f8d6734c826045d02a1079ad658322dad/src/Intervention/Image/Gd/Encoder.php#L77), but `$this->quality` is never set to `IMG_WEBP_LOSSLESS`.  Something's weird though, when I made that change locally I got an `Undefined constant IMG_WEBP_LOSSLESS` error, even though I'm running PHP 8.1.

**Comment by olivervogel** [comment]
I adjusted this in https://github.com/Intervention/image/commit/bc09f0d42fba594b5a88a530d86cba6a11ebfd84. Included in next release.
