### ISSUE TITLE
Encoding from existing JPG to JPG significantly increases file size

### ISSUE THREAD

**Issue by ToshY** [Intervention/image#1125]
I've just noticed that using the `encode` method increases the file size significantly if you try to encode a JPG to JPG.

Example:

```php
$image = $this->image->make($originalJpgImage);
$imageJpgEncoded = (string)$image->encode('jpg',100);
```
Results with `GD`:
* Original: 42 KB
* Encoded: 112 KB

Results with `Imagick`:
* Original: 42 KB
* Encoded: 61 KB

Setting the quality 80 gets me decently close to the original file size, but I fail to understand what is causing such an increase. Could someone elaborate on why this is happening? And is this normal behavior?

**Comment by olivervogel** [comment]
The `quality` parameter functions as an absolute value for the compression quality/image size and is not based on the existing compression/quality and is also not related to the original value.

If you encode with `100` as the quality value as shown in the example, you will always achieve the maximum possible quality value (and the associated file size), even if the input file was saved with a quality value of `0`.
