### ISSUE TITLE
getBoxSize() from \Intervention\Image\Gd\Font modifies UTF-8 Text Input

### ISSUE THREAD

**Issue by GregorVoelkl** [Intervention/image#1126]
The getBoxSize() function of \Intervention\Image\Gd\Font has the following behaviour which seems to be unwanted.

Problem:

        $text = 'Jörg';

        $font = new \Intervention\Image\Gd\Font($text);
        $font->file(public_path('fonts/montserrat-v14-latin-700.ttf'));
        $font->valign('top');
        $box = $font->getBoxSize();

        dump($font->getText());  // internal text is: J&#246;rg

        // getBoxSize() is called in applyToImage()
        // J&#246;rg is written on the image
        $font->applyToImage($this->stage, 200, 200);

        dump($font->getText()); // internal text is: J&#38;#246;rg

Inside getBoxSize()

            $this->text = mb_encode_numericentity($this->text, array(0x0080, 0xffff, 0, 0xffff), 'UTF-8');

is called, which modifies Codepoints above 0x0080 to decimal unicode representation.

My suggestion would be either to document this behaviour or to restore the original text input.

**Comment by wisp-x** [comment]
Same question.

**Comment by olivervogel** [comment]
This issue should be resolved as of version 3.
