### ISSUE TITLE
GIF animation not playing?

### ISSUE THREAD

**Issue by CyferZ** [Intervention/image#1139]
Hi there,

Just wanna say this library is fantastic, and good work!

The issue I am having is as follows: The user is able to upload any image they like. Upon uploading, I store it, run the make function, resize the image and use a callback function within it, and save like below:

```
$imagePath = $img->store('/' . $category, 'projects');

                    $image = Image::make("storage/projects/{$imagePath}")
                                    ->resize(null, 720, function ($constraint) {
                                        $constraint->aspectRatio();
                                        $constraint->upsize();
                                    });
                    $image->save();
```

Unfortunately, when it comes to GIFs, once it has been uploaded, it no longer plays the animation. Would the resizing be causing this by any chance? I am at a loss, but I am adding resizing to reduce the size of the image once stored on the server to enable quicker rendering on the site.

**Comment by jiang8la** [comment]
me too, who can tell me who to solve the problem

**Comment by cyaxaress** [comment]
same issue

**Comment by CodyPChristian** [comment]
Same issue here as well v2.7.2 on php8.1 and using GD driver

**Comment by maverickchangithub** [comment]
Here is a hack , but not guaranteed:
 - under  vender folder, find the file `Intervention/Image/src/Intervention/Image/Imagick/Decode.php
 - comment this line `$object = $this->removeAnimation($object); `
 - you must use `Imagick` as driver


```
public function initFromImagick(\Imagick $object)
    {
        // currently animations are not supported
        // so all images are turned into static
        // $object = $this->removeAnimation($object);  //comment this line

        // reset image orientation
        $object->setImageOrientation(\Imagick::ORIENTATION_UNDEFINED);

        return new Image(new Driver, $object);
    }
```

I tested, it works.

**Comment by olivervogel** [comment]
Support for animated images are now available in [version 3](https://image.intervention.io/v3/).
