### ISSUE TITLE
Why not set the quality of other formats like WebP in converting process?

### ISSUE THREAD

**Issue by gitgetgotgotten** [Intervention/image#1140]
I want to convert jpg to webp and set the quality to 50 (as an example). But the Image Intervention only supports the quality parameter only for jpg files. Is there any workaround?

**Comment by jcogs-design** [comment]
I have not checked the code for the Imagemagick driver, but the GD driver **does** include the quality parameter when saving webp images... here is the code - the GD driver uses the imagewebp method to do the save (from src/Intervention/Image/Gd/Encoder.php).

HTH

```
    protected function processWebp()
    {
        if ( ! function_exists('imagewebp')) {
            throw new NotSupportedException(
                "Webp format is not supported by PHP installation."
            );
        }

        ob_start();
        imagepalettetotruecolor($this->image->getCore());
        imagealphablending($this->image->getCore(), true);
        imagesavealpha($this->image->getCore(), true);
        imagewebp($this->image->getCore(), null, $this->quality);
        $this->image->mime = defined('IMAGETYPE_WEBP') ? image_type_to_mime_type(IMAGETYPE_WEBP) : 'image/webp';
        $buffer = ob_get_contents();
        ob_end_clean();
        
        return $buffer;
    }
```

**Comment by olivervogel** [comment]
The parameter for Webp quality is definitely available in version 3.
