### ISSUE TITLE
Offer option to set PNG compression level

### ISSUE THREAD

**Issue by jcogs-design** [Intervention/image#1142]
It appears that Intervention saves PNGs using the default level of compression (-1) when working with GD library and the JPEG default compression level when using Imagemagick.

It would be good if this value could be controlled through the library in V3 - for example allowing the choice of maximum compression (to reduce size of files produced).

**Comment by olivervogel** [comment]
After consideration and examination I do not consider the benefit of an adjustable compression level to be too great compared to the default setting.

See https://github.com/Intervention/image/issues/1243#issuecomment-1870438010
