### ISSUE TITLE
Website redirects users with Russian IPs to amnesty.org

### ISSUE THREAD

**Issue by VKolegov** [Intervention/image#1155]
Why would you deny access to documentation based on user's ip/location?

It's not even that important that this site is obviously biased and publishes unverified or refuted statements, passing them off as facts, but actually just promoting hatred towards Russian people.

What is important is that you engage in political propaganda, effectively refusing to provide services to a group of people based solely on nationality.

What are you trying to achieve?
Even you are sympathetic to Ukrainian civilians, just like me, it does not justify whole county ban.

I am both angry and disappointed.

P.S. And don't tell me this isn't the place for political discussions, it's you who decided to dive into that.

**Comment by SerafimArts** [comment]
I am grateful to the authors of this package for their contribution to the community, but I agree with the theses of @VKolegov and propose to abandon Racism... Racism on your part looks lousy. =\
