### ISSUE TITLE
uploading png image is increasing it's size than the original

### ISSUE THREAD

**Issue by Kiransai-webonise** [Intervention/image#1158]
$image = Image::make($img->path());
$image->save($img_name, 70);

Above piece of code is working fine for jpg images but when i upload png image its size is increasing. Am I doing anything wrong or it is an issue?

**Comment by basemkhirat** [comment]
same issue
version: 2.7.2

**Comment by olivervogel** [comment]
Duplicate of https://github.com/Intervention/image/issues/632
