### ISSUE TITLE
NotReadableException in PHP8 and v2.5.1

### ISSUE THREAD

**Issue by umpirsky** [Intervention/image#1159]
```
Intervention\Image\Exception\NotReadableException Image source not readable
```

This is what you can get on `v2.5.1` with PHP8. In `v2.7.2` the error is fixed, but if `v2.5.1` is not compatible with PHP8, composer requirement should prevent installing it.

**Comment by harish-successive** [comment]
I am getting the same error even with `PHP8` & `v2.7.2`
