### ISSUE TITLE
Implicit conversion from float 359.99 to int loses precision

### ISSUE THREAD

**Issue by Pilskalns** [Intervention/image#1178]
Hi,

I don't use this package directly, but I noticed a lot of warning messages in logs while developing a Laravel application and went down a rabbit hole I shouldn't..... The full warning message I get:
```
Implicit conversion from float 359.99 to int loses precision in
/var/www/html/vendor/intervention/image/src/Intervention/Image/Gd/Shapes/EllipseShape.php on line 58
```
[This is caused](https://github.com/Intervention/image/blob/032263954ca2a5258fb5fe7492962c1a16ca9f3c/src/Intervention/Image/Gd/Shapes/EllipseShape.php#L58) by calling PHP's `imagearc` function with `end_angle` parameter of hardcoded **float** `359.99`.
According to the [documentation](https://www.php.net/manual/en/function.imagearc.php), all parameters are **integer** type - hence the type casting on every single execution causes precision to be dropped to a round `359`.

I cannot figure out why full `360` was not used as a full circle angle, but [given it was written 8 years ago](https://github.com/Intervention/image/blame/032263954ca2a5258fb5fe7492962c1a16ca9f3c/src/Intervention/Image/Gd/Shapes/EllipseShape.php#L58), it might have been a workaround for another upstream issue or the spec might have changed over the years.

I see three ways to calm down the warning messages and set the hardcoded `end_angle` to one of:
* `360` - this works ok
* `(int) 359.99` - keep the original idea, but pre-cast to an integer
* `359` - an integer it would end up with anyway

Unfortunately, I don't have a proper setup for testing this, so I shamelessly edited `end_angle` in the vendor dir and checked my app to observe the changes.

![image](https://user-images.githubusercontent.com/6931156/178140617-74c048e6-a02e-45c0-a598-73b4008e949c.png)

My environment:
* WSL2, Ubuntu 22.04
* PHP 8.1.6
* Laravel 9.19.0

**Comment by snapey** [comment]
Same issue here. PHP 8.1.8

**Comment by leandro-lifepet** [comment]
There is another issue at:
`src/Intervention/Image/Gd/Font.php` +210

Just change from:

`imagettftext($image->getCore(), $this->getPointSize(), $this->angle, $posx, $posy, $color->getInt(), $this->file, $this->text);` 

to

imagettftext($image->getCore(), $this->getPointSize(), $this->angle, intval($posx), intval($posy), $color->getInt(), $this->file, $this->text);

**Comment by lehnen** [comment]
Thanks for this package.
The needed change seems to be so simple. So please be kind and update.

**Comment by olivervogel** [comment]
Please use [Version 3](https://image.intervention.io/v3) of Intervention Image.
