### ISSUE TITLE
Deprecation warning under php8.1 / Intervention/image 2.7.2

### ISSUE THREAD

**Issue by passchn** [Intervention/image#1180]
Hello!

I'm getting the following deprecation notice running `php 8.1` and `intervention/image 2.7.2`:

````
**Deprecated:** strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /.../vendor/intervention/image/src/Intervention/Image/Size.php on line 281
````

I'm using the `widen()` method in a `FilterInverface`.

**Comment by passchn** [comment]
I looked more into this and have another problem with the insert() method. Here, `$position` is annotated as having `"top-left"` as the default value. However, this is not passed through, as all methods are called by the magic `__call()` method in `Image.php`.

The deprecation notice comes in `Size::align()`, where `$position` is now `null` and not the expected default value. And `null` is passed to `strtolower()`. 

It would be great to handle this by e.g. casting the variables to strings: `strtolower((string) $position)`. 

A user-side fix is to pass the default string to the `Image::insert()` method - or any method with similar issues. But then your IDE will tell you that this is obsolete - but it is not! 

![depracation-fix](https://user-images.githubusercontent.com/77938819/229202269-9dc78250-42a9-4b4b-8bf9-d6f00eef75ad.png)

Also, as it is only a deprecation, the error is hard to track down. You have to either have xDebug set up or to modify the file in the vendor directory and debug the backtrace to know where you are coming from.

**Comment by olivervogel** [comment]
Please use [Version 3](https://image.intervention.io/v3) of Intervention Image.
