### ISSUE TITLE
Site is down. Where else can I see the documentation?

### ISSUE THREAD

**Issue by deniro21** [Intervention/image#1182]
Hello. Site with docs intervention.io has HTTP ERROR 451... At least I've been seeing this error for the last three days. Where else can I see the documentation?

**Comment by rez1dent3** [comment]
@deniro21 apparently, the site is closed for Russian IP. Go through VPN, the site will open.

**Comment by deniro21** [comment]
> @deniro21 apparently, the site is closed for Russian IP. Go through VPN, the site will open.
Спасибо. Открылся через VPN, как-то сразу не подумал об этом. А почему его закрыли от российских айпишников?

**Comment by deniro21** [comment]
Спасибо. Открылся через VPN, как-то сразу не подумал об этом. А почему его закрыли от российских айпишников?
