### ISSUE TITLE
Upload pictures that do not support GIF format?

### ISSUE THREAD

**Issue by siyecoo** [Intervention/image#1183]
The uploaded GIF image is converted into a static image
Is this normal? No solution?

version: "intervention/image": "^2.5"

**Comment by sumonst21** [comment]
try: [imagecreatefromgif ](https://www.php.net/manual/en/function.imagecopyresized.php)

**Comment by olivervogel** [comment]
Animated GIF are not supported by 2.x. Try using Version 3.
