### ISSUE TITLE
Deprecation warning Intervention/Image/Gd/Shapes/PolygonShape.php

### ISSUE THREAD

**Issue by ghost** [Intervention/image#1188]
I updated PHP to version 8.1.12 and now i get a deprecation warning.
Im using version 2.7.2 of the library
![image](https://user-images.githubusercontent.com/106733770/199793204-067cdf4c-cfbd-45cc-b75d-214dad0c8fb2.png)

Code
`$mask->polygon( $polygon, function( PolygonShape $draw ) {
                    $draw->background( '#000000' );
                } );`

**Comment by olivervogel** [comment]
Please use [Version 3](https://image.intervention.io/v3) of Intervention Image.
