### ISSUE TITLE
Is this library still maintaned?

### ISSUE THREAD

**Issue by seebeen** [Intervention/image#1193]
Is this library still maintained?

If not, can you delegate to another maintainer which will merge PRs and work on the development.

**Comment by ankurk91** [comment]
Looks like no, i have been searching for alternatives as well.

Php 8.2 is around the corner but this library still stuck on php 7.4

**Comment by hawkiq** [comment]
Feels the same I've been using this package for a long time,  now am trying to used to Spatie media library it's advanced from this but you can have more options not only for image but as file system too.
You can try Glide image from Spatie too its simple just like intervention. But personally I still prefer intervention its so easy to manipulate images .hope someone maintain package instead.

**Comment by stefket** [comment]
@hawkiq FYI: Glide is using Intervention Image.

**Comment by olivervogel** [comment]
[Version 3](https://image.intervention.io/v3) has just been released.
