### ISSUE TITLE
Compatibility issue with Symfony\Component\HttpFoundation\Response

### ISSUE THREAD

**Issue by marcusig** [Intervention/image#1199]
Hi there,

Thank you for this tool! It's been very useful. :)

For context, I use this in a WordPress plugin.

I have just encountered an issue when using the `response()` method, when Symfony\Component\HttpFoundation\Response is also loaded (by an other plugin).

When that class is loaded, `Intervention\Image\Response::make()` [will use it to](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Response.php#L63) send the image data. 

As a result, the image is broken in the browser:

![image](https://user-images.githubusercontent.com/11990914/213642406-848a0f50-b45b-4f98-b4b9-bce521fc1a71.png)

I haven't been able to find what the issue actually is, only that it happens with the Symfony Response option.
It works fine when the fallback option is used. 

Marc

**Comment by marcusig** [comment]
Salut Marc,

I managed to find a workaround by editing [Response.php](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Response.php#L63)
It's far from ideal, as this won't work if the library is loaded by another plugin. 

This is the context: https://github.com/marcusig/woocommerce-product-customizer/blob/master/src/inc/images.php

Basically when [this code](https://github.com/Intervention/image/blob/54934ae8ea3661fd189437df90fb09ec3b679c74/src/Intervention/Image/Response.php#L63) is executed, the issue happens:

```
$response = new SymfonyResponse($data);
$response->headers->set('Content-Type', $mime);
$response->headers->set('Content-Length', $length);
```

**Comment by MarcBrillault** [comment]
Is there a way to test your project without having to install woocommerce ?

**Comment by olivervogel** [comment]
The integration of the option to build HTTP responses was a mistake. The task of this library is image manipulation. Handling HTTP request or responses should be done by a dedicated library. For this reason, Intervention Image Version 3 no longer support `response()`.
