### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Onepamopa** [Intervention/image#1208]
ERROR: Allowed memory size of 536870912 bytes exhausted (tried to allocate 53248 bytes) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 536870912 bytes exhausted (tried to allocate 53248 bytes) at /home/...redacted.../public_html/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:33)
[stacktrace]
#0 {main}
"}

The line in question is $core = @imagecreatefrompng($path);

**Comment by olivervogel** [comment]
Seems to be related with the setting of PHP's [memory limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit).
