### ISSUE TITLE
Using resize() and getSize() to get image dimensions without computing the resulting image

### ISSUE THREAD

**Issue by marios88** [Intervention/image#1227]
Hello, in my use case i want to know the resulting image dimensions without generating them ahead of time.

I believe "getSize()" should be documented as an API function as its provides valuable information

Here is a example for anyone interested in calculating output dimensions without actually resizing the image

```php
ImageManagerStatic::configure(['driver' => 'imagick']);
$img = ImageManagerStatic::make('path');
$sizes = $img->getSize()->resize(1000,1000, function ($constraint) {
    $constraint->aspectRatio();
    $constraint->upsize();
});

// Even faster without parsing the image if you know original's w,h
$sizes = ImageManagerStatic::canvas($w,$h)->getSize()->resize($maxW,$maxH, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
```

**Comment by olivervogel** [comment]
You can use `Intervention\Image\Geometry\Tools\RectangleResizer::class` to calculate size without actual images. You have to use version 3 of Intervention Image though.

```php
$targetWidth = 60;
$targetHeight = 60;

$size = new Rectangle(300, 200);
$resized = $size->scaleDown($targetWidth, $targetHeight); // result: 60 x 40
```

See [`Rectangle::class`](https://github.com/Intervention/image/blob/develop/src/Geometry/Rectangle.php)
and [`RectangleResizer::class`](https://github.com/Intervention/image/blob/develop/src/Geometry/Tools/RectangleResizer.php)
