### ISSUE TITLE
Unsupported image type image/avif. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.

### ISSUE THREAD

**Issue by stealeks** [Intervention/image#1229]
Unsupported image type image/avif. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.

However AVIF is supported by GD

**Comment by stealeks** [comment]
https://github.com/Intervention/image/pull/1228
https://github.com/Intervention/image/pull/1217

**Comment by Darkethic06** [comment]
Assign, Please
