### ISSUE TITLE
Unsupported image type image/heic. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.

### ISSUE THREAD

**Issue by Darkethic06** [Intervention/image#1230]
Unsupported image type image/heic. GD driver is only able to decode JPG, PNG, GIF, BMP, or WebP files.

**Comment by olivervogel** [comment]
Of course it is possible to help out. However, please only add new features to the `main` branch on version 3. Intervention Image version 2 will not be further developed by me.

**Comment by Darkethic06** [comment]
> Of course it is possible to help out. However, please only add new features to the `main` branch on version 3. Intervention Image version 2 will not be further developed by me.

Working

**Comment by Darkethic06** [comment]
No need to add a new Function to handle image/heic.

`
if ($file->getClientOriginalExtension() == 'heic') {
$file = $request->file('image')
 $manager = new ImageManager(Driver::class);
 $image = $manager->read($file);
 $filename =  uniqid() . time() . rand(10, 1000000) . '.jpg';
 $image->toJpeg()->save('storage/images/'.$filename);
}
 ` 

The Image will be saved in JPG format.
