### ISSUE TITLE
flip() not working without toJpeg()

### ISSUE THREAD

**Issue by sh4msi** [Intervention/image#1235]
Hi,

When I use the ->flip() method, no changes are made to the image. However, when I use ->flip() together with ->toJpeg()->save($imagePath), the flip is applied.

Why does ->flip() not work without ->toJpeg()?

**Comment by olivervogel** [comment]
Can't reproduce. How do you check the result without `toJpeg()`.

**Comment by sh4msi** [comment]
> Can't reproduce. How do you check the result without `toJpeg()`?

I directly check the original file

--------

My code without ```toJpeg()```

```
        $manager = ImageManager::gd();
        $image = $manager->read($imagePath);
        $image->flop();
```

**Comment by olivervogel** [comment]
You have to write the original file, to see the changes.

**Comment by sh4msi** [comment]
When I use ```$image->save($image Path)``` , I get an error and I did not find a method to write in the documents.

**Comment by sh4msi** [comment]
How should I do this?
I use version 3

**Comment by olivervogel** [comment]
You only can call `save()` on encoded images. It's all in the [docs](https://image.intervention.io/v3/basics/image-output).

**Comment by sh4msi** [comment]
Unfortunately
I still haven't figured out how to access the encoding without using toJpeg() (or similar) so that I can save without calling toJpeg()

I did not find a code example that directly calls the save method

**Comment by olivervogel** [comment]
Maybe you are looking for this feature. https://github.com/Intervention/image/issues/1237
