### ISSUE TITLE
Scaling image to several sizes doesn't work

### ISSUE THREAD

**Issue by aimeos** [Intervention/image#1236]
Example:
```php
[
    (clone $image)->pad( 320, 240 ),
    (clone $image)->pad( 640, 480 ),
    (clone $image)->pad( 960, 720 ),
]
```
All images will be 320x240 and padded to the given size instead of each image is scaled/padded individually. Seems like the nested image object from the driver isn't cloned in a `__clone()` method

**Comment by olivervogel** [comment]
Image objects are unfortunately not yet clonable. See #1233
