### ISSUE TITLE
Re-add encode() method

### ISSUE THREAD

**Issue by aimeos** [Intervention/image#1237]
The `encode()` method in 2.x was a handy way to encode images according to configuration (not hard-coded). Now it must be:
```
switch( $type ) {
    case 'image/jpeg': $img = $image->jpeg(); break;
    case 'image/gif': $img = $image->gif(); break;
    case 'image/png': $img = $image->png(); break;
    case 'image/webp': $img = $image->webp(); break;
}
```

 It would be a good idea to add the method in 3.x again but use different methods to set the quality/number of colors depending for the output format.

**Comment by olivervogel** [comment]
Yes, I agree.

**Comment by misaert** [comment]
Hi,

I agree too and I think it misses the type guessing of an `Image` like before:
```php
        $image = $this->imageManager->make($input);
        $extension = match ($image->mime) {
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
            'image/gif' => 'gif',
            'image/png' => 'png',
            default => throw new RuntimeException('Invalid mime type.'),
        };
        $data = $image->encode($extension);
```

Thanks,

Mickaël

**Comment by olivervogel** [comment]
> I agree too and I think it misses the type guessing of an `Image` like before:

Not only the media type but ideally also the type and quality of compression, the number of colors and perhaps other things.

**Comment by aimeos** [comment]
But quality and number of colors should be set by their own methods if possible because they depend on the output format, e.g.:
```php
$image->quality( 75 );
// or
$image->maxcolors( 255 );
$encoded = $image->encode( 'image/jpeg' );
$encoded->save('path/to/file');
```

The `encode()` method can also accept mime types and file extension names:
```php
public function encode( $mime ) : EncodedImage
{
        $mime = match ($mime) {
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
            'image/gif' => 'gif',
            'image/png' => 'png',
            default => $mime,
        };
        return $this->driver->encode($this, $mime);
}
```

**Comment by olivervogel** [comment]
The `encode()` method was reintroduced in version `3.1`. See [documentaion](https://image.intervention.io/v3/basics/image-output#general-encoding).

**Comment by aimeos** [comment]
@olivervogel As long as there's no method available which maps (mime) types to the class names, the new `encode()` method has no value.

**Comment by olivervogel** [comment]
> @olivervogel As long as there's no method available which maps (mime) types to the class names, the new `encode()` method has no value.

Explain this in more detail.

**Comment by aimeos** [comment]
In an application, the output format is either configured or selected by the user. In both cases, the format is always a string and to be most portable, it's most often the mime type that is used. Using an intervention class name would tie the application exclusively to the library and changing the image processing library later would be a bigger issue.

Thus, we have the (mime) type as input and the intervention class name as required parameter. If the library doesn't provide a method to do the mapping, the application code still needs to implement:
```php
switch( $type ) {
    case 'image/jpeg': $img = $image->encode(JpegEncoder::class); break;
    case 'image/gif': $img = $image->encode(GifEncoder::class); break;
    case 'image/png': $img = $image->encode(PngEncoder::class); break;
    case 'image/webp': $img = $image->encode(WebpEncoder::class); break;
}
```
So there's no value to use `encode()` over:
```php
switch( $type ) {
    case 'image/jpeg': $img = $image->jpeg(); break;
    case 'image/gif': $img = $image->gif(); break;
    case 'image/png': $img = $image->png(); break;
    case 'image/webp': $img = $image->webp(); break;
}
```

**Comment by olivervogel** [comment]
As of version `3.2` you can use [encodeByMediaType()](https://image.intervention.io/v3/basics/image-output#encode-image-by-media-mime-type) in your example code.
