### ISSUE TITLE
upgrading from 2.7.2 to 3.0.1 causes  Class "Intervention\Image\ImageServiceProvider" not found

### ISSUE THREAD

**Issue by rebbieboi** [Intervention/image#1238]
**Describe the bug**
When upgrading from 2.7.2 to 3.0.1 composer will show  Class "Intervention\Image\ImageServiceProvider" not found error and the whole system will break.

**Code Example**
composer update

**Expected behavior**
should pass composer and work

**Images**
n/a

**Environment (please complete the following information):**
 - PHP Version: 8.1.23
 - OS: 20.04.6 LTS
 - Intervention Image Version:
 - GD or Imagick:

**Comment by olivervogel** [comment]
Version 3 no longer contains a ServiceProvider for Laravel. I didn't like the close connection to the framework and decided to take a more agnostic approach with the major update.

Alternatives are to create your own provider or to do without it altogether.

See: https://image.intervention.io/v3/introduction/upgrade#other-changes
