### ISSUE TITLE
possible not require define format to output

### ISSUE THREAD

**Issue by SnowRunescape** [Intervention/image#1241]
**Describe the bug**
There is no method to save without having to enter an output format, for example `$image->toGif()->save($file->getRealPath());`
it would be interesting to just do `$image->save($file->getRealPath());` the same existed in version 2.x

**Code Example On 2.x**
```php
Image::make($file->getRealPath())->resize($width, $height, function ($constraint) {
    $constraint->aspectRatio();
    $constraint->upsize();
})->orientate()->save();
```

**Code Example On 3.x**
```php
$manager = ImageManager::gd();
$image = $manager->read($file->getRealPath());

$image->scale($width, $height);
$image->toGif()->save($file->getRealPath());
```

**Environment (please complete the following information):**
 - PHP Version: 8.2
 - OS: Windows 10
 - Intervention Image Version: 3.1
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
I will come up with a solution that fits the current architecture.

**Comment by olivervogel** [comment]
As of version `3.2`, it is now possible to [encode & save in one call](https://image.intervention.io/v3/basics/image-output#writing-images-directly).
