### ISSUE TITLE
$image->rotate($degrees) is missing in v3 documentation

### ISSUE THREAD

**Issue by kobe-ra** [Intervention/image#1248]
I have this code in my older project

```
$image->rotate($direction === 'left' ? 90 : -90);
```

The new project is using version `3.2` and I can't find the new rotation documentation anywhere.

If the functionality is implemented, I believe it's missing in the documentation.

**Comment by olivervogel** [comment]
You're right it's missing.

**Comment by kobe-ra** [comment]
[Documentation has been added.](https://github.com/Intervention/docs/commit/5d35b3cb3570dcabd72299d5fa2e1610523bda83)
Thank you.
