### ISSUE TITLE
Call to undefined method Intervention\Image\Facades\Image::make()

### ISSUE THREAD

**Issue by nickdelja** [Intervention/image#125]
I am unable to make images.  I get the following message:

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to undefined method Intervention\Image\Facades\Image::make()
open: /Users/Sites/gcfs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php

I am running Intervention\Image 1.6.2

**Comment by appsbits** [comment]
See for yourself if maybe have a model named Image. That would make a problem here.

**Comment by mattvb91** [comment]
Has this been fixed? I had to downgrade to "intervention/image": "1.*" to fix this issue.

**Comment by amjithps** [comment]
Add 

> use Image;

on top of your controller without changing anything in app.php. It will work fine in laravel 5.*

**Comment by StefanoGroenland** [comment]
@amjithps over 6 months since u commented but wanted you know it worked =) Thanks :+1:

**Comment by lfarkas** [comment]
It's still not working with:
- laravel/framework                     v5.2.35
- intervention/image                    2.3.7
even if I follow the installation.

**Comment by adelsedighi** [comment]
I have problem implementing intervention, I fix this and some other problem, I run xampp in local and laravel framework 5.2, this is what you should do:
1- add these line in your composer.json
"laravelcollective/html": "5.2.*",
		"intervention/image": "dev-master",
		"guzzlehttp/psr7":" ~1.1",
		"Illuminate/Html": "~5.0",
		"illuminate/support": "4.*|5.*",
2- add provioder to your app.php in config folder
 Intervention\Image\ImageServiceProviderLaravel5::class,
add this line to alias
'Image' => Intervention\Image\Facades\Image::class,

3- open cmd.exe or windows powershel and write this command:
cd to your working folder of your project when you have your composer.json
composer update
4-i have these class included in my controller
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View; 
use Illuminate\Http\Request;
//use Intervention\Image\Image as Img;
//use Intervention\Image\ImageManager;
use Intervention\Image\ImageManagerStatic as Image;
//use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Http\Requests;

I think use Intervention\Image\ImageManagerStatic as Image; was the main class for intervention

5-this is my whole upload section
if (Input::hasFile('image'))
			{
				$file = Input::file('image');
				$destinationPath = 'images/services';
				$extension = $file->getClientOriginalExtension();
				$filename = str_random(12).".{$extension}";
			
				
				$upload_success = $file->move($destinationPath, $filename);
				Input::merge(array('imageAddress' => $destinationPath.'/'.$filename));
				
				//intervention image resize
				$img= 'images/services'.'/'.$filename;
				$img = Image::make(public_path($img))->resize(200, 200);
				$img->save('images/services'.'/'.$filename);

			}

you just need these three lines

//intervention image resize
$img= 'images/services'.'/'.$filename;
$img = Image::make(public_path($img))->resize(200, 200);
$img->save('images/services'.'/'.$filename);

**Comment by GoodJob** [comment]
Same problem for me. Changing alias to "Img" doesn't work, downgrading to 1.* also didn't worked :( Tried everything with fresh Laravel 5.3 to make it work :(

**Comment by murph133** [comment]
**Laravel, Intervention and Amazon S3**

```
$file = $request->file('file'); // Get file input
$img = Image::make($file); // Create Intervention instance
$name = time() . '_' . $file->getClientOriginalName(); // Example file name
$payload = (string)$img->encode();
$upload = Storage::disk('s3')->put($name, $payload, 'public');
```

Don't forget:

`use Intervention\Image\Facades\Image;`

**Comment by Lucascoml** [comment]
so folks, I don't know if it's resolved, but I ran that command "composer require intervention / image" and it worked again. I'm using version 7.29
