### ISSUE TITLE
Add more detailed encoder control

### ISSUE THREAD

**Issue by olivervogel** [Intervention/image#1259]
**Describe the feature you'd like**
Add more detailed control on the encoding process. A settings object might be useful.

**Settings to control**

- Compression Level (Quality)
- Compression Type
- Interlace Option
- Bit Depth (Maybe because the supported bit depth is often linked to the image format)
- ...

### Example (draft)

```php
$image->encode(new PngEncoder(
    quality: 65,
    compression: Compression::ZIP,
    interlace: true,
    depth: 8
));
```

**Comment by konnng-dev** [comment]
@olivervogel is there a plant to reintroduce interlacing images?

I'm working together w/ the creator of https://github.com/thephpleague/glide/ to bring support to intervention v3 and we did some tweaks to support interlacing on JPEGS there, but it won't work case Driver is GD.

**Comment by olivervogel** [comment]
Yes, there are plans to bring back interlaced support. However, the exact path is not clear yet.

The main thing to think about is how to handle the differences between GD and Imagick and where to set the interlace flag in the public API.

Also, "interlace" can mean different things for different formats. For example, GD with `imageinterlace` will produce progressive Jpeg data if a Jpeg is output at the end. The interlace bit is also closely related to the output format for the GIF format.

For this reason, I am currently considering integrating this feature into the encoding process. Which somehow makes sense, because after an image has been decoded it exists undefined and "normalized" as a `GDImage` or `Imagick` object in memory. At this point, an "Interlace" command makes less sense than when a (new) image format is defined again, namely for encoding.

**Comment by olivervogel** [comment]
In version `3.6.0`, the option of interlaced encoding of the GIF and PNG image formats was reintroduced. Furthermore, the Jpeg encoder now also offers the option of progressive encoding.

See documentation:
https://image.intervention.io/v3/basics/image-output#encoding-gif-format
https://image.intervention.io/v3/basics/image-output#encoding-png-format
https://image.intervention.io/v3/basics/image-output#encoding-jpeg-format

cc @konnng-dev

**Comment by konnng-dev** [comment]
@olivervogel Thank you for finding time for this update. I really appreciate the effort maintaining this awesome lib.

I was able to move on w/ my project regarding progressive JPEGs, but I ran in into another issue.

My code tries to detect which format I want to encode based on the format and set quality. But since now the encoders have its own parameters, it no longer works.

```php
// ...
$encoded = $image->encodeByExtension($format, $quality)->toString();
// ...
```

On the above example, `$format` is specified by dynamic argument. It can be "jpg", "png",  "webp", "gif", etc. Same w/ `$quality` value.

The script throws the following Exception:

```
{
  "message": "Intervention\\Image\\Encoders\\PngEncoder::__construct(): Argument #1 ($interlaced) must be of type bool, array given, called in /var/www/html/vendor/intervention/image/src/Format.php on line 105"
}
```

According to https://image.intervention.io/v3/basics/image-output#encode-images-by-file-extension, in theory it would be possible to specify the quality.

I think the situation is the encoders now has different set of arguments, which throws this exception.

Would be possible to support quality, regardless the encoder I choose?

**Comment by konnng-dev** [comment]
I ended up doing the following approach

```php
//...
       $shouldInterlace = filter_var($this->getParam('interlace'), FILTER_VALIDATE_BOOLEAN);
       $encoderOptions = ['extension' => $format];
        switch ($format) {
            case FileExtension::AVIF->value:
            case FileExtension::HEIC->value:
            case FileExtension::AVIF->value:
            case FileExtension::TIFF->value:
            case FileExtension::AVIF->value:
            case FileExtension::JPG->value:
            case FileExtension::WEBP->value:
                $encoderOptions['quality'] = $quality;
            case FileExtension::JPG->value:
                $encoderOptions['progressive'] = $shouldInterlace;
                break;
            case FileExtension::GIF->value:
            case FileExtension::PNG->value:
                $encoderOptions['interlaced'] = $shouldInterlace;
                break;
            default:
        }

        $encoded = $image->encodeByExtension(...$encoderOptions);
//...
```

**Comment by olivervogel** [comment]
Yes, this is unfortunately an issue in 3.6. But I'm already preparing a [workaround](https://github.com/Intervention/image/pull/1333) that will be released very soon.

See also #1332

**Comment by konnng-dev** [comment]
Thanks for jumping right in, I'll be following #1332 then.

Feel free to mark this one as closed.
