### ISSUE TITLE
ImageMagick extension not available with this PHP installation.

### ISSUE THREAD

**Issue by adishdahal777** [Intervention/image#1266]
**Describe the bug**
message: "ImageMagick extension not available with this PHP installation.",…}
exception
: 
"Intervention\\Image\\Exceptions\\RuntimeException"
file
: 
"E:\\restaurant-ms\\vendor\\intervention\\image\\src\\Drivers\\Imagick\\Driver.php"
line
: 
36
message
: 
"ImageMagick extension not available with this PHP installation."

**Code Example**
 if (request()->has('image') && (request('image') != null)) {

            $manager = new ImageManager(new Driver());

            $img = $manager->read(request('image'));

            $originalWidth = $img->width();
            $originalHeight = $img->height();

            $maxSize = 512;
            if ($originalWidth > $originalHeight) {
                $newWidth = $maxSize;
                $newHeight = intval($originalHeight * ($maxSize / $originalWidth));
            } else {
                $newHeight = $maxSize;
                $newWidth = intval($originalWidth * ($maxSize / $originalHeight));
            }
            $img->resize($newWidth, $newHeight);

            $new_profile_image = "{$slug}.png";
            $path = storage_path("uploads/table/$new_profile_image");
            $old_page = $slug ? storage_path("uploads/table/" . explode("?t=", $slug)[0]) : "";
            $img->save(storage_path("uploads/table/$new_profile_image"));
            if ($old_page != "" && $old_page != $path) @unlink($old_page);
            $usertype->image = $new_profile_image . "?t=" . time();
        }

**Expected behavior**

**Images**
If applicable, add problematic images or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - PHP Version: 8.1
 - OS: Window
 - Intervention Image Version:
 - GD or Imagick:

**Comment by olivervogel** [comment]
Intervention Image provides a standardized API for the PHP image processing extensions GD and Imagick. One of these extensions must be installed for the library to work.

In this case, Imagick does not seem to be available.

**Comment by destinybravos** [comment]
> Intervention Image provides a standardized API for the PHP image processing extensions GD and Imagick. One of these extensions must be installed for the library to work.
> 
> In this case, Imagick does not seem to be available.

Can you please suggest how Imagick can be installed/configured on XAMPP Local Server in a Windows OS Environment?

**Comment by olivervogel** [comment]
> Can you please suggest how Imagick can be installed/configured on XAMPP Local Server in a Windows OS Environment?

No. There are already plenty of good guides available.

**Comment by destinybravos** [comment]
> > Can you please suggest how Imagick can be installed/configured on XAMPP Local Server in a Windows OS Environment?
> 
> No. There are already plenty of good guides available.

You could have just recommended any of the plenty good guides available bro
