### ISSUE TITLE
LARAVEL Support dropped in version 3?

### ISSUE THREAD

**Issue by MGeurts** [Intervention/image#1267]
Version 3 is not working anymore in LARAVEL (8-9-10).
Class "Intervention\Image\Facades\Image" not found.

Did you remove support for PHP frameworks like LARAVEL on purpose?
If so, please state this clearly in the documentation.

Thanks.

**Comment by olivervogel** [comment]
Please read the [documentation](https://image.intervention.io/v3/introduction/upgrade) before opening issues.

**Comment by MGeurts** [comment]
That was very well hidden.
