### ISSUE TITLE
Quality after compressing is low

### ISSUE THREAD

**Issue by abdullafahem** [Intervention/image#1268]
**Describe the bug**
I am using Laravel 10 with Livewire v3 Jetstream and I need to compress the image or resize it without losing quality.

**Code Example**
```
$manager = new ImageManager(new Driver());
$this->media_name = Carbon::now()->timestamp . '.' . $this->media->extension();
$img = $manager->read($this->media);
$img->resize(160, 160)->save(public_path('storage/projects/media/small/' . $this->media_name), 80);
$img->resize(null, 300)->save(public_path('storage/projects/media/medium/' . $this->media_name), 80);
$img->resize(1280, null)->save(public_path('storage/projects/media/large/' . $this->media_name), 80);
```

**Expected behavior**
Expected to just resize the image and reduce quality to 80% but is blurry I can't see the image

**Environment (please complete the following information):**
 - PHP Version: 8.2
 - OS: Ubuntu 23.10
 - Intervention Image Version: 3.2
 - GD or Imagick: Imagick

**Comment by olivervogel** [comment]
It would be great if you could provide the image you are working with. Preferably a before and after version.

**Comment by abdullafahem** [comment]
![1705305066](https://github.com/Intervention/image/assets/49653818/298c4959-8fcb-467f-aba7-f0cd60a3af65)
The original file.


![1705305066](https://github.com/Intervention/image/assets/49653818/0d8e57b4-124e-40b0-b218-8b29d37b04f2)
The resized file.

**Comment by abdullafahem** [comment]
Oh, that's right. Thank you so much!

**Comment by abdullafahem** [comment]
> According to your code, the first step is to resize the original image to 160 x 160 pixels. In the second step, only the height is increased from 160 pixels to 300 pixels (quality loss). In the third step, the width is increased from 160 pixels to 1280 pixels (extreme quality loss).
> 
> If you need to save multiple sizes in one action, I would use cloning.
> 
> ```
> $img = $manager->read($this->media);
> 
> $small = clone $img;
> $large = clone $img;
> 
> $small->resize(160, 160);
> $large->resize(1280, null);
> ```


Oh, that's right! Thank you so much!
