### ISSUE TITLE
Laravel service provider

### ISSUE THREAD

**Issue by seebeen** [Intervention/image#1270]
**Describe the feature you'd like**
InterventionImage Laravel Service provider drop-in

**Is your feature request related to a problem? Please describe.**
Version 3 dropped direct laravel integration. 

Can you make a repository for a laravel service provider (for example - intervention/laravel-image-provider), and assign developer privs on it. I can code one out.

**Comment by olivervogel** [comment]
Yes, I've thought about that too. I like `intervention/image-laravel` short and sweet.

**Comment by fwilliamconceicao** [comment]
I had the same issue here and the only solution it was downgrade to version "intervention/image": "2.5". It's seems the pull request that solve this issue was merged, now just need to wait the new release tag.

**Comment by olivervogel** [comment]
It is still possible to use Intervention Image 3 with Laravel. You just have to call the `ImageManager::class` directly instead of the Facade, and the configuration file is not read in automatically.

**Comment by seebeen** [comment]
> Yes, I've thought about that too. I like `intervention/image-laravel` short and sweet.

Awesome possum. 💪 Send me an invite when you create the repo.

**Comment by olivervogel** [comment]
Already done for Laravel 10:
https://github.com/Intervention/image-laravel

**Comment by seebeen** [comment]
Awesome.

Are you interested in implementing a semantic-release workflow which will auto publish new version as a tag / release?

**Comment by olivervogel** [comment]
> Are you interested in implementing a semantic-release workflow which will auto publish new version as a tag / release?

I am open to any good suggestions.
