### ISSUE TITLE
Can't install in php version 8.3.1 

### ISSUE THREAD

**Issue by joneyspark** [Intervention/image#1272]
Hi, I'm trying to install Intervention/image one of my laravel project. But i'm failed. it's problem creating in my lastest php version. could you help me. How to solved it ?

<img width="1043" alt="intervetion-image-error" src="https://github.com/Intervention/image/assets/34330722/f3cb7e58-74ab-45a5-87f6-39dfe72e067e">

**Comment by olivervogel** [comment]
I guess it is this:
> nette/schema v1.2.2 requires php >=7.1 <8.2 -> your php version (8.3.1) does not satisfy that requirement.

**Comment by olivervogel** [comment]
> So it does not support PHP version 8.3 version ?

nette/schema v1.2.2 does not. Intervention Image does.
