### ISSUE TITLE
`backup()` and `reset()` functionality in v3

### ISSUE THREAD

**Issue by chescos** [Intervention/image#1274]
Is there currently some way to replicate the [backup()](https://image.intervention.io/v2/api/backup) and [reset()](https://image.intervention.io/v2/api/reset) functionality in v3? If not, is there a plan to add them back in v3 with a future release?

**Comment by olivervogel** [comment]
In version 3, the image objects can be cloned. This means that the same result can be achieved using less native PHP commands.

### Version 2

```php
// original image 800 x 600
$img = Image::make('public/foo.jpg');

// backup status
$img->backup();

// small version
$img->resize(320, 240);
$img->save('public/small.jpg');

// reset image (return to backup state)
$img->reset();

// large version
$img->resize(640, 480);
$img->save('public/large.jpg');
```

### Version 3

```php
// original image 800 x 600
$img = $imageManager->read('public/foo.jpg');

// small version
$small = clone $img;
$small->resize(320, 240);
$small->save('public/small.jpg');

// large version
$img->resize(640, 480);
$img->save('public/large.jpg');
```
