### ISSUE TITLE
Image size increases if the uploaded image is compressed image

### ISSUE THREAD

**Issue by ASAMNYA** [Intervention/image#1288]
I have noticed when a compressed image is uploaded and if the image quality save is set to 100 then uploaded image size increases significantly.

- If the compressed size is 100 KB and uploaded to server using intervention package with save method and option of '100' image quality then the uploaded image's size increased significantly 700-800KB.

`
$thumbnailImage->save($originalPath . $uploadFileName, 100);
`

Original Compressed Image Size
100 KB

After uploading to server via Intervention Package
704 KB

**Environment **
 - PHP Version: 7.4
 - OS: Windows 10
 - Intervention Image Version: 2.7

**Comment by olivervogel** [comment]
The previous compression and optimization is discarded during the decoding and encoding process. This is normal behavior. 

The deciding factor is the quality parameter, which in your example is `100`, resulting in a very large file size.  You can reduce the file size by lowering the value of the parameter. The additional compression optimization must then be done again.
