### ISSUE TITLE
AVIF image support has been disabled

### ISSUE THREAD

**Issue by naseefpv** [Intervention/image#1289]
**Describe the bug**
Not able to use AVIF format.
Getting an error like: 

imagecreatefromavif(): AVIF image support has been disabled at /var/www/platoshop-v2/vendor/intervention/image/src/Drivers/Gd/Decoders/FilePathImageDecoder.php:48)

**Code Example**
```
 $manager = new ImageManager(new Driver());
 $img = $manager->read($file);
```

**Expected behavior**
It should read my avif file.

**Environment (please complete the following information):**
 - PHP Version: 8.2.15
 - OS: Ubuntu 20.04
 - Intervention Image Version: 3.3.2
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
This seems to be due to the setup of the GD library on the server host and is not under the influence of Intervention Image.

Read [how to setup Avif with GD properly](https://php.watch/versions/8.1/gd-avif).
