### ISSUE TITLE
PNG w/ transparency to JPEG conversion creates black background

### ISSUE THREAD

**Issue by eugenelight16** [Intervention/image#129]
Not sure if there is a workaround when inputting a transparent PNG but generating a JPEG with your package. Let me know if you'd like to see an example or if this is a common problem. Thanks.

**Comment by sustmi** [comment]
I still get black background when I use `$image->fit()` method.
I use `gd` driver and this source image: http://www.pngall.com/donald-duck-png/download/15985

**Comment by MichMich** [comment]
For anyone looking for a solution to fix this using `fit()`, this worked for me:

```
$image = Image::make('/path/to/source.png')->fit(250, 250);

Image::canvas($image->width(), $image->height(), 'ffffff')
    ->insert($image)
    ->save('/path/to/target.jpg', 70, 'jpg');
```
