### ISSUE TITLE
image pattern fill question

### ISSUE THREAD

**Issue by refactor73** [Intervention/image#1297]
Hi!

I have more or less a question, instead of a feature request:

following scenario:

i have two images.
one image is an image pattern (like a metallic surface - something complex, so nothing you can simply define with an color code).
the second picture is a rectangle with an hole in the middle. the hole is transparent.
both images have the same size.
now i want to place (or better fill) image 1 over image 2 without covering the hole. the pattern should only apply on non-transparent parts of image 2. is this even possible?

thank you very much!

**Comment by olivervogel** [comment]
I know what you have in mind. Unfortunately, it is currently not possible to fill with an image as a texture. I have [already worked on this feature](https://github.com/Intervention/image/pull/1263), but have encountered problems that need to be solved first.

I would recommend using the Imagick library directly.
