### ISSUE TITLE
imagesetthickness() in DrawLineModifier has no effect in certain environments

### ISSUE THREAD

**Issue by ulfie22** [Intervention/image#1298]
**Describe the bug**
The `width` parameter for the `drawLine` method was implemented in v 3.3.3. It worked correctly upon upgrade. For reasons unknown, it has stopped working and all drawn lines are 1 px, no matter what the `width` parameter is. This is so effing weird!

**Code Example**
```
public function drawLine($fromX, $fromY, $toX, $toY, $color, $width): void
    {
        ray($width)->blue();
        $this->image->drawLine(function ($line) use ($fromX, $fromY, $toX, $toY, $color, $width) {
            $line->from($fromX, $fromY);      // starting point of line
            $line->to($toX, $toY);            // ending point
            $line->color($color);             // color of line
            $line->width($width);             // line width in pixels
        });
    }
```

**Expected behavior**
In the above example, `$width` was set to 4 (and verified by ray()) - image produced has a 1 px line

**Images**
![CleanShot 2024-02-07 at 18 33 25@2x](https://github.com/Intervention/image/assets/161110/1f79a7c7-9905-42e8-996c-dac26d6453b1)

**Environment (please complete the following information):**
 - PHP Version: 8.3
 - OS: MacOS Sonoma 14.3
 - Intervention Image Version: 3.3.3
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
That's really strange. Unfortunately, I can't reproduce it right now.

According to a [very old comment](https://www.php.net/manual/en/function.imagesetthickness.php#86007) in the PHP documentation, the function `imagesetthickness()` does not work if `imageantialias()` is activated. I can't say whether this is still relevant (my tests show that it works with both options). But maybe you can comment out [the antialias line](https://github.com/Intervention/image/blob/develop/src/Drivers/Gd/Modifiers/DrawLineModifier.php#L22) in the vendor code and see if it has an influence.

**Comment by ulfie22** [comment]
@olivervogel Thanks for this response. THAT ACTUALLY FIXES THE PROBLEM! Is there a way for me to override this one function? I tried to just override that one class, but it's buried so deep inside Image Intervention that my override was not being recognized. Thank you for your help!

**Comment by ulfie22** [comment]
@olivervogel Thanks for this response. THAT ACTUALLY FIXES THE PROBLEM! Is there a way for me to override this one function? I tried to just override that one class, but it's buried so deep inside Image Intervention that my override was not being recognized. Thank you for your help!

**Comment by olivervogel** [comment]
On the one hand, this is good news. On the other hand, it is also bad news, as the current implementation does not seem to work on certain systems. What particularly surprises me is that I can't detect any problems and I'm even using the same setup (MacOS, PHP 8.3.2, GD). And it is not really clear what triggers the behavior and how to handle this.

As a quick solution for the moment, I would suggest to use a [custom modifier](https://image.intervention.io/v3/modifying/custom-modifiers) that replicates the function of the `DrawLineModifer` without antialiasing.

It could look like this:

```php
use Intervention\Image\Interfaces\ModifierInterface;
use Intervention\Image\Interfaces\ImageInterface;

class DrawPixelLine implements ModifierInterface
{
    public function __construct(
        protected int $fromX,
        protected int $fromY,
        protected int $toX,
        protected int $toY,
        protected mixed $color,
        protected int $width
    ) {
    }

    public function apply(ImageInterface $image): ImageInterface
    {
        $lineColor = $image->driver()->colorProcessor($image->colorspace())->colorToNative(
            $image->driver()->handleInput($this->color)
        );

        foreach ($image as $frame) {
            imagealphablending($frame->native(), true);
            imagesetthickness($frame->native(), $this->width);
            imageline(
                $frame->native(),
                $this->fromX,
                $this->fromY,
                $this->toX,
                $this->toY,
                $lineColor
            );
        }

        return $image;
    }
}
```

I'm sorry that I can't offer you a better solution at the moment.

**Comment by olivervogel** [comment]
Here are the specs of my local GD installation for comparison. Maybe there are differences that you can recognize.

<img width="971" alt="Bildschirmfoto 2024-02-09 um 14 56 05" src="https://github.com/Intervention/image/assets/884642/e13ff6aa-7963-41e3-92b8-264b802fb6e2">

**Comment by ulfie22** [comment]
@olivervogel wow - thank you for all the great information. After some further research on my end, I am pretty sure this has something to do with my system, not your code. One of my co-workers pulled my code to his machine (actually a windows box running Sail) and everything worked as expected. I've been trying to get Laravel Herd to work successfully so my guess is something in that process caused this issue. I'm going to say thank you (big time!) and close this - I don't think you need to spend any more time on it unless someone else encounters the same thing.
