### ISSUE TITLE
Gif Allowed memory size exhausted

### ISSUE THREAD

**Issue by mpn7** [Intervention/image#1305]
I'm using your package to upload and edit images the user submits to the server, when the user submits a GIF file it gives the error `Allowed memory size of 134217728 bytes exhausted` I changed the memory limit to 256MB and it still throws this error. The GIF file has 6MB.
I'm upgrading from the version 2, while it didn't keep the animation it also didn't throw this error.

The error happens in this line. The driver is GD
```php
$manager = new ImageManager(new Driver());
$resized_image = $manager->read($image->getRealPath());
```

 - PHP Version:8.2
 - OS: MacOS
 - Intervention Image Version: 3.4
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
Unfortunately, the GD Library does not really conserve resources. This is especially true for animated GIFs, as animation is not natively supported and therefore has to be decoded frame by frame into a `GDImage` instance by this library.

Unfortunately, I have to advise you to increase the limit further or to use Imagick.

**Comment by olivervogel** [comment]
This topic gave me the following idea, which will be dealt with further in a separate issue (#1307).
