### ISSUE TITLE
imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by soheylfarzane** [Intervention/image#1316]
when i want to read png file from local i get this error
i was update from 2 to 3.5
can you help me ?

**Comment by olivervogel** [comment]
I can confirm this for certain PNG files with GD driver. However, I don't seem to have any way to do anything about it. Even if `imagecreatefrompng` is called with error control operator for suppression, the warning.
