### ISSUE TITLE
Unable to mock final classes

### ISSUE THREAD

**Issue by clementlanot** [Intervention/image#1324]
**Describe the bug**
Impossible to test with PHPUnit and Laravel.

**Code Example**
```
Image::shouldReceive('save')->andThrow(new NotWritableException());
```

Throw the error:
```
Mockery\Exception: The class \Intervention\Image\ImageManager is marked final and its methods cannot be replaced. Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock, but only if the mock is not subject to type hinting checks.
```

And using Mockery:
```
$m = Mockery::mock(new Image());
```
Throw the error:
```
Cannot redeclare Mockery_3_Intervention_Image_Laravel_Facades_Image::shouldReceive()
```

**Expected behavior**
Perhaps we should not declare classes as final?

**Environment (please complete the following information):**
 - PHP Version: 8,2
 - Laravel 11
 - Intervention Image Version: 3

**Comment by olivervogel** [comment]
I think this is more a topic for Mockery. Also have a look at [dg/bypass-finals](https://github.com/dg/bypass-finals).

**Comment by ChrGriffin** [comment]
_Strongly_ disagree that this is an issue for Mockery to resolve. Mockery is subject to the rules of how the language operates, like anyone else. On the one hand, you could simply _not_ mark the class as `final`. On the other hand, Mockery could try some hacky nonsense to circumvent the basic rules of the language. It doesn't take a genius to see which option is preferable.

There's no real reason to mark the ImageManager as `final` to begin with. Literally the only thing you accomplish by doing so is cause a pain for those who need to mock it for testing or extend it. Sure, there are ways around it, like the package you linked. But why offload the responsibility on us when there's no good reason for you not to make a minor change to the package?

Heck, I'd make the PR myself and save you the work (such as it is), if it wasn't clear you aren't disposed towards it.
