### ISSUE TITLE
How encode image to binary?

### ISSUE THREAD

**Issue by idem84** [Intervention/image#1325]
**Describe the feature you'd like**
Not found how return output like "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAJYCAMAAAB7MkC6AAADAF..."

If i can load image from that string with Image::read() why not do some thing to output with same format? Some thing like $image->toBase64();

Now i do like that in code: "data:{$image->origin()->mediaType()};base64," . base64_encode($image->encode()) by self

**Comment by olivervogel** [comment]
See https://image.intervention.io/v3/basics/image-output#creating-data-uri-scheme
