### ISSUE TITLE
access the core format imagemagick without getCore();

### ISSUE THREAD

**Issue by danielthomascarr** [Intervention/image#1327]
A new function that allows the same but now removed functionality of getCore()

**Comment by olivervogel** [comment]
You can access the underlying `GDImage` or `Imagick` object in an `Intervention\Image\Image::class` like so:

```php
$result = $image->core()->native();
```

**Comment by danielthomascarr** [comment]
Thank you for your response, yes I found that looking through the code, but switching between Intervention Image and Imagemagick is a bit trickier with the new version, use to use getCore() and then Image::make would except an Imagick instance to switch back but I can see that the new read() function doesn't, is there any function that could be used instead?
