### ISSUE TITLE
Add possibility to read Imagick or GDImage instance directly with ImageManager::read()

### ISSUE THREAD

**Issue by danielthomascarr** [Intervention/image#1328]
Most use cases would use Imagick or GD and it would be useful to include these as parameters in the new read function like the make function had done in previous versions, so you can extend the functionality by switching between the two with core()->native and read().

**Comment by olivervogel** [comment]
As far as I understand you, you would like to be able to read in objects of type `GDImage` or `Imagick` directly via the `ImageManager::class`. I will look into this.

**Comment by olivervogel** [comment]
Turns out, the Decoder are already there, but they were not linked in the input handler. Will be included in the next feature release.
