### ISSUE TITLE
The text method different output the Chinese/Japanese string which use the gd/imagic.

### ISSUE THREAD

**Issue by hetao29** [Intervention/image#1339]
**Describe the bug**
gd output chinese string need to unicode
imagic not need

**Code Example**
```
$manger = Intervention\Image\ImageManager::imagick();
$manger->text("中国");
$manger = Intervention\Image\ImageManager::gd();
$manger->text("中国");
$manger->text(toUnicode("中国"));

function toUnicode($string){
        $str = mb_convert_encoding($string, 'UCS-2', 'UTF-8');
        $arrstr = str_split($str, 2);
        $unistr = '';
        foreach ($arrstr as $n) {
            $dec = hexdec(bin2hex($n));
            $unistr .= '&#' . $dec . ';';
        }
        return $unistr;
    }

```

**Expected behavior**
do not toUnicode when use the gd.

**Comment by olivervogel** [comment]
I can not reproduce this issue. Please make sure that you are using the latest version of the GD and/or Imagick libraries and a font that supports the corresponding characters.

**Comment by olivervogel** [comment]
Works as well. Maybe upgrading to a newer GD version helps.

## GD
![gd](https://github.com/Intervention/image/assets/884642/4b032100-5919-461d-99a6-e447d2bc343c)


## Imagick
![imagick](https://github.com/Intervention/image/assets/884642/a0019684-53b1-4683-944f-38c7ecf4a4ee)
