### ISSUE TITLE
Text watermark issue

### ISSUE THREAD

**Issue by grafikkaos** [Intervention/image#134]
I am using the following line to apply a text watermark to uploaded images:

$thumbImg = Image::make(realpath($destinationPath . '/' . $filename));
$thumbImg->text('This is my text!!', 0, 0, function($font) {
                    $font->file(public_path().'/samples/fontname.ttf');
                    $font->size(24);
                    $font->color('#ffffff');
                    $font->align('right');
                    $font->valign('bottom');
                    $font->angle(0);
                });
$thumbImg->save($thumbPath . '/' . $filename, $quality);

The problem I am having is that the text watermark is actually not being shown on the image.  If i set the optional x-ordinate and y-ordinate to something, I can see the text, however, this is not placed where I want it to be which is at the bottom right of the image.

Any ideas?

**Comment by malshenawy** [comment]
look at here :)

http://image.intervention.io/api/insert
