### ISSUE TITLE
Error: Class "Intervention\Image\Drivers\Gd\Driver" not found

### ISSUE THREAD

**Issue by Mohsen322** [Intervention/image#1355]
hello. i just used example code and got this error.
php version: 8.1
run on localhost
GD library is enable.

`
// include composer autoload
require './vendor/autoload.php';

use Intervention\Image\ImageManager;

// create image manager with desired driver
$manager = new ImageManager(
    new Intervention\Image\Drivers\Gd\Driver()
);

// open an image file
$image = $manager->read('test.png');

// resize image instance
$image->resize(height: 300);

// insert a watermark
$image->place('polygon.png');

// encode edited image
$encoded = $image->toJpg();

// save encoded image
$encoded->save('example.jpg');
`

**Comment by olivervogel** [comment]
The error is not coming from this library. Provided that the installation with Composer has been carried out and the specified path of the autoloader exists, something does not seem to be correct. I cannot say more with the information given.

**Comment by Mohsen322** [comment]
I followed the instructions in the documentation step by step and used Composer and didn't nothing wrong.
