### ISSUE TITLE
Reading a very large image with Imagick results in error "Unable to decode input"

### ISSUE THREAD

**Issue by hetao29** [Intervention/image#1357]
**Describe the bug**
If the image file is huge(17.4MB, 9952 x 14032), then error :
vendor/intervention/image/src/Drivers/AbstractDecoder.php(38)	0:Unable to decode input

**Code Example**
```php
$mgr = Intervention\Image\ImageManager::imagick();// ::gd() is OK.
$img = $mgr->read("/tmp/large.jpg");

```

**Environment (please complete the following information):**
 - PHP Version:
 - OS:
 - Intervention Image Version:
 - GD or Imagick:

How to set setresourcelimit https://www.php.net/manual/en/imagick.setresourcelimit.php

**Comment by olivervogel** [comment]
Thanks for reporting. I will look into this.

**Comment by olivervogel** [comment]
I think the best way is to do this configuration outside of this library for Imagick directly in the `policy.xml`.

Something like this.

```xml
<policymap>
  <policy domain="resource" name="memory" value="256MB"/>
  <policy domain="resource" name="map" value="512MB"/>
  <policy domain="resource" name="disk" value="1GB"/>
  <policy domain="resource" name="file" value="768"/>
  <policy domain="resource" name="thread" value="1"/>
</policymap>
```
See [Imagick Documentation](https://www.imagemagick.org/script/architecture.php) for further details.
