### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by Zae** [Intervention/image#136]
How do I clear the Intervention Image cache? 

Some images are not updated after the source is changed because the cache is still valid, can I clear it somehow?

**Comment by Kreshnik** [comment]
What solved my problem was adding;

```
"extra": {
    "laravel": {
        "dont-discover": [
            "intervention/image",
            "intervention/imagecache"
        ]
    }
},
```
Which disables laravel auto discovery for intervention image and imagecache.
