### ISSUE TITLE
ValueError: application/pdf is not a valid backing value for enum Intervention\Image\MediaType in >= 3.7.1

### ISSUE THREAD

**Issue by Temepest74** [Intervention/image#1373]
I am using the laravel package integration. As soon as I updated to 3.7.1 my tests (phpunit) where I read some pdf files with Image::read() started failing with the error from title. 3.7.0 works just fine

**Comment by olivervogel** [comment]
I can confirm that the ValueError occurs since `3.7.1` for PDF files. However, PDF is **not** an [officially supported format](https://image.intervention.io/v3/introduction/formats) and only works with the Imagick driver by a coincidence. I will think about how to deal with this.

**Comment by olivervogel** [comment]
As of version [3.7.2](https://github.com/Intervention/image/releases/tag/3.7.2) the previous behavior is again possible.

I would like to point out that PDF is not actually one of the formats supported by this library and that I recommend using Imagick directly.
