### ISSUE TITLE
Place function error

### ISSUE THREAD

**Issue by NikolaDivjak97** [Intervention/image#1376]
## Describe the bug
I have a problem. When i load an image with read function (ImageManager::read(), and i create a text image like this https://prnt.sc/t3CLPvMMPnmm, it creates it with good background and good text color and font and(all other attributes). But when i try to add new text image to my 'MAIN' image it colors go nuts: https://prnt.sc/7utg9svba4V-
EDIT: When I add element with text to empty image (filled with white background with fill() 
example: 
$image = $manager->create($this->width, $this->height)->fill('#fff');
$image->place($textImage, 'top-left', $textElement['x'], $textElement['y']);
) this error occurrs.

## Code Example
                $textImage = $manager->create($textElement['width'], $textElement['height']);
                $backgroundColor = $textElement['textStyle']['background-color'] ?: null;

                if ($backgroundColor)
                {
                    $textImage->fill($backgroundColor);
                }

                $textImage->text($textElement['textStyle']['text'], $textElement['width'] / 2, $textElement['height'] / 2, function (FontFactory $font) use ($textElement) {
                    $font->filename(public_path('fonts/' . $textElement['textStyle']['font-family'] . '.ttf'));
                    $font->size((int)$textElement['textStyle']['font-size']);
                    $font->color($textElement['textStyle']['color']);
                    $font->align('center');
                    $font->valign('middle');
                });

                $textImage->save($elementPath);

                $clone->place($textImage, 'top-left', $textElement['x'], $textElement['y']);
                $clone->save($clonePath);
## Expected behavior
I want to just place the image to another image as it is, i don't understand why place is changing the colors of the image that is placed to main image..

## Environment (please complete the following information):
 - PHP Version: 8.1
 - OS: Windows 10
 - Intervention Image Version: v3
 - GD or Imagick: Imagick driver

**Comment by olivervogel** [comment]
The problem is that Imagick automatically chooses the output format for PNG depending on the color scheme of the image. If the image has only one color (white), as in this example, it is automatically saved in grayscale PNG format. Of course, this has the disadvantage that the colored image added later loses its colors when it becomes part of the parent image through `place()`.

This is a tricky issue related to the different PNG formats, for which there is currently no real control in this library. I will look into it.

**Comment by olivervogel** [comment]
This should now work with version 3.8.0.
