### ISSUE TITLE
"image/x-heic" is not a valid backing value for enum "Intervention\Image\MediaType"

### ISSUE THREAD

**Issue by BriceTossim** [Intervention/image#1377]
## Describe the bug
We encountered this error when trying to upload a heic file from an older version of ios

## Images
![Screenshot 2024-07-10 at 10 54 38](https://github.com/Intervention/image/assets/56340950/fb91c26a-6634-4279-99b6-b50cff4e6b94)

## Environment (please complete the following information):
 - PHP Version: 8.1.29
 - OS: Linux
 - Intervention Image Version: 3.7.2
 - GD or Imagick: Imagick

**Comment by olivervogel** [comment]
Thanks for reporting. This non-standard mime type is now [added ](https://github.com/Intervention/image/commit/6daaedf7ed739a8f5a7ca5dde2dae41934dd4779) and will be available in the next patch release.

**Comment by olivervogel** [comment]
This is now included in Version 3.8.0.
