### ISSUE TITLE
Transparent Background Image Issue

### ISSUE THREAD

**Issue by imakbar** [Intervention/image#1390]
I upgraded v2 to v3 now I am facing the issue and I am unable to find the solution.
Issue is If I read a PNG transparent file It should stay with transparent background. If my image size is 200 by 200 and I read the file in contain() function I use 400 by 200 so after read the file my original image area is transparent but the new area saved with white background from left and right side. While It should be transparent because I did not select any color in the function.
I have attached an sample Image after output. 

here is the code I am using
`Image::read($file)->contain($width, $height)->save(public_path($fullPath));`

![1723072948-green-villa-675x468](https://github.com/user-attachments/assets/d7dc5a43-232d-420a-ba7d-dc9e9c5d4540)

If I use this function, It is good Image is now transparent but Image aspect ration has good. Image is stretch, I also attached image of this output
`
Image::read($file)
  ->resize($width, $height, 
      function($constraint){
          $constraint->aspectRatio();
      })
  ->resizeCanvas($width, $height)
  ->save(public_path($fullPath));
`
![1723153019-green-villa-675x468](https://github.com/user-attachments/assets/68d5b1af-3906-43a5-b1ca-f41d2f14dce2)

 - PHP Version: 8.2.12
 - OS: Windows
 - Intervention Image Version: v3
 - GD or Imagick: GD

**Comment by olivervogel** [comment]
With the method `contain()` you have the possibility to [specify a background color](https://image.intervention.io/v3/modifying/resizing#padded-resizing-with-upscaling) with which the newly created areas are filled. By default, this is white `#ffffff`.

If you want this areas to be transparent, you just have to set this color as fully transparent in your call.

```php
Image::read($file)
    ->contain($width, $height, background: '#ffffff00')
    ->save(public_path($fullPath));
```

In this example the transparent color is set by hexadecimal format, but you can have the option to use all [supported color formats](https://image.intervention.io/v3/introduction/formats#color-formats) if you like.

For example the following color definitions all result in a fully transparent color.

```php
$color = '#ffffff00'; // fully transparent
$color = 'rgba(15, 20, 255, 0)'; // fully transparent
$color = 'transparent'; // fully transparent
```

See [color format documentation](https://image.intervention.io/v3/introduction/formats#color-formats).
