### ISSUE TITLE
Font size not working even after providing the font file

### ISSUE THREAD

**Issue by Merchant6** [Intervention/image#1395]
I am using **Intervention** with **Laravel** to generate e-signatures and using a custom font file for them. The issue is that I cannot increase or decrease the **font size**, I am providing the font file correctly, the font is loading and working perfectly without any issues. I have tried both **GD** and **Imagick** but no luck.

Here's the method:
```
public function handle(string $firstname, string $lastname)
    {
        $fontPath = public_path('/font/cedarville-cursive/Cedarville-Cursive.ttf');

        $fullName = ucfirst($firstname) . " " . ucfirst($lastname);

        $manager = new ImageManager(Driver::class);

        $image = $manager->create(800, 150)->fill('white');
        
        $imageX = $image->width() / 2;
        $imageY = $image->height() / 2; 
        
        $font = (new Font($fontPath))
            ->setSize(20)
            ->setColor('#000000')
            ->setAlignment('center')
            ->setValignment('middle');

        $image->text($fullName, $imageX, $imageY, $font);

        $signature = $image->encodeByExtension('png');

        return $this->processImage($signature->toDataUri(), random_int(1, 100));
    }
```

**Comment by olivervogel** [comment]
Unfortunately, I cannot reproduce the issue. I have loaded “Cedarville-Cursive Regular 400” from Google Fonts and can change the size without any problems.

Does the problem also exist with other fonts?

```php
$image = ImageManager::withDriver(Driver::class)
    ->create(800, 200)
    ->fill('white');

$font = (new Font('./CedarvilleCursive-Regular.ttf'))
    ->setSize(120)
    ->setColor('#000000')
    ->setAlignment('center')
    ->setValignment('middle');

$image->text('just a test', $image->width() / 2, $image->height() / 2, $font);
```
## Font Size 120

![localhost-3](https://github.com/user-attachments/assets/2d518150-bb37-4074-9e12-223970279076)


## Font Size 40

![localhost-4](https://github.com/user-attachments/assets/3a957916-d812-4d58-9856-fdf8d5d42d12)

**Comment by Merchant6** [comment]
I have not tested other fonts but I will post here once I have tested them and thanks for the reply.
