### ISSUE TITLE
Unexpected DecoderException thrown

### ISSUE THREAD

**Issue by ADmad** [Intervention/image#1400]
## Describe the bug
`DecoderException` is thrown when trying to read a heic image created by lib itself. The error only occurs for `heic` and not for other image types. Also the exception only occurs on Ubuntu 24.04, it does not happen on 22.04, so it's likely an environment issue and not an issue with the lib, but I needed help to figure how to handle it.

The exact error can be seen here:
https://github.com/thephpleague/glide/actions/runs/11540990914/job/32122452702?pr=400#step:5:29

## Code Example
```php
use Intervention\Image\Encoders\MediaTypeEncoder;
use Intervention\Image\ImageManager;

$manager = ImageManager::imagick();
$img = $manager->read($manager->create(100, 100)->encode(new MediaTypeEncoder('image/heic'))->toFilePointer());
```

## Expected behavior
No exception to be thrown.

## Environment (please complete the following information):
 - PHP Version: PHP 8.3
 - OS: Ubuntu 24.04
 - Intervention Image Version: 3.9.1
 - GD or Imagick: Imagick

**Comment by olivervogel** [comment]
Thanks for reporting. 

This seems to be an issue with Imagick. I have [extracted the entire process](https://github.com/Intervention/image/blob/24f89602cc884632c7d61de6bf004b12d61ed8dc/tests/Unit/HeicTest.php) and recreated it using only “native” Imagick calls.

https://github.com/Intervention/image/blob/24f89602cc884632c7d61de6bf004b12d61ed8dc/tests/Unit/HeicTest.php#L15-L36

You [can see](https://github.com/Intervention/image/actions/runs/11543034579/job/32126941974?pr=1402#step:6:14) that the result of Imagick::getImagesBlob() is an empty string. This then [leads to an exception](https://github.com/Intervention/image/actions/runs/11543040020/job/32126954393?pr=1402#step:6:21) when reading in again.

I'll try to narrow it down further tomorrow.

**Comment by olivervogel** [comment]
I have reported this issue to Imagick as there is nothing else I can do at the moment.

https://github.com/Imagick/imagick/issues/707
