### ISSUE TITLE
I want to cerate a background on a uploaded image. 

### ISSUE THREAD

**Issue by SaadKiani-5** [Intervention/image#1407]
## Describe the bug
Image quality lost after resize.

## Code Example
 public function store(Request $request) 
{
    $validated = $request->validate([
        'url' => 'required|string',
        'image' => 'nullable|file|mimes:jpeg,png,jpg,gif|max:2048',
    ]);

    // $manager = ImageManager::gd();
    $manager = new ImageManager(Driver::class); 

    $identifier = Str::uuid();

    // QR code file paths
    $qrCodeFilename = 'qrcodes/' . uniqid() . '.png';
    $qrCodePath = 'storage/' . $qrCodeFilename;
    $fullPath = storage_path('app/public/' . $qrCodeFilename);

    // Create the directory if it doesn't exist
    if (!file_exists(dirname($fullPath))) {
        mkdir(dirname($fullPath), 0755, true);
    }

    // Generate the redirect URL for the QR code
    $redirectUrl = route('qr.redirect', ['identifier' => $identifier]);

    // Create the QR code with a transparent background
    QrCode::format('png')
        ->size(800)
        ->margin(2)
        ->backgroundColor(0, 0, 0, 0) // Set transparent background
        ->errorCorrection('H')
        ->generate($redirectUrl, $fullPath);

    // Load the generated QR code image
    $qrImage = $manager->read($fullPath);

    $logoPath = null;

    // Process the uploaded logo image if it exists
    if ($request->hasFile('image')) {
        $uploadedImage = $request->file('image');
        
        // Read the uploaded image
        $logo = $manager->read($uploadedImage);

         $background = $manager->create($logo->width(), $logo->height())->fill('#ffffff');

        // Place the uploaded image over the white background
        $background->place(
        $logo,
        'center'
        );  // Insert the image in the center of the white background

        // Resize logo (optional, 30% of QR code width)
        $qrWidth = $qrImage->width();
        $logoSize = (int)($qrWidth * 0.3);
        $background->resize($logoSize, $logoSize, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });

        // Save the processed logo with white background
        $logoPath = 'uploads/logos/' . uniqid() . '.' . $uploadedImage->getClientOriginalExtension();
        $logoFullPath = storage_path('app/public/' . $logoPath);
        $background->toPng()->save($logoFullPath);

        // Place the logo (now with a white background) on the QR code
        $qrImage->place(
            $logoFullPath,
            'center', // Place the logo in the center of the QR code
            0, 
            0
        );
    }

    // Save the final QR code with the logo placed on it
    $qrImage->save($fullPath);

    // Create and save the custom QR code in the database
    $customQR = CustomQR::create([
        'url' => $validated['url'],
        'image_url' => $logoPath,
        'status' => true,
        'client_id' => auth()->id(),
        'qr_code_path' => $qrCodeFilename,
        'identifier' => $identifier,
    ]);

    return redirect()->route('customQR.show', ['id' => $customQR->id])
                     ->with('success', 'QR Code created successfully with logo!');
}

## Expected behavior
Image the QR code lost quality after resizing.

## Images
If applicable, add problematic images or screenshots to help explain your problem.
![qrcode-7](https://github.com/user-attachments/assets/0333570b-ef1e-4ca4-86e4-327ee646ee48)

## Environment (please complete the following information):
 - PHP Version: 8.3
 - OS:
 - Intervention Image Version: "^3.8"
 - GD or Imagick: Imagick

**Comment by olivervogel** [comment]
The mentioned `resize()` call with the specification of `$constraint` is Intervention Image version 2 code. Since you are using version 3, this should be adapted.

See the following links:
https://image.intervention.io/v3/introduction/upgrade
https://image.intervention.io/v3/modifying/resizing#scaling-images-but-do-not-exceed-the-original-size
