### ISSUE TITLE
Can't install successfully

### ISSUE THREAD

**Issue by raselkhancse** [Intervention/image#141]
Can't install successfully
    "require": {
        "laravel/framework": "4.1.*",
         "intervention/image": "dev-master",
    }

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo \* -> the requested PHP
 extension fileinfo is missing from your system.

**Comment by StrangerMdj** [comment]
simple !!
1- go to php.ini and change (;extension=php_fileinfo.dll) to (extension=php_fileinfo.dll) and retar your your server 
2- go to composer.json and put "intervention/image": "2.2.*"
3- run a  command composer install 
enjoy :100:

**Comment by madhusudhan1234** [comment]
Hello guys 
I got the same problem .And i am using xampp and my php version is 5.5.15 how to solve it please help !

"require": {
		"laravel/framework": "5.0.*",
		"illuminate/html": "~5.0",
               "intervention/image": "2.*"
	},

E:\Laravel Projects\laravel5>composer require intervention/image
Using version ^2.2 for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - intervention/image 2.2.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.2.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.2.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for intervention/image ^2.2 -> satisfiable by intervention/image[2.2.0, 2.2.1, 2.2.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by stitisami** [comment]
yes extension=php_fileinfo.dll

**Comment by eiyu** [comment]
![prob](https://cloud.githubusercontent.com/assets/2733614/12501573/4ba2f65e-c0f1-11e5-9502-0fe2a75fec03.jpg)

Hi, I'm having same issue and following @Rahul-Giri  instruction then it gives me above image, is it successfully installed or what? 
I'm using PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
inside  xampp environtment 
lavarel 5.2

**Comment by Sunilkanigalupula** [comment]
I am also facing this problem..finally i resolve it..actually what am i did in past..i was changed this in 
extension=php_fileinfo.dll(php file) ..after my realization i adding same "extension=php_fileinfo.dll" 
xampp control panel/config/php.ini file then it works..
happy..thank u all (still any one suffer try this..)you feel happy

**Comment by eiyu** [comment]
I'm facing same problem and trying to uncomment the : extension=php_fileinfo.dll

Still not working

go to cli : 

$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

no fileinfo module. Why this happen?

**Comment by jiyikong** [comment]
I think you hava two php version ，you can see environment variables
