### ISSUE TITLE
Image response problem

### ISSUE THREAD

**Issue by rogerfn** [Intervention/image#146]
Hi All, 

For some reason I can't get the image directly from the browser. This is the code that I'm using. 

```
Route::get('/', function()
{
$img = Image::make('tmp/test.jpg');
return Response::make($img, 200, ['Content-Type' => 'image/jpeg']);
});
```

I can manipulate the object img without any problem (resize, save, etc)... the problem is just the response. Any ideas?

![captura de pantalla 2014-05-29 21 49 12](https://cloud.githubusercontent.com/assets/6075200/3122786/4d7c170a-e76b-11e3-96fc-d245edf8c6c2.png)

Cheers

**Comment by nimanima2011** [comment]
> 
> 
> I'm testing exactly the same example that is posted in the manual and it
> doesn´t work.
> 
> Route::get('/', function() {
> $img = Image::canvas(800, 600, '#ff0000'); //
> $response = Response::make($img->encode('png')); // set content-type
> $response->header('Content-Type','image/png'); // output
> return $response });
> 
> 2014-05-29 22:52 GMT+02:00 Oliver Vogel [notifications@github.com](mailto:notifications@github.com):
> 
> > Closed #146 #146.
> > —
> > Reply to this email directly or view it on GitHub
> > [#146 (comment)](https://github.com/Intervention/image/issues/146#event-126171745).
i exactly  have this problem
