### ISSUE TITLE
Error reading certain JPG's: "NotReadableException: Image source not readable"

### ISSUE THREAD

**Issue by nathanfirth** [Intervention/image#148]
I have the latest version installed in my Laravel 4 app, it works 80% of time time but for some reason certain JPG's cause it to throw a 500 error that says "Image source not readable". Any JPG from my Canon 7D DSLR causes that error. If I import the image to Photoshop and re-save it then it'll work just fine. But I've also found the same issue with quite a few images from the web. If I pick 10 images at random about 20% of them will fail consistently.

Seems like a bug.

**Comment by jedgueruela** [comment]
Hi, was this issue fixed ? I am having this problem as well. Some images are readable and some are not, which is bizarre. My Laravel version is 4.2 and I am using the latest release of intervention. Here is one of the images not isn't working on my end: 
![sam_9033](https://cloud.githubusercontent.com/assets/4901529/5594853/285f2ef4-929b-11e4-9499-09c86683767a.JPG)

**Comment by jedgueruela** [comment]
does it have something to do with the file size or so? cheers!

**Comment by olivervogel** [comment]
@jedgueruela Just tested successfully with your image.

PHP 5.5.3, GD bundled (2.1.0 compatible)

> memory_limit: 128M	

```php
require '../vendor/autoload.php';
use Intervention\Image\ImageManagerStatic as Image;

$img = Image::make('285f2ef4-929b-11e4-9499-09c86683767a.JPG')
$img->widen(300);
echo $img->response('jpg');
```



 What is the error message? Any info in your php log file?

**Comment by jedgueruela** [comment]
hi @olivervogel . just found out that the issue is not on the intervention/image library but on laravel's getRealPath(). seems like it isn't accepting greater than 2mb image size. by the way, what are your settings on upload_max_filesize and post_max_size? thanks for the help.

**Comment by skmetaly** [comment]
Just a quick note : if you are using it with Laravel, make sure that the path you are trying to write the image is readable and reachable. Even if you use public_path() make sure that it's properly set up in bootstrap/paths.php

**Comment by dubems** [comment]
am haivng the same issues

**Comment by dalenguyen** [comment]
I got the same problem "NotReadableException in AbstractDecoder.php line 302", and it's fixed!

In my case, Image::make(directory), the directly need the full the directory. So add the rest to the url which is:

Image::make('/var/www/test'.$this->path)
->fit(200)
->save('/var/www/test'.$this->thumbnail_path);

And it works! :D

**Comment by kamalNayak86** [comment]
Hi

    i had Issue in Windows Operating System . When i had uploaded image file its Works Fine on Linux Maschine . But when i try to run Same Code on My Windows Maschine it will Be thrown error.

    Encoding format(tmp) is not supported. i had checked in AbstractEncoder.php on Line no 150 and found that there is not such case for tmp in linux they dont append tmp while in windows they append tmp extension to image file

   So please its humble request to give some sollution to that so code is become more elegant and cross platform So we can utilize it.

Thanks

**Comment by howtomakeaturn** [comment]
just met this issue. spent two hours and finally find @SilverPaladin 's solution. thank you so much for saving my life.

**Comment by andrew-za** [comment]
I seem to be having this error when uploading from a mobile device Chrome browser - not when accessing it from the PC.

**Comment by n1smo** [comment]
Same here,

works on mac with chrome.

But not on my iphone. tested in mobile safari and chrome.
Any ideas?

**Comment by JCWolf** [comment]
I had the same problem, getting 'Image source not readable'. I could open the image in browser but not in php. So, my fix was adding `file_get_contents` inside `Image::make()`. 
Be aware, `file_get_contents` does not accept spaces so you need to replace them with %20. My final code is this;
```php
$path = str_replace(' ', '%20',$path);
$image = Image::make( file_get_contents($path) );
```

**Comment by naime-hossain** [comment]
Thanks @SilverPaladin

**Comment by stuartcusackie** [comment]
And thank you @JCWolf.

I'm not sure what the issue is but **file_get_contents** fixes it.

I was trying this: 

`$img = Image::make("http://homestead.app/storage/media/image1.jpg");`

Which was return the not readable error. So I tried JCWolf's solution:

$img = Image::make(file_get_contents(str_replace(' ', '%20',"http://homestead.app/storage/media/image1.jpg")));

And it works.

**Comment by IllyaMoskvin** [comment]
I had this happen when attempting to load a local file using a full path. For some reason, `is_file()` on [AbstractDecoder.php#L194](https://github.com/Intervention/image/blob/a54d1e9e6af2815c5ec24972d1d9209c677ce452/src/Intervention/Image/AbstractDecoder.php#L194) was returning `false`, although that file definitely existed. I tried substituting it with `file_exists()`, but that returned `false` as well.

I'm guessing that it has something to do with file or directory tree permissions, but I didn't bother digging further. As a work-around, I used Laravel's `Storage::get` to retrieve file contents, and passed them to `ImageManger::make`. Here's an example:


    $files = Storage::files( 'images' );

    foreach( $files as $file )
    {
        // Passing this to $manager->make() wasn't working for me:
        // $path = storage_path() . '/' . $file

        $contents = Storage::get( $file );

        $manager = new ImageManager( array('driver' => 'imagick') );
        $image = $manager->make( $contents );
    }

Hope this helps someone.

**Comment by JenryOllivierre** [comment]
In my case, this was happening because I was moving the file to storage before I manipulated it silly error I know! Meaning using \Illuminate\Http\UploadedFile::move() or move_uploaded_file. So when I called Image::make($file->getRealPath()), it was unable to read it.

**Comment by howtomakeaturn** [comment]
So much thanks to @SilverPaladin !

**Comment by howtomakeaturn** [comment]
Meet the issue again! 
So much thanks to @SilverPaladin again!

**Comment by howtomakeaturn** [comment]
Btw, it will be great if the error message in this exception can be more expressive.

**Comment by MatheusR1** [comment]
> No meu caso, isso estava acontecendo porque eu estava movendo o arquivo para o armazenamento antes de manipulá-lo. Erro bobo, eu sei! Significa usar \ Illuminate \ Http \ UploadedFile :: move () ou move_uploaded_file. Então, quando chamei Image :: make ($ file-> getRealPath ()), não foi possível ler.

You solved my problem. Thanks!
