### ISSUE TITLE
Cannot set custom font file.

### ISSUE THREAD

**Issue by ludo237** [Intervention/image#149]
Hello.

I'm trying to do this simple callback in Laravel 4 with PHP 5.5.13 (latest stable at the moment). I've downloaded a font from [DaFont](http://dafont.com) called Alpaca and stored it in `public/fonts/alpaca/` . I want to use, so I made up this

```
$dealImage->text("Text on Image", 5, 5, function($font) {
                $font->file(asset('fonts/alpaca/alpaca_ttf));
                $font->size(120);
                $font->color('#00000');
                $font->align('left');
                $font->valign('top');
});
```

But the application returns an exception 

```
Intervention \ Image \ Exception \ NotSupportedException
Internal GD font () not available. Use only 1-5.`
```

I don't know how to setup the custom font. I've read the entire documentation but no clue on some configuration or similar so I tough it might be an issue.

**Comment by bkkrishna** [comment]
I am getting the same problem even specifying the correct public path. Can anyone find out the issue. My code is : 
$img->text($text, 275, 200, function($font) {
            $font->file(public_path('assets/fonts/Alpaca.ttf'));
            $font->size(60);
            $font->color('#fdf6e3');
            $font->align('center');
            $font->valign('middle');
            $font->angle(45);
        });

**Comment by lfkwtz** [comment]
if anyone is trying to access `storage/app` and not the public folder - i was able to utilize `storage_path('app/fonts/abril-fatface.ttf')`

**Comment by Proloy-Bhaduri** [comment]
` $imtimg->text('uparjanpatrika.com',530,400,function($font){ 

    $font->file(__DIR__.'/myfonts/proloybhaduri.ttf');
    $font->size(14);
    $font->color('#000000');
    $font->align('center');
    $font->valign('top');
}); `

Using __DIR__ worked for me

**Comment by Proloy-Bhaduri** [comment]
<pre> $imtimg->text('uparjanpatrika.com',530,400,function($font){ 
    $font->file(__DIR__.'/myfonts/proloybhaduri.ttf');
    $font->size(14);
    $font->color('#000000');
    $font->align('center');
    $font->valign('top');
}); </pre>
this code  worked for me
