### ISSUE TITLE
Nginx URL Manipulation return 404

### ISSUE THREAD

**Issue by fer-ri** [Intervention/image#174]
hi, i know this is not bugs related with your package, but i just want to know if someone already use this feature (url manipulation) with nginx and work properly, mine is not work

http://bit.ly/1iUI7PD

Its return 404 of nginx page, seems like nginx try to looking for real image based on url path in disk
So if someone already done this before in nginx, please share in here

Thanks

**Comment by laravelish** [comment]
i had this in my conf file

```
     location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }
```

removing it fixed it
