### ISSUE TITLE
¿Animated GIF support?

### ISSUE THREAD

**Issue by Gelurban** [Intervention/image#176]
Hello, I was wondering to know if it is possible to get and save an animated GIF, since when I try:

Image::make('mygif.gif')->save('images/mygif.gif);

It will become a "static" image, losing the animation.

Thanks in advance

**Comment by kevdotbadger** [comment]
A great suggestion. At the moment I'm just copying the resource, but it'll be great to be able to crop an animated gif.

**Comment by loginwashere** [comment]
As I understand this feature is already present in development branch.
(I've forked repo and merged master into development and checked this functionality in laravel app I'm currently working on)
@olivervogel can you comment on when you plan to release it.
I see tag nextversion on this issue but not sure what it exactly means.

**Comment by olivervogel** [comment]
The development branch represents what will be the next major version (3.x). But it is currently under development and I would not use the branch for anything than development at all. Tag `nextversion` means that this feature will be available in the next **major** version.

Currently there is no release date. This is a free open source project and I'm working on it in my spare time.

**Comment by loginwashere** [comment]
@olivervogel thanks for clarification

**Comment by philippzentner** [comment]
What is the current status here?

**Comment by bubjavier** [comment]
make sure to use strtolower() on getClientOriginalExtension() as some images may have different casing on file extensions.

**Comment by revi4n4** [comment]
https://github.com/glukash/glu-image

**Comment by revi4n4** [comment]
system("convert big.gif -coalesce coalesce.gif");
system("convert -size 200x100 coalesce.gif -resize 200x10 small.gif");

**Comment by odahcam** [comment]
Keep GIF animation for Imagick:

```php
$im = new \Imagick('path/to;image');

if ($format == 'GIF') {
    $im = $im->coalesceImages();

    do {
        $im->resizeImage($resize['width'], $resize['height'], \Imagick::FILTER_BOX, 1);
    } while ($im->nextImage());

    $im = $im->deconstructImages();
} else {
    $im->resizeImage($resize['width'], $resize['height'], \Imagick::FILTER_LANCZOS, 1, true);
}

$im->writeImages('some/path/to', true)
```
For GD check animation:
```php
function is_animated($filename)
    $filecontents = file_get_contents($filename);

    $str_loc = 0;
    $count = 0;
    while ($count < 2) { // There is no point in continuing after we find a 2nd frame

        $where1 = strpos($filecontents, "\x00\x21\xF9\x04", $str_loc);
        if (!$where1) {
            break;
        } else {
            $str_loc = $where1 + 1;
            $where2 = strpos($filecontents, "\x00\x2C", $str_loc);
            if (!$where2) {
                break;
            } else {
                if ($where1 + 8 == $where2) {
                    ++$count;
                }
                $str_loc = $where2 + 1;
            }
        }
    }

    return $count > 1;
}
```

**Comment by NeilSeligmann** [comment]
Any News?

**Comment by diz123** [comment]
Any update for animated GIFs,?

**Comment by adumskis** [comment]
Still gif images are not supported

**Comment by HMAZonderland** [comment]
Perhaps make a pull request to help them out, if this is so important?

**Comment by YOzaz** [comment]
Up

**Comment by idevin** [comment]
Yeah i'm in too.

**Comment by odahcam** [comment]
The code a pasted above is not usefull?

**Comment by idevin** [comment]
Thanks, it's usefull!

**Comment by odahcam** [comment]
I have a full class that supports GIFs for working with the GD library. I can post it as a Gist if you like.

**Comment by odahcam** [comment]
Image GD class that supports manipulating GIFs: https://gist.github.com/odahcam/e7255f406e02ddf390080bf3add2cd43#file-imagegd-php-L4

**Comment by scottybo** [comment]
Any plans for this? Gifs are a big part of the web these days...

**Comment by scottybo** [comment]
Any update on this? :)

**Comment by MegaphoneJon** [comment]
@olivervogel You mention above a development branch, but I can't seem to find it anywhere.  Is it public?  If so, where might one find it?  And of course, thanks for this great package!

**Comment by kennyalmendral** [comment]
Thanks @marcoflorian

**Comment by brandonburkett** [comment]
I am interested in this one as well.  I see only the first frame is captured on resize, so for now will just copy GIF resources.

**Comment by ipiqadm** [comment]
Simply curious does anyone know how to make Intervention just completely ignore modifications  to gifs completely? For example I have stored animated gifs (these are unaltered and just stay as files served to end users) and just simply using Intervention as a means to fix the content types /mime types for Internet Explorer. Without Intervention they show as text/gif vs the proper image/gif to display in IE. Seems like when end clients load the gifs Intervention is improperly modifying the gifs and only showing a static first frame of the gif even though it shouldn't be modifying it in any way.

**Comment by patricknelson** [comment]
@olivervogel, I know this is ancient, but are you still able to link to the development code that was referenced above? I'm not seeing anything anymore except for a `master` and a `1.6` branch in this repository. I'm asking because I'd like to potentially expand upon what's already built, if possible (since I need this for something I'm working on and may need to move to `intervention/image` myself in the future, i.e. SilverStripe v4). So, if we can incorporate this as core functionality (at least with `Imagick`) I may be interested.

**For what it's worth:** This is the first time I've looked at `intervention/image`. However, digging deeper into how this would work in `Imagick` at least, I think this has probably lagged behind a bit, since working with an animated `gif` seems to require that you basically iterate over every single frame as it's own separate instance of `Imagick` (a child of the parent instance) and then and apply the defined transformations repeatedly (e.g. `->resize()`, `->resizeCanvas()`, `->fit()` and etc.) before being merged back together as a single image (i.e. the final encoded blob/file, per the internal API). I'm not sure how this would be accomplished internally within this library, but I could see how that might require yet another layer of abstraction/complexity. For example, maybe one could ensure that if this is an animated `gif` (e.g. `Imagick->count() > 0`) you would wrap the execution of commands in an iteration that would be called on a cached result of `Imagick->coalesceImages()`. I don't know; I haven't actually used this library yet, but I will someday 😄.

**Comment by LewisLarsen** [comment]
Still interested in animated gif support, this package is almost perfect, the lack of gif support does hurt though!

**Comment by wiejakp** [comment]
> Still interested in animated gif support, this package is almost perfect, the lack of gif support does hurt though!

As previous fella. :)

**Comment by Snakzi** [comment]
How is this still not a thing?

**Comment by mrchimp** [comment]
Is anybody actively working on this? Has there been any work done on this? Is there a branch that I could pick up? What's stopping it? Complexity and/or lack of developer motivation? Technical hurdles?

**Comment by maxvisser** [comment]
We at Forus are also really interested in such a feature.

**Comment by singleseeker** [comment]
Any updae?

**Comment by Snakzi** [comment]
> Any updae?

There will never be an update. Just use ImageMagick

**Comment by totten** [comment]
Ooh, I haven't looked for a while, but there are some encouraging signs:

* There are tags for`3.0.0.alpha{1,2,3}` at the start of the year (eg [alpha3](https://github.com/Intervention/image/commits/3.0.0-alpha.3))
* 3.0 [uses another library](https://github.com/Intervention/image/commit/d47e83fc0ed7b47f3c3512732ab95fcd5bd7228b) whose purpose appears to be [decoding/encoding animated gifs](https://github.com/Intervention/gif).
* If you dig into the docs, there is a section about 3.0 alpha: (https://image.intervention.io/v3).

@olivervogel Does this mean it's a good time for some alpha testers?

**Comment by MegaphoneJon** [comment]
@totten 3.0.0.alpha4 was released on Packagist this month, and contains explicit links to v3 documentation, so I think it's reasonable to assume that v3 is publicly available in alpha.

**Comment by Stevemoretz** [comment]
> 

Yeah it doesn't work with imagick either, at least not without a workaround, v3.0 will probably contain this feature though.

So it's not never.
