### ISSUE TITLE
Call to undefined function Intervention\Image\finfo_buffer() while trying to make am image

### ISSUE THREAD

**Issue by developernaren** [Intervention/image#184]
I had added this issue to the previous issue but since the issue was closed  I did not get the answer. so i am craeting a new issue.

I have been stuck at this for days and everywhere I look the solution is fileinfo extension in PHP. I do not get this error while uploading file but while trying to resize or make a  image to try to resize.

I have fileinfo extension enabled in mine but I still get this error..
And yes I have restarted my WAMP server.
My Php version is 5.4.12

This is the part of my php.ini file.

```
;extension=php_exif.dll
```

   extension=php_fileinfo.dll
    extension=php_gd2.dll
    ;extension=php_gettext.dll
    ;extension=php_gmp.dll;

and this is the error

```
Call to undefined function Intervention\Image\finfo_buffer()
```

I just cannot get this working

this is my code
    $name = Input::file( 'image' )->getClientOriginalName();
    $path = './mypath/'.$name;
    Input::file( 'image' )->move( './mypath/', $name );
    $img = Image::make( $path );
    $img->resize( 300, null, function ( $constraint ) {
    $constraint->aspectRatio();
    });

```
$img->save('./mypath/abc' . $name );
```

**Comment by slikk66** [comment]
Comment here.. encountered same issue.  The finfo_file call in the File.php class doesn't work with S3 stream wrapper, commented it out and it works.

L#56
```if (file_exists($path) && is_file($path)) {
            //$this->mime = finfo_file(finfo_open(FILEINFO_MIME_TYPE), $path);
        }
```
