### ISSUE TITLE
Support for bmp image

### ISSUE THREAD

**Issue by lalop** [Intervention/image#200]
Hello,
Is there some plan to support bmp format ?

**Comment by Niktux** [comment]
Hello,
BMP support was introduced in GD 2.1 : http://php.net/manual/en/intro.image.php
Any plan to support it in Intervention ? (Imagick is not ok because it's very greedy in production)

Thank you in advance for your reply !

**Comment by hackel** [comment]
This was resolved in #984.  Look forward to seeing it in an upcoming release.

**Comment by Niktux** [comment]
Great news. Many thanks
