### ISSUE TITLE
imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Premature end of JPEG file

### ISSUE THREAD

**Issue by altrim** [Intervention/image#21]
I am using this package with laravel and for some files that I am trying to resize it happens randomly I get this error:

> imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Premature end of JPEG file"

**Stack Frame**

```
/Applications/MAMP/htdocs/laravelweb/vendor/intervention/image/src/Intervention/Image/Image.php

       case IMG_PNG:
       case 3:
       $this->resource = imagecreatefrompng($path);
       break;

       case IMG_JPG:
       case 2:
       $this->resource = imagecreatefromjpeg($path);
       break;
```

**Comment by barryvdh** [comment]
Also see this thread: https://github.com/owncloud/core/pull/21950

Perhaps we should add that here also?

**Comment by barryvdh** [comment]
Also, with Laravel, I think the problem is that instead of warnings, that options generates notices. And notices are still triggering the error handler. So you might want to change your error reporting settings to ignore notices.

**Comment by stueynet** [comment]
@barryvdh I am getting this as well. What exactly is the Laravel fix you are mentioning above? How would one specifically ignore this notice. I am finding it behaves differently on different environments. it definitely starts with the image though. In my case it seems to often be images taken via an Android device and then uploaded to our web app. On some deployments it causes:

`Intervention\Image\Exception\NotReadableException`

And on others I get
`imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: `

In the second case the images all get created just fine though despite the error getting thrown.

**Comment by hassanamirkhan** [comment]
You can set default value of  `gd.jpeg_ignore_warning=1` in `php.ini`

OR

You can set it like this `ini_set('gd.jpeg_ignore_warning', true);` in your PHP script before calling  `imagecreatefromjpeg()` 

After implementing any of the above, GD Library will ignore the error where it use to fail and  `imagecreatefromjpeg()`  will return an `image resource identifier`.

Note: In `PHP 7.1.0` the default value of `gd.jpeg_ignore_warning` has been changed from `0` to `1`.

**[Reference][1]**


  [1]: https://www.facebook.com/notes/php-tutors/php-gd-library-imagecreatefromjpeg-premature-end-of-jpeg-file-issue/721592434694661

**Comment by jaystream** [comment]
Thank you. It solve my problem.
