### ISSUE TITLE
Multiline text centering

### ISSUE THREAD

**Issue by kivivuori** [Intervention/image#219]
Text methods callback parameter align doesn't center multiline text. I'm using GD library. See the image below.

![image](https://cloud.githubusercontent.com/assets/364219/4088506/18c47404-2f5e-11e4-83a1-361b395ca5ac.png)

**Comment by emir** [comment]
I've same problem about centered text.

**Comment by setvir** [comment]
Hope this will help someone:
`    $img2 = Image::canvas(300,250);`
`        $string = wordwrap($name,15,"|");`
`	$strings = explode("|",$string);`
`	$i=3;`
`	foreach($strings as $string){`
`		$img2->text($string, 150, $i, function($font) {`
`			$font->file('fonts/RobotoCondensed-Bold.ttf');`
`		    $font->size(40);`
`		    $font->color('#826c61');`
`		    $font->align('center');`
`		    $font->valign('top');`
`		});`
`		$i=$i+42;`
`	}`

**Comment by imuller** [comment]
@setvir Thanks!

**Comment by olivervogel** [comment]
This issue should no longer occur in [version 3](https://image.intervention.io/v3/modifying/text-fonts).
