### ISSUE TITLE
Blur, Fill  X Y 

### ISSUE THREAD

**Issue by JohnDotOwl** [Intervention/image#225]
Can i define X Y like CROP for Blur or any other suggested function that could hide/blur a specific x y range. I'm trying to blur text I "Crop" from images.

**Comment by maiorano84** [comment]
I'd like to re-open this, as I'm looking to do something similar. Maybe I can explain the use-case:

Part of the application we're building involves moderation for user-uploaded photos. As part of that, we're building out a UI for administrators to go in and blur out sections of photographs that either contain private information, branding that hasn't been approved by a given company, or other pieces of content that isn't quite suitable for the site but can be doctored to fit in with the site's guidelines.

We're exploring a few different options, but your package seems to be the closest in offering the most "complete" solution that we have to work with.

While I understand this might be an edge case, I think there could be some value in providing something like x/y coordinate arguments for the blur tool.

But in the meantime, I'm thinking the only way to implement a partial blur would be to crop a specific part of the image out, blur the crop, and layer it over the original in the same spot. Just a thought, but if you had any insight, that would certainly be appreciated.

**Comment by olivervogel** [comment]
> But in the meantime, I'm thinking the only way to implement a partial blur would be to crop a specific part of the image out, blur the crop, and layer it over the original in the same spot. Just a thought, but if you had any insight, that would certainly be appreciated.

I would do this the same way, and wrap it into a [filter class](http://image.intervention.io/use/filters).

**Comment by maiorano84** [comment]
For reference, I was able to achieve this behavior like so:

https://gist.github.com/maiorano84/9e85495b7ebfe41161f1
