### ISSUE TITLE
Intervention/image with Flysystem

### ISSUE THREAD

**Issue by mikeshow** [Intervention/image#228]
Hello,

I just discovered Flysystem and learn that it will be integrated into Laravel 5.0. Is it possible to use Flysystem with Intervention/image right now in Larravel 4.2 and how, or do you plan to support it?

Thanks.

**Comment by marlongichie** [comment]
Hello @mikeshow , @olivervogel 

I seem to be experiencing the same issue. @mikeshow , were you able to figure out what exactly the problem was?

**Comment by mikeshow** [comment]
Hello Marlon,

Yes I solved my problem, mainly a semantic one. Here the function to save photos either on dropbox or on local system using flysystem in laravel 4.2 probably works as is in 5.0:

```

   public function storeFlysystem($sadapter)
   {
      if (Session::token() != Input::get('_token'))
      {
         Session::flash('message', 'Error CSRF');
         return Redirect::route('admin.photos.index', array($sadapter));
      }

      $client = null;
      $filesystem = null;
      $subdirphoto = '';

      if ('DB' == $sadapter)
      {
         $client = new Client(Config::get('dropbox.token'), Config::get('dropbox.appName'));
         $filesystem = new Filesystem(new adaptDropbox($client, 'public'));
         $subdirphoto = 'db';
      }
      elseif ('LC' == $sadapter)
      {
         $client = asset('public');
         $filesystem = new Filesystem(new adapLocal($client));
         $subdirphoto = 'local';
      }

      $files = Input::file('photo');
      if (null != $files[0])
      {
         try
         {
            foreach ($files as $fileimg)
            {
               // --------------------------------------------------------------------
               // Do some checking.
               //
               $imgfilename = '[file: ' . $fileimg->getClientOriginalName() . '] ';

               switch ($fileimg->getError())
               {
                  case UPLOAD_ERR_OK:
                     break;
                  case UPLOAD_ERR_NO_FILE:
                     throw new RuntimeException($imgfilename . 'No file sent.');
                  case UPLOAD_ERR_INI_SIZE:
                  case UPLOAD_ERR_FORM_SIZE:
                     throw new RuntimeException($imgfilename . 'Exceeded System filesize limit.');
                  default:
                     throw new RuntimeException($imgfilename . 'Unknown errors.');
               }

               if ($fileimg->getClientSize() > 1048576)
               {
                  throw new RuntimeException($imgfilename . 'Exceeded filesize limit (>1MB).');
               }

               if ($fileimg->getClientMimeType() != 'image/jpeg')
               {
                  throw new RuntimeException($imgfilename . 'Invalid file format. Must be jpeg.');
               }
               //
               // --------------------------------------------------------------------
               $newfilename = Str::slug(Str::random(32));
               $origfile = $fileimg->getRealPath();
               $extension = $fileimg->getClientOriginalExtension();
               $dirphoto = Config::get('packages/intervention/image/config.dir_img_brides') . '/' . $subdirphoto;

               $photo_dsktp = Image::make($origfile);
               $photo_dsktp->resize(Config::get('packages/intervention/image/config.desktop_width'), null, function ($constraint)
               {
                  $constraint->aspectRatio();
               });
               $photo_dsktp->encode('jpg');

               try
               {
                  $filesystem->put($dirphoto . '/' . $newfilename . '.' . $extension, (string)$photo_dsktp);
               } catch (Exception $e)
               {
                  // Problem during the write of a file
                  Session::flash('message', '(' . $dirphoto . '/' . $newfilename . '.' . $extension . ') ' . $e->getMessage());
                  return Redirect::route('admin.photos.index', array($sadapter));
               }
            }
         } catch (RuntimeException $e)
         {
            // Problem during the read of a file
            Session::flash('message', $e->getMessage());
            return Redirect::route('admin.photos.index', array($sadapter));
         }

         Session::flash('message', 'Add with success!');
         return Redirect::route('admin.photos.index', array($sadapter));
      }
      else
      {
         return Redirect::route('admin.photos.create', array($sadapter))
            ->withInput()
            ->with('message', 'Error file photo.');
      }
   }

```

As you can see save the photo with a random name (str::random(32)) both for security reason and to avoid funky names sometimes given by users.

Kindly.

**Comment by bkschatz** [comment]
Thank you for this!  It was causing me all kinds of headaches.  It does work in the homestead vm, but within the forge standard deployment it didn't.  I wonder if there is an issue with mime detection settings on the standard forge deployment.

**Comment by mikeshow** [comment]
Unfortunately I have no experience on this.

**Comment by marlongichie** [comment]
@bkschatz @mikeshow 

The implementation that worked for me both in homestead and forge is pretty much what @olivervogel suggested.

From what I have seen this line is important `Flysystem::put($upload_path, (string) $image);` as it casts the `Image` created by `InterventionImage` to string  during the actual upload.

It also worked using it as `Flysystem::put($upload_path, $image->_toString());`

Hope this helps.

```
 public function upload($file)
 {
        $filename = strtolower(str_random(40)) . '.' . $file->getClientOriginalExtension();

        $image = Image::make($file)
                        ->encode($file->getClientOriginalExtension())
                        ->save();

        try
        {
            $upload_path = getenv('UPLOAD_DIRECTORY') . $filename;

            Flysystem::put($upload_path, (string) $image);
        }
        catch (Exception $ex)
        {
            return 'Upload failed';
        }

        return $filename;
 }
```

**Comment by bkschatz** [comment]
@marlongichie
It did work for me.  I was just saying that it works without (string) on my vm (laravel/homestead), but it doesn't in production.  I was looking at the errors and it stemmed from a mime detection problem on the production system.  So there is some configuration or outdated package that throwing that error.

Thanks for the help!

Brandon

**Comment by nWidart** [comment]
Hello,

I'm having similar issue with the `->writeStream()` method on Flysystem. I previously used the `->encode()` method too on Intervention/Image, but since it needs a stream I used this instead:

``` php
$image = $image->stream(pathinfo($path, PATHINFO_EXTENSION));

$this->filesystem->disk($this->getConfiguredFilesystem())->writeStream($filename, $image, [
    'visibility' => 'public',
    'mimetype' => 'image/png',
]);
```

Issue with this is that `writeStream` requires a 'stream', ie I'm getting this error: 

```
League\Flysystem\Filesystem::writeStream expects argument #2 to be a valid resource.
```

While the `->stream()` method returns an instance of `GuzzleHttp\Psr7\Stream`. 

Any ideas how I could get an actual resource ?

Thank you

**Comment by frankdejonge** [comment]
@nWidart you can get the resource by calling the `detach` method on the `GuzzleHttp\Psr7\Stream` response.

**Comment by nWidart** [comment]
That works, thank you very much! :smile:

**Comment by jcogs-design** [comment]
Following up on [this post](https://github.com/Intervention/image/issues/228#issuecomment-55908512)

> ```
> use Dropbox\Client;
> use League\Flysystem\Filesystem;
> use League\Flysystem\Adapter\Dropbox as Adapter;
> 
> $client = new Client($token, $appName);
> $filesystem = new Filesystem(new Adapter($client, 'path/optional'));
> 
> $img = Image::make($filepath);
> $img->widen(50);
> $img->encode('png');
> 
> $d = $filesystem->put('test.png', (string) $img);
> ```

What is the Imagine 2.x equivalent to `encode()`?
