### ISSUE TITLE
Encoding format (tmp) is not supported.

### ISSUE THREAD

**Issue by marcoflorian** [Intervention/image#231]
On windows servers where the file is saved as tmp, file is not recognized as an image. Although, Laravel does validate it as an image with Validator.

**Comment by rahilwazir** [comment]
> for security reasons I usually don't do this but create random/hashed filenames and convert any format to jpg

@olivervogel Even `.gif`?

**Comment by Kolyunya** [comment]
@olivervogel in my particular scenario I need to save resized files with `:100x200` suffixes like `file.jpg:100x200`. Seems to be impossible in current state of the library, isn't it? Upvoting to add an `format` parameter. This won't even break the BC.

**Comment by qingchengdelaike** [comment]
vendor\intervention\image\src\Intervention\Image\Image.php
 I think like this to fix it on windows server error:
row 131:
$file = fopen($path, "rb");
        $bin = fread($file, 2); //only read 2 bit
        fclose($file);
        $strInfo = @unpack("C2chars", $bin);
        $typeCode = intval($strInfo['chars1'].$strInfo['chars2']);
        $fileType = '';
        switch ($typeCode)
        {
        	case 7790:
        		$fileType = 'exe';
        		break;
        	case 7784:
        		$fileType = 'midi';
        		break;
        	case 8297:
        		$fileType = 'rar';
        		break;
        	case 8075:
        		$fileType = 'zip';
        		break;
        	case 255216:
        		$fileType = 'jpg';
        		break;
        	case 7173:
        		$fileType = 'gif';
        		break;
        	case 6677:
        		$fileType = 'bmp';
        		break;
        	case 13780:
        		$fileType = 'png';
        		break;
        	default:
        		$fileType = 'unknown: '.$typeCode;
        } 
        
        if (is_null($path)) {
            throw new Exception\NotWritableException(
                "Can't write to undefined path."
            );
        }
        
        $data = $this->encode($fileType, $quality);

**Comment by raphaeldemedion** [comment]
> $img->save('foo' . $img->getClientOriginalExtension());

this worked for me, thanks man

**Comment by lexkyiv** [comment]
> $data = $this->encode($fileType, $quality);

thank you for this workaround, you're the best
