### ISSUE TITLE
Undefined index: _sf2_meta

### ISSUE THREAD

**Issue by mouhsinelonly** [Intervention/image#238]
i'm getting this error when using Laravel 5 ,i hope for a fix soon

**Comment by PhilMarc** [comment]
I am still getting this error, the solution by jmfleming works, but I have to manually do it each time I run composer update...

**Comment by jmfleming** [comment]
@PhilMarc You can use this in Laravel without using the service provider.  Changed to this awhile back and works the same.  It does change the code a bit though, which is the only downside.  Does allow you to composer update and not worry about blowing the fix away.

**Comment by atmediauk** [comment]
as @jmfleming flemming mentioned, after commenting out the line:
https://github.com/Intervention/image/blob/master/src/Intervention/Image/ImageServiceProviderLaravel5.php#L88 

The url based images seem to work as expected again (it seemed to break after moving to L5).

**Comment by olivervogel** [comment]
I had no problems with this line in Laravel 5.

```php
$app['config']->set('session.driver', 'array');
```

But another session cookie for XSRF-TOKEN is set anyway, so session cookies are not completely disabled for the route. Hence I removed the line in 8f3761154b4c1f5128365dfc32cbf757f27d97b6 for now. At least until I can figure out a way, how to disable session cookies completely for a certain route from a ServiceProvider.

**Comment by atmediauk** [comment]
Thanks, appreciate that. I don't think their is a simple way to unset middleware in a package. Most people suggest manually removing from the global kernel array which isn't ideal. 

I'm not sure if it helps but I am using Laravel 5 in conjunction with Platform by Cartalyst (https://cartalyst.com/). 

Thanks again

**Comment by iamfreee** [comment]
Still getting this error :cry:

**Comment by baribadamshin** [comment]
Still getting this error

**Comment by RobinMalfait** [comment]
I am also getting this error...

**Comment by olivervogel** [comment]
Make sure you are on the newest version. The problematic line should no longer be present in `
/src/Intervention/Image/ImageServiceProviderLaravel5.php`.

```php
// should be gone
$app['config']->set('session.driver', 'array');
```

**Comment by thbsolutions** [comment]
Still getting this error..

**Comment by youndivian** [comment]
I am also getting this error

**Comment by youndivian** [comment]
for me the problem was in Illuminate\Session\Store.php on line 286, so I changed from this:
```
foreach (array_merge($this->bags, [$this->metaBag]) as $bag) {
       $this->put($bag->getStorageKey(), $this->bagData[$bag->getStorageKey()]);
}

```

to this:
```
 foreach (array_merge($this->bags, [$this->metaBag]) as $bag) {
       if(isset($this->bagData[$bag->getStorageKey()])){
         $this->put($bag->getStorageKey(), $this->bagData[$bag->getStorageKey()]);
       }
 }


```

**Comment by ogrethegreat** [comment]
This can be solved by 

     config()->set('session.driver', null);

rather than editing core.
