### ISSUE TITLE
Image source not readable - make from base64 encoded data

### ISSUE THREAD

**Issue by simplenotezy** [Intervention/image#245]
I am trying to generate an image from a base64 encoded string. As far as I have found out, this should be possible.

By doing:

```
$image = Image::make('iVBORw0K..');
echo $image->response('jpg', 70);
```

I get "Image source not readable".

(during testing, I have encoded a random image from this service: http://base64image.org/).

**Comment by CLOUGH** [comment]
Awsome this helped
