### ISSUE TITLE
Saturation command

### ISSUE THREAD

**Issue by neon64** [Intervention/image#256]
I was wondering if it would be possible to implement a saturation command. It seems like a very common use case that unfortunately this package doesn't provide.

**Comment by Reeslo** [comment]
Hi,

I create a command

```php
<?php

namespace Intervention\Image\Imagick\Commands;

class SaturateCommand extends \Intervention\Image\Commands\AbstractCommand
{
    /**
     * Changes image brightness
     *
     * @param  \Intervention\Image\Image $image
     * @return boolean
     */
    public function execute($image)
    {
        $level = $this->argument(0)->between(-100, 100)->required()->value();

        return $image->getCore()->modulateImage(100, 100 + $level, 100);
    }
}

```

How can I register this command in my app ?

**Comment by olivervogel** [comment]
I would rather extend the library with the [filter architecture](http://image.intervention.io/use/filters).

**Comment by MitchellBouwman** [comment]
@reeslo Did you find out? Really interested in finding out how to do it.

**Comment by reeslo** [comment]
nope sorry :/
