### ISSUE TITLE
Draw transparent rectangle on JPEG image

### ISSUE THREAD

**Issue by mweghorst** [Intervention/image#257]
When I tried drawing a transparent rectangle onto a jpeg image resource I was not able to set an alpha value. Adding

``` php
$this->gdResourceToTruecolor($core);
```

after line 34 in /Image/Gd/Decoder.php fixed it for me. Is this a bug or is that call left out on purpose?

My code:

``` php
$image->rectangle($x1, $y1, $x2, $y2, function ($draw) {
    $draw->background( array(255, 255, 255, 0.5 )
});
```

**Comment by n8udd** [comment]
This appears to still be an issue.

i am unable to get a transparent rectangle if I edit the image before creating the rectangle (which I need to do to re-size and crop it before adding the rectangle).

**Comment by ahosker** [comment]
This is still an issue. I called this first and the transparency broke.
` $img->resize($width, $height);`

**Comment by ekpono** [comment]
I am having the same issue.
Is there any workaround?
