### ISSUE TITLE
memory_limit

### ISSUE THREAD

**Issue by mrgauthier** [Intervention/image#267]
Seems that when processing images in a loop with Intervention/Image memory tends to run away...  Even when using `destroy()` method at the end of each loop.    It's easy enough to disable **memory_limit** in php, but when processing large batches of images memory eventually exceeds cpu memory.   Any thoughts on this?

**Comment by solcik** [comment]
I had same problem with loop:
- one Image object
- backup() before loop
- in loop resizing sending to s3
- at the end of loop reset()
- after loop destroy()

Memory was going away pretty quick.

When I changed that to:
- destroy() before loop
- in loop new object
- at the end of the loop destroy

Suddenly there is no problem.
