### ISSUE TITLE
Unable to init from given url 

### ISSUE THREAD

**Issue by ronjunevaldoz** [Intervention/image#283]
http://cdn.dota2.com/apps/570/icons/econ/leagues/subscriptions_ren_ren_yi_che_joy_league_first_season_large.1cf72b430b0f4bac6fd480b4f79e82448d8eefde.p

Why error was thrown in this url using remote url?

**Comment by eswarreddy43** [comment]
I am also facing the same problem.

I have used following code
```
$img = Image::make($myUrl);
```

Please refer my error.
```
{
"success":false,
"message":{
"id":100,
"description":"Unable to init from given url (https://s3urlhere/temp/2015/15/1428665024-sintel-trailer.png).. FILE:: /mnt/hgfs/myproject/backend/api/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php LINE:: 70TRACE:: #0 /mnt/hgfs/myproject/backend/api/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(245): Intervention\\Image\\AbstractDecoder->initFromUrl()\n#1 /mnt/hgfs/myproject/backend/api/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\\Image\\AbstractDecoder->init()\n#2 /mnt/hgfs/myproject/backend/api/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\\Image\\AbstractDriver->init()\n#3 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(3267): Intervention\\Image\\ImageManager->make()\n#4 /mnt/hgfs/myproject/backend/api/app/controllers/v1/CommonController.php(235): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#5 (): v1\\CommonController->cropImage()\n#6 /mnt/hgfs/myproject/backend/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array()\n#7 /mnt/hgfs/myproject/backend/api/app/controllers/RouteController.php(66): Illuminate\\Routing\\Controller->callAction()\n#8 (): RouteController->route()\n#9 /mnt/hgfs/myproject/backend/api/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array()\n#10 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5847): Illuminate\\Routing\\Controller->callAction()\n#11 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5835): Illuminate\\Routing\\ControllerDispatcher->call()\n#12 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5040): Illuminate\\Routing\\ControllerDispatcher->dispatch()\n#13 (): Closure$Illuminate\\Routing\\Router::getClassClosure()\n#14 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5398): call_user_func_array()\n#15 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5065): Illuminate\\Routing\\Route->run()\n#16 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(5053): Illuminate\\Routing\\Router->dispatchToRoute()\n#17 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(715): Illuminate\\Routing\\Router->dispatch()\n#18 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(696): Illuminate\\Foundation\\Application->dispatch()\n#19 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(7825): Illuminate\\Foundation\\Application->handle()\n#20 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(8432): Illuminate\\Session\\Middleware->handle()\n#21 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(8379): Illuminate\\Cookie\\Queue->handle()\n#22 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(11045): Illuminate\\Cookie\\Guard->handle()\n#23 /mnt/hgfs/myproject/backend/api/bootstrap/compiled.php(657): Stack\\StackedHttpKernel->handle()\n#24 /mnt/hgfs/myproject/backend/api/htdocs/index.php(72): Illuminate\\Foundation\\Application->run()\n#25 {main}"
},
"data":[
]
}
```

**Comment by lianwenjun** [comment]
I know it you can catch the error than give a default image for your code

**Comment by samthomson** [comment]
I reccommend adding a leading slash to @lianwenjun answer above to make it work across classes in different namespaces. Like so:

catch (\Intervention\Image\Exception\NotReadableException $e)

**Comment by notflip** [comment]
Is there any news on this? I also get this error, but only on the live server, not on my localhost

**Comment by Philwn** [comment]
I am also receiving this error, development version works fine, staging server NotReadableException, yet the image url it gives is correct and pasted in a new window shows the correct image.

**Comment by Alver23** [comment]
this error have solution ?

**Comment by Jossnaz** [comment]
@Alver23 actually it seems that requesting the file via HTTPS did not work for me. I did the following:

```
    $manager = new ImageManager();
    $image_url = str_replace('https', 'http', strtolower($image_url));
    $image = $manager->make( $image_url );

```

this works. Is it because of expired https certificate? invalid certificate? i dont know

**Comment by cillosis** [comment]
I just wanted to add a comment here since I found this via a Google search and none of the solutions helped. 

In my case, I got "Unable to init from given url", but running it directly in the browser showed "Request has expired". Turns out the time on the server (EC2 - Ubuntu) had drifted from what Amazon S3 had, causing the signed URL's to be immediately expired. Had to install NTP and force the clock to sync:

    sudo apt-get install ntp -y
    sudo service ntp stop
    sudo ntpdate -s time.nist.gov
    sudo service ntp start

**Comment by juanmonstra** [comment]
+1 >> Laravel 5.4
The file exists, but exception still happends only to a few images. All requests are only http.
I make a horrible solution to keep recalling the same URL until works, but some time the scripts is executed 15 times to be able to get image.

**Comment by amitgds** [comment]
I am getting the same "unable to init from given url" error on live, staging and development environment. But when I try to open the image url in browser's new tab it works it means that the images are there but there is something else which keeps displaying this error. One strange thing happen is when I tried to load page 2-3 time after getting error message it some time starts working.  I am using  "intervention/image": "^2.3" package. 
"laravel/framework": "5.2.*"

----Code ----
$canvas = \Image::canvas($w, $h);
$image = \Image::make($imageUrl)->resize($w, $h,
                function($constraint) {
                $constraint->aspectRatio();
            });
return $canvas->insert($image, 'center')->encode('data-url');

Can any body help me to get rid of this issue...

**Comment by amitgds** [comment]
Hi Guys can any body help me as I am  getting the same error again and again on my live website.

**Comment by jerauf** [comment]
I started getting this error since updating to Laravel 5.5. Can anyone help?

**Comment by zschuessler** [comment]
For anyone else who is lost and has verified the following:

1. GD library installed, apache restarted
2. Image exists and is writable
3. Saving works locally, but not on staging or production environments
4. Typical normal stuff to check (composer dependencies installed, etc)

I found out that this won't work:
`$fullFilePath = \Storage::disk('public')->url($filePath);`

But this does:
`$fullFilePath = \Storage::disk('public')->get($filePath);`

The above uses a real url, while the second uses the full file path. This is odd because my PHP settings would imply this shouldn't be a problem, but it is. fopen is enabled, and everything else looks OK.

@olivervogel Do you know why this might be? Btw very much appreciate this package and your work on it!

**Comment by panique** [comment]
Same here (with image https-image-urls), I could workaround by replacing `https` with `http` :)

**Comment by jonbonsilver** [comment]
If you code worked locally don't try these workarounds. All Intervention's make() function does is call php's file_get_contents() function.

The solution is to edit your php.ini and set allow_url_fopen to 1.

I upgraded to php 7.2 and this function was disabled which confused me too.

**Comment by laocoi** [comment]
Try to add this line to php.ini config
```
openssl.cafile=/path/cacert.pem
```
Download cacert at here: https://curl.haxx.se/docs/caextract.html

**Comment by AkshayBaldia** [comment]
I am getting the same error and my function is 

public function getCachedImage($cacheSubDir, $imageUrl, $width = 480, $height = 320)
    {
        Image::configure(["cache" => ['path' => base_path('public/thumbs') . $cacheSubDir]]);

        try {
            $img = Image::cache(function ($image) use ($imageUrl, $width, $height) {
                $image->make($imageUrl)->resize($width, $height, function($constrain){
                                                $constrain->aspectRatio();
                                        });
            }, 10, true);
        } catch (NotReadableException $nre) {
            /* Fall back to no-photo image if the listing photo can't be found */
            $img = Image::make(base_path('public/images/default.jpg'))->resize($width, $height);
        }

        return $img->interlace();
    }

**Comment by AkshayBaldia** [comment]
I got this error. Try to hit image URL with **http://** and see network log from the console. It hits two requests one returns 302 and then it hit **https://** which returns 200. Try to force hit request with **https://**

**Comment by AkshayBaldia** [comment]
Getting another error for default image.

**Error message:** Intervention\Image\Exception\NotReadableException:** Unable to init from given url (https://www.crye-leike.com/images/default.jpg)

public function getCachedImage($cacheSubDir, $imageUrl, $width = 480, $height = 320)
{
Image::configure(["cache" => ['path' => base_path('public/thumbs') . $cacheSubDir]]);
try {
        $img = Image::cache(function ($image) use ($imageUrl, $width, $height) {
            $image->make($imageUrl)->resize($width, $height, function($constrain){
                                            $constrain->aspectRatio();
                                    });
        }, 10, true);
    } catch (NotReadableException $nre) {
        /* Fall back to no-photo image if the listing photo can't be found */
        $img = Image::make(base_path('public/images/default.jpg'))->resize($width, $height);
    }
    return $img->interlace();
}

**Comment by iraldoad** [comment]
I have the same problem.

![DeepinScreenshot_20190524183855](https://user-images.githubusercontent.com/15159678/58361308-3b130b80-7e53-11e9-8d47-22dd53ac8254.png)

![DeepinScreenshot_20190524183908](https://user-images.githubusercontent.com/15159678/58361310-3ea69280-7e53-11e9-9e0e-443c7dcbfe90.png)

**Comment by ousid** [comment]
>Asset helper returns a URL. You don't want a URL when working with files, you want a PATH that the filesystem can understand

> try storage_path/public_path instead

```php
$img = Image::make(storage_path('assets/images/sample.png'));
```
Adjust your path to suit, I doubt it is storage/app/public/profile/sample.php because that's a PHP file

Take a look at the answer [here](https://laracasts.com/discuss/channels/laravel/unable-to-init-from-given-binary-data-intervention-laravel-56)

**Comment by uaibo** [comment]
This is most probably because you may be using a self-signed certificate and it can't be verified properly.

InterventionImage uses [stream_context_create][1] which by default verifies the certificate.

Since Intervention Image doesn't directly allow a workaround via options, open ```vendor/intervention/image/src/Intervention/Image/AbstractDecoder``` and inside the function ```initFromUrl()``` add this 
```
'ssl' => array(
   'verify_peer'   => false,
)
```

It will look something like this:
```
$options = [
   'http' => [
      'method'=>"GET",
      'protocol_version'=>1.1, // force use HTTP 1.1 for service mesh environment with envoy
      'header'=>"Accept-language: en\r\n".
       "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36\r\n"
    ],
    'ssl' => array(
       // don't validate certificate
       'verify_peer'   => false,

       // alternatively you may add our certificate file path here and make
       'cafile'        => __DIR__ . '/cacert.pem',
       'verify_depth'  => 5,
       'CN_match'      => 'your-local-domain.com'
    )
 ];

$context  = stream_context_create($options);
```

It's not the perfect solution but it will allow you to continue to work locally.



  [1]: https://www.php.net/manual/en/function.stream-context-create.php

**Comment by tauseedzaman** [comment]
the same issue here when i use

this works
``
        $image = Image::make("https://plus.unsplash.com/premium_photo-1683631774703-f43d458bcf74");

``
and this does not
``
https://prote.satmk.com/core_invapp/public/storage/documents/O5vDeFo0FvXce74w72S6rvQPIC93iSlULzY4mpZr.jpg
``

**Comment by olivervogel** [comment]
The integration of the option to read data directly via URLs was a mistake. The task of this library is image manipulation. Reading data via HTTP should be done by a corresponding client. For this reason, Intervention Image Version 3 does not support reading URLs.
