### ISSUE TITLE
Callback: font size

### ISSUE THREAD

**Issue by filip01** [Intervention/image#290]
When you write text on image like 

$image->text("foo", 0, function($font) {
    $font->size(24);
});

font size actually never changes.

**Comment by olivervogel** [comment]
Please read [documentation](http://image.intervention.io/api/text). You have to provide a font file, to alter font sizes.

**Comment by userbq201** [comment]
font size actually never changes.
```php
text('test name',  100, 100, function($font) {
            $font->size(24);
            $font->color('#000');
            $font->align('center');
            $font->valign('bottom');
        })
```

**Comment by tisuchi** [comment]
@ghost

> Set font size in pixels. Font sizing is only available if a font file is set and will be ignored otherwise. Default: 12


http://image.intervention.io/api/text
