### ISSUE TITLE
Memory exhausted

### ISSUE THREAD

**Issue by alexbet** [Intervention/image#291]
First I must say that I absolutely love your library and i use it all the time.  

I am using your library with Laravel 4.2, and I am getting a "Allowed memory size of 134217728 bytes exhausted" when trying to resize and crop a 3.2Mb image. I am not sure what uses so much memory, but I think that you should look into this because I am pretty sure that a lot of people will get this error. The error happens on the line of code when I am trying to create a new image resource like this:

$img = Image::make($uploadedFile);

... where the $uploadedFile is the path to the newly uploaded file. 

I know that I can increase the memory limit, but I think that 128Mb is more than enough for this operation. Attached is the image that I am trying to manipulate for your convenience.

![285f2ef4-929b-11e4-9499-09c86683767a](https://cloud.githubusercontent.com/assets/3966760/5622735/011a26b4-9516-11e4-98d9-ad15fce323f8.JPG)
It would greatly help if you have a solution for this. Thanks!

**Comment by olivervogel** [comment]
With GD library you can't put filesize on a level with memory usage. GD unfortunately uses much more. For a 4000x3000 pixel image, RGB, 8 bits per channel you have to provide at least ~50 MB, just to get it into memory. Any manipulation takes up additional memory.

I recommend using Intervention/Image with Imagick, if you're dealing with large images. It's more memory efficient.

**Comment by alexbet** [comment]
OK, thanks Oliver!
