### ISSUE TITLE
2.0.17 - Class 'Intervention\Image\ImageServiceProvider' not found

### ISSUE THREAD

**Issue by Gisleburt** [Intervention/image#292]
Updating from 2.0.16 to 2.0.17 causes the following error when updating/installing with composer.

    PHP Fatal error:  Class 'Intervention\Image\ImageServiceProvider' not found in vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157

Returning to 2.0.16 fixes this error.

**Comment by olivervogel** [comment]
`2.0.17` only added one new command and didn't touch the ServiceProvider at all, I think the error is somewhere else. Which Laravel version are you using?

**Comment by Gisleburt** [comment]
4.2.16

**Comment by olivervogel** [comment]
I have a Laravel 4.2.16 installation running with Intervention Image 2.0.17 ... works fine.
