### ISSUE TITLE
How will I get box size of a text with custom font and size?

### ISSUE THREAD

**Issue by anupamsaha** [Intervention/image#294]
I am trying to write a text on a pre-printed certificate and want to calculate the x coordinate dynamically w.r.t. the width of the text used with the certain font and size. As a result, I want to calculate the text width before writing it on the image.

I see that there is a public method getBoxSize() exists in GD\Font.php file. How can I use that with Image::text() method or even call it seperately?

If there is a way, an example would be highly appreciated.

Thanks!

**Comment by olivervogel** [comment]
You can access the method inside the callback.

```php
$img->text('foo', 100, 100, function ($font) {

    $font->file('helvetica.otf');
    $font->size(40);

    // box size
    $box = $font->getBoxSize();

});
```

**Comment by anupamsaha** [comment]
Thanks for the reply. So, there is no way that I can call the method outside the closure?

**Comment by olivervogel** [comment]
You can make it global I guess.
