### ISSUE TITLE
Gradient colors

### ISSUE THREAD

**Issue by niknetniko** [Intervention/image#296]
I was wondering if it was possible to fill a canvas with a color gradient?

I'm trying to apply a reflection effect on my image, so I'd thought I do it like this:
- Make a new canvas twice the height of the image
- Make a reflection: flip the image and apply the gradient
- Paste the original and the reflection in the canvas.

However, I can't seem to find anything to do the second step. Am I missing anything or is it not supported right now?

**Comment by olivervogel** [comment]
Sorry, creating gradients is not supported out of the box.

**Comment by danielpost** [comment]
For anyone stumbling on this issue trying to add a gradient to their image, don't worry. **It's possible**. It's just going to take some extra work.

The easiest way is to create a gradient in your image editor, save it as a `.png` file and insert it on your `Intervention\Image\Image` instance using `insert()`. Boom, done. If you're looking for a method to change the color in PHP, try this:

In your image editor, create a new gradient on a transparent background. Make sure the color is `#777777`—a neutral grey. I've attached the gradient that I used to this comment, let's call it `gradient.png`. Mine goes from 0% opacity to 100% opacity, but you can tweak this however you like.

![gradient](https://user-images.githubusercontent.com/1713699/83338045-a42c2b00-a2c0-11ea-8d68-febf5bf05f1e.png)

Next, choose a color for your gradient. In this example, I'll use `#C45618`.

```php
use Intervention\Image\ImageManagerStatic as Image;

$color = '#C45618';
$r = round((hexdec(substr($color, 1, 2)) - 119) / 255 * 100);
$g = round((hexdec(substr($color, 3, 2)) - 119) / 255 * 100);
$b = round((hexdec(substr($color, 5, 2)) - 119) / 255 * 100);
$gradient = Image::make('gradient.png')->colorize($r, $g, $b);

// Add it to your image
$image = Image::canvas(1200, 630, '#fff');
$image->insert($gradient);
```

What's happening here? We're calculating the RGB difference between our chosen color and `#777777`, which is equal to `rgb(119, 119, 119)`. We then convert this difference to a number between `-100` and `100` for red, green and blue, and use the `colorize()` function to change the color of our gradient. This gives us the following image:

![1](https://user-images.githubusercontent.com/1713699/83338199-25d08880-a2c2-11ea-90ec-a394a257c4b9.png)

It's possible to tweak the size and direction of the gradient using `rotate()`, `flip()` etc. It's not perfect (some of the gray leaks through) but it might be helpful.

**Comment by therajumandapati** [comment]
For the next person to stumble on this, here's what I did to create gradients with this library. 

The primary function to call is `createAndApplyGradient` and pass in your ImageManager (only tested to work with `GD`) that can be used to create a canvas, and this new canvas will be filled into the existing `Image`. The colors for gradients are available in the class this function lives in. See `$this->bgColor[0]` and `$this->bgColor[1]`. Hope this helps. 

```
    private function createAndApplyGradient(ImageManager $image, Image $avatar, $width, $height): Image {
       $gradient = $this->applyHorizontalGradientToImageCanvas($image->canvas($width, $height), $width, $height);
       $avatar->fill($gradient);
        return $avatar;
    }

    private function calculateRgbValues($start, $end, $steps, $i): array {
        $r = $start[0] - ((($start[0]-$end[0])/$steps)*$i);
        $g = $start[1] - ((($start[1]-$end[1])/$steps)*$i);
        $b = $start[2] - ((($start[2]-$end[2])/$steps)*$i);

        return [$r, $g, $b];
    }

    private function applyHorizontalGradientToImageCanvas($canvas, $width, $height): Image {
        $x = 0;
        $y = 0;
        $x1 = $width;
        $y1 = $height;
        $steps = $x1 - $x;
        for($i = 0; $i < $steps; $i++) {
            list($r, $g, $b) = $this->calculateRgbValues($this->bgColor[0], $this->bgColor[1], $steps, $i);
            $apply_x = $x+$i;
            $apply_x1 = $x1+$i+1;
            $canvas->rectangle($apply_x, $y, $apply_x1, $y1, function ($draw) use($r, $g, $b) {
                $draw->background([$r, $g, $b]);
            });
        }
        return $canvas;
    }
```
