### ISSUE TITLE
Issue for Laravel 5

### ISSUE THREAD

**Issue by fdusautoir** [Intervention/image#300]
Hi there  :)

Any issue for Laravel 5 ?  L5 don't support package at this time and can't run Intevention Image  :(
Taylor said a few hours ago :  "go ahead and start hacking with L5 even if it’s not totally released because it’s mainly just minor polish and docs now"

Source : Twitter -> https://twitter.com/taylorotwell/status/553325029854052352

Please  :)

**Comment by Aaron3** [comment]
More info: https://github.com/laravel/framework/issues/6583

**Comment by olivervogel** [comment]
Please read https://github.com/Intervention/image/issues/307

**Comment by morrislaptop** [comment]
Hey guys,

I've got an interim work around - https://github.com/morrislaptop/LaravelFivePackageBridges

Cheers,
Craig
