### ISSUE TITLE
Output as download (browser inline, etc.)?

### ISSUE THREAD

**Issue by jamesgrayillustration** [Intervention/image#301]
I'm wondering if I can convert, let's say, a JPG to a PNG and then provide a link to a download (either inline or w/e) instead of either encoding the image as a data-url or saving the new file to the filesystem?

Please see the Output Parameters section of the [Cloud Convert](https://cloudconvert.com/apiconsole) API to see what I'm referring to.

**Comment by olivervogel** [comment]
Sure, you can set the `content-disposition` of the HTTP header and attach the encoded image data directly.
