### ISSUE TITLE
Call to undefined function Intervention\Image\finfo_buffer() on Statamic CMS site

### ISSUE THREAD

**Issue by danielfowler** [Intervention/image#306]
Getting the following error on [a site using Statamic CMS](http://grco.fowlertown.com), which is using the Intervention Image first-party add-on.

```
Fatal error: Call to undefined function Intervention\Image\finfo_buffer() in C:\xxx\xxx\website\_app\vendor\Intervention\Image\Image.php on line 1802
```

[Ticket on Statamic Lodge](http://lodge.statamic.com/support/456-v19-causing-fatal-error-on-all-cp-pages-)

It doesn't appear on my local build using MAMP. My server is using PHP 5.4+ which should be current enough to handle the requirements.

Any help is appreciated... I'm hitting a wall.

**Comment by olivervogel** [comment]
[Fileinfo extension](http://php.net/manual/de/book.fileinfo.php) is required to use Intervention Image.

**Comment by danielfowler** [comment]
And that's a server configuration thing I need to activate? How would I describe this to my hosting provider? Sorry, I'm server-side-stupid.

**Comment by danielfowler** [comment]
This is a duplicate issue (not really an issue with Intervention Image at all, but rather the server's PHP config). For reference: https://github.com/Intervention/image/issues/298
