### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by olivervogel** [Intervention/image#307]
Package handling changed in Laravel 5 and is currently still under development. **I will add support as soon the new package/config part is available and documented.**

If you want to use Intervention Image in Laravel 5 now, I suggest to skip adding the `ImageServiceProvider` and instatiate `ImageManager` objects as shown in the [documenation](http://image.intervention.io/getting_started/installation) manually.

**Comment by morrislaptop** [comment]
Hey guys,

I've got an interim work around - https://github.com/morrislaptop/LaravelFivePackageBridges

Cheers,
Craig

**Comment by Charkhan** [comment]
Hi,

Just to let you know that L5 has now the vendor publishing support ("vendor:publish" command) :).

**Comment by olivervogel** [comment]
Intervention Image (>=2.1) is now compatible with both Laravel 4 and 5.

**Comment by barryvdh** [comment]
Could be worth creating a different package for Laravel support, so you can support multiple versions.

**Comment by alexleonard** [comment]
FYI I updated to the 2.1 version, added the service provider and alias, and then did `php artisan vendor:publish`. Strangely even though the command came back saying published there's no image.php file in /config.

Further confusion comes from the fact that with the service provider enabled in config/app.php I get the following error:

    FatalErrorException in ServiceProvider.php line 57:
    Illuminate\Support\ServiceProvider::mergeConfigFrom(): 
    Failed opening required 'image' (include_path='/path/to/vendor/phpunit/php-text-template:/path/to/vendor/phpunit/php-file-iterator:/path/to/vendor/phpunit/php-timer:.:/usr/share/php:/usr/share/pear')

I'm not sure why phpunit is coming into it there.

I manually created config/image.php and copied the content from /vendor/intervention/image/src/config/config.php but the above error remains.

If I comment out `'Intervention\Image\ImageServiceProvider',` in my config/app.php then the site loads again as normal.

I'll keep digging around.

**Comment by olivervogel** [comment]
Please update to `dev-master` and try again. There was a parameter switch in Laravel's ServiceProver, I just merged.

**Comment by olivervogel** [comment]
`2.1.1` is tagged.

**Comment by alexleonard** [comment]
Woop woop! That worked a charm :) :+1: 

Thanks again @olivervogel

**Comment by SylarRuby** [comment]
Sorry but this does not work for me. I have namespace: use Intervention\Image; or use Intervention\Image\Facades\Image; and nothing worked. My dd's work ok: dd($image->getRealPath()); and dd($image->getClientOriginalName()); My issue is with the "Image::make". That does not work in Laravel 5.

**Comment by SylarRuby** [comment]
![screen shot 2015-04-08 at 17 52 31](https://cloud.githubusercontent.com/assets/7381195/7050272/1b777926-de18-11e4-8973-d615611e9ee3.png)

**Comment by SylarRuby** [comment]
Typo: dd(Image::make....)
