### ISSUE TITLE
Destroy method not working...

### ISSUE THREAD

**Issue by Shogun147** [Intervention/image#308]
Hi there, thanks for great library!

I have a little issue which i can't find solution for. I'm resizing few images in a loop and getting annoying `memory_limit` error even if I call the destroy method:
```php
foreach($images as $imageId) {
  $imageFile = $imageId.'.jpg';
  $image = Image::make($imagesBasePath.$imageFile);
  $image->backup();

  $imageDestinationFile = $imageId.'_160.jpg';
  $image->resize(160, null, function($constraints) {
	return $constraints->aspectRatio();
  })->save($imagesThumbsPath.$imageDestinationFile);

  $image->reset();

  $imageDestinationFile = $imageId.'_250.jpg';
  $image->resize(250, null, function($constraints) {
	return $constraints->aspectRatio();
  })->save($imagesThumbsPath.$imageDestinationFile);

  $image->destroy();
}
```
Can somebody please tell me what i'm doing wrong here?

Thanks.

**Comment by olivervogel** [comment]
I think the memory may reach its limit, because `destroy()` only clears the actual image and not the version created by `backup()`.

You add one of the following lines (before destroy()) as a workaround.

```php
// if youre using GD add this
imagedestroy($image->getBackup());

// or Imagick add this
$image->getBackup()->clear();

$image->destroy();
```

Please report if it helps. I will address this problem in a future release.

**Comment by Shogun147** [comment]
Hi @olivervogel,

I've tried `imagedestroy` for GD, but without any effect. :(

**Comment by olivervogel** [comment]
I think you have to raise your memory limit then. And I suggest to Imagick, it's more memory efficient.

**Comment by olivervogel** [comment]
`destroy()` now also frees memory of backup (6554d8165e048972b470a7d56ab5f4d6fd6c6367).

**Comment by Shogun147** [comment]
@olivervogel - I downloaded lib with this update, but still same result... it doesn't frees memory for GD(32MB limit). I tried even without making any backup, just an resize in a loop. 

```php
foreach($images as $imageId) {
  $imageFile = $imageId.'.jpg';
  $image = Image::make($imagesBasePath.$imageFile);

  $imageDestinationFile = $imageId.'_160.jpg';
  $image->resize(160, null, function($constraints) {
	return $constraints->aspectRatio();
  })->save($imagesThumbsPath.$imageDestinationFile);

  $image->destroy();
}
```

I can't use Imagick at the moment.

**Comment by olivervogel** [comment]
You should raise your `memory_limit`. GD wants alot for simple tasks. Try 128MB.

**Comment by Shogun147** [comment]
Yeah, okay... but this is nonsense i think.

Thanks.

**Comment by peterpan666** [comment]
Same problem here! To fix it I use fopen instead of feeding make with the path.

So in your case, this is what I've got and it seems to work for me but I have NO idea why...

```php
foreach($images as $imageId) {
  $imageFile = $imageId . '.jpg';
  $original = fopen($imagesBasePath . $imageFile, 'r');

  $imageDestinationFile = $imageId.'_160.jpg';
  Image::make($original)
    ->resize(160, null, function($constraints) {
      return $constraints->aspectRatio();
    })->save($imagesThumbsPath.$imageDestinationFile)
      ->destroy();

  fclose($original);
}
```

**Comment by jerrime** [comment]
It also happen to me. so i use an alternative.

File::delete($img_path);

use Illuminate\Support\Facades\File; 

i hope in can help.
