### ISSUE TITLE
Add possibility to define image type when outputting data-url

### ISSUE THREAD

**Issue by olivervogel** [Intervention/image#314]
https://github.com/Intervention/imagecache/issues/32

**Comment by oh-ren** [comment]
+1 ;-)

(Currently one must: `encode` to anything but `data-url`, then manually `base64encode` and put`data:[<mime type>][;charset=<charset>][;base64],` in front.)

Though this isn't just a matter of specifying the image type, one must be able to specify the optional *quality* parameter as well here.

Another option is to remove `data-url` from the encoding options (but of a strange one there anyway), and create a new `Image` method for this functionality(?)

**Comment by olivervogel** [comment]
This feature is now available in [version 3](https://image.intervention.io/v3/).
