### ISSUE TITLE
how to tell user that file is no image / not readable ?

### ISSUE THREAD

**Issue by h82** [Intervention/image#318]
I have this in a try catch block:
```
$img = Image::make(Input::file('image'));
```
the catch part :
```
catch(Exception $e){
    return Redirect::back()->withErrors('Error: ' . $e->getMessage());
}
```
but laravel throws an error when I upload a php-file or another non-image-file and the redirect does not happen:
```
NotReadableException in Decoder.php line 21:
Unable to read image from file
```
Can I somehow avoid the "whoops.. error " from laravel and redirect back with an info message? What does `Image::make` return if it fails?

**Comment by olivervogel** [comment]
Sorry, I can't see any reason why catching exceptions should not work. I just tested the following.

```php
try {
     $img = Image::make('nothing');
} catch (Exception $e) {
    return Redirect::to('img')->withErrors('Error: ' . $e->getMessage());
}
```

**Comment by h82** [comment]
My fault.
My website is namespaced, I had to use `\Exception` or write a `use Exception;` at the top of the file. Now it works.

**Comment by Stelefanten** [comment]
@h82 

thanks for posting your solution. Just upgraded to Laravel 5 and ran into the same problem... 

"Must think... name space..."
