### ISSUE TITLE
Cached image returns broken

### ISSUE THREAD

**Issue by RoffeDH** [Intervention/image#319]
I'm trying to serve a cached image but I'm only getting a broken image link. How come?
~~~
$cachedImage = Image::cache(function($img) {
			return $img->make('http://cdn.smosh.com/sites/default/files/ftpuploads/bloguploads/twilight-meme-scumbag-edward.jpg');
		}, 10, true);

return Response::make($cachedImage, 200, array('Content-Type' => $cachedImage->mime));
~~~

This is my result:
![Image](http://mediaelite.net/laravel/public/general/image/10522308_497275400407428.jpg)

And this should be the result:
![Image](http://cdn.smosh.com/sites/default/files/ftpuploads/bloguploads/twilight-meme-scumbag-edward.jpg)

Does anyone here have a solution to this? It works just fine on a localhost server, but once live it just stopped. Any help would be much appreciated.

**Comment by olivervogel** [comment]
It's possible that the server is configured, to accept only requests with a valid `user-agent`. Intervention Image just uses `file_get_contents()`, and sends no agent info. I would try to fetch the file via Curl or Guzzle with a valid `user-agent` info and pass it to Intervention Image afterwards.
