### ISSUE TITLE
Problem when cropping + resizing + rotating

### ISSUE THREAD

**Issue by newtonianb** [Intervention/image#321]
What's the correct order to get this working? I pretty much tried all variations and nothing seems to produce expected result.

The top is what the picture should look like after the operations but below is how it actually crops it.
My front end library sends this information to the back end. Without the rotate operation the cropping works perfectly.
Here is how I process this with intervention

``$img->resize(840, 1002)->crop(800, 400, 13, 276)->rotate(45)``

```
img_initial_width: 335
img_initial_height: 400
img_width: 840
img_height: 1002.9850746268656
img_y1: 276
img_x1: 13
crop_h: 400
crop_w: 800
rotate: 45
```

![problem](https://cloud.githubusercontent.com/assets/2313644/6161399/2fa69fe0-b23e-11e4-9aa6-25b473e2e7b4.jpg)

**Comment by olivervogel** [comment]
Sorry, I don't understand, what you are trying to do.

**Comment by newtonianb** [comment]
I have a JS library where the user can upload a picture. 

This JS library then allows to rotate and zoom the picture so that it fits within a specific WIDTH and HEIGHT. When the user submits all this information is sent to intervention to process the image.

From the image shown above the first image is the modifications the user sees after selecting the image, zooming and rotating. The image is enclosed within this fixed WIDTH and HEIGHT rectangle.

When I sent all this information back to intervention the resize and cropping works great but as soon as I add rotation to the chain of events then everything gets messed up and I end up with the second image shown above which is not processed correctly.

**Comment by olivervogel** [comment]
Is it possible that the rotation function is Interpreted differently by the JS lib and Intervention Image? Looks like it rotates but keeps the size, while PHP rotates and resizes the boundaries.

**Comment by newtonianb** [comment]
Do you have any suggestions how I could get this working? Because the resizing and cropping of intervention given the information from the JS library works perfectly. But when I add rotation information (which is just an integer passed to intervention) representing an angle then it breaks.

**Comment by estudiogenius** [comment]
i have the same isue

**Comment by newtonianb** [comment]
Unfortunately I still don't have a solution for this. It does seem like a bug to me as it's supposed to be chain able features but these two together don't work.

**Comment by thijsw** [comment]
I was also struggling with this, but in my case the solution was surprisingly simple: first rotate, then crop.

Change
```php
$img->resize(840, 1002)->crop(800, 400, 13, 276)->rotate(45)
```
to
```php
$img->resize(840, 1002)->rotate(45)->crop(800, 400, 13, 276)
```
Hope it is of help to anybody!
