### ISSUE TITLE
Rotate png - Loss quality

### ISSUE THREAD

**Issue by ChristianGerdes** [Intervention/image#322]
Hi,

Current i'm converting all types of images to png using the encode('png') method.
Later on when i want to rotate the images, after several times to image loss quality and become blurry?

This is my rotatescript
``
$image = Picture::make(public_path()."/images/items/".$id.".png")
				->rotate(-90)
				->save(public_path()."/images/items/".$id.".png")
				->resize($this->max_thumbnail_width, $this->max_thumbnail_height, function($constraint){
					$constraint->upsize();
	    			$constraint->aspectRatio();})
				->resizeCanvas($this->max_thumbnail_width, $this->max_thumbnail_height, 'center', false, "#fff")
				->save(public_path()."/images/items/".$id."_tn.png");
``

**Comment by olivervogel** [comment]
I would guess that multiple rotatation (resampling) can cause quality loss. I would use [backup()](http://image.intervention.io/api/backup) and [reset()](http://image.intervention.io/api/reset), to go back to a certain state of the image.

**Comment by ChristianGerdes** [comment]
How would you do that?
Right now it only rotates the image, and if using backup and reset the rotate is just ignored? It doesn't help :(

**Comment by olivervogel** [comment]
Take the original and rotate once (90°), return to the original and rotate once again (180°). May be better than rotating once (90°) and rotating (90°) from the already resampled image again.
