### ISSUE TITLE
How to implement own filter

### ISSUE THREAD

**Issue by schorsch3000** [Intervention/image#323]
Hi,
i need a very specific filter which i will implement by my self.
i don'T think it makes sense to merge this filter into the project since it is a very specific need, so i like to have this filter as a kind of plugin.
sure, i'll could fork the project, do my changes and merge everything form you, but i don't like this solution, is there a way to load filter as a kind of plugins?

**Comment by olivervogel** [comment]
Yes, you can write your own [filter classes](http://image.intervention.io/use/filters).
