### ISSUE TITLE
Grab and drag an image to crop it

### ISSUE THREAD

**Issue by Dargus77** [Intervention/image#324]
Hi,

I'm trying to do an image resizer in laravel using your library. Now I'm uploading and resizing images to receive a download of the edited image and works very well, but for some images it's not enough without a preview for edit the image area to crop.

Is there any method you can choose the area to be cropped, manually grabbing and dragging the image?

**Comment by olivervogel** [comment]
Intervention Image does not provide this. But I'm sure there are JavaScript Libraries, which do let you define a rectangle by dragging. The coordinates can be passed to Intervention Image.

**Comment by Dargus77** [comment]
Thanks for the answer Oliver.

For if it helps someone, I found the Guillotine jquery plugin to do this.

**Comment by marcelgruber** [comment]
Do we have any examples anywhere on how to apply all the Guillotine transformations using Intervention/Image?
