### ISSUE TITLE
Focal point support

### ISSUE THREAD

**Issue by ducktype** [Intervention/image#327]
Actually does not seems possible to specify a custom centering point for fit/crop methods. 

The position argument supports only fixed anchors like 'bottom-left' and so on. 

Some cms allow the user to specify the focus coordinates for each image.

I propose to allow values like '20%:70%' in the position argument to specify a custom anchor position for the resize operation for example at 20% of the height and 70% of the width.

**Comment by reinink** [comment]
Just wondering, if you're looking to provide users with this sort of fine-tuning, would it not make more sense to simply provide a crop interface?

**Comment by ducktype** [comment]
This will require more work for "editors" team that needs to crop N times every image.

Also the "html designers" team is not free to change things as fast as they want because if a new ratio is required all old images need to be manually cropped by the "editors team".

Also more uneccessary coordination between the 2 teams is required.

Seems a pain we can alleviate.

Focus point will free both teams about all this implications about how they are using images and this greatly simplifies mobile and responsive designs patterns that are required in today's web.

what do you think?

**Comment by cviebrock** [comment]
This would also be a great feature for cases where you pass the image to a service that automagically does face detection, or finds the "most interesting" part of the image.  So you could then crop to that point.

**Comment by cviebrock** [comment]
Being able to specify a focal point for fit/crop methods would also be useful if you were using some API or code that did face detection on an image, or identified the most "interesting" part of an image.

User-uploaded images could then be auto-cropped to those focal points more easily.

**Comment by jasonvarga** [comment]
I would love this feature.

It seems to me it would be just be the `fit` method with the ability to set pixel based position coordinates instead of `top-left`, etc.

**Comment by reinink** [comment]
Out of genuine curiosity, where and how would this actually get used in an app? I'm assuming a use would be able to specify more specifically where the crop would occur, correct?

**Comment by jasonvarga** [comment]
The following image is taken from the jQuery plugin, [focuspoint](https://github.com/jonom/jquery-focuspoint), but the idea is the same.

![](https://raw.githubusercontent.com/jonom/jquery-focuspoint/master/demos/img/demo.jpg)

The way I'm picturing it, is someone uploads a full-size image through a CMS (ie. the photo on the left) They'd have some kind of interface to define the focal point. (ie. they could click somewhere between the two people's faces). The coordinates would get saved.

Then depending on your site's art direction, you might want to use the same image as a horizontal homepage banner, a square thumbnail, etc.

In your templates, there's no way to know which crop point we should be using in advance. (eg. if we choose `center`, we might end up with an image like the top right) This is where specifying the coordinates of the crop point would be perfect.

**Comment by reinink** [comment]
Gotcha, that's very interesting. I'd love to see this added to Intervention, but if it can't be, I'm sure we can get it in Glide either way.

**Comment by psren** [comment]
Missed that feature, too.

**Comment by EdgarPost** [comment]
I made a fork to implement this feature, since I needed this as well. But I am currently thinking of the best way to use it.

Of course, a string would work
`$img->fit(150, 1000, function() {}, '25%,50%');`

But, usually we already have the values ready, so why not pass it as an array?
`$img->fit(150, 1000, function() {}, array(25, 50));`

What do you guys think?

**Comment by reinink** [comment]
Wow, I was actually going to work on adding this to [Glide](https://github.com/thephpleague/glide) *today*, but I might wait and see if this gets added first. I very much like your second suggestion with the array. Great thinking!

**Comment by EdgarPost** [comment]
Personally, I think that using a string `'25%,50%'` is following the current style more of Intervention.

I have commited a version in my own fork where you can use a string as the position parameter
https://github.com/EdgarPost/image/commit/c9babbdf867e4cb8af6d3839a99e1969a107667e

`$img->fit(150, 1000, function() {}, array(25, 50));`

I am kind of new to this GitHub forking thing, so let me know if there's a better way of sharing and discussing issues and new code! :)

**Comment by reinink** [comment]
> ...is following the current style more of Intervention 

Hmm, then that might be worth considering. In the end it doesn't matter to me. We'll need @olivervogel's take on this.

**Comment by reinink** [comment]
For what it's worth, I've added this to Glide already. Docs [here](http://glide.thephpleague.com/1.0/api/crop/#crop-focal-point). Implementation [here](https://github.com/thephpleague/glide/blob/2bb66ed4b8a59ea446b2e98f535b9d5e2dc70d4c/src/Manipulators/Size.php#L336-L379).

**Comment by EdgarPost** [comment]
Awesome. I've requested a pull request in the meantime.

**Comment by aleemb** [comment]
Pinging @olivervogel since this issue may be buried but implementation code is readily available.
