### ISSUE TITLE
Question: Why is argument $quality for imagepng() set to -1?

### ISSUE THREAD

**Issue by ADmad** [Intervention/image#328]
The PHP manual states that value for `$quality` argument of [imagepng()](http://php.net/manual/en/function.imagepng.php) should be value integer between 0 to 9 but here [here](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Gd/Encoder.php#L34) a value of `-1` is passed.

Can you please explain the reason behind that?

**Comment by jwpage** [comment]
[This comment on php.net explains why.](http://php.net/manual/en/function.imagepng.php#106093)

Short version: -1 is a special value for quality in GD to use the default compression level.

**Comment by ADmad** [comment]
That's wack :stuck_out_tongue: Thanks for the info. Might be a good idea to add a comment in the code in that regards in case someone else is curious too.
