### ISSUE TITLE
I've been wondering about this

### ISSUE THREAD

**Issue by Teranode** [Intervention/image#330]
When we set the images to save onto the server.
Does the images get saved as progressive or baseline?
Is there an option to set this?

**Comment by olivervogel** [comment]
JPG Images will only be saved Baseline by default. I think GD and Imagick will save progressively, if you try to save JPG files in "interlace mode". So [this](http://image.intervention.io/api/interlace) could be a workaround.

**Comment by Teranode** [comment]
Thanks, i got it fixed now.
