### ISSUE TITLE
Shortcut for scale image

### ISSUE THREAD

**Issue by Dargus77** [Intervention/image#331]
I was searching in the API for a scale() method, but I can't find it. This could be a new implementation.

I have a number that I want to multiply for the image width and height to obtain a new size. I can do this simply using width() and height() methods and then multiplying for my scale value, but a scale() method who only needs the scale value could be great.

**Comment by olivervogel** [comment]
I thought about a `scale` method, when I started the project, but I don't see any real use case. Usually I want to output images with at least one axis size fixed.
