### ISSUE TITLE
Won't initialize object

### ISSUE THREAD

**Issue by ChristianGerdes** [Intervention/image#332]
Hi,
Here's my code and it didn't output anything?

```
dd($image = Picture::make($image->getRealPath()));
```
I've justed a alias as you can see.
Can someone tell me why my code doesn't return anything?

**Comment by 0legtr** [comment]
Hi,
i'm probably having the same issue.
And it looks like it depends on image size.

**Comment by 0legtr** [comment]
What solved it for me is this:
Image::make(file_get_contents($file->getRealPath())));

Best regards

**Comment by olivervogel** [comment]
Please check you PHP memory limit settings. Maybe you're running out of memory, trying to init large images.

http://image.intervention.io/getting_started/configuration
