### ISSUE TITLE
How do i get image size in bytes after a transformation?

### ISSUE THREAD

**Issue by 0legtr** [Intervention/image#333]
Hi,
is there a way to get a size of an image in bytes after i resize it?
I don't want to save it first to disk and read the file size.

Thanks.

**Comment by olivervogel** [comment]
Not directly. You have to encode to get the filesize.

```php
$img = Image::make('foo.jpg');
$size = strlen((string) $img->encode('png'));
```

**Comment by 0legtr** [comment]
Thanks.
