### ISSUE TITLE
Class '\Intervention\Image\ImageServiceProviderLaravel4' not found

### ISSUE THREAD

**Issue by devmtnaing** [Intervention/image#339]
PHP Fatal error:  Class '\Intervention\Image\ImageServiceProviderLaravel4' not found in /tmp/build_0a925d049967e8104bef0b8f7b5ceee3/vendor/intervention/image/src/Intervention/Image/ImageServiceProvider.php on line 70

Above is the error I get everytime i push my project to heroku. 

Any idea why this is causing?

**Comment by olivervogel** [comment]
Make sure you are on version `>= 2.1.0`. ImageServiceProviderLaravel4 exists only after this version, because of Laravel 5 support.
