### ISSUE TITLE
Finfo_buffer triggering exception on HHVM

### ISSUE THREAD

**Issue by azcoppen** [Intervention/image#340]
Env: Ubuntu 14.04 with HHVM 3.6.0

HipHop VM 3.6.0 (rel)
Compiler: tags/HHVM-3.6.0-0-g6ef13f20da20993dc8bab9eb103f73568618d3e8
Repo schema: 3ab6576af394a33abbb29796c652f06b1c7640ce

Laravel 4.2 with Intervention/Image (require "intervention/image": "2.*") and Flysystem with AWSS3 driver.

Code:

// make $client, etc
$filesystem = new Filesystem(new Adapter($client, \Config::get('s3.bucket')));
$original_path = '_files/example.jpg'; // S3 URL
$original_image = \Image::make($file->getRealPath())->encode('jpg'); // from file upload

        try {
            $filesystem->write($original_path, $original_image, ['visibility' => 'public']);
        } catch (\Exception $e) {
            \Log::warning('Exception writing  image ('.$original_path.'): '.$e->getMessage());
        }

Error returned is:

dev.ERROR: exception 'ErrorException' with message 'Argument 1 to finfo::buffer() must be of type ?string, Intervention\Image\Image given' in /var/www/webapp/server/vendor/league/flysystem/src/Util/MimeType.php:23

Works fine on OSX and Homestead. Image output string is fine (viewed in log file).

Following solutions have not worked:

    (string) $original_image or __toString()
    encode('jpg') output

Mime-type errors with Intervention also reported by colleague on Ubuntu 12 since last Friday. Unsure as to whether it's an Intervention problem, or Flysystem. 2 projects crashing - 1 Laravel, 1 not. Both using Ubuntu (12 and 14) and Intervention, both getting the same error.

**Comment by olivervogel** [comment]
Sorry, I never tested Intervention Image on HHVM.

**Comment by devmark** [comment]
same problem
hhvm with homestead

~~~~
ErrorException in MimeType.php line 23:
Argument 1 to finfo::buffer() must be of type ?string, Intervention\Image\Image given
~~~~

**Comment by green-mike** [comment]
convert data type to string, it work
```
(string)$image->encode();
```
