### ISSUE TITLE
Exif returns null, exif_read_data() returns not null

### ISSUE THREAD

**Issue by CitizenBeta** [Intervention/image#343]
I'm trying to read my exif data. If I run $image->exif(), it returns null. If I run exif_read_data() on the same file, I get the full array with complete data. Any ideas?

**Comment by olivervogel** [comment]
Maybe [this](https://github.com/Intervention/image/issues/336) is the same problem.

**Comment by chimit** [comment]
I encountered the same strange behavior in Laravel (Lumen) when using images stored on Amazon S3.

```php
$source_file = Storage::disk('s3')->get($filename);
$exif = Image::make($source_file)->exif();
info($exif); // nothing
```

But at the same time if I use the default `exif_read_data()` function I can get EXIF information without saving the file on the server:

```php
$source_file = Storage::disk('s3')->url($filename);
$exif = exif_read_data($source_file);
info($exif);
```

Output:

```
[2019-08-26 09:44:15] local.INFO: array (
  'FileDateTime' => 0,
  'FileSize' => 5658377,
  'FileType' => 2,
  'MimeType' => 'image/jpeg',
  'SectionsFound' => 'ANY_TAG, IFD0, EXIF',
  'COMPUTED' => 
  array (
    'html' => 'width="4032" height="3024"',
    'Height' => 3024,
    'Width' => 4032,
    'IsColor' => 1,
    'ByteOrderMotorola' => 1,
  ),
  'Orientation' => 6,
  'Exif_IFD_Pointer' => 38,
  'ColorSpace' => 1,
  'ExifImageWidth' => 4032,
  'ExifImageLength' => 3024,
)  
```

This problem also affects the `orientate()` method and causes a lot of problems with vertical photos captured by iPhones (https://github.com/Intervention/image/issues/906, https://github.com/Intervention/image/issues/868, https://github.com/Intervention/image/issues/890, https://github.com/Intervention/image/issues/392, https://github.com/Intervention/image/issues/336, https://github.com/Intervention/image/issues/714, https://github.com/Intervention/image/issues/295, https://github.com/Intervention/image/issues/142).

If `exif_read_data()` can read EXIF data why can't `exif()` method do the same? Any chances to see this fixed, @olivervogel?

**Comment by FrittenKeeZ** [comment]
@mattmcdonald-uk using `setFileInfoFromPath($url)` makes `orientate()` work correctly as well - thanks!

**Comment by lukasjuhas** [comment]
@FrittenKeeZ, oh my... that totally worked. Thank you!

**Comment by mattkomarnicki** [comment]
Thanks for the hint @mattmcdonald-uk! 👍🏻

**Comment by oneWaveAdrian** [comment]
Hate to reopen this, but it is still happening and cost me a couple hours of searching to stumble upon this thread.
@mattmcdonald-uk's solution worked, however it did leave some questions open:

1. why does this happen/is the workaround still necessary?
2. should this not be documented in http://image.intervention.io/api/exif and http://image.intervention.io/api/orientate?

I am happy to alter the docs, just want to confirm this is not some other deeper issue...?

**Comment by olivervogel** [comment]
This no longer seems to be an issue with version 3 of Intervention Image.
