### ISSUE TITLE
sometimes NotWritableException

### ISSUE THREAD

**Issue by syrakozz** [Intervention/image#347]
i was saving an image
my code is
      $img1 = Image::make($imglink1)->resize(160, 160);
        $img2 = Image::make($imglink2)->resize(160, 160);
        $img3 = Image::make($imglink3)->resize(160, 160);
        $img4 = Image::make($imglink4)->resize(160, 160);
        
        $img = Image::canvas(320, 320, '#ffffff');
        
        $img->insert($img1, 'top-left', 0, 0);
        $img->insert($img2, 'top-right', 0, 0);
        $img->insert($img3, 'bottom-left', 0, 0);
        $img->insert($img4, 'bottom-right', 0, 0);
        //echo $img->response();
        echo "done.. " . $name . '.png';

          //echo $imglink1."\n".$imglink2."\n".$imglink3."\n".$imglink4;exit;
        $img->save('generatedimages/x' . $name . '.png');

i was able to save few images but in some image i got

exception 'Intervention\Image\Exception\NotWritableException' with message 'Can't write image data to path (generatedimages/xpls301.png)'

but the directory is writable

**Comment by JapSeyz** [comment]
Why was this closed? I am having the same issue.
