### ISSUE TITLE
Add support for Lumen (http://lumen.laravel.com/)

### ISSUE THREAD

**Issue by daemonfire300** [Intervention/image#352]
I tried to put the package into lumen.
Bootstraping it like this:

    $app->register('Intervention\Image\ImageServiceProviderLaravel5'); // also tried using the normal provider
    $app->bind('Intervention\Image\Facades\Image');

It seems to fail due to the missing `app/config.php` in lumen.
It would be nice to have some lumen integration aswell. Or maybe I just did it wrong.

**Comment by olivervogel** [comment]
From the Lumen documentation:

> Also, unlike Laravel, Lumen is not intended to be used with additional Laravel "packages" such as debug bars, CMS systems, etc.

But I guess you can instantiate Intervention Image objects manually, as described in the [examples](http://image.intervention.io/getting_started/installation).

**Comment by daemonfire300** [comment]
Thank you for the suggestion. I thought about making a pull request offering some sort "LumenProvider".

**Comment by rizwanmcs** [comment]
hi
any one can help me that how i can install intervention image library in laravel lumens version?
Thanks

**Comment by olivervogel** [comment]
Try this:

```php
$app->register(Intervention\Image\ImageServiceProviderLumen::class);
```

**Comment by qasimalbaqali** [comment]
@olivervogel works :)

**Comment by goyuquan** [comment]
add this two config in bootstrap/app.php
`$app->withFacades(
    class_alias('Intervention\Image\Facades\Image', 'Image');
);

$app->register(Intervention\Image\ImageServiceProviderLumen::class);`
