### ISSUE TITLE
Laravel route alias

### ISSUE THREAD

**Issue by sleeping-owl** [Intervention/image#357]
There was the route alias `imagecache` in package under 2.1.3 (https://github.com/Intervention/image/blob/2.1.3/src/Intervention/Image/ImageServiceProviderLaravel5.php#L84).

In version 2.1.4 there is no route alias (https://github.com/Intervention/image/blob/2.1.4/src/Intervention/Image/ImageServiceProviderLaravel5.php#L88).

I don't want to get route prefix from imagecache config and construct the url manually. Please fix it.

**Comment by olivervogel** [comment]
Update both `intervention/image` and `intervention/imagecache` to `>=2.2.0` and the alias should be back.

**Comment by sleeping-owl** [comment]
Thanks
