### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by bcreeves** [Intervention/image#358]
Any plans for PDF support? For converting pdf's to image thumbnails.

**Comment by olivervogel** [comment]
No plans, sorry.

**Comment by azamuddin** [comment]
Converting pdf to image will be really useful.

**Comment by freekmurze** [comment]
+1

**Comment by mmguide2003** [comment]
Definitely useful.

**Comment by freekmurze** [comment]
I've made [a little package that can convert images to pdf](https://github.com/spatie/pdf-to-image). You can use that to create an image and use intervention/image for manipulating it further.

**Comment by mmguide2003** [comment]
Nice, just a quick (maybe dumb)Q. When you say pathtopdf, is this relative to anything? I'm using Storage::  which defaults to 'storage/app' folder , so storage_path().'/'.app  should work?  i.e. /home/vagrant/projects/laravel5/storage/app

**Comment by freekmurze** [comment]
Nope, pathtopdf isn't relative to anything. If you have further questions about the spatie/pdf-to-image pose them on the issue tracker of that package.

**Comment by potherca** [comment]
@olivervogel If anyone would be foolish enough to create one, would you be willing to accept a PR for this?

**Comment by olivervogel** [comment]
@potherca I think using a external package like [spatie/pdf-to-image](https://github.com/spatie/pdf-to-image) is the better way. Intervention Image is already bloated.

**Comment by potherca** [comment]
My suggestion would be to add `spatie/pdf-to-image` as an (optional?<sup>[1]</sup>) dependency and have that library handle to logic. No need to re-invent the wheel. This should keep the bloat on the project to a minimum...

The pdf-to-image library depends on Imagick, so its functionality wouldn't be available if the drivers is `GD`.

<sup>[1]</sup> For instance by adding a [composer suggest section](https://getcomposer.org/doc/04-schema.md#suggest) stating "Add support for reading PDF format".
