### ISSUE TITLE
[question] Possibility to set background color?

### ISSUE THREAD

**Issue by stefanschindler** [Intervention/image#36]
I am using your class to load images from different sources and formats, convert them to jpeg and save them to the server hdd.

Is there a built in possibilty to change the background color of the resulting jpeg? when converting some transparent PNGs, the background color of the jpeg changes to black.

**Comment by j-applese3d** [comment]
I had a similar issue with `->crop()` where the crop was possibly larger than the existing image or expanded past 1 or more edges.  Anything outside the original image dimensions would be black.

To solve the problem, I first resize the canvas of the image -- as that allows setting a background color -- and then crop.

Here's the code I used:
```php
$image = ImageManagerStatic::make($this->getPath(false));

// calculate how much to expand the canvas in each direction
$leftExtra = $x < 0 ? abs($x) : 0;   // $x and $y are the crop offset
$topExtra = $y < 0 ? abs($y) : 0;
$rightExtra = $height + $y - $image->height();  // $height and $width are the crop rectangle's dimensions
$widthExtra = $width + $x - $image->width();
$bg = 'FFFFFF';

if ($leftExtra > 0 || $topExtra > 0)
{
    // expand the canvas to the left and up as needed
    $image->resizeCanvas($image->width() + $leftExtra, $image->height() + $topExtra, 'right-bottom', false, $bg);
    // adjust the crop start position, because our canvas has been shifted. ex: [-20, -10] becomes [0, 0]
    $x = max($x, 0);
    $y = max($y, 0);
}
if ($rightExtra > 0 || $widthExtra > 0)
{
    $image->resizeCanvas($image->width() + $rightExtra, $image->height() + $bottomExtra, 'top-left', false, $bg);
}

$image->crop($width, $height, $x, $y);
