### ISSUE TITLE
Error when resizing .jfif

### ISSUE THREAD

**Issue by samkaranja** [Intervention/image#360]
When uploading and resizing a jpg image with extension .jfif, the image gets uploaded but the resize fails with exception "NotSupportedException in AbstractEncoder.php line 149: Encoding format (jfif) is not supported.", Edited AbstractEncoder.php and added ".jfif" in the function process under switch case jpg. Has anybody come across such an issue and how did you solve it?

**Comment by olivervogel** [comment]
Writing JFIF format is not supported. Use one of the supported formats.
