### ISSUE TITLE
Laravel ServiceProvider should support an alias.

### ISSUE THREAD

**Issue by tiran133** [Intervention/image#362]
You should set an alias in the service Provider

$app->alias('image',ImageManager::class);

So when ever I use the image instance via DI I be sure it will return an app('image') instance with the provided config.

Other wise laravel just creates  a new instance via new and the config is empty fall back to default driver gd. Its wired behaviour if I expect to use the imagick driver I set in the config file.

Alex

**Comment by olivervogel** [comment]
Thanks for the tip. 79f0a35da7d4f75bb85d9c04513dd5929e21f75e
