### ISSUE TITLE
Writing EXIF/IPTC tags to jpeg 

### ISSUE THREAD

**Issue by katzefudder** [Intervention/image#363]
Although it is possible to read EXIF and IPTC from jpeg, there's no way to write data to files.
What about this feature? Does somebody want/need that?

**Comment by olivervogel** [comment]
Unfortunately GD is not able to deal with meta data at all and Imagick can retain existing data but not write new values. I think proper dealing with meta data is worth a dedicated package and I recommend using libraries like Exiftool.

* https://github.com/romainneutron/PHPExiftool

**Comment by jarodium** [comment]
https://github.com/agutoli/Image_Iptc
