### ISSUE TITLE
Check if upload is success

### ISSUE THREAD

**Issue by vtellez** [Intervention/image#365]
Hi,

Thank you very much for your package, I find it very useful!

I've a doubt..  the save() method return an instance of Intervention/Image/Image, but how can I check if this example has completed succefully?

// resizing an uploaded file
$img = Image::make(Input::file('photo'))->resize(300, 200)->save('foo.jpg');

I though, I could be able to check like this:

if ($img) {
//manage upload
}

Thanks in advance.

Best regards,

**Comment by olivervogel** [comment]
I would use something like this:

```php
try {
    
    $img = Image::make(Input::file('photo'))->resize(300, 200)->save('foo.jpg');

    // do something in case of success

} catch (Exception $e) {
    
    // do something in case of failure

}
```

**Comment by vtellez** [comment]
Thank you very much @olivervogel
