### ISSUE TITLE
How can I get image dpi value?

### ISSUE THREAD

**Issue by rajanrawal** [Intervention/image#370]
I want to get the image dpi value. Is there any direct or indirect way to get this? Thank you. After knowing this, If I want to increase/decrease dpi values, is it possible to achieve with this? Please let me know. Thank you.

**Comment by olivervogel** [comment]
Intervention Image currently deals only with absolute pixel values. But you can bypass this by calculating the pixel values of the corresponding dpi values.

Example: A 300 x 200 pixel image 300dpi would be 150 x 100 in 150dpi.

**Comment by rajanrawal** [comment]
I am really sorry, but I did not get your statement "A 300 x 200 pixel image 300dpi would be 150 x 100 in 150dpi." Would you please elaborate?

**Comment by olivervogel** [comment]
If you want to resize 300 x 200 pixel image from 300dpi to 150dpi, you end up with an actual pixel size of 150 x 100.

**Comment by olivervogel** [comment]
You can also read the resolution via the [exif()](http://image.intervention.io/api/exif) method:

```php
$img = Image::make('foo.jpg');

// resolution for x axis
$x = $img->exif('XResolution');

// resolution for y axis
$y = $img->exif('XResolution');
```

**Comment by rajanrawal** [comment]
Oh! I did `exif` before i opened up issue, but I could not see that in result. Does that result varies based on GD or Imagick? Thank you.
