### ISSUE TITLE
Using getCore/setCore correctly?

### ISSUE THREAD

**Issue by pstephan1187** [Intervention/image#375]
I am using the Imagick driver and trying to strip the exif data from the image using imagick:

```php
$image = Image::make($filename);
$a = $image->exif();
$core = $image->getCore();
$core->stripImage();
$image->setCore($core);
$b = $image->exif();

// $a === $b;
```

Running `$core->getImageProfiles()` after `$core->stripImage();` results in no data even though running it before `$core->stripImage();` does (expected).

Running `$core->getImageProperties()` after `$core->stripImage();` results in less data than running it before `$core->stripImage();` does (expected).

Both `$a` and `$b` return the exact same data (unexpected).

What am I doing wrong?

**Comment by olivervogel** [comment]
You're doing nothing wrong. `exif()` uses [exif_read_data()](http://php.net/manual/en/function.exif-read-data.php) to read from the corresponding filename and not from the actual Imagick object. So unless you write the file, there will be no change visible.

**Comment by pstephan1187** [comment]
Makes sense. Thank you.
