### ISSUE TITLE
Join two images

### ISSUE THREAD

**Issue by huglester** [Intervention/image#376]
Hello,

is there a way to join two images? i.e. horizontally or vertically?

say I have two images 50x100.
If I join them horizontaly, I get 50x200 size
if I join them vertically - I would get: 100x100 size

Thanks!

**Comment by olivervogel** [comment]
Not out of the box and automatically. But I think it would be easy to achieve this with [canvas()](http://image.intervention.io/api/canvas), [insert()](http://image.intervention.io/api/insert), [width()](http://image.intervention.io/api/width) and [height()](http://image.intervention.io/api/height). Ideally you wrap it in a [custom filter](http://image.intervention.io/use/filters) at the end.

**Comment by huglester** [comment]
hello @olivervogel 

Thanks for the idea. Did not think about this. Firstly I tried:
```php
$img_canvas = Image::canvas(200, 100);
$img_canvas->fill(Image::make('img/color.jpg'), 0, 0);
$img_canvas->fill(Image::make('img/grey.jpg'), 100, 0); // add offset
$img_canvas->save('img/canvas.png', 100);
```
But it was adding same (color) picture over and over.

Using insert:
```php
$img_canvas = Image::canvas(200, 100);
$img_canvas->insert(Image::make('img/color.jpg'));
$img_canvas->insert(Image::make('img/grey.jpg'), 'top-right'); // add offset
$img_canvas->save('img/canvas_horizontal.png', 100);

$img_canvas = Image::canvas(100, 200);
$img_canvas->insert(Image::make('img/color.jpg'));
$img_canvas->insert(Image::make('img/grey.jpg'), 'bottom-left'); // add offset
$img_canvas->save('img/canvas_vertical.png', 100);
```
I basicly can achieve what I wanted :)
I will try creating a filter maybe, which would accept two images and 'join type', or something like that.

We will see If I will manage it. So far very 'eloquent-like' lib :)

Thanks!

**Comment by olivervogel** [comment]
It's also possible to insert directly, without creating a new image instance.

```php
$img_canvas = Image::canvas(200, 100);
$img_canvas->insert('img/color.jpg');
$img_canvas->insert('img/grey.jpg', 'top-right'); // add offset
$img_canvas->save('img/canvas_horizontal.png', 100);
```
