### ISSUE TITLE
Image rotation with imagick doesn't work as expected

### ISSUE THREAD

**Issue by tikendra-chand** [Intervention/image#377]
I tried to rotate this image:
![picture](https://cloud.githubusercontent.com/assets/9821274/7982182/a04b0206-0ad4-11e5-9c95-3554d70130d6.jpg)

like this using imagick as driver:
$img = Image::make('picture.jpg');
$img->rotate(40, '#ffffff');
$img->save('xyz.jpg');
It resulted:
![xyz](https://cloud.githubusercontent.com/assets/9821274/7982204/d855c3f2-0ad4-11e5-986e-6bc163fc040c.jpg)

When I try to rotate using imagick like this:
$imagick = new \Imagick();
$imagick->readImage('picture.jpg');
$imagick->rotateImage(new \ImagickPixel('#ffffff'), -40);
$imagick->writeImage('my_rotated.jpg');

I got correctly rotated image:
![my_rotated](https://cloud.githubusercontent.com/assets/9821274/7982232/23b68aac-0ad5-11e5-9923-5f794b407cae.jpg)

While debugging I found out that its due to merging layers while encoding jpg image(line 20 of https://github.com/Intervention/image/blob/master/src/Intervention/Image/Imagick/Encoder.php). 
Can you please fix it?

Thanks.

**Comment by olivervogel** [comment]
Thanks for reporting. Is fixed in f388f8cbdecb28e960d257c975dc9b5254c4c7ba.
