### ISSUE TITLE
How do I use Imagick functions with Intervention?

### ISSUE THREAD

**Issue by golevel** [Intervention/image#379]
I want to apply imagick vignette to an image but I don't see an example of how to do this in the documentation.

Here's the PHP docs for it:

http://php.net/manual/en/imagick.vignetteimage.php

Do I have to create a custom filter or is there an easy one liner that I can use?

**Comment by olivervogel** [comment]
Just access the imagick object as seen in [example](http://image.intervention.io/api/getCore).

**Comment by golevel** [comment]
Gotcha. Thank you. How do I turn it back into an intervention object?

**Comment by olivervogel** [comment]
Just access the "imagick object" like this.
```php
$img = Image::make('foo.jpg');
$img->getCore()->vignetteImage();
$img->save('foo.jpg);
```
