### ISSUE TITLE
Allowed memory size of 67108864 bytes exhausted

### ISSUE THREAD

**Issue by rodislav** [Intervention/image#382]
Hello, 

I'm using a shared hosting from godaddy, and there php ```memory limit``` is set to ```64M```, 
I use ```gd```, beause ```imagick``` is not supported, somehow..
when I'm trying to convert a list of 170 images, in a for loop, I get this error:

```Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 16668 bytes) in /home/content/77/5333977/html/zaporojandesign/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on line 115```

Have you encountered this issue ? or maybe it's not possible to do more images in a row !?

**Comment by olivervogel** [comment]
I would try to free memory with the `destroy()` method in the loop.

```php
for ($i=0; $i < 10; $i++) { 
        $img->resize(...);
        $img->destroy();
}
```

**Comment by rodislav** [comment]
I did so, still no luck, I have a stack of 170 images, and at some point I get that error, do you think by using a 1 second delay could solve the problem ? maybe this will be ok for garbage collector !?

**Comment by olivervogel** [comment]
`64M` might also be too low. GD is not very memory sufficient and resizing a 3000 x 2000 pixel image to 300 x 200 may take up to 32MB memory.

**Comment by rodislav** [comment]
Hm, yes, some images are around that size,  I'll try to increase memory limit to 128M, if this will not help I'll create a ajax-based que

Thanks for help, I guess you could mention these details in wiki for next users
