### ISSUE TITLE
PHP segmentation fault when png/gif images are rotated using GD

### ISSUE THREAD

**Issue by tikendra-chand** [Intervention/image#383]
I am getting segmentation fault when I try to rotate png/gif image without any backgroud color. I happens with random set of images like:
It works fine for this image: http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-60-92-metablogapi/4075.PngEncoder_2D00_Sample.png, but it throws that error for this image: http://palmzlib.sourceforge.net/images/baboon.png. 
### PHP system:

PHP 5.6.4, bundled GD version 2.1.0
### Used Code

```
    use Intervention\Image\Facades\Image;

    $image = Image::make("http://palmzlib.sourceforge.net/images/baboon.png");
    $image->rotate(180);

    $image->crop(410, 254, 103, 256);

    $image->encode(null, 100);

    header('Content-Type: '.image_type_to_mime_type(IMAGETYPE_PNG));
    echo $image->getEncoded();
```
### Thrown error

```
   WARNING: [pool www] child 266 exited on signal 11 (SIGSEGV) after 597.391665 seconds from start
```

It works fine when I use 0 as background color in imagerotate function instead of $color->getInt() in:

```
   Intervention\Image\Gd\Commands\RotateCommand.php:
   in this line:
   $image->setCore(imagerotate($image->getCore(), $angle, $color->getInt()));
```

Can you please have a look into it.
Thanks

**Comment by olivervogel** [comment]
I don't know whats the problem here. Seems to be a GD issue. However it works fine on my computer with PHP 5.6.6 and GD 2.1.1-dev.

What happens if you rotate with other background colors?

```php
$image->rotate(180, 'ccc');
```

**Comment by tikendra-chand** [comment]
I also tried $image->rotate(180, '#ffffff'); it failed ....... It works only when supplying 0 here(Intervention\Image\Gd\Commands\RotateCommand.php):
$image->setCore(imagerotate($image->getCore(), $angle, 0));

**Comment by ahamilton9** [comment]
Confirming the issue. Bunch of images over a few megabytes failing to rotate. Bundled GD 2.1.0, PHP 5.4. Switched to ImageMagick (now that there's a safe package again) and it works fine.

**Comment by anonpma** [comment]
anyone has a solution?
