### ISSUE TITLE
2nd parameter on mask() is optional on docs but not on the code 

### ISSUE THREAD

**Issue by abishekrsrikaanth** [Intervention/image#384]
The documentation of the `mask()` function indicates that the 2nd parameter `bool $mask_with_alpha` is optional as per http://image.intervention.io/api/mask. But the code at https://github.com/Intervention/image/blob/master/src/Intervention/Image/Image.php#L31

Doesn't seem to have a default value.

**Comment by harikt** [comment]
This could be closed : See https://github.com/Intervention/image/blob/cbec1cdf3f8d8e4c7eff2db4eedfd40f6cfce6f4/src/Intervention/Image/Image.php#L34
