### ISSUE TITLE
Write Text to Image with dimensions

### ISSUE THREAD

**Issue by bradsapp** [Intervention/image#385]
Is it possible to write text to an image with boundaries for the text? I want the text to auto wrap and not go beyond 200px from the edge (left/right).

**Comment by olivervogel** [comment]
Not currently. But it will be available in the next version.

**Comment by bradsapp** [comment]
Any idea when the next version will be released? (ball park date)

**Comment by valkirilov** [comment]
+1

**Comment by lucas-luchack** [comment]
Still nothing...
