### ISSUE TITLE
Images do not save.

### ISSUE THREAD

**Issue by TechKat** [Intervention/image#386]
I am using Laravel Lumen and I have made a command to generate thumbnails for all uploaded images. (I run a little image hosting website, I use this commend when thumbnails haven't been generated.)

```
283 / 11495 thumbnails were generated.
284 / 11495 thumbnails were generated.
285 / 11495 thumbnails were generated.
286 / 11495 thumbnails were generated.
287 / 11495 thumbnails were generated.
288 / 11495 thumbnails were generated.
289 / 11495 thumbnails were generated.
290 / 11495 thumbnails were generated.
291 / 11495 thumbnails were generated.
292 / 11495 thumbnails were generated.
293 / 11495 thumbnails were generated.
294 / 11495 thumbnails were generated.
295 / 11495 thumbnails were generated.
```

This is what my console outputs, should a thumbnail be generated. However, if I ran this command again, I still get x / 11495 thumbnails, meaning nothing is being generated but the script assumes it has.

I have updated my memory_limit to 2048MB, and using imagick. Is there something I can use to get the result of the class/methods?

**Comment by olivervogel** [comment]
I think this is a local problem and has nothing to do with this library. Make sure your folder is writable and check your log files for further error informations.

**Comment by TechKat** [comment]
@olivervogel The directory is writable as it works on the first run. For some weird reason, Artisan kills the script after around 2,000+ thumbnails generated and re-running doesn't work. I have checked the logs, several times, and nothing.
