### ISSUE TITLE
Writing text does nothing

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Intervention/image#388]
I have the following code:

``` php

$img = Image::canvas(300,300, "#000");
$img->text('foo', 10, 10,
                function ($font) {
                    $font->color('#fdf6e3');
                }
            );
$img->response();
```

No text is being drawn. I receive the canvas just fine in the correct color, but the text is missing. No warnings/errors/exceptions.

**Comment by olivervogel** [comment]
Try adding a font file.

```php
// for example
$font->file('fonts/arial.ttf');
```

**Comment by felicitus** [comment]
I did specify 1 as mentioned in the documentation for the GD adapter, still nothing. It should at least give a warning, if not an exception, if no text can be drawn,

**Comment by olivervogel** [comment]
I just tested your code and it works just fine. Maybe there something funky with your PHP/GD/FreeType installation.

![test](https://cloud.githubusercontent.com/assets/884642/8363840/112fb8e6-1b82-11e5-93d4-5cd9842fffda.jpg)
