### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by renalpha** [Intervention/image#391]
Running:
composer require intervention/image

[Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/intervention/image$60fbb9cbeb6ad2f89a34ace1be195cae0d289516cba607e373ac6bb9b4e6b988.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again
  and report this if you think it is a mistake.

**Comment by chrisforrence** [comment]
Hmm, I wasn't able to replicate this in my environment. Perhaps it was a temporary issue?

---

```
[chris@little-mac:lrvl]$ composer require intervention/image
Using version ^2.3 for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing intervention/image (2.3.0)
    Downloading: 100%         

intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
A new helper file was written to _ide_helper.php
Generating optimized class loader
[chris@little-mac:lrvl]$ 
```

**Comment by olivervogel** [comment]
I think @chrisforrence is right. This seems to be a local issue.

**Comment by renalpha** [comment]
seems to be an local issue indeed. Thanks for checking guys.
