### ISSUE TITLE
Uploaded image is rotated

### ISSUE THREAD

**Issue by iamgoodbytes** [Intervention/image#392]
I'm not sure why, but when I upload a certain portrait image, it gets rotated to a landscape image, which shouldn't happen. The original image is "480 × 640", and I'm using the code below to resize (if necessary) to a maximum of 1024 pixels. 

\Image::make(Request::file('image'))->resize(1024, null, function($constraint){ $constraint->upsize(); $constraint->aspectRatio(); })->save("useruploads/".$image_name);

This is my test image if anyone would like to try it out.

![img_3210](https://cloud.githubusercontent.com/assets/3899360/8532336/c42bbef0-242d-11e5-90a1-2078cd3811eb.JPG)

What's extra weird, is that github is also rotating the image after uploading, here is the original one take with an iphone: http://cl.ly/image/0h2m0H1o0D0m

**Comment by olivervogel** [comment]
Have you tried to use [orientate()] to correct image orientation after uploading?

```php
$img = \Image::make(Request::file('image'));
$img->orientate();
$img->resize(1024, null, function($constraint){ 
    $constraint->upsize();
    $constraint->aspectRatio();
});
$img->save("useruploads/".$image_name);
```

**Comment by iamgoodbytes** [comment]
Damned, I just found out that it's due to EXIF data being applied to the images, first time I encountered that. Thanks @olivervogel and sorry for logging the issue probably to quickly.

**Comment by sebastiaanluca** [comment]
Just had this issue (only on large images). Solution still works, thanks!

**Comment by alfredobarron** [comment]
Not found for me, some idea?

```
$img = Image::make($file);
$img->orientate();
$img->resize($width, $height, function ($constraint) {
    $constraint->upsize()
})
->encode();

Storage::put($path, (string) $img);
```

**Comment by ArtemProkopenko** [comment]
For those who do not help this method, you should pay attention to the next line from the documentation:

> Image object must be instantiated from file path to read the EXIF data correctly.

I initialized the instance by passing a URL to the picture, so this did not work for me.

**Comment by chimit** [comment]
@ArtemProkopenko so how did you solve the problem?

**Comment by ArtemProkopenko** [comment]
@chimit, I now have to first download the file from URL to disk and only then instantiated it from file path.

**Comment by csimpi** [comment]
Why just can't maintain the original aspect ratio? Hard to believe in 2020 we required to read the image exif data to maintain the orientation of an image. This is ridiculous. 
`$img->orientate();` didn't help
Storing the file, open it and process that image (as suggested above) didn't help.

Still wrong orientation... 

```
               //Store original file
               Storage::disk('uploads')->put($hash_file_name, $file);

               //Get the file from the disc to read the exif data to maintain orientation
               $file = Storage::disk('uploads')->get($hash_file_name);

                $img = Image::make($file);
                $img->orientate();

                $img->resize(null, 400, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
                Storage::disk('uploads')->put($hash_file_name.'.medium', $img->stream()->__toString());

```

**Comment by dgome** [comment]
I found the solution, it has taken me quite a long time:

`//Receive the image file in controller function
$imagedata = request()->file('image');

//Call image_orientate to change the orientation
$this->image_orientate($imagedata->getRealPath(), 90);

//And you use "intervention image" on the modified file, and that's it. 
$img = Image::make($imagedata);

.....
.....
//Function in controller, for example

function image_orientate($source, $quality = 90, $destination = null)
     {
         if ($destination === null) {
             $destination = $source;
         }
         $info = getimagesize($source);
         if ($info['mime'] === 'image/jpeg') {
             $exif = exif_read_data($source);
             if (!empty($exif['Orientation']) && in_array($exif['Orientation'], [2, 3, 4, 5, 6, 7, 8])) {
                 $image = imagecreatefromjpeg($source);
                 if (in_array($exif['Orientation'], [3, 4])) {
                     $image = imagerotate($image, 180, 0);
                 }
                 if (in_array($exif['Orientation'], [5, 6])) {
                     $image = imagerotate($image, -90, 0);
                 }
                 if (in_array($exif['Orientation'], [7, 8])) {
                     $image = imagerotate($image, 90, 0);
                 }
                 if (in_array($exif['Orientation'], [2, 5, 7, 4])) {
                     imageflip($image, IMG_FLIP_HORIZONTAL);
                 }
                 imagejpeg($image, $destination, $quality);
             }
         }
         return true;
     }

`

**Comment by semno** [comment]
`  $img = Image::make($image->path());

        $img->orientate();
        $img->resize(1024, null, function($constraint){
            $constraint->upsize();
            $constraint->aspectRatio();
        });
        $img->save();`

**Comment by mattvb91** [comment]
> `
> $img = Image::make($image->path());
> 
> ```
>     $img->orientate();
>     $img->resize(1024, null, function($constraint){
>         $constraint->upsize();
>         $constraint->aspectRatio();
>     });
>     $img->save();
> ```
> 
> `

none of these solutions work for me, any other ideas as to what could be causing the rotation?

**Comment by christoph-werker** [comment]
For all the ppl. that are still challenge this feature... Just put the `$img->orientate();` after the resize and it should work.

```php
$img = ImageManagerStatic::make($file->getPathname());
$img->resize(1000, null, function ($constraint) {
    $constraint->aspectRatio();
    $constraint->upsize();
});
$img->orientate();
$img->save($file->getPathname());
```

**Comment by microinginer** [comment]
> For all the ppl. that are still challenge this feature... Just put the `$img->orientate();` after the resize and it should work.
> 
> ```
> $img = ImageManagerStatic::make($file->getPathname());
> $img->resize(1000, null, function ($constraint) {
>     $constraint->aspectRatio();
>     $constraint->upsize();
> });
> $img->orientate();
> $img->save($file->getPathname());
> ```

Thanks, this solution works for me! Save my time!

**Comment by adelsedighi** [comment]
$img = Image::make($dest_path);
$img->orientate(); /* I only added this line and it fixed my problem */
$img->resize($width,$height);

**Comment by aifodu** [comment]
This has been working as expected with v2. But with the auto-orientation in v3 images are not re-oriented as expected. I would appreciate a nudge in the right direction if this is not an issue but a fault on my end.

Here's what I'm doing:

```
$manager = new ImageManager(new Driver());

$manager->read($file->getPathname())
                 ->scaleDown(700)
                 ->toPng()
                 ->toFilePointer();
```
