### ISSUE TITLE
Application version check [Laravel 4]

### ISSUE THREAD

**Issue by yorickdewid** [Intervention/image#394]
The application check in d6c915496f86a19f60197f7ab6ce2baed793f3f8 only works in Lumen and Laravel 5+. Since Laravel 4 doesn't support `$this->app->version()` the application fails.
```
[RuntimeException]                                                           
  Error Output: PHP Fatal error:  Call to undefined method Illuminate\Foundat  
  ion\Application::version() in /intervention/imag  
  e/src/Intervention/Image/ImageServiceProvider.php on line 66
```

**Comment by olivervogel** [comment]
Thanks for pointing out. 6771cbfc785a04cbf863879bc41991e5e2cf9ec3 should fix it.
