### ISSUE TITLE
imagick inside controoller

### ISSUE THREAD

**Issue by dhsagar** [Intervention/image#398]
I am new in laravel. I have installed Intervention Image package in my project as instructed http://image.intervention.io/getting_started/installation here. It is working properly while using inside my routes.php file. I ran the example provided in http://image.intervention.io/getting_started/installation#laravel.
it was like 
Route::get('/', function()
{
    $img = Image::make('foo.jpg')->resize(300, 200);

    return $img->response('jpg');
});
it worked perfectly. Even Imagick claass also work here. But I am facing problem when i try to use the same thing inside a controller file name imagecontroller.php . 
I can not understand what sould I write at the top of my imagecontroller.php. I used
use Intervention\Image\ImageManager; 
but still not working . It would be very helpful for me if get an example what should i include inside my imagecontroller.php file to run the code example i mentioned above.?
 I am a new laravel learner. May be the question is standard enough but please help.

**Comment by olivervogel** [comment]
You can use Laravel's [Controllers Dependency Injection](http://laravel.com/docs/5.1/controllers#dependency-injection-and-controllers) or just the Facade.
