### ISSUE TITLE
Can't find what's wrong..

### ISSUE THREAD

**Issue by Klousky** [Intervention/image#399]
Hi, i'm a student and i try to use Intervention/image with Symfony2. I followed the Instalation and Configuration. 
I'm trying to use the example from Usage->HTTP Response. 
I use 
use Intervention\Image\ImageManager;
use Intervention\Image\Response;
use Intervention\Image\Image;

with the code : 
$img = Image::canvas(800, 600, '#ff0000');
echo $img->response('jpg', 70);

But i get the issue : 
Attempted to call an undefined method named "canvas" of class "Intervention\Image\Image".

If someone can explain me what i am doing wrong 
Thanks by advance.

**Comment by willrowe** [comment]
Unfortunately, it isn't made very clear in the docs. You should be using the `ImageManager` or `ImageManagerStatic` class. As you can see [here](http://image.intervention.io/getting_started/configuration) under the 'Static Example' section, the manager is aliased:
```php
use Intervention\Image\ImageManagerStatic as Image;
```
