### ISSUE TITLE
Can't install through Composer

### ISSUE THREAD

**Issue by nateajohnson** [Intervention/image#400]
I am trying to install this into a fresh laravel 5 install and am getting this:

vagrant@homestead:~/Code/grow$ sudo composer require intervention/image
Using version ^2.3@dev for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/psr7 == 1.0.0.0 -> satisfiable by guzzlehttp/psr7[1.0.0].
    - intervention/image 2.3.0 requires guzzlehttp/psr7 ~1.1 -> satisfiable by guzzlehttp/psr7[1.1.0].
    - intervention/image 2.3.1 requires guzzlehttp/psr7 ~1.1 -> satisfiable by guzzlehttp/psr7[1.1.0].
    - intervention/image 2.3.x-dev requires guzzlehttp/psr7 ~1.1 -> satisfiable by guzzlehttp/psr7[1.1.0].
    - Conclusion: don't install guzzlehttp/psr7 1.1.0
    - Installation request for intervention/image ^2.3@dev -> satisfiable by intervention/image[2.3.0, 2.3.1, 2.3.x-dev].

**Comment by huglester** [comment]
Hello,

try maybe "intervention/image": "2.3.*" 
in composer.json?

**Comment by GencBlakqori** [comment]
First, you need to instal guzzlehttp/psr7.
Second, go to your php.ini file and uncomment this line : 
;extension=php_fileinfo.dll      To    extension=php_fileinfo.dll

**Comment by balinux** [comment]
;extension=php_fileinfo.dll To extension=php_fileinfo.dll
it's worked thanks

**Comment by hasib202030** [comment]
ok
