### ISSUE TITLE
Error photo when resize and upload photo to S3

### ISSUE THREAD

**Issue by vandung2k6** [Intervention/image#404]
Hi Guys,

I am using Intervention/image to resize photo.

I can resize photo, but when upload this photo to S3, have error for that photo as http://take.ms/K5se9

I am using laravel 4.2

Code:
$photo = Input::file('photo');
$img = Image::make($photo);
$crop = max($width, $height);
$img->resizeCanvas($crop, $crop, 'center', false, 'fafafa');
$img->save('abc.jgp');

Upload::pushToS3('abc.jgp');

I think: when $img is resizing and saving => at the same time, system run pushToS3 function.

How to fix it?

Many thanks.

**Comment by olivervogel** [comment]
I dont' know what "pushToS3" does, but I would not use `save()` to write into the local filesystem, if you want it in S3 anyway. I would use [encode()](http://image.intervention.io/api/encode) to get the image data directly and push the output of this method to S3.
