### ISSUE TITLE
Can`t install in laravel

### ISSUE THREAD

**Issue by Valonix** [Intervention/image#405]
In the $providers array add the service providers for this package.
'Intervention\Image\ImageServiceProvider'

i have another array
![image](https://cloud.githubusercontent.com/assets/8511169/9021847/6a56ed2a-3862-11e5-8021-b4c33df3f0df.png)

and so, i have error 

Fatal error: Undefined constant 'Intervention\Image\ImageServiceProvider' 

i am new in Laravel. so help me plz install this :)

**Comment by willrowe** [comment]
You should either wrap it in quotes:
```php
'Intervention\Image\ImageServiceProvider'
```
or use the class property like the others do in that file:
```php
Intervention\Image\ImageServiceProvider::class
```

**Comment by Valonix** [comment]
yes, thank.
