### ISSUE TITLE
Mandrill base64 encoded:NotReadableException in AbstractDecoder.php

### ISSUE THREAD

**Issue by lewiswharf** [Intervention/image#406]
Throws exception from Mandrill image attachment base64 encoded from:

	public function messageInbound() {
		$mandrill_events = Request::get('mandrill_events');
		$mandrill_events = json_decode(urldecode($mandrill_events));

		foreach ( $mandrill_events as $mandrill_event ) {
            foreach ( $mandrill_event->msg->attachments as $file ) {
                // retracted
                $content = (string) Image::make($file->content)->encode($file->type);
                // retracted
            }
        }
	
Composer update with *2.3.**. Any ideas?

**Comment by olivervogel** [comment]
Sorry, remote debugging is hard. You gotta check what `$file->content` contains.
