### ISSUE TITLE
Create image form html web page (screen capture)

### ISSUE THREAD

**Issue by MaximeEvolunium** [Intervention/image#407]
Hi, 

I need to create an image based on a web page (a screen capture). I seen it is possible to create an image from an URL like 'http://example.com/example.jpg' and that works well, but not with 'http://example.com'. Is it possible to do this ? 

Thanks !

**Comment by olivervogel** [comment]
No thats not possible. But there are command line scripts to create screenshots from websites. After these images are generated you can process them with Intervention Image.

**Comment by MaximeEvolunium** [comment]
Thanks @olivervogel, I will try ;)
