### ISSUE TITLE
Can't install via Composer

### ISSUE THREAD

**Issue by asaf050** [Intervention/image#408]
Hey,
I try to install the package with the Composer and I get this error:
 `[Composer\Repository\RepositorySecurityException]
 The contents of http://packagist.org/p/provider-latest$556fbba4af54f9f8142fd066692bdccd9bad766fecffd554a26bd352fd19
 d010.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.`

**Comment by olivervogel** [comment]
I think this is more a Composer issue.
