### ISSUE TITLE
Already Created autoload.php for this lib to include in PHP

### ISSUE THREAD

**Issue by rajjanorkar** [Intervention/image#409]
Hi Team,

Most of the projects on github have autoload.php created, so no need to use Composer.
I dont use Composer in my project. But i love to use this library, it looks really great lib.

- Is there any way to just use PHP include to use this lib?

Thank you.

**Comment by olivervogel** [comment]
I think it is possible, but I never tried to user Intervention Image without Composer. Since Composer is written in PHP, you have to figure out what Composer does and do the same thing manually with PHP.

**Comment by rajjanorkar** [comment]
Thank you @olivervogel, if someone can generate and ship the autolaod.php with every release that would be great.

**Comment by olivervogel** [comment]
Shipping the autoload.php with a release makes no sense. It depends on your local project and includes all your required composer dependencies.
