### ISSUE TITLE
Using in Laravel 5 without Facades

### ISSUE THREAD

**Issue by jonathantjh** [Intervention/image#413]
**Question :**
How do you use this without Facades in laravel 5?

**Answer : **
use Intervention\Image\Facades\Image as Image;

Call the functions accordingly after declaring the use.

**Comment by olivervogel** [comment]
Like explained in [documentation](http://image.intervention.io/getting_started/installation).

```php
// import the Intervention Image Manager Class
use Intervention\Image\ImageManagerStatic as Image;

// configure with favored image driver (optional)
Image::configure(array('driver' => 'imagick'));

// and you are ready to go ...
$image = Image::make('public/foo.jpg')->resize(300, 200);
```

**Comment by Kyslik** [comment]
@olivervogel  Where does it say in documentation to `use Intervention\Image\ImageManagerStatic as Image;` (while using Laravel)?

Laravel has ServiceProviders and Facades and method injection which does not work.

(I am on L5.3 - dev)
