### ISSUE TITLE
Image gets stretched and looks weird after resize()

### ISSUE THREAD

**Issue by harishtoshniwal** [Intervention/image#415]
I am using Laravel 5.1 on wamp 
Image before resize :

![110113-eminem-623-1383326611](https://cloud.githubusercontent.com/assets/11228182/9441667/05f34faa-4a95-11e5-80a1-8b592b6eae87.jpg)

Image after resize : 
![31](https://cloud.githubusercontent.com/assets/11228182/9441678/22ed5bd2-4a95-11e5-988b-de7748e2815a.jpg)

My code to store and resize the image : 

        static function uploadFile(Request $request, $recordId, $upload_field, $upload_path)
	{
		if ($request->hasFile($upload_field)) {
	        
	            if ($request->file($upload_field)->isValid())
	                {
	                    $destinationPath = public_path($upload_path);
	                    $extension = $request->file($upload_field)->getClientOriginalExtension(); // getting image extension
	                    $fileName = $recordId.'.'.$extension;
	                    $request->file($upload_field)->move($destinationPath, $fileName);

	                    Image::make($destinationPath."/".$fileName)->crop(200, 200)->save($destinationPath."/".$fileName,'jpg');

	              }
                   }
	         }
                }

Am I doing something wrong or what is the issue? Help or support would be highly appreciated :)

**Comment by olivervogel** [comment]
The second parameter is wrong.

```php
save($destinationPath."/".$fileName,'jpg');
```

Please check the documentation. 

http://image.intervention.io/api/save
