### ISSUE TITLE
Imagesource not readable with special characters

### ISSUE THREAD

**Issue by canfiax** [Intervention/image#416]
If the URL contains specialcharacters, like "æ, ø, å", it is not readable.

The following URL is not readable:

http://about.athliit.com/wp-content/uploads/2015/03/Frederik-Løchte-by-Pearl-B-20141-e1426678987643.jpg

**Comment by olivervogel** [comment]
For security reasons the route only accepts filenames consisting of the following characters a-z, A-Z, 0-9, - (minus), _ (underscore), / (slash) and . (dot).

**Comment by canfiax** [comment]
I see, but shouldn't this be made differently? Since above image is indeed valid, and can be accessed without issues on any browser.

**Comment by olivervogel** [comment]
Unfortunately PHP's own `filter_var` does not recognize this URL.

Check for yourself.

```php
// url
$url = 'http://about.athliit.com/wp-content/uploads/2015/03/Frederik-Løchte-by-Pearl-B-20141-e1426678987643.jpg';

// returns false (should be true?)
$check = (bool) filter_var($url, FILTER_VALIDATE_URL);
```

You may report this to the PHP core.
