### ISSUE TITLE
Serialize image operations

### ISSUE THREAD

**Issue by garygreen** [Intervention/image#418]
Is it possible to get some form of serialized operations that will be performed on the image?

**Comment by olivervogel** [comment]
Something like this is done in the [intervention/imagecache](https://github.com/Intervention/imagecache) package.

```php
$cache = new Intervention\Image\ImageCache;

$cache->make('foo.jpg');
$cache->greyscale();
$cache->resize(200, 200);

$serialized_operations = serialize($cache->calls);
```

**Comment by garygreen** [comment]
Thanks, didn't realise you could catch calls when inside a closure with the magic method.
