### ISSUE TITLE
Add memery check

### ISSUE THREAD

**Issue by DarioCorno** [Intervention/image#419]
I'm facing the common memory error, reaching the memory_limit with GD by manipulating large images (ok,not THAT large but GD takes up a lot of space to do tasks).

Is it possible to prevent that error by checking PHP settings and, maybe guessing memory needed to manipulate the image?

I'm not able to intercept the error in any way, even with the following code : 

    try{
        some_kind_of_loop{
           $img = Image::make($path);
           $img->fit(150)->save($destpath);
           $img->destroy();
        }
    } catch(Exception $e) {
         //never gets here
         warnSomeoneShitHappened($e);
    }

**Comment by olivervogel** [comment]
Would be nice to have but I don't think this is possible. As far as I know, if PHP runs out of memory it can't do anything, not even throw an exception.
