### ISSUE TITLE
error: exif_read_data(): Not a file in

### ISSUE THREAD

**Issue by Drive4ik** [Intervention/image#421]
Hi. i found error in your library
debug_backtrace:
http://prntscr.com/8bi2vw

this error was reproduce when you load binary image data and then call 
```php
$image->interlace()->orientate()
```
ExifCommand::execute call not with image object, its call with string `/`
and then on line 27 execute $image->dirname and then - error

please, fix it
Thanks & Regards,
Drive4ik

**Comment by olivervogel** [comment]
To use `orientate()` or `exif()` the image must be created from a file, because the PHP function `exif_read_data` reads from filesystem and not from a GD or Imagick instance/resource.

**Comment by Drive4ik** [comment]
Ok, but why you not add exception ex.: if file load from resource or has not path return empty "exif data"?

Thanks & Regards,
Drive4ik
