### ISSUE TITLE
Laravel-free package

### ISSUE THREAD

**Issue by shadowhand** [Intervention/image#422]
To improve the adoption of this package outside of the Laravel ecosystem, I would suggest separating all of the Laravel functionality into a separate package that depends on this one. While nothing in the current package prevents me from using it outside of Laravel, the extra files and configuration that is included is confusing. A separate package would be able to declare dependencies on Laravel/Illuminate, which would be beneficial for compatibility.

**Comment by olivervogel** [comment]
Thanks for your suggestion. I will keep this in mind for the next version.
