### ISSUE TITLE
Use images direct paths instead searching in folders?

### ISSUE THREAD

**Issue by lonerunner** [Intervention/image#424]
Is it possible to use images direct paths instead searching. I have sort of structure with dynamic folders where users can create their own folders and each of the users have separate folders.

For example 

`User 1`
`/public/uploads/1`
`User 2`
`/public/uploads/2`
`User 3`
`/public/uploads/3`

And each of the users can create own folders inside so user 1 can have
`/public/uploads/1/myavatars/avatar1.jpg`

Upon save i save full path in my database

`user_avatar`
`/public/uploads/1/myavatars/avatar1.jpg`

So is it possible to just have full path in imagecache instead searching for image in specific paths?

So i can use it like 

`route('imagecache', ['icons', $user->user_avatar ])`

where`icons` is my template and `$user->user_avatar` is image path `/public/uploads/1/myavatars/avatar1.jpg`

I have setup intervention image with imageache and url caching with laravel 5

**Comment by akempes** [comment]
I know it's an old issue but for anyone looking for the answer:

The getImagePath() function in the ImageCacheController.php will search for the exact path within the folder(s) specified in the 'paths' section of the imagecache.php config file.

In the case above I would only add the '/public/uploads' path the 'paths' section like:
```php
'paths' => array(
    public_path('uploads)
),
```
Now you safely use the routes:  
http://yourhost.com/{route-name}/{template-name}/1/myavatars/avatar1.jpg
http://yourhost.com/{route-name}/{template-name}/2/myavatars/avatar1.jpg
