### ISSUE TITLE
Support for  JPEG-2000 

### ISSUE THREAD

**Issue by monaye** [Intervention/image#425]
Is there any plan on supporting  JPEG-2000 ?

**Comment by RomainSauvaire** [comment]
Too bad this question has no answer. Yet a simple one. Please :)

**Comment by m-bosch** [comment]
As far as google want us to use the NEXT-GEN images it would be nice that we could use JPEG-2000 and JPEG-XR. webp we could use already but isnt supported on safari and lower IE's

**Comment by Hillcow** [comment]
Has been a long time since this has been asked. But I think it's still not possible?

**Comment by mattkenefick** [comment]
ping

**Comment by m-bosch** [comment]
Pong

**Comment by PommeVerte** [comment]
Anyone?

**Comment by olivervogel** [comment]
Jpeg2000 format is now supported as of Version `3.2` with Imagick driver.
