### ISSUE TITLE
i got "Image file missing" error in Laravel 5

### ISSUE THREAD

**Issue by ysupr** [Intervention/image#429]
So i installed intervention image for my laravel projects. everythings going fine when i using local image. but problem when i use make() from another url.

i use this ones

```
$img = Image::make('https://farm6.staticflickr.com/5816/21602569956_bb060c3562_q.jpg')->save("image.jpg");
```

i have checked my allow_url_fopen is enable. and i running in my local vagrant. 
is it problem with http to https ? or other things?

**Comment by olivervogel** [comment]
I don't know but Flickr might do some stuff to block certain clients. I would fetch the image with a seperate http request and be able to debug the status. Intervention Image just uses `file_get_contents` which might end up with unknown errors.

**Comment by ysupr** [comment]
I have handled this problem using normal file_get_content then using file_put_content to produce the image. And it works with flickr too.

Maybe i'll check it later why intervention fail to getting the image
