### ISSUE TITLE
Usage with Cloud filesystem, i.e. Amazon AWS S3

### ISSUE THREAD

**Issue by canfiax** [Intervention/image#431]
How can I setup image intervention to upload images to my cloud storage setup in L5 filesystem config?

Most applications running on DigitalOcean will need some additional cloud if they are hosting images, so we're talking about a relatively large market (laravel applications hosting images, running on i.e. DO).

**Comment by olivervogel** [comment]
You take the result of encode() and save it to any storage you like.

```php
$data = (string) Image::make('public/foo.png')->encode('jpg', 75);
Storage::put('file.jpg', $data);
```

**Comment by Ardakilic** [comment]
@olivervogel 's solution gave me another error:

```
League/Flysystem fstat() expects parameter 1 to be resource, object given
````

So I had to modify a bit.

Since the second parameter needs to be a string, I appended the `__toString()` method.

```php
$data = (string) Image::make('public/foo.png')->encode('jpg', 75)-> __toString();
Storage::put('file.jpg', $data);
```

And it works as a treat.
