### ISSUE TITLE
How to convert TGA image ? 

### ISSUE THREAD

**Issue by anonprophet** [Intervention/image#437]
i want convert TGA to JPG, i dont find API something like
`convert()`

sorry for noob question

**Comment by olivervogel** [comment]
```php
Image::make('foo.tga')->save('foo.jpg');
```

**Comment by anonprophet** [comment]
thx im already doing that
``
$img = Image::make(public_path('WC3ScrnShot_090515_002602_01.tga'));
$img->save(public_path('WC3ScrnShot_090515_002602_01.jpg'));
``

but got error
```
NotReadableException in Decoder.php line 21:
Unable to read image from file (C:\xampp\htdocs\laravel5\public\WC3ScrnShot_090515_002602_01.tga).
```

already try use Imagick
