### ISSUE TITLE
NotReadableException

### ISSUE THREAD

**Issue by alainbelez** [Intervention/image#438]
~~~
Unable to init from given url (https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xta1/v/t1.0-9/12143298_1185327551493926_8427033518728564976_n.jpg?oh=3756f6ed0a31f054cee2c7dfedb2ab5c&oe=5692B7E8&__gda__=1452461077_be71424b6be03ae56f80eeb8ff7d7dd6)
~~~
the file do exist.

**Comment by olivervogel** [comment]
The host might do some stuff to block certain clients. I would fetch the image with a seperate http request and be able to debug the status. Intervention Image just uses file_get_contents which might end up with unknown errors.
