### ISSUE TITLE
Not all IPTC tags are returned

### ISSUE THREAD

**Issue by haricharan** [Intervention/image#439]
Is there a reason not all tags from `iptcparse()` are read and returned when we call `$image->iptc()`?

For example, Sub Location & Creation Time is not parsed. The following lines should be added to `IptcCommand.php` to parse those values.

```
$data['SubLocation'] = isset($iptc["2#092"][0]) ? $iptc["2#092"][0] : null;
$data['CreationTime'] = isset($iptc["2#060"][0]) ? $iptc["2#060"][0] : null;
```

Can I submit a pull request for this?

**Comment by olivervogel** [comment]
Sure, please do.
