### ISSUE TITLE
::make() fails silently

### ISSUE THREAD

**Issue by JeremyHargis** [Intervention/image#441]
Hi, there. I am trying to use this package in a Laravel 5.1 project I am working on. I am seeing an issue on my Windows dev machine. Basically, I have a very simple file upload page. Files uploaded here are used with the Intervention make() method for later processing. The snippet I am testing is very simple:

```php
InterventionImage::make($file->getPathName());
```

In this snippet, InterventionImage is what I have the Intervention facade mapped to. This line works for most images, but for SOME jpgs, it fails silently and I am returned a 500 status for the POST-to URL (I see a blank white screen). No exceptions are thrown and nothing shows up in laravel.log. Execution just stops. When I debug this in PHPStorm, execution goes right up to this line and then halts.

Looking at the jpgs that fail, there seems to be a trend that the jpgs that fail are all larger images (~5k x 3k and above). That is really my only hint, but I have post_max_size and upload_max_filesize in php.ini set much higher than the size of these images so that could simply be correlation rather than causation.

Any ideas for what might be going on here?

Thanks for your help.

**Comment by olivervogel** [comment]
My guess is that you run out memory. Try to set the `memory_limit` directive to a higher value in php.ini.

**Comment by JeremyHargis** [comment]
@olivervogel Thank you for your prompt response. Yes, that fixed it for me. Thanks for your help in this.

**Comment by IrishAdo** [comment]
I have this problem when trying to load a large jpeg but when I use php's ini_get print the memory limit its 128MB of ram    the image is 3000+ pixels wide by 4000px+  but is only 1.2MB in size  if I crop the image down to 1200px wide it works fine.

**Comment by IrishAdo** [comment]
ok tracked this down.
ini_set('memory_limit','256M');
and removed the @ symbol from the following Gd/Decoder.php 

$core = imagecreatefromjpeg($path);

file is uploaded via php upload and works correctly for smaller files
![20161015_205724](https://cloud.githubusercontent.com/assets/634607/19455165/01ba311e-94b4-11e6-9a19-76b22c0e64cb.jpg)


Warning: imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG in /Users/myaccount/Development/Sites/mysite/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on line 35

Warning: imagecreatefromjpeg(): '/Users/myaccount/Development/Sites/mysite/files/tmp/ffec80542d38a4569071299919e21064.jpg' is not a valid JPEG file in /Users/myaccount/Development/Sites/mysite/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on line 35

Notice: Undefined variable: image in /Users/myaccount/Development/Sites/mysite/src/app/admin_ecards.php on line 222



Any ideas would be very welcome

**Comment by IrishAdo** [comment]
work around add this before call to imagecreatefromjpeg
ini_set ('gd.jpeg_ignore_warning', 1);
