### ISSUE TITLE
Text stroke (outlines) not working?

### ISSUE THREAD

**Issue by graphicgeek** [Intervention/image#443]
This appears to have been added (https://github.com/Intervention/image/pull/289), but when I attempt to use it I get this error:

Call to undefined method Intervention\Image\Imagick\Font::strokeWidth()

Here's the code I'm using:

$fontFile = public_path('fonts/times_new_yorker.ttf');

        $image->text('my text', 250, 15, function($font) use($fontFile) {
            $font->file($fontFile);
            $font->size(24);
            $font->color('#fff');
            $font->align('center');
            $font->valign('top');
            $font->strokeWidth('3');
        });

**Comment by olivervogel** [comment]
No, https://github.com/Intervention/image/pull/289 is not merged.

**Comment by elliottchaves** [comment]
the #289 will be merged any time?

**Comment by NotNoah** [comment]
Could #289 be merged in?

**Comment by erickskrauch** [comment]
[I have implemented a one-stop solution](https://github.com/Intervention/image/pull/609). Until it will be merged, you can use it by adjusting you `composer.json` file:

1. Add repositories section with my fork link:
   ```json
   {
       "repositories": [
           {
               "type": "git",
               "url": "git@github.com:erickskrauch/image.git"
           }
       ]
   }
   ```

2. Require branch version:
   ```json
   {
       "require": {
           "intervention/image": "dev-text_stroke"
       }
   }
   ```
