### ISSUE TITLE
Creating Dynamic Filters with attributes

### ISSUE THREAD

**Issue by rafaelcanical** [Intervention/image#445]
Is it possible somehow to create a dynamic filter, where we send trough the [url](http://image.intervention.io/use/url) the `width` and `heigth` of the new image?

Somethink like:

``` html
http://127.0.0.1/my-app/imagecache/myfilter/1200x300/image-path.png
```

**Comment by olivervogel** [comment]
I guess, you can read the size from the url in your [template class](http://image.intervention.io/use/url) and resize to the passed dimension.
