### ISSUE TITLE
Image::make() throws an exception for certain files

### ISSUE THREAD

**Issue by james-ff** [Intervention/image#451]
Hello,

I'm developing an iOS app that relies on a Laravel API backend

Image uploading had previously worked fine using this library and Alamofire for file uploading, until recently
- Some images now cause a NotReadableException where there used not to be one

Does anyone know why this might be?

To reiterate, the images that throw the exception are normal photos from my iPhone camera roll, no different from those that work fine.

Many Thanks

**Comment by abhimanyusharma003** [comment]
Check if you have fileinfo and exif extensions enabled.

**Comment by james-ff** [comment]
![screen shot 2015-11-06 at 02 48 31](https://cloud.githubusercontent.com/assets/1874352/10988055/edbda68a-8430-11e5-9b61-f8d490f8f33d.png)

This is what phpinfo() is returning

**Comment by JapSeyz** [comment]
I have the same issue.

This code:
    <img src="{{public_path('img/qr_front.png')}}">
Is working fine, but this:
    \Image::make(public_path('/img/qr_front.png'));
throws an NotFoundException on AbstractDecoder.php line 302.

The strange part is that it works just fine when calling it from a controller, but throws the exception when called through a Queue Job. (Laravel)

**Comment by carbontwelve** [comment]
I wonder if this is to do with what the helper function `public_path` returns given the differing environment context.

**Comment by jmichaelterenin** [comment]
Having the same problem, called through frozennode/administrator, here is my phpinfo:
exif

EXIF Support	enabled
EXIF Version	1.4 $Id: ab2a50435139d06a6aaac1b47adb458267625069 $
Supported EXIF Version	0220
Supported filetypes	JPEG,TIFF
Directive	Local Value	Master Value
exif.decode_jis_intel	JIS	JIS
exif.decode_jis_motorola	JIS	JIS
exif.decode_unicode_intel	UCS-2LE	UCS-2LE
exif.decode_unicode_motorola	UCS-2BE	UCS-2BE
exif.encode_jis	no value	no value
exif.encode_unicode	ISO-8859-15	ISO-8859-15
fileinfo

fileinfo support	enabled
version	1.0.5
libmagic	517

**Comment by dhensby** [comment]
sounds like this can be closed?
