### ISSUE TITLE
Problem with transparent png image

### ISSUE THREAD

**Issue by matpache** [Intervention/image#455]
Dear, 
I need to format a png image that is to paste a signature generator certificates.
The problem is that the image is transparent and reformatting (leave of 650x650 px) leaves completely black.
The code is:

<code>$signature = Image::make($destinationPath.'/'.$fileName);</code>
<code>$width = $signature->width;</code>
<code>$height  = $signature->height;</code>
<code>$signature->resizeCanvas(($width > $height) ? $width : $height, ($width > $height) ? $width :    $height, 'center', false, 'rgba(0, 0, 0, 0)');</code>
<code>$signature->resize(650, 650);</code>
<code>$signature->save($destinationPath.'/'.$fileName);</code>

The idea is that the canvas is completely transparent.
greetings from Chile !

**Comment by olivervogel** [comment]
Because you're using the width/height properties, I assume you're using version 1.*

I recommend to [upgrade to version 2.*](http://image.intervention.io/getting_started/upgrade).

**Comment by matpache** [comment]
Dear, thank you very much worked perfect, actually it was version 1. *, Greetings!
