### ISSUE TITLE
No EXIF info if Storage facade is used to read the file.

### ISSUE THREAD

**Issue by abhimanyusharma003** [Intervention/image#456]
If Storage facade is used, `exif()` returns `null`

```php
$img = Storage::read('image.jpeg'); // Using S3 or Dropbox or local
$image = Image::make($img);
dd($image->exif()); // NULL
```

The reason i'm using Storage facade is to get image from cloud based drivers. 

**Image orientation is also ignored**

It think because of this issue `image orientation` is also not working fine.

If this is not the correct way, **how can I read/resize image from cloud driver.**

**Comment by abhimanyusharma003** [comment]
Even if base64 encoded image passed, there is no `EXIF`  info and `image orientation` is complete ignored.

**Comment by olivervogel** [comment]
Like mentioned in the [docs](http://image.intervention.io/api/exif), the image object must be instantiated from file path, to read EXIF info.

**Comment by abhimanyusharma003** [comment]
@olivervogel I can understand that, but what if i'm using cloud driver like amazon s3, in that case `image orientation` is ignored. There must be some way to do this.
