### ISSUE TITLE
encode() quality makes no difference to final image

### ISSUE THREAD

**Issue by christiangusukuma** [Intervention/image#459]
Hi,
It dont matter if i use 1 or 100 for the quality parameter, the final image will have the same quality aways.
I'm using laravel 5.1.

my code:
Image::make(Input::file('foto1'))->encode('jpg', 50)->fit(300, 200)->save('uploads/capa_' . $random1 .'.jpg');

Any guess?

By the way, sorry for my bad english.

**Comment by olivervogel** [comment]
```php
// this should work
Image::make(Input::file('foto1'))->fit(300, 200)->save('uploads/capa_' . $random1 .'.jpg', 50);
```
