### ISSUE TITLE
 Could not load package intervention/image in http://packagist.org

### ISSUE THREAD

**Issue by nickleus73** [Intervention/image#464]
Hi,

I don't know why, but I have this error when I install your project in Laravel:

`[RuntimeException]                                                                                                                                                      
  Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.x.x: Invalid version string "4.x.x" `

Then: 

`[UnexpectedValueException]                                                
  Could not parse version constraint 4.x.x: Invalid version string "4.x.x"`

In my case (in France), this problem appeared this afternoon :(

I hope can help me :)

**Comment by paulgrimes1** [comment]
Hi, FWIW I'm getting the same issue, but only when a `composer update` is attempted *outside* of vagrant / Laravel homestead. Inside vagrant/homestead, all is well..

**Comment by Rjs37** [comment]
I'm seeing this problem from within Vagrant. I don't have composer setup from the outside so can't try that.

**Comment by r3oath** [comment]
Can confirm, updating my `composer.phar` solved this issue for me. Most likely an added feature in the latest composer to support `.x` wildcards on versions.

**Comment by nickleus73** [comment]
Nice ! Thanks :)

For me, I executed `docker pull composer/composer`

**Comment by anrei0000** [comment]
Can confirm as well, running `composer self-update` then `composer update` worked.

**Comment by KMDSOUF** [comment]
You have just to update composer to the latest version

**Comment by somesh79** [comment]
Composer self-update then composer update worked.

**Comment by JureVeler** [comment]
Updating composer fixed it for me as well.

**Comment by moaxaca** [comment]
I got it working, but after I removed my apt-get composer and manually installed it. It might be helpful to note if you installed composer via apt-get it will not have the update-self command.
