### ISSUE TITLE
Option to save a custom dpi (density?) in a jpg

### ISSUE THREAD

**Issue by thepeels** [Intervention/image#465]
I have a site processing images for including in word and pdf documents to be printed at 300dpi. Is it possible to add a class to save the image with 300dpi in the image properties? This enables the image to be shown at the correct size by default instead of needing to be re-sized by the user.

**Comment by jubairsaidi** [comment]
I second this, this is also important when converting SVG (vector) images to a non vector format and to do so, you may need to use the dpi to control the "size" of the image without loosing image quality.

An example of how i do this now, lets say a DPI of 6000 with Imagick is:
```
        $image = new Imagick();
        $image->setResolution(6000, 6000);
        $image->setBackgroundColor(new ImagickPixel('transparent'));
        $image->readImageBlob(file_get_contents('path/to/image.svg');
        $image->setImageFormat("png32");
        $image->writeImage('path/to/new-image.png');
```

Now obviously I know that after this I can pass the $image object into Intervention, but it would be nice to have the **setResolution** method built into the Intervention api.

**Comment by badalsurana** [comment]
+1 for the setResolution method built into the Intervention api

**Comment by jasperf** [comment]
> I have create the Imagick command for setImageResolution methode, where can I submit my file?

You can do a pull request at this repo I would think @gregoryroda . Was looking for something like this for @2 retina images so this would be a welcome addition.

**Comment by LastDragon-ru** [comment]
#959 😄

**Comment by olivervogel** [comment]
This should be possible with [version 3](https://image.intervention.io/v3/).
