### ISSUE TITLE
Unable to run composer update

### ISSUE THREAD

**Issue by Albofish** [Intervention/image#467]
I'm trying to update my Laravel packages and it falls over when this package is present. Removing image and imagecache from my composer file and deleting from vendors and config/app.php allows composer to update.

`Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.x.x: Invalid version string "4.x.x"`

**Comment by esbenp** [comment]
I have same error.

**Comment by esbenp** [comment]
@Albofish https://github.com/Intervention/image/issues/464

**Comment by shuuichiakai** [comment]
have same error :(

**Comment by olivervogel** [comment]
This seems to be a Composer issue, explained here: https://github.com/Intervention/image/issues/464

**Comment by Uhelliton** [comment]
I decided to enabling the extent
php_fileinfo.dll in => php.ini
