### ISSUE TITLE
NotReadableException on a 777 image

### ISSUE THREAD

**Issue by nWidart** [Intervention/image#473]
Hello,

I've been getting the `NotReadableException` when trying to perform image manipulations, starting with `->make($path)`.

This is the current step that fails:

``` php
$image = $this->image->make($this->getDestinationPath($path->getUrl()));
```
This for some reason returns `"Intervention\Image\Exception\NotReadableException"`. 

Even though when I dump the following, it returns `true`:

``` php
var_dump($this->fileExists($this->getDestinationPath($path->getUrl()))); exit;

private function fileExists($filename)
{
    return $this->filesystem->disk($this->getConfiguredFilesystem())->exists($filename);
}
```

The weird part is that it works when I'm using the Amazon S3 adapter for Flysystem. But it only fails when reading the file locally.

The file has a `0777` permission, `-rwxrwxrwx`.

Any hints as to why I'm getting this ?

Thank you,

**Comment by olivervogel** [comment]
Hard to say, without access to the machine. The best way is read the image file "manually" with PHP (or Flysystem) and pass the raw image data to `make`.

**Comment by nWidart** [comment]
Thank you very much. Indeed, a simple `get(file)` did the trick, instead of giving the make method the image path.

Thanks again :smile:
