### ISSUE TITLE
Empty content

### ISSUE THREAD

**Issue by gocanto** [Intervention/image#493]
Hey there, I am using your package along with the new version of Laravel (5.2) and I am getting and empty content (blank image) using the example that you got posted on your web site. 

Example:

// create a new image resource
$img = Image::canvas(800, 600, '#ff0000');

// send HTTP header and output image data
header('Content-Type: image/png');
echo $img->encode('png');

I do not know why it happens because I have the same controller doing the duty with the before Laravel version and it works fine. 

any guide will be great.

thanks!

**Comment by olivervogel** [comment]
Any error messages in log files?

**Comment by gocanto** [comment]
No bud.. There is not logs at all. that's why I came up to you guys. I am still having the issue

**Comment by olivervogel** [comment]
Hard to remote debug your application without any further information. Have you tried to use [Laravel's own HTTP response classes](https://laravel.com/docs/5.2/responses) instead?

**Comment by gocanto** [comment]
Yes sir, I have tried everything I could and found as solutions around the web. This is my implementation, nothing major because I wanted to see if the error was in the app itself



Route:
Route::get('image/{file?}', 'FileController@image')->where('file', '(.*)');

Controller:

public function image(Request $request, $file)
    {
        $path = storage_path() . '/files/'. $file;

        echo $path;

        $img = \Image::make($path);

        // dd($img);

        // $img = \Image::canvas(800, 600, '#ff0000');

        // $img->save($path.'hey.png');

        return \Image::make($path)->response('png');

        // header('Content-Type: image/png');
        // echo $img->encode('png');

        // dd($img);

        // $response = \Response::make($img)->header('Content-Type', 'image/png');



        // // set content-type
        // // $response->header('Content-Type', 'image/png');

        // dd($response);

        // return $response;

        // dd($file, $path, $response);
    }


I left the comments to see if you can be guided out.

Thanks

**Comment by olivervogel** [comment]
I just tried your example with Laravel 5.2 on my machine and it works fine. The last thing I can think of is a memory issue, if you're trying to load a large image, your PHP instance may be crashing without an error because it runs out of memory set by `memory_limit` in your php.ini settings.

Memory Settings: http://image.intervention.io/getting_started/configuration

**Comment by gocanto** [comment]
it is so weird because my memory limit is set up to 512M. I have the same package working fine with a previous version of Laravel.

I am trying to have this running after I updated to the 5.2. is there something different to be aware of? any other ideas

**Comment by olivervogel** [comment]
Maybe set it even higher. Sorry, but I think I can't help you.

**Comment by gocanto** [comment]
yes, i know it is a weird error.. I also tried changing my memory_limit to 32M as it is said on the web site,but still nothing happened.. 

Thanks.. hopefully somebody else can have an clue about it.

**Comment by gocanto** [comment]
@olivervogel You were right my friend, there is something going on in my local box.. I just tested the example on line and it is working well.. Thanks for the guiding!

**Comment by gocanto** [comment]
hey there, i have upgrade my vagrant & homestead and I have the issue yet... another suggestion for this crazy scenario?

**Comment by canfiax** [comment]
Same issue here - both locally and on production. No images. See

https://github.com/Intervention/image/issues/501

Resposne output:

![image](https://cloud.githubusercontent.com/assets/3786627/12342627/89f79f74-bb2c-11e5-997e-bab9eaaf9814.png)

**Comment by gocanto** [comment]
I still have that issue.. I assume that is Laravel version, but nobody else says anything and that's why that I am looking for another solution.. if ya'll find something, please, post it out

**Comment by tiran133** [comment]
I recently updated my virtual box to 5.0.
Since then I have this error as well and I'm still on L5.0. 

My homestead is 0.2.5. and my Vagrant version is 1.8.1

I haven't found a solution yet. I keep you updated.

**Comment by angelov** [comment]
Any progress on this? I'm having the same issue.

It is okay if I try to generate an image using only GD, for example:

```php
<?php

header("Content-Type: image/png");
$im = @imagecreate(500, 500)  or die("Cannot Initialize new GD image stream");
$background_color = imagecolorallocate($im, 0, 0, 0);
$text_color = imagecolorallocate($im, 233, 14, 91);
imagestring($im, 50, 5, 5,  "It works", $text_color);
imagepng($im);
```

but when I try to create an canvas or show an image using the library, i get only an empty square, like in the previous comments:

```php
<?php
include '../vendor/autoload.php';

$manager = new \Intervention\Image\ImageManager(['driver' => 'gd']);
$img = $manager->canvas(500, 500, '#FF0000');
$response = $img->response('png');

var_dump($response);
```

**Comment by canfiax** [comment]
@angelov be sure to check for any whitespace outside any <?php tag. That was the issue for me.

In a `app/config.php`-file, I had a tab character before the PHP tag started, and that caused the empty square.

A way to test this, could be to make a route that returns nothing, and then inspect the source to check if the output is actually empty as expected. If not, good luck finding that space/tab/whatever.

**Comment by angelov** [comment]
@canfiax you were right, there was some whitespace. Thank you.

**Comment by kai101** [comment]
Have this issue earlier, try to check the buffer and confirmed a white space. 

After fixing the white space everything back to normal.

**Comment by leandromatos** [comment]
Thanks @canfiax.

**Comment by Nube2021** [comment]
Hey same issue here. Really horrible experience. I'm stuck with this error since 4 hours now. How can it be that it show nothing, just a blank page??!
I have isolated my code to these few lines: 


`			    $imageObj1 = Image::make('imagepath/image1');
			    echo "hello";
			    $imageObj2 = Image::make('imagepath/image2');   // when I comment this line, both "hellos" are echoed. When the line is executed, I see only a blank page.
			    echo "hello";
`

**Comment by gocanto** [comment]
Thanks so much @angelov 


That's was the problem..

**Comment by lednhatkhanh** [comment]
@simplenotezy You saved my life! For me, it's the `imagecache.php` file itself...

**Comment by gduffy100** [comment]
I couldn't find where the whitespace was being added so I used ob_clean() to empty the output buffer at the start of my controller method.
