### ISSUE TITLE
Why file_get_contents($url) or file_get_contents(urlencode($url)) returns http request fail

### ISSUE THREAD

**Issue by at-ngocp** [Intervention/image#494]
http://stackoverflow.com/questions/34649859/why-file-get-contentsurl-or-file-get-contentsurlencodeurl-returns-http-r

**Comment by olivervogel** [comment]
For remote content I would always use CURL or libraries like Guzzle to fetch the data first and pass it to Intervention Image afterwards. This way you have better control over HTTP errors and can take the necessary measures.
