### ISSUE TITLE
The problem with the alignment of the text

### ISSUE THREAD

**Issue by cawa-93** [Intervention/image#495]
``` php
    require_once 'vendor/autoload.php';
    use Intervention\Image\ImageManagerStatic as Image;

    $img = Image::make($_GET['backgroundsPath'].$_GET['backgroundFile']);

    $img->text($_GET['text'], 335, 175, function ($font) {
        $font->file('../fonts/intro-black-caps-webfont.woff');
        $font->size(34);
        $font->color("#ffffff");
        $font->align('center');
        $font->valign('top');
    });
```

![2016-01-09 12 14 42](https://cloud.githubusercontent.com/assets/1662812/12215563/99d9dc60-b6ca-11e5-85dd-86b02bf766e4.png)
As can be seen in the image of the text in the middle position. But the text is not formatted correctly.
How do I get something like this result?
![2016-01-09 12 17 49](https://cloud.githubusercontent.com/assets/1662812/12215566/10f776e0-b6cb-11e5-975e-86d28406abd8.png)

**Comment by olivervogel** [comment]
There is an issue with Intervention Image and `GD` library when writing multiline text. I suggest to use Intervention Image with `Imagick` driver for now.

**Comment by kovinet** [comment]
I am using `Imagick` and I am trying to align text  vertically to middle and it is not working when text is multi line.

![image](https://user-images.githubusercontent.com/707846/163252410-456a1243-44e2-401e-b9d6-6dfbe3c25a58.png)

And with multi line text (same code):

![image](https://user-images.githubusercontent.com/707846/163252617-ae479393-9a3e-4913-93b6-fb3ab17c0c6c.png)

```php
$img->text($titles, 640, 360, function (Intervention\Image\Imagick\Font $font) {
        $font->file(storage_path('fonts/Roboto-Regular.ttf'));
        $font->size(22);
        $font->color('#ffffff');
        $font->align('center');
        $font->valign('middle');
    });
```

basepoint is exactly in center of the image. According to comments above this is supposed to work?

**Comment by omarshamali** [comment]
reopening

**Comment by wyyr** [comment]
any solution for aligning center text over image ?

**Comment by genzoadam** [comment]
Try to do something like this
`//get image width and height
            $image_width = Image::make($image->getRealPath())->width() / 2;
            $image_height = Image::make($image->getRealPath())->height() / 2;

            Image::make($image->getRealPath())->text('Genzo Adam', $image_width , $image_height, function($font) {
                                                $font->file(storage_path().'/app/public/font/AppleTea-z8R1a.ttf');
                                                $font->size(50);
                                                $font->color('#f1f1f1');
                                                $font->align('center');
                                                $font->valign('middle');
                                            })->save($path, 50);`

**Comment by genzoadam** [comment]
Try to do something like this
```php
//get image width and height
            $image_width = Image::make($image->getRealPath())->width() / 2;
            $image_height = Image::make($image->getRealPath())->height() / 2;

            Image::make($image->getRealPath())->text('Genzo Adam', $image_width , $image_height, function($font) {
                                                $font->file(storage_path().'/app/public/font/AppleTea-z8R1a.ttf');
                                                $font->size(50);
                                                $font->color('#f1f1f1');
                                                $font->align('center');
                                                $font->valign('middle');
                                            })->save($path, 50);
```

**Comment by putrafajarh** [comment]
I have this problem too, already try add align center and valign middle
<img width="783" alt="Screenshot 2023-09-20 at 11 02 43" src="https://github.com/Intervention/image/assets/39898896/5f1863d9-e0b0-418c-a7dd-791443639255">

**Comment by genzoadam** [comment]
have u tried width() / 2 & height() / 2 to get the real center pixel of your image? not just align/valign. 
check the code carefully on my [last replay](https://github.com/Intervention/image/issues/495#issuecomment-1712102986) because ive done with this issue with that.

**Comment by putrafajarh** [comment]
@genzoadam its not about centering the text vertically or horizontally,
I want to the text-align to be centered, not align left. (2 line)
