### ISSUE TITLE
darkening grayscale bug

### ISSUE THREAD

**Issue by dehenne** [Intervention/image#497]
In ImageMagick exists a darkening grayscale bug. The Bug exists in 6.7.6 and 6.7.7.

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=23092&sid=f489924de8692fe13fd47be112e54bbe&start=15

But we can use a workaround:

``` php
$image->transformImageColorspace(\Imagick::COLORSPACE_RGB);
```

I don't know the whole library, so i don't know where to fix it correctly.
For me i make a workaround in:
https://github.com/Intervention/image/blob/master/src/Intervention/Image/Imagick/Encoder.php#L46

and insert:

```
$imagick->transformImageColorspace(\Imagick::COLORSPACE_RGB);
```

Exists a better solution? Can I set a global colorspace?

**Comment by te-chris** [comment]
+1
