### ISSUE TITLE
Problem with text Vertical positioning 

### ISSUE THREAD

**Issue by cawa-93** [Intervention/image#498]
```php
	$text = "123456";
	require_once 'vendor/autoload.php';
	use Intervention\Image\ImageManager;

	$manager = new ImageManager(array('driver' => 'imagick'));
	$img = $manager->make('http://tigermilk.ru/generator/backgrounds/humor-bd3f29.jpg');

	$img->text($text, 0, 0, function ($font) {
		$font->file('../fonts/OpenSansSemiBold.ttf');
		$font->size(34);
		$font->color("#ffffff");
		$font->align('left');
		$font->valign('top');
	});

	echo $img->response();
```
If one line, the text is inserted where needed. 
![1](https://cloud.githubusercontent.com/assets/1662812/12419918/ca8b164a-bec1-11e5-95e3-65793056091c.jpg)

But with an increase in the number of lines of text falls below all of the specified coordinates.
```php
	$text = "1\n23456";
```
![2](https://cloud.githubusercontent.com/assets/1662812/12419936/e12ddffe-bec1-11e5-8e8a-1e84086793b4.jpg)
```php
	$text = "1\n2\n3456";
```
![3](https://cloud.githubusercontent.com/assets/1662812/12419947/eee8350e-bec1-11e5-91fe-306385b7fa7d.jpg)
```php
	$text = "1\n2\n3\n456";
```
![4](https://cloud.githubusercontent.com/assets/1662812/12419953/f6ca95c8-bec1-11e5-8daa-fa5f4c6fa700.jpg)

**Comment by Dadibom** [comment]
This is not fixed, why is the issue closed?
