### ISSUE TITLE
ImageMagick module not available with this PHP installation.

### ISSUE THREAD

**Issue by kadirarli** [Intervention/image#499]
$ /Applications/XAMPP/xamppfiles/bin/php -i | grep imagick
imagick
imagick module => enabled
imagick module version => 3.3.0
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0

ImageMagick module not available with this PHP installation.

Can u help me?

**Comment by nivv** [comment]
I think you need to install ImageMagick. Imagick is the PHP-library that depends on ImageMagick
