### ISSUE TITLE
Imagick isn't working with BMP

### ISSUE THREAD

**Issue by TechKat** [Intervention/image#500]
I have ```imageimagick``` installed, along with ```php5-imagick```.

I run a minimal image hosting service which does support BMP images. The error Laravel throws back at me is:

```
exception 'Intervention\Image\Exception\NotReadableException' with message 'Unable to init from given binary data.' 
/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:91
```

The image.php config file's driver setting is on: imagick

**Comment by olivervogel** [comment]
Can't really say, without access to the BMP file or machine. Maybe your Imagick installation has no BMP support compiled in? Maybe the the BMP file is corrupted?

**Comment by TechKat** [comment]
I've managed to get it to work with BMP files... However Image causes BMP files to download, rather than display as an image inside the browser. Is that meant to happen?
