### ISSUE TITLE
file_exists and imagettfbbox might use different base paths

### ISSUE THREAD

**Issue by mermshaus** [Intervention/image#507]
Hi.

The code in `Intervention\Image\Gd\Font::getBoxSize()` ([link](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Gd/Font.php)) tests whether a font file exists before passing the path to `imagettfbbox`. That doesn’t work in all cases for all kinds of paths because `file_exists` and `imagettfbbox` use different logic to resolve “virtual” paths like `"arial.ttf"` that are neither relative nor absolute. `file_exists` seems to resolve these paths in relation to the current working directory whereas `imagettfbbox` seems to use the content of the `GDFONTPATH` environment variable as basis. This leads to situations in which a file exists but is not found by `imagettfbbox`.

Code to demonstrate the general issue (`arial.ttf` needs to exist in the directory):

``` php
<?php

putenv('GDFONTPATH=');
$font = 'arial.ttf';
if (file_exists($font)) { imagettfbbox(12, 0, $font, 'test'); }
    // PHP Warning:  imagettfbbox(): Could not find/open font

putenv('GDFONTPATH=.'); // Note the dot
$font = 'arial.ttf';
if (file_exists($font)) { imagettfbbox(12, 0, $font, 'test'); }
    // Works

putenv('GDFONTPATH=');
$font = './arial.ttf'; // Note the dot
if (file_exists($font)) { imagettfbbox(12, 0, $font, 'test'); }
    // Works
```

There are a few ways to fix this. As a user, you can pass an absolute or relative path, or you can set `GDFONTPATH` to a fitting value. As a developer, framing the `$font` parameter with `realpath`—either globally or when calling `imagettfbbox`—might be a solution.

I consider this to be an issue with this package (and not just a configuration issue with GD) because I think that you are explicitly trying to avoid calling `imagettfbbox` with a “non-existing” font parameter. The current code can’t guarantee this.

Best

PS: Please also note the (probably incomplete) [documentation](http://php.net/manual/en/function.imagettfbbox.php) for `imagettfbbox`:

> Depending on which version of the GD library that PHP is using, it may attempt to search for files that do not begin with a leading '/' by appending '.ttf' to the filename and searching along a library-defined font path.

**Comment by olivervogel** [comment]
Thanks for figuring this out. I will look into this.

**Comment by olivervogel** [comment]
> As of PHP 8.0.0, [imagettfbbox()](https://www.php.net/manual/en/function.imagettfbbox.php) is an alias of imageftbbox().

Intervention Image Version 3 uses `imageftbbox()` only and this function does not seem to care about `GDFONTPATH`.
