### ISSUE TITLE
Gd enabled and "GD Library extension not available with this PHP installation"

### ISSUE THREAD

**Issue by chiquitto** [Intervention/image#508]
Hello, i trying use the lib, but i get the message:

Intervention\Image\Exception\NotSupportedException
GD Library extension not available with this PHP installation.

I checked the installation of GD library, and it looks like it's all right.

```
$ php -i | grep gd
/etc/php5/cli/conf.d/20-gd.ini,
gd
GD Support => enabled
GD Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0
```

Can you help me find a solution?
Thanks

**Comment by chiquitto** [comment]
Resolved.
I use vagrant, and re-create the development environment.
I believe it was some problem in the PHP installation.

**Comment by Puzbie** [comment]
For anybody else getting this error, I found this worked:

sudo apt-get install php7.0-mysql php7.0-curl php7.0-gd

You can delete extensions you don't need.

**Comment by timothyallan** [comment]
I just started getting this after the 7.0.3 update on my live site. GD say's it's installed and working. I've tried the apt-get re-install, same thing.
