### ISSUE TITLE
Combine Image Into Tiles

### ISSUE THREAD

**Issue by ghprod** [Intervention/image#509]
Hi, 

First, this is not issue, just need some guide :)

Second, any idea how to insert/combine image and make into image below ?

![image](https://cloud.githubusercontent.com/assets/1922652/12712602/0ef5893e-c8fc-11e5-8f16-b234217a5aae.png)

Any idea would be appreciated ..

Thanks

**Comment by olivervogel** [comment]
There is no ready out the box solution. Create empty [canvas](http://image.intervention.io/api/canvas), calculate coordinates, combine images with [insert()](http://image.intervention.io/api/insert). You can put together everything in a [filter class](http://image.intervention.io/use/filters), when ready.

**Comment by ghprod** [comment]
Thanks for reply :)
