### ISSUE TITLE
Canvas background transparent?

### ISSUE THREAD

**Issue by closca** [Intervention/image#51]
Hello.
I'm using the resize canvas to obtain exact sizes witch i want.
$imgs->resizeCanvas(160,122, 'center',false,'ffffff');
I want to know if is possible instead of white background to have transparent?
image is png.

**Comment by d4rkd0s** [comment]
For furture reference and to help others,

This does NOT work:
`$img->resizeCanvas(160, 160, 'center', false, array(0, 0, 0, 0));`

Nor does this:
`$img->resizeCanvas(160, 160, 'center', false, 'rgba(0, 0, 0, 0)');`

The resulting images are ALL black backgrounds not transparent. I also noticed the Intervention image Docs mention just CSS HEX colors working, I think its purely RGB not RGBA... can someone help?

I have attached 2 originals and 2 images after intervention image.

![file00053809264](https://cloud.githubusercontent.com/assets/2348814/18917464/9a7bad44-855d-11e6-9831-f676ad30f4c7.jpg)

![file00053809264_intervention](https://cloud.githubusercontent.com/assets/2348814/18917513/a2c7474c-855d-11e6-9ee2-6dc75960291b.jpg)

![file000132701536](https://cloud.githubusercontent.com/assets/2348814/18917515/a69b3400-855d-11e6-9783-dde7e4a37c65.jpg)

![file000132701536_intervention](https://cloud.githubusercontent.com/assets/2348814/18917521/abbf3a26-855d-11e6-9bee-f1fe929b14c1.jpg)

My exact code is as follows:
```
// Request $request - Laravel request object
$file = $request->file('photo');
$image = Image::make($file);
$image->resize(1000, 1000, function ($constraint) {
    $constraint->aspectRatio();
});
$image->resizeCanvas(1000, 1000, 'center', false, 'rgba(0, 0, 0, 0)');
$imageStream = $image->stream();
Storage::disk('s3')->put($storage_path, $imageStream->__toString());
```

and I have also tried:
```
// Request $request - Laravel request object
$file = $request->file('photo');
$image = Image::make($file);
$image->resize(1000, 1000, function ($constraint) {
    $constraint->aspectRatio();
});
$image->resizeCanvas(1000, 1000, 'center', false, array(0, 0, 0, 0));
$imageStream = $image->stream();
Storage::disk('s3')->put($storage_path, $imageStream->__toString());
```

If someone could shed some light that would be great.

@closca did you ever end up having a solution or luck fixing this issue?

(Using intervention image 2.3.x on Laravel 5.2.x)

**Comment by 1988gadocansey** [comment]
How do I check if an image background is pure white or red

**Comment by d4rkd0s** [comment]
@1988gadocansey you should post a new issue, or skim through 
http://image.intervention.io/api/fill
and
#36

There isn't much support for editing photos, as intervention image is more of a Image manipulation library not a photo editing library.

You may want to checkout: http://phpimageworkshop.com/

**Comment by dhensby** [comment]
@d4rkd0s did you manage to get around your issue?

**Comment by dhensby** [comment]
bah - this will only work with PNGs, I was testing on JPGs...

**Comment by d4rkd0s** [comment]
@dhensby wasn't able to resolve it, just used functions to fit and crop, as well as frontend libraries to allow users to crop before uploading.

**Comment by dhensby** [comment]
It looks like you were testing on JPGs too. If you want transparency you need to save as PNG
