### ISSUE TITLE
Class not found with autoload

### ISSUE THREAD

**Issue by NecroBorg** [Intervention/image#511]
Fatal error: Class 'Intervention\Image\ImageManager' not found in C:\xampp\htdocs\project\test.php on line

require 'vendor/autoload.php';
use Intervention\Image\ImageManager;
$manager = new ImageManager(array('driver' => 'gd'));
$image = $manager->make('test.jpg')->resize(256,256);

0777 write permissions

No idea what's up

**Comment by olivervogel** [comment]
I can't remote debug your code but you might try: 

```php
use \Intervention\Image\ImageManager;
```

**Comment by NecroBorg** [comment]
Ah thanks. It worked.
