### ISSUE TITLE
Text is too small 

### ISSUE THREAD

**Issue by areyi** [Intervention/image#512]
Hello! When I try to put a text on the image using text() method, I can't get the text to be big enough to be read. The text stay small even I pass the size with the value of 75

This is my code:
```
$res = $product_image->image;
$image = Image::make($res)
      ->insert('watermarks/official.png', 'right');
				
			
$image->text('HELLO THERE! 1000000000000000', 300, 300, function($font) {
        $font->size(75);
        $font->align('center');
        $font->valign('center');
});
			
$image->contrast(8)
	->encode('jpg', 100);
			
$image->save($uri, 50); 

```

The text will not be big no matter what I do. I'm using version 2.3 for laravel. Any help will be appreciated, thanks

**Comment by olivervogel** [comment]
You need to pass a path to a font file (TTF for example), in order to set the font size.

**Comment by ericcumbee** [comment]
Having a similar issue. When you say pass a font file does that mean doing 

`$font->file(1); 
$font->size(75);`

won't get the job done? because that seems to be what I am running up against.
