### ISSUE TITLE
Image::make("my/dir/image") return null in images png|gif

### ISSUE THREAD

**Issue by kron-z** [Intervention/image#513]
For example:

use Intervention\Image\ImageManagerStatic as Img;

// format png
$img = "img/example.png";
// Or format gif
$img = "img/example.gif";

$exImg = Img::make($img);
var_dump($exImg->exif());           // this return null

Why is this happening?

Thanks in advance for the help

**Comment by olivervogel** [comment]
Maybe there is no exif data in the image?

**Comment by kron-z** [comment]
Oh, so it returns null.

Apparently this metadata are available in JPEG and TIFF.

Thanks for answering!
