### ISSUE TITLE
(Laravel) Gifs are not being encoded properly?

### ISSUE THREAD

**Issue by jaesung2061** [Intervention/image#515]
When the gif is temporarily stored on local server, the gif acts as intended. However once, I upload it to the remote server, it does not animate.

Upload code:

```
Storage::put($uri, $img->encode('gif'));
```

The gifs appear as static images.

**Comment by olivervogel** [comment]
Unfortunately animated GIFs are currently not supported by Intervention Image.

**Comment by jaesung2061** [comment]
Will they be supported some time in the future? If not, is there another package I can use to handle gifs?
