### ISSUE TITLE
Can't install without Composer

### ISSUE THREAD

**Issue by SatanicGeek** [Intervention/image#522]
Hello.

I'm trying to install Intervention without Composer but it doesn't work.
I don't use Laravel and Composer.

Can anyone help me to install this ?

**Comment by penafo** [comment]
You could take this golden chance to start using Composer on your projects! I'm just saying cause I'm only using composer for 1 month now and it really is simple even on Windows. 3 or 4 clicks every time you want to install some new plugin and that's it, no more unpacking zips, choose the files needed, drag here, include there.

I installed Intervention today by just editing one file with an extra line, 2 clicks of the mouse.

I can help you with the composer thing if you want
