### ISSUE TITLE
Can't install with Composer

### ISSUE THREAD

**Issue by ryanaddams** [Intervention/image#523]
Getting this when I run the installation as per the instructions:

$ composer require intervention/image
                                                                    
  [RuntimeException]                                                                                                                        
  Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.x.x:   
  Invalid version string "4.x.x"                                                                                                            
                                                                          [UnexpectedValueException]                                                
  Could not parse version constraint 4.x.x: Invalid version string "4.x.x"  
                                                                            
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [--] [<packages>]...

**Comment by olivervogel** [comment]
See: https://github.com/Intervention/image/issues/472
