### ISSUE TITLE
Set text positions after the callback

### ISSUE THREAD

**Issue by raheelkhan** [Intervention/image#527]
Hi,

Thanks for the nice library.

I am stuck in this code where i have to define `posx`and `posy` of `text()` function. But these positions i need to modify based on the `getBoxSize()` function.

```
    $canvas->text($text1, $logo->logo_specs['text1']['x'], $logo->logo_specs['text1']['y'], function($font) use ($destination, $logo, $selected_theme){
                $font->file($destination . "/assets/fonts/"  . $logo->logo_specs['text1']['font']);
                $font->size($logo->logo_specs['text1']['size']);
                $font->color($logo->logo_specs['text_color'][$selected_theme->title]['text1']);
                $box = $font->getBoxSize();
                dd($box);
            });
```

Inside the closure i get the $box array and i have to do some calculation and set the x and y of text. Is there any way i can achieve this by not doing any mess with the library ?

Thanks

**Comment by carkii** [comment]
I have same issue
