### ISSUE TITLE
Incorrect result when accessing getCore()

### ISSUE THREAD

**Issue by jamesdb** [Intervention/image#532]
Hi,

Having some unexpected behaviour when accessing the core.

```php
$imagick = new \Imagick('test.pdf');
var_dump($imagick->getNumberImages()); // returns correct result 2


$manager = new ImageManager(['driver' => 'imagick']);
$intervention = $manager->make($imagick);
$core = $intervention->getCore();
$pages = $core->getNumberImages();
var_dump($pages); // returns incorrect result 1
```

No matter how I load the file, whether it be a file path, stream or passed in Imagick instance, the result is always the same.

**Comment by olivervogel** [comment]
I think it's because of this [line](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Imagick/Decoder.php#L62). Intervention Image is not primary designed to deal with PDF. I suggest to just stick to pure Imagick.

**Comment by jamesdb** [comment]
Ok this makes sense thanks for clarifying that. ;)
