### ISSUE TITLE
Improvement: Offer image optimisation

### ISSUE THREAD

**Issue by andrefelipe** [Intervention/image#533]
I'd appreciate a lot if Intervention offered an easy-to-use image optimisation feature. Maybe even on a 'optimize()' method!

Meanwhile, if you could share how that could be done by myself, I'd appreciate. Here is a lot of details about image optimisation:
https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/

Thanks for your great library!

**Comment by olivervogel** [comment]
Would be nice to have. But I can't see this applied to both GD and Imagick in a similar way.

**Comment by andrefelipe** [comment]
Thanks @olivervogel for considering. 

That's definitely understandable to have the image optimisation only via Imagick. Just like exif() only works when the exif library is compiled in php. 

If you have the time, I'd strongly support the optimisation feature! It's just too important to ignore nowadays. 

Even Wordpress 4.5 has added image optimisation to the core.
