### ISSUE TITLE
Modify text line-height

### ISSUE THREAD

**Issue by thomas-dm** [Intervention/image#534]
Hello,

My question is pretty straightforward: is there any way to change the default line-height of a font when inserting text? If not, any tip on how I could circumvent that?

**Comment by olivervogel** [comment]
This is currently not possible.

**Comment by bizsimon** [comment]
> Hello,
> 
> My question is pretty straightforward: is there any way to change the default line-height of a font when inserting text? If not, any tip on how I could circumvent that?

Break the text into multiple lines, then loop and insert them with the desired line height. Not ideal, but somewhat a workaround. PHP has `wordwrap()`
