### ISSUE TITLE
NotReadableException thrown when URL begins with //

### ISSUE THREAD

**Issue by abejfehr** [Intervention/image#535]
We have a function that returns a CDN URL of an image, but it returns the URLs so as to begin with a double slash, which don't work in this library. Is this done on purpose? I realize there's no base URL to infer the scheme from, but maybe falling back to http would be nice.

**Comment by olivervogel** [comment]
I think it's better to modify the url before passing it to Intervention Image. Manipulating URLs is not the job of this library.
