### ISSUE TITLE
change background from black when using crop

### ISSUE THREAD

**Issue by TanjaEl** [Intervention/image#536]
Hi,

If I crop the image to smaller than the new image width the crop function gives it a black outline. How do I change this color? 

Help. Please

**Comment by emergingdzns** [comment]
@TanjaEl did you ever solve this? I'm having the same issue. I'd rather have it white background with no border.

**Comment by michaeljcoyne** [comment]
Bump?

**Comment by michaeljcoyne** [comment]
I had to do it like this

  $background = Image::canvas($data['height'], $data['width']);
  $background->fill('#fff');
  $image = Image::make($file);
  $background->insert($image, 'top-right', -intval($data['x']), -intval($data['y']));
  $background->resize(300, 300)->save($path);

**Comment by andrew-za** [comment]
@michaeljcoyne Image::canvas( WIDTH, HEIGHT); your code had it swapped around.

**Comment by michaeljcoyne** [comment]
Ok thanks I think I didn't notice as I am doing square images.

**Comment by sunand** [comment]
I had to modify a little bit to make it work for me.

$left = intval($data['left']);
$top = intval($data['top']);
$height = intval($data['height']);
$width =  intval($data['width']);

$background = Image::canvas($width*3, $height*3);
$background->fill('#fff');
$image = Image::make($file);
$background->insert($image, 'top-left',$width,$height);
$background->crop($width, $height,$width+$left,$height+$top)->save($path);

Idea is to create a larger image canvas with #FFF background and crop from that.

**Comment by osuagwu** [comment]
The above solutions do not seem general. 
Here is a more general solution that works for any image size:
https://github.com/osuagwu/crop-intervention-image/blob/master/cropImage.php
