### ISSUE TITLE
Orientate image

### ISSUE THREAD

**Issue by kamov** [Intervention/image#538]
Hi,
I would like to know about orientate() method.
I am using Flysystem (http://flysystem.thephpleague.com/) library to store images.

After calling orientate as below:

```php
$img = Image::make($filePath)->orientate();
```

I need to store the image using flysystem, but not sure how to do this.

Plus I would like to know, if I can first of all orientate image from temp_name before move image, or I need to orientate after uploading. Since I am creating also different sizes, I guess if I can just original image orientate, and then resize, does in this case the resized images are correct orientated?

```php
$img = Image::make($fileTempName)->orientate();
$result = $flysystem->writeStream($img->getPath() , $destination); // not sure if exist a getPath() ?
// OR

$path = $flysystem->writeStream($fileTempName , $destination); 
$img = Image::make($path)->orientate();
// save again ...
$path = $flysystem->writeStream($img->getPath() , $destination);  // not sure if exist a getPath() ?
```

Thanks!

**Comment by kamov** [comment]
Maybe I solved this, seem work...

```php
Image::make($fileTempName)->orientate()->save($fileTempName);
// save with flysystem
```

**Comment by kamov** [comment]
However, the question is now about resizing..

```php
            $img->resize($maxlimit, null, function ($c) {
                $c->aspectRatio();
            })->save();
```

how to save resized image with flystem?

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/228.

**Comment by kamov** [comment]
Awesome! Thank you!

**Comment by kamov** [comment]
Do you think that is better save directly with flysystem instaed of on tempfile ?
