### ISSUE TITLE
Remove EXIF

### ISSUE THREAD

**Issue by DrDeath72** [Intervention/image#542]
Add function to remove EXIF data like https://github.com/catch404/php-image-exif-strip/blob/master/strip.php for smaller thumbs size

**Comment by JHGitty** [comment]
Duplication of #363.

**Comment by DrDeath72** [comment]
just use for Imagick
```
$image->getCore()->stripImage();
```

**Comment by Vixed** [comment]
Ok, but any fn for GD driver?

**Comment by gtraxx** [comment]
Hi, it's possible with GD driver ?
