### ISSUE TITLE
ImageCache not accepting options array...or so it seems.

### ISSUE THREAD

**Issue by paxperscientiam** [Intervention/image#543]
Hi there!

Thanks for the awesome package; Image works very well for me.The problem I am having is with ImageCache. I don't use Laravel, though it seems that IC should work without it -- am I mistaken?

What I think should happen is that IC should check if the processed image is currently stored in cache and then process the input if not. Then, return a link to the cached item.

Am I mistaken? Any assistance would be greatly appreciated!

This is the code I am working with currently.

```php
  use Intervention\Image\ImageCache as IC;
  use Intervention\Image\ImageManager as IM;
  
  function wm($rel_path_to_image) {
      global $install_path;

      $imgPath = $install_path . $rel_path_to_image;
      $watermarkPath = $install_path . "assets/img/watermark.png";
      
      $manager = new IM(array('driver' => 'imagick'));
      //
      $cacher  = new IC();

      $img = $cacher->cache(function($manager) use ($imgPath,$watermarkPath) {
          $manager->make($imgPath)
                  ->insert($manager->make($watermarkPath)->rotate(45), 'center');
      },10, true);
      
  }
```

**Comment by olivervogel** [comment]
Yes, it works without Laravel. If you want customize your storage settings, you have to pass a `Illuminate\Cache\Repository` to the ImageCache instance. [See constructor](https://github.com/Intervention/imagecache/blob/master/src/Intervention/Image/ImageCache.php#L55).

The return value of the cache() method is either the raw image data or an Intervention Image object.

**Comment by paxperscientiam** [comment]
Thanks for the response @olivervogel . I'm gonna try that now and report back later.

**Comment by paxperscientiam** [comment]
Hey @olivervogel 

Sorry about all the postings.

I finally got Image and ImageCache creating cache files (got some help from some of your answers to older questions)! The problem though is that the cache folder is being populated by what seems to be corrupted image files. These files are created without extensions. I did try manually adding an extension, but that did not help (cache files are still corrupt).

Thoughts appreciated.


```PHP
use Intervention\Image\ImageManager as ImageManager;
use Illuminate\Filesystem\Filesystem as FileSystem;
use Illuminate\Cache\FileStore as FileStore;
use Illuminate\Cache\Repository as Repository;
use Intervention\Image\ImageCache as ImageCache;

function wm($rel_path_to_image) {
    global $install_path;

    //
    $imgPath = $install_path . $rel_path_to_image;
    $watermarkPath = $install_path . "assets/img/watermark.png";
    $cachePath = $install_path . "cache";

    //
    $manager = new ImageManager(array("driver" => "imagick"));
      
    $filestore = new FileStore(
        new Filesystem(),
        $install_path . "cache");

    $repository = new Repository($filestore);
    $cache = new ImageCache($manager,$repository);

    $cache->lifetime = 10;

    $watermarkedImage = $cache->make($imgPath)->get(0,true);

                      
}

```

**Comment by olivervogel** [comment]
No, the files in the cache folder are not corrupted images. The are just fine. The cache storage just works this way, storing every data (no matter what it is) in a file. I think you are misunderstanding the concept of the ImageCache. You don't have to pay attention to any filenames. The images in cache are stored by the manipulation actions you perform in the closure. If this actions has been executed already and the result is in cache, the image data comes directly from cache and any performance intensive GD or Imagick processing is skipped.

**Comment by jason-engage** [comment]
@paxperscientiam Thanks for the code!

what are those parameters for ->get()? 

    $watermarkedImage = $cache->make($imgPath)->get(0,true);
