### ISSUE TITLE
Image BG distortion (lines) on resize using GD

### ISSUE THREAD

**Issue by rmff** [Intervention/image#547]
Hi,

I tried to resize some large img 800x1067 to 200x300 and on image background appear some lines, as can see on Zoomed file. I'm using GD as driver, because my hosting don't have Imagick PHP extension.

I did the following:

```
        //If image wider than ratio, resize using widen
        //and resize canvas to fill height with white color

        if ($image->height() / $image->width() < 1.5) {

            $image->widen($this->width);
            $image->resizeCanvas($this->width, $this->height, 'center', false, '#ffffff');

        } else {

            $image->heighten($this->height);
        }
```

Anyone had faced this problem?

The only way that I found for fix it, was put come contrast (5) to background lines desapear.

Zoomed
![zoom](https://cloud.githubusercontent.com/assets/5833880/14968241/33adb368-1092-11e6-9fac-d38ed319fbca.png)
Size down
![18706-200x300_1460877101](https://cloud.githubusercontent.com/assets/5833880/14968109/90bcf27c-1091-11e6-99a0-b5a676605239.jpg)
Original
![18706_1460877101](https://cloud.githubusercontent.com/assets/5833880/14968111/92dad65a-1091-11e6-8532-ca9b04ef1e69.jpg)

**Comment by olivervogel** [comment]
Not reproducible.
