### ISSUE TITLE
all day  not  solve

### ISSUE THREAD

**Issue by lt123456** [Intervention/image#548]
# NotReadableException in /vagrant/www/p2.com/p2web-In-House/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php line 68:

Unable to init from given url (```http://img.baidu.com/img-original/2016/5/3/3/31/40/zslk3na_p0.jpg```).

# I think  ```Image::make($file)``` have a problem

 You can help me to 1416040754@qq.com , thankyou!

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/494
