### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Su9Tail** [Intervention/image#550]
When I use `composer require intervention/image`, it can not worked. And the Error Message is like below:

> Using version ^2.3 for intervention/image
> ./composer.json has been updated

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove laravel/framework v5.2.24
>     - Conclusion: don't install laravel/framework v5.2.24
>     - Can only install one of: laravel/framework[v5.2.21, v5.2.24].
>     - don't install laravel/framework v5.2.24|remove illuminate/config v5.2.21
>     - don't install illuminate/config v5.2.21|don't install laravel/framework v5.2.24
>     - don't install illuminate/config v5.2.21|don't install laravel/framework v5.2.24
>     - Installation request for laravel/framework == 5.2.24.0 -> satisfiable by laravel/framework[v5.2.24].
>     - Installation request for illuminate/config == 5.2.21.0 -> satisfiable by illuminate/config[v5.2.21], laravel/framework[v5.2.21].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by wilsmex** [comment]
Same here.
"Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.x.x: Invalid version string "4.x.x""

**Comment by wilsmex** [comment]
`composer self-update` fixed this issue for me.

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/464
