### ISSUE TITLE
Transparency on PNG

### ISSUE THREAD

**Issue by txusramone** [Intervention/image#551]
Hi

I save from original png with transparency and when i save loose the transparency and put a black background.

$imageObj = Image::make($request->file('activityUploadPhoto'))->orientate();
$imageName = substr(md5(Auth::user()->id), -10) . '_' . md5(microtime()) . '.' . $request->file('activityUploadPhoto')->getClientOriginalExtension();
$imageObj->save(config('paths.storage_tmp_imgs') . $imageName)

I have this version             "version": "2.3.7",

Is a bug?

Thanks

**Comment by WebNinjrDesign** [comment]
I'm having a similar issue, where the PNG's shadow that is semi transparent is converted to flat black.

If you upload this....

![screen shot 2016-05-25 at 7 19 10 pm](https://cloud.githubusercontent.com/assets/11359834/15535093/321219f2-22af-11e6-9a12-e456377bb1b0.png)

to this...
https://www.apps.regenr8web.com.au/image-preparation/

you get this...
![prepared-image-5745700c12bbe](https://cloud.githubusercontent.com/assets/11359834/15535120/4c291b24-22af-11e6-9fe0-02da9355ea88.jpeg)

The controller simply resizes to max size and saves as JPEG with quality of 85.

Thoughts or ideas? Most recent version of the plugin (as of right now).

**Comment by olivervogel** [comment]
JPEG does not support alpha channel / transparency. If you want the background in another color than black, I would suggest you create an empty image with `canvas()` with the desired background color and `insert()` your semi-transparent image into this container.

**Comment by olivervogel** [comment]
Like this:
```php
$png = Image::make('transparent.png');
$jpg = Image::canvas($png->width(), $png->height(), '#ff0000');
$jpg->insert($png);
$jpg->save('foo.jpg');
```

**Comment by txusramone** [comment]
with imagick run correctly the plugin, with gd no

**Comment by WebNinjrDesign** [comment]
that did the trick with both GD and imagick drivers.

@olivervogel I wonder if this is a sensible default that should be apart of the framework. Is this a pull request you would consider if I put it together (or someone else)?

I figure if the image is being converted to a jpg, by default it should have a white background and keep the original images transparency (with the white behind it of course).

**Comment by olivervogel** [comment]
I think total transparency is converted to white and everything in between becomes black. That's just the way GD works.
