### ISSUE TITLE
Command (grayscale) is not available for driver

### ISSUE THREAD

**Issue by micfai** [Intervention/image#554]
I have tried using both GD and Imagick and both return the same error.

I have tested using PHP 5.5, 5.6 and 7 to see if that could have been the issue however it didn't change anything.

Here is the code I am using. I can use all the other api methods except this one, which is the one I need.
`$img   = Image::make($image)->grayscale()->save($savePath,100);`

**Comment by olivervogel** [comment]
It's greyscale()

http://image.intervention.io/api/greyscale

**Comment by micfai** [comment]
Thanks! I could have sworn I had copy/pasted from the docs. Simple mistake. Thanks!
