### ISSUE TITLE
 Fatal error: Call to undefined method Intervention\Image\Image

### ISSUE THREAD

**Issue by premier213** [Intervention/image#556]
how to solve this problem?

![2016-05-20_10-25-18](https://cloud.githubusercontent.com/assets/4321174/15418543/4fd3ae94-1e75-11e6-89ba-ad3fcf8df85a.jpg)

my code :
`require '../../vendor/autoload.php';
require('Uploader.php');
use Intervention\Image\Image;
$img= Image::make($newName);`

**Comment by wernight** [comment]
It looks like almost all basic examples are missing a few important lines. That method should be under `\Intervention\Image\ImageManager make` see http://image.intervention.io/api/make

See PR #557

**Comment by premier213** [comment]
i get this error :(
![2016-06-21_19-18-57](https://cloud.githubusercontent.com/assets/4321174/16233900/1fcde1cc-37e5-11e6-8b14-c5b05723c0b4.jpg)

**Comment by wernight** [comment]
Yes it does need ImageMagick.

**Comment by olivervogel** [comment]
Please follow the [example](http://image.intervention.io/use/basics) in the documentation.
