### ISSUE TITLE
Max CPU usage when resizing lots of images

### ISSUE THREAD

**Issue by timo002** [Intervention/image#561]
Hello,

I need to resize approximately 100.000 images and I'm using image intervention. When performing the modifications on one image, it's blazing fast. When running in a loop, it get's slower and slower and slower. Killing the script, restarting it again and it runs fast from the start, but again, it will get slower and slower and slower.

Memory is no issue, it uses around 7MB. CPU however is full in stress, 100% as long as the script is running.

I'm running it now in badges of 1000 images, but that means I need to run the script 1000 times manually to get all images converted.

Below the script that runs in a loop.

```
$size = getimagesize($source . $file);
if (($size[1] / $size[0]) == 1.2) {
  // For the current list of images, this is always true.
   $original5bij6 = true;
}

$img = Image::make($source . $file);
if (!$original5bij6) {
  $img->trim('top-left', null, 10, 5);
}
$img->resize($width, $height, function ($constraint) {
  $constraint->aspectRatio();
  $constraint->upsize();
});
if (!$original5bij6) {
  $img->resizeCanvas($width, $height);
}
$img->encode('jpg')
  ->save($destination . $file, $quality);
$img->destroy();

```

**Comment by TechKat** [comment]
Are you attempting to run this script via the browser, or CLI?

**Comment by timo002** [comment]
CLI. I wrote a console command with Symfony.

**Comment by michael-001** [comment]
this might be the problem.
`$img->trim('top-left', null, 10, 5);`
Trim() function in Intervention uses high resources with GD driver.
http://image.intervention.io/api/trim

A suggestion from https://github.com/Intervention/image/issues/98 is to use intervention 2.x and use the Imagick driver
