### ISSUE TITLE
"GD Library extension not available" with working GD installation

### ISSUE THREAD

**Issue by Roemerb** [Intervention/image#562]
Hi, I'm having trouble using the library. When I try to init an image, I get a `NotSupportedException` with the message `GD Library extension not available with this PHP installation.` even though GD is definitely installed.

```
$ php -i | grep gd
/etc/php/7.0/cli/conf.d/20-gd.ini,
gd
gd.jpeg_ignore_warning => 0 => 0

$ php -i | grep GD
GD Support => enabled
GD headers Version => 2.1.1
GD library Version => 2.1.1
```

I tried `apt-get install --reinstall php7.0-gd && service apache2 restart` but no success. The exception gets thrown on line 16 of `src/Intervention/Image/Gd/Driver.php` because the statement in `coreAvailable()` returns false. When I run the same statement in `artisan tinker` (I use Laravel) it returns true.

Any ideas?

Thanks in advance!

**Comment by olivervogel** [comment]
Maybe GD is only available on command line PHP.

**Comment by Hobstweedl** [comment]
I'm running into the same issue with GD and php7-fpm. I have other projects that seem to use the gd library fine. Maybe this is something to do with an incompatibility with the exception handler?

**Comment by geidelguerra** [comment]
I ran into the same issue. if you are using Apache, check if the php7 mod is enabled. Maybe Apache is loading the mod of a previous version of PHP

**Comment by Roemerb** [comment]
@olivervogel @Hobstweedl @geidelguerra I eventually solved the problem by literally reinstalling everything. Apache, PHP etc. Not sure what the problem was but it did work 😐

**Comment by Hobstweedl** [comment]
I'm running NGINX with this error. Never solved it, but it's possible there have been some patches to php7 since May that have addressed this. Still not sure what the issue was.

**Comment by cuonghuynh** [comment]
after installing GD plugin, run `service apache2 reload`
