### ISSUE TITLE
Unable to set the image format 

### ISSUE THREAD

**Issue by ctf0** [Intervention/image#565]
>ErrorException in Driver.php line 39
Unable to set the image format

when using imagick the error pop up, but with gd its working fine.
what is driving me crazy is i didnt even touch the library, am simply viewing a page that have an image made by https://github.com/laravolt/avatar

using `homebrew/php/php70-imagick: stable 3.4.2`

**Comment by DracotMolver** [comment]
It's not clearly the problem. Can you provide more info? Errors and code?
