### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by ctf0** [Intervention/image#567]
>FatalErrorException in Decoder.php line 28:
Allowed memory size of 134217728 bytes exhausted (tried to allocate 29708800 bytes)

its related to the encode especially from png to jpg, using `destroy()` makes no difference.

code
```php
foreach ($photos as $one) {
            $newName = $i++ . '.jpg';

            $image = Image::make($one)
                ->resize(800, null, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                })
                ->encode('jpg', 100)
                ->save("sopath/$newName"))
                ->destroy();
        }
```

**Comment by ctf0** [comment]
i found the issue, apparently the package doesn't work under some memory limit cuz currently i have it set to 128M , 
so i thought maybe we need to pump it up to 134M but that also doesn't solve the issue, 
so i changed it again to 256M and now all is good, 

so is there anyway we can debug this or get the exact amount of memory it needs to process a one 3mb image ?

**Comment by olivervogel** [comment]
Resizing images is a very memory consuming task. You can't assume that a 1MB image takes 1MB of memory. Resizing a 3000 x 2000 pixel image to 300 x 200 may take up to 32MB memory for example. Even if the image is under 1MB.

**Comment by fahmilatib** [comment]
Switch the driver to Imagick. It uses less memory.

**Comment by rytisder** [comment]
@fahmilatib Is right, use Imagick driver. I faced the same issue on my side project (https://wizlogo.com) Intervention is using GD by default. If you need any help, feel free to contact me. 

Basically you can add this to your constructor and it will do - `Image::configure(array('driver' => 'imagick'));`, of course you need to enable imagick extension before using it - ` "require": {
        "ext-imagick": "*",
        "php": "^7.1.3",
        "ext-gd": " *",`
