### ISSUE TITLE
insert is not available for GD

### ISSUE THREAD

**Issue by okansahin** [Intervention/image#570]
Hello,

NotSupportedException in AbstractDriver.php line 115: Command (insert) is not available for driver (Gd).

when I am try to this code,

`
$image_path = public_path() . '/images/brand_logo/' . $file_name;

                $image = Image::make($request->img_src)->resize(500, 500, function ($c) {
                    $c->aspectRatio();
                });
                
                
                Image::canvas(500, 500)->insert($image, 'center')->save($image_path);`

**Comment by okansahin** [comment]
I found the problem. My locale is Turkish. And it converts 'insert' => 'İnsert' and it doesnt find the class. 
I added small fix for me.

**Comment by enverarslan** [comment]
[#L106-L107](https://github.com/Intervention/image/blob/master/src/Intervention/Image/AbstractDriver.php#L106-L107)

"ucfirst()" not compatible for Turkish.
