### ISSUE TITLE
in shared-hosting, cpanel 56.0.24

### ISSUE THREAD

**Issue by FreelanceMM** [Intervention/image#571]
MissingDependencyException in ImageManager.php line 123:

PHP Fileinfo extension must be installed/enabled to use Intervention Image.

**Comment by joelezeu** [comment]
I am facing this issue too, please reopen this issue.

**Comment by josoye24** [comment]
I have same issue using NameCheap, I cant upload image i got error "Intervention \ Image \ Exception \ NotReadableException Image source not readable"
 
Please Anyone with working solution?

**Comment by joelezeu** [comment]
This exception is a false positive. I was able to fix this issue by just fixing a typographical errors on the code base. I lost the project, I would have shared how I fixed it

**Comment by abduk65** [comment]
on which code base are we talking? is it the original fileinfo extension codebase or the line of code which seems to be throwing this exception 
if ( ! function_exists('finfo_buffer')) {
            throw new MissingDependencyException(
                "PHP Fileinfo extension must be installed/enabled to use Intervention Image."
            );
}
