### ISSUE TITLE
Provides.json invalid json

### ISSUE THREAD

**Issue by alokrajiv** [Intervention/image#573]
Backslash used inside the json string type, is invalid.

therefore
line 3 and 8 are invalid and the error is thrown in multiple IDEs and JSLinters.

Consider changing
 `"providers": [
    "Intervention\Image\ImageServiceProvider"
  ]`
to
`"providers": [
    "Intervention\\Image\\ImageServiceProvider"
  ]`

As well as
`"facade": "Intervention\Image\Facades\Image"`
to
`"facade": "Intervention\\Image\\Facades\\Image"`

**Comment by alokrajiv** [comment]
I have attempted to correct it and made pull request [#574](https://github.com/Intervention/image/pull/574).

**Comment by olivervogel** [comment]
Merged, thank you.
