### ISSUE TITLE
NotReadableException

### ISSUE THREAD

**Issue by jamiehd** [Intervention/image#575]
Hi,

I appear to be getting this exception on a few different files. Here are the urls of a a few files that are causing this - I'm not sure if the issue is with Intervention or the library I am using that implements it, but given that other images work fine I think it would make sense for it to be Intervention.

http://www.affiliatewindow.com/logos/5771/logo.gif
http://www.affiliatewindow.com/logos/2749/logo.gif

**Comment by olivervogel** [comment]
I don't know why, but it seems GD is unable to read these files. Try Intervention Image with Imagick. This works fine.

**Comment by jamiehd** [comment]
Ok I'll give Imagick a go. Thanks.

**Comment by Luddinus** [comment]
Same issue, not working with Imagick
