### ISSUE TITLE
vendor:publish failed with Nothing to publish for tag []. and more problems with Intervention

### ISSUE THREAD

**Issue by pixelfriese** [Intervention/image#576]
Hi,

i have installed the newest version of intervention for Laravel 5.2. After I have inserted the necessary lines in config/app.php and started the command `php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"` the console shows me `Nothing to publish for tag [].` Whats wrong with that?

Then I have copied manually the file image.php in the config folder. Is that ok or is it important to register the script with the publish command?

It is not possible to configure the driver in this file. Intervention uses permanently the gd driver. But I have changed the line to `'driver' => 'imagick'`. How can I use imagick without inserting `Image::configure(array('driver' => 'imagick'));` in my controllers?

Why I cant use the image object of Intervention in my controllers? I have set `Illuminate\View\ViewServiceProvider::class,` under providers and `'Image'      => Intervention\Image\Facades\Image::class,` under aliases and refreshed the Laravel autoloader. But the only way to use Image is to define it by `use Intervention\Image\ImageManagerStatic as Image;`

I don´t see anything of this under the installation instructions: http://image.intervention.io/getting_started/installation

**Comment by krychu90** [comment]
I had the same problem. Try to run:
```bat
php artisan config:clear
```
after that:
```bat
php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"
```
