### ISSUE TITLE
limitColors(1) never returns white or black

### ISSUE THREAD

**Issue by petrhanak** [Intervention/image#577]
```
$img = Image::make($file);
$img->limitColors(1);
$color = $img->pickColor(0,0);
```

given black image it returns rgb(4,2,4)
for white image, the result is rgb(252, 254, 252)

**Comment by olivervogel** [comment]
The color quantization process is under the control of the respective driver methods. For GD this is `imagetruecolortopalette ` and for Imagick `Imagick::quantizeImage`. Unfortunately, I can't say what's going on under the hood.
