### ISSUE TITLE
Animated Gif loses animation after going through intervention

### ISSUE THREAD

**Issue by padjodev** [Intervention/image#578]
Im trying to upload an animated gif and it loses its animation once it gets uploaded.. heres the code I am using:

        $file         = Request::file('file');
        
        $extension    = $file->getClientOriginalExtension();
        
        $image_normal = Image::make( File::get($file) );
        
        $image_normal = $image_normal->stream();
        
        $newImageName = strtolower( str_random(40) );

        Storage::disk('local')->put('full/'  . date('Y-m') . "/".  $newImageName  . "." .  $extension, $image_normal->__toString() );

The file stores etc but it doesnt animate when loaded in the browse afterwards. At the moment it just stored it locally but I hope to modify the code to allow it to store in aws s3 once its tested and working

**Comment by olivervogel** [comment]
Animations are currently not supported by Intervention Image.
