### ISSUE TITLE
how to change the color of non-transparent part with a png file?

### ISSUE THREAD

**Issue by Jaggle** [Intervention/image#579]
I know there is fill() method to fill color, but my image is irregular,so I can't do that with fill() method ,what else can I do to resolve my problem ?

**Comment by TechKat** [comment]
The `colorize()` method seems to be what you're looking for?

**Comment by Jaggle** [comment]
@TechKat thanks,although  I gave up using this package and at last, I have tried this method `colorize()` , but this method just takes or takes out colour from the origin image  , my goal is filling the image where there is untransparent  with exactly color varible , but I can't find a method like this,finally I used the original ImageMagic and solved this problem , thank you again !
