### ISSUE TITLE
ImageCache paths configuration

### ISSUE THREAD

**Issue by sunnyjayjay** [Intervention/image#582]
Sorry but I am having to reopen this issue as the answer was unclear last time. I repeat my question:

In the imagecache.php config file in Laravel 5 you need to put the paths to images. Is there a wildcard option here? I have the images in many (user-generated) subfolders of an images folder. Can I just add the path images/*?

Your answer was I can add paths to the subfolders. But I ask you how? With a wildcard or do I have to add each one individually?

**Comment by olivervogel** [comment]
You just have to define the root folder in `imagecache.php`.

```php
'paths' => [
    'app/public/images'
],
```

Now you have access to all the files and folders in this directory, just add them in the URL.

For example

`app/public/images/test1.png` is accessible with `/imagecache/small/test1.png`:
`app/public/images/foo/test2.png` is accessible with `/imagecache/small/foo/test2.png`:
`app/public/images/foo/bar/test3.png` is accessible with `/imagecache/small/foo/bar/test2.png`:
