### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by zak-123** [Intervention/image#584]
while using 

$img->text('The quick brown fox jumps over the lazy dog.');

on php PHP Version 7.0.8

cent os 

Linux  3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ErrorException
A non well formed numeric value encountered

intervention/image/src/Intervention/Image/Image.php line 1613

`return imagecolorallocatealpha($this->resource, $r, $g, $b, $a);
`

thanks

**Comment by cocciagialla** [comment]
@olivervogel maybe this issue could be closed by the #687
