### ISSUE TITLE
Can't recognize images from DropBox directory

### ISSUE THREAD

**Issue by MarwenSami** [Intervention/image#585]
I've been running Intervention Image on Laravel Framework and I noticed that it can't read valide images if they are uploaded from dropbox directory.

**Comment by Xiphin** [comment]
get remote data by url as a temp variable

**Comment by MarwenSami** [comment]
I didn't get it, The issue occured with a client who tried to upload an image using an upload form from my website and choose an image located in his dropbox folder in his computer.

**Comment by Xiphin** [comment]
look up your error log, show it here.
