### ISSUE TITLE
How to draw a dotted line?

### ISSUE THREAD

**Issue by robschaefer** [Intervention/image#590]
I've looked through the docs, but I haven't been able to find how to draw a figure with a dotted or dashed line?  I know that php has IMAGEDASHEDLINE(), but not sure how I would mix that in the the intervention/image library.

Can someone please point me in the right direction?

Thanks.

R Schaefer

**Comment by olivervogel** [comment]
You can access the GD resource via [getCore()](http://image.intervention.io/api/getCore) to apply functions like `imageddashedline()`.
