### ISSUE TITLE
Undefined class constant 'IMGTYPE_TRUECOLORMATTE'

### ISSUE THREAD

**Issue by lokielse** [Intervention/image#591]
`/vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php`

magick module version	`3.4.2`

**Comment by lokielse** [comment]
ImageMagic version `7.0.1 Q16 HDRI`

**Comment by lokielse** [comment]
I downgrade ImageMagic and imagick works!

**Comment by OranTing** [comment]
一样的问题，你降级到哪个版本了？

**Comment by lokielse** [comment]
@OranTing 

    ImageMagick 6.7.8-9
    imagick 3.4.3RC1

**Comment by valentinxxx** [comment]
Fixed in #679, released in 2.3.11

**Comment by liliangali** [comment]
这个问题解决了吗

**Comment by liliangali** [comment]
Has the problem been solved?
