### ISSUE TITLE
must be an instance of Closure, string given, this because I have the path the image

### ISSUE THREAD

**Issue by Augustino7** [Intervention/image#593]
Hi I have the following error

Error Type:
Catchable Fatal Error (4096)
Error Message:
Argument 1 passed to Intervention\Image\ImageManagerStatic::cache() must be an instance of Closure, string given, called in F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\index.php on line 38 and defined
Location:
File: F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\ImageManagerStatic.php
Line: 83

Code:

		$img=Image::cache($ruta);
		$img = Image::make($ruta)->resize($medida['nuevo_ancho'], $medida['nuevo_alto']);

**Comment by Augustino7** [comment]
Also try with this

$img = Image::cache(function($ruta,$nuevo_ancho, $nuevo_alto) {
			Image::make($ruta)->resize($nuevo_ancho, $nuevo_alto);
		}, 10, true);

I have the following error

Fatal error: Uncaught exception 'Intervention\Image\Exception\NotReadableException' with message 'Image source not readable' in F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\AbstractDecoder.php:302 Stack trace: #0 F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init(Object(Intervention\Image\ImageCache)) #1 F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\ImageManager.php(50): Intervention\Image\AbstractDriver->init(Object(Intervention\Image\ImageCache)) #2 F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\ImageManagerStatic.php(57): Intervention\Image\ImageManager->make(Object(Intervention\Image\ImageCache)) #3 F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\index.php(42): Intervention\Image\ImageManagerStatic::make(Object(Intervention\Image\ImageCache)) #4 F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\ in F:\XAMPP\htdocs\WIO\SIPROCESA\IMA\vendor\intervention\image\src\Intervention\Image\AbstractDecoder.php on line 302

**Comment by olivervogel** [comment]
http://image.intervention.io/use/cache
http://image.intervention.io/api/cache
http://php.net/manual/de/functions.anonymous.php
