### ISSUE TITLE
Tag image

### ISSUE THREAD

**Issue by slow-loris** [Intervention/image#600]
Hi folks,

I got a problem and I'm not sure if I can solve this with this library.
My customer has a shop and wants to add watermarks to all pictures.
I could create a cron and crawl the the media folder to add the watermark image to every picture. But this  would include the already modified pictures.
Can I somehow tag a picture with this library to detect modified pictures?
I tried to set a single picture with an predefined color, but $image->pickColor() does not constantly return the same color value.

I would be very grateful for your help

**Comment by olivervogel** [comment]
No, "tagging" is not possible. I would save the already modified filenames somewhere (Redis) or maybe rename the image after modify.
