### ISSUE TITLE
Resize algorithms?

### ISSUE THREAD

**Issue by vicary** [Intervention/image#601]
Can I specify which pixel processing algorithms when resizing an image?

**Comment by olivervogel** [comment]
Out of the box, you can't. I wanted to keep things simple and for the most part I don't care which algorithm is used, as long as the result is great.

But you can access the Imagick object via [getCore()](http://image.intervention.io/api/getCore) and apply your own [custom resizing](http://php.net/manual/en/imagick.resizeimage.php) method.
