### ISSUE TITLE
Error "execute git status" when I launch composer update on Laravel 5

### ISSUE THREAD

**Issue by GiacomoK** [Intervention/image#603]
Hi,
I am trying to update laravel and when I do the "composer update" command I get this error on intervention/image package:

Update failed (Failed to execute gti status --porcelain --untracked-files=no
error: bad index file sha1 signature
fatal: index file corrupt
)

I tried to delete the git index file and reset it but I still get this error.

Someone knows why?

Thanks.

**Comment by olivervogel** [comment]
Sorry, I can't help you here.
