### ISSUE TITLE
Transparent PNG resize issue

### ISSUE THREAD

**Issue by gmagnai** [Intervention/image#604]
![15](https://cloud.githubusercontent.com/assets/18567291/18028151/d358058c-6cb1-11e6-843f-e487c02ef964.jpg)

Hello i am using this package. And i have a problem about resize for transparent png picture.
This is example resized picture.

Here is my code:

`$target_image->resize(null, $height, function($constraint){  $constraint->aspectRatio();  });`

And how to resize correctly?

**Comment by JeroenVanOort** [comment]
You've saved your image as JPG, which doesn't support transparency. Could you try to save it als png?

**Comment by olivervogel** [comment]
You have the original (unresized) image? Are you using GD or Imagick?

**Comment by jaimingohel** [comment]
use this it worked for me..

`$img->fit(100, 100)->encode('png', 100)->trim();`
