### ISSUE TITLE
Resize image based on portrait or landscape

### ISSUE THREAD

**Issue by mikemand** [Intervention/image#608]
I have been having trouble trying to figure out how to resize images based on if it is portrait or landscape. If it's a landscape _or square_, I want to limit the width; if it's a portrait, I want to limit the height.

Is there something I'm missing? I tried `fit()`, but that crops the image and I do not want that. I've also tried using `resize()` with the height and width both set to what I want, but this causes problems when it resizes a square image.

**Comment by DracotMolver** [comment]
Do you mean something like this?

```php
if ($width > $height) { //landscape
 $image->resize(300 /* limit to 300? */, null, function($constraint) {
   $constraint->aspectRatio();
 });
} else {
  // Do the inverse here
}
```

**Comment by mikemand** [comment]
Yes, something like that. How would I get the width and height of whatever image is currently being transformed?

**Comment by DracotMolver** [comment]
Intervention has `height()` and `width()` getter methods.
