### ISSUE TITLE
Drawing rectangle with a dashed border

### ISSUE THREAD

**Issue by julius-s** [Intervention/image#611]
This is more of a feature request/query than an issue- is there a method available through the component for specifying a border style to generate dashed borders? I suspect this is a limitation of Imagick itself.

Thanks

**Comment by olivervogel** [comment]
This feature is not part of Intervention Image but I guess you can try to use the [getCore()](http://image.intervention.io/api/getCore) method to access Imagick directly with the following method:

http://php.net/manual/en/imagickdraw.setstrokedasharray.php
