### ISSUE TITLE
Can't write data to path

### ISSUE THREAD

**Issue by beshambher** [Intervention/image#612]
I'm uploading an image in a new folder which does not exists i.e.' I want t create folders dynamically.
but when my Intervention/Image is trying to create a folder it is having permission problems however when I am uploading the same image file to same indented path by some other image uploader package, it is uploading and creating folder. Where do I'll give such permission to Intervention/Image class/package?

   Image->save($path . '/newfolder/' . $imageneme);

 I really like this package because it is simple and re-sizing any image is very easy. Help me asap.

**Comment by beshambher** [comment]
I have also tried it by using absolute path but still no effect.
 Image->save(public_path($path . '/newfolder/' . $imageneme));

All my uploading directories have full permissions of read, write, create, and delete files. I'm using Ubuntu 14.0 LTS

**Comment by olivervogel** [comment]
You have to create folders manually. Intervention Image does not deal with filesystem operations.

**Comment by beshambher** [comment]
ya unfortunately I had to use some other package :(

**Comment by Goldengide01** [comment]
Pls what other packages

**Comment by beshambher** [comment]
@Goldengide01 there is a package named Matriphe Laravel Imageupload.
