### ISSUE TITLE
make() changes colorspace of the image

### ISSUE THREAD

**Issue by jespejoh** [Intervention/image#616]
Hi there!

I update the issue as after doing some more tests I noticed the error is somewhere else. I'm pretty certain that the image I'm opening is CMYK, but it gets opened as SRGB, so whenever I try to resize it generates a new image but with a wrong color space, so the original and the thumbnail looks pretty different.

Cheers!
Jesús E.

**Comment by caoquan95** [comment]
I also got this problem. @jespejoh Have you found any solutions?

**Comment by AminEshtiaghi** [comment]
Wow, it's open from 2016! long time! I've faced same issue at 2020

**Comment by paullaffitte** [comment]
I still got this issue also. For those using GD I don't know if a solution exists, but with Imagick we could use [Imagick::transformImageColorspace](https://www.php.net/manual/fr/imagick.transformimagecolorspace.php).

**Comment by olivervogel** [comment]
This issue should no longer occur in [version 3](https://image.intervention.io/v3). However GD only supports RGB color space.
