### ISSUE TITLE
Resizing image fails

### ISSUE THREAD

**Issue by dhrubo001** [Intervention/image#617]
![resize](https://cloud.githubusercontent.com/assets/7116995/18751907/58624f34-80fe-11e6-8e21-f43b2eea3391.png)

I am trying to resize a image after it's uploaded to the destination folder

$image = Image::make(sprintf('/assets/img/projects_images/09e1ce51bedade9825cb4b70b633284c4989c07b-FkN9to9eYoLB.jpg'))->resize(900, 700)->save();

But when executing the resize function it's giving error, what i am doing wrong

**Comment by olivervogel** [comment]
You first have to install Intervention Image's requirements.

**Comment by dhrubo001** [comment]
What needs to be installed, plz suggest and how to
