### ISSUE TITLE
Letter-spacing, is it possible? 

### ISSUE THREAD

**Issue by diegoemerique** [Intervention/image#619]
I don't know if here is the right place to ask it, but I couldn't find a forum or something like that. Sorry about that :(

I need to do something like that:

**CSS:**
`.class {
   letter-spacing: -10px;
}`

Is it possible? Cause I found an trick that is render letter one by one, and shift the x position by the number you want. but it probably will bea a performance  problem.

Thx u guys and sorry for create an issue for asking it.

**Comment by olivervogel** [comment]
Letter spacing is currently not integrated into Intervention Image.

**Comment by lupka** [comment]
I need something like this too. Not that familiar with the Intervention source, but do you think it would be tough to do? I could give it a shot if someone could point me in the right direction. It seems like ImageMagick supports kerning: http://www.imagemagick.org/Usage/text/#kerning

**Comment by olivervogel** [comment]
I am closing this topic for version 2. There is a [follow-up](https://github.com/Intervention/image/issues/1246) for version 3 of Intervention Image.
