### ISSUE TITLE
Call to undefined method Intervention\Image\ImageServiceProviderLumen::boot()

### ISSUE THREAD

**Issue by chimit** [Intervention/image#621]
After upgrading Lumen from 5.2 to 5.3 I faced the error: `Call to undefined method Intervention\\Image\\ImageServiceProviderLumen::boot()`, which is caused by

```
$app->register(Intervention\Image\ImageServiceProvider::class);
```

in `bootstrap/app.php`.

composer.json:

```
"intervention/image": "^2.3",
```

Please, help me to fix it.

**Comment by pedrolopes10** [comment]
+1

**Comment by AnitaYip** [comment]
+1

**Comment by vikashkrkashyap** [comment]
In your bootstrap/app.php
Remove **$app->register(Intervention\Image\ImageServiceProvider::class);**
Add  **$app->register(Intervention\Image\ImageServiceProviderLumen::class);**

**Comment by yuesh** [comment]
good

**Comment by tremby** [comment]
I just hit this too. This is a workaround, not a fix. I've submitted a pull request: just don't call the boot method if there isn't one.
