### ISSUE TITLE
Fit() makes JPEG flips image backwards

### ISSUE THREAD

**Issue by HACKHERS** [Intervention/image#625]
Hey, I dont know every JPEG to this but you can try what i did, image is this http://i.imgur.com/nj235L8.jpg code I'm using is; 

```
 $manager = new ImageManager(array('driver' => 'GD'));
 $img = $manager->make('image.jpeg');
$img->fit(262, 392);
$img->save('main/test.png');
```

Result: http://i.imgur.com/B9bVIgo.png

**Comment by Lopez-i** [comment]
same problem with on upload on mobile picture

**Comment by Lopez-i** [comment]
please solve this :(

**Comment by Albofish** [comment]
You need to use the `orientate()` function. This reads the meta data of the image and rotates it to be upright.
`$img->orientate()->fit(262, 392);`
