### ISSUE TITLE
Low quality when save image as jpg

### ISSUE THREAD

**Issue by DracotMolver** [Intervention/image#628]
Hi there. I'm saving some images to JPG using the 100% of quality, but the image is still having a low quality. I'm using imagick. Is this an issues of imagick or a normal behavior?

This is my code
```php
Image::configure(['driver' => 'imagick']);
$image = Image::make($_FILES['images']['tmp_name'][0]);
$image->resize($sizes['home'][0], $sizes['home'][1])
            ->save($path.'home-'.$file_name, 100) // Home
            ->resize($sizes['busqueda'][0], $sizes['busqueda'][1])
            ->save($path.'busqueda-'.$file_name, 100) // Busqueda
            ->resize($sizes['normal'][0], $sizes['normal'][1])
            ->save($path.$file_name, 100) // Normal
            ->resize($sizes['thumb'][0], $sizes['thumb'][1])
            ->save($path.'thumb-'.$file_name, 100); // Thumb
$image->destroy();
```

**Comment by DracotMolver** [comment]
I realized that it was my mistake.

**Comment by lincyrey** [comment]
Could you let me know how you solved this issue. I am facing the same problem.

**Comment by DracotMolver** [comment]
Well, the code above it works. But!, My mistake was had forgotten how the JPG algorithm works.

> JPG algorithm is accumulative. This means, that if you compress an image and then you compress the already compressed image, the second one created it'll loose more quality.

So having the issue mentioned above; in my code it was happening that. I've got just one instance​ of  `Image` and I resize many times based on the same - already resize - JPG images. Therefore, i just had to make differents instances of the original image and do all the works i needed; in my case it was a resizing work.

**Comment by lynnrey** [comment]
Thank you so much for getting back to me. This is my code.  I removed encode line also and tried with imagemagick. But still image is blurred. Am I missing something? I am trying to make the image to an height of 650 px. 

Image::configure(array('driver' => 'gd'));
$img = Image::make($imgName);
$img->resize(null,650, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            });
$img->encode('jpg', 100);
$img->save($img_path, 100);

**Comment by DracotMolver** [comment]
Of course, if your image is lower than 650px, it'll be blurry and with low quality.
don't know if you understand the meaning of the `aspect ratio` word. But use the `aspectRatio()` funciton only if your image has a size based on an aspect ratio (check the Wikipedia [https://en.wikipedia.org/wiki/Aspect_ratio_(image)](url).  So why don't you use the `heighten()` function

>**heighten** Resizes the current image to new height, constraining aspect ratio. Pass an optional Closure callback as third parameter, to apply additional constraints like preventing possible upsizing. And! returns a resized instance of Intervention\Image\Image.

* The `encode()` functions returns you a new instance of the Image object. Before this, you can save that object to a path. So, in your code you are not doing it right.

Try this code:
```php
Image::configure(array('driver' => 'gd'));
$image = Image::make($imgName);
$image->heighten(650) // Try this with and without a callback
      ->encode('jpg', 100) // this will returns the new encoded object and save it, don't save the old one that was in your code.
      ->save($img_path, 100);
```

**Comment by lynnrey** [comment]
Thank you Diego. I will check that out. Much appreciated. !!
