### ISSUE TITLE
canvas() not supported in GD

### ISSUE THREAD

**Issue by simivar** [Intervention/image#633]
When I try to create new empty canvas I get:
`Fatal error: Uncaught exception 'Intervention\Image\Exception\NotSupportedException' with message 'Command (canvas) is not available for driver (Gd).' in [...]/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php on line 124`

**Comment by sigfriedseldeslachts** [comment]
Like the error says, you cannot use canvas in PHP GD. Try the Imagick extension.

> sudo apt-get install php-gd

Or enable in your PHP.ini

Greetings
