### ISSUE TITLE
issue with save the image in laravel

### ISSUE THREAD

**Issue by 8lbiasian** [Intervention/image#635]
hello i just try to save the image but its give an error 

Can't write image data to path 
`(C:\laragon\www\idealmgmt\storage/files/Certificates/123123123123-2.png)`

this is my save line 
       ` $img->save(storage_path() . '/files/Certificates/' . $student->register_number . '-' . $type->id . '.png', 80);
`
with the response i got the image preview correctly without any issue but now iam trying to save the file

**Comment by sigfriedseldeslachts** [comment]
Does Laravel have the permissions to write the file? If you're on Linux try

> chmod -R 777 storage/files/Certificates/
Keep in mind that you should never give your whole Laravel app 777 permissions.

Greetings
