### ISSUE TITLE
Method Intervention\Image\Image::__toString() must return a string value

### ISSUE THREAD

**Issue by mirko-pagliai** [Intervention/image#636]
I'm trying to resize a `psd` file.

Maked and resized the file, I get this error trying to enconde:

    $content = (string)$imageInstance->encode('psd', 90);

Error:

    Method Intervention\Image\Image::__toString() must return a string value

Debugging the instance **before** trying to encode:

```
object(Intervention\Image\Image) {
        encoded => ''
        mime => 'image/vnd.adobe.photoshop'
        dirname => '/home/mirko/Libs/Plugins/cakephp-thumber/tests/test_app/webroot/img'
        basename => '400x400.psd'
        extension => 'psd'
        filename => '400x400'
        [protected] driver => object(Intervention\Image\Imagick\Driver) {
                decoder => object(Intervention\Image\Imagick\Decoder) {

                }
                encoder => object(Intervention\Image\Imagick\Encoder) {
                        result => null
                        image => null
                        format => null
                        quality => null
                }
        }
        [protected] core => object(Imagick) {

        }
        [protected] backups => []
}

```

This happens only with the psd files. It happens to me on two local environments, but not remotely (Travis).

What can it be?

I'm using `php-imagick 3.4.3~rc1` and `imagemagick 6.9.6.2` (both local environments are on debian testing).

Thanks.

**Comment by isszz** [comment]
I also encountered this problem.
`
	    // create response and add encoded image data
	    $response = Response::make($img->encode('jpg', $quality));

	    // set content-type
	    $response->header('Content-Type', 'image/png');

	    // output
	    return $response;`

This error message:

`The Response content must be a string or object implementing __toString(), "object" given.`

**Comment by isszz** [comment]
Helpless, I was so temporary:

```
$img->encode('jpg', $quality);
$data = $img->getEncoded();
$mime = finfo_buffer(finfo_open(FILEINFO_MIME_TYPE), $data);
header('Content-Type: ' . $mime);
echo $data;
exit;
```

**Comment by mirko-pagliai** [comment]
Thanks @isszz . shame that here any answer.
