### ISSUE TITLE
Resize to Maximum Pixel Size

### ISSUE THREAD

**Issue by nojacko** [Intervention/image#639]
Don't think this is currently a feature. If ya'll like it, I'll make a pull request.

**The Idea**

- Function called resizeMaxPixels($maxPixels).
- This would resize the image such that it usages no more than $maxPixels pixels in total.

**Examples:**

Image 1:
* Size: 1000 x 1000
* $maxPixels = 250,000 (500 x 500)
* Output Size: 500 x 500 
* Output Total Pixels: 250,000

Image 2: 
* Size 1000 x 2000
* $maxPixels = 250,000 (500 x 500)
* Output Size: 353 x 707 (both values rounded down)
* Output Total Pixels: 249,571

**Comment by olivervogel** [comment]
Maybe I have no imagination but I can't think of any use case where the total pixel count is more important than the actual image width/height.

**Comment by nojacko** [comment]
It's something The PHP League's Glide library does.

> Notice that Glide doesn’t actually restrict the width or height, but rather the total image size. [...] This accomplishes the same thing, while offering more flexibility with your image sizes.
> http://glide.thephpleague.com/1.0/config/security/#max-image-size

It just makes things simpler when resizing images that either really wide or really tall. Limiting the width or height these types of images doesn't work well.
