### ISSUE TITLE
Composer removed other packages

### ISSUE THREAD

**Issue by Sheikh-Alvee** [Intervention/image#640]
When i run this command on my CMD.
`composer require intervention/image`
Using version ^2.3 for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing anouar/paypalpayment (1.1.1)
  - Removing paypal/rest-api-sdk-php (v1.3.0)
  - Removing league/glide (1.0.0)
  - Removing pqb/filemanager-laravel (2.0.7)
  - Removing barryvdh/laravel-elfinder (v0.3.7)
  - Removing barryvdh/elfinder-flysystem-driver (v0.1.5)
  - Removing studio-42/elfinder (2.1.11)
  - Removing league/flysystem-cached-adapter (1.0.3)
  - Removing psr/cache (1.0.0)
  - Removing barryvdh/laravel-dompdf (v0.6.1)
  - Removing laravel/cashier (v6.0.14)
  - Removing dompdf/dompdf (v0.6.2)
  - Removing phenx/php-font-lib (0.2.2)
  - Removing stripe/stripe-php (v3.12.1)
  - Removing psr/http-message (1.0)
  - Installing psr/http-message (1.0.1)
    Loading from cache

  - Removing guzzlehttp/psr7 (1.3.0)
  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Removing intervention/image (2.3.7)
  - Installing intervention/image (2.3.8)
    Loading from cache

Writing lock file
Generating autoload files
> php artisan clear-compiled

**Comment by olivervogel** [comment]
I think this is rather a composer issue.
