### ISSUE TITLE
Image->iptc('attribute') returns Image instead of null

### ISSUE THREAD

**Issue by Swanty** [Intervention/image#643]
The problem is here:
https://github.com/Intervention/image/blob/2.3.8/src/Intervention/Image/Image.php#L107

IPTC tests don't catch it since, they're using IptcCommand directly:
https://github.com/Intervention/image/blob/2.3.8/tests/IptcCommandTest.php

In normal usage developers would use Image->iptc('attribute') as it is described in the documentation here:
http://image.intervention.io/api/iptc

To reproduce this, just try to get an iptc attribute that is not set inside the image.
IptcCommand will set output to null, but Image __call will return Image object

**Comment by olivervogel** [comment]
Can't reproduce the described bug.

1. The `IptcCommand` [sets](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Commands/IptcCommand.php#L60) the output to `false` if the attribute is not found.
2. `__call` will [check](https://github.com/Intervention/image/blob/2.3.8/src/Intervention/Image/Image.php#L107) if command `hasOutput`, in this case `false` is output.
3. `$command->getOutput()` is returned, which will [resolve](https://github.com/Intervention/image/blob/master/src/Intervention/Image/Commands/AbstractCommand.php#L57) to `null` in this case.
