### ISSUE TITLE
Emoji support?

### ISSUE THREAD

**Issue by casenjo** [Intervention/image#645]
I've tested with various fonts (including [OpenSansEmoji](https://github.com/MorbZ/OpenSansEmoji)) and I can't get emoji characters to properly appear, they always display as weird characters instead (see image). I'm using the latest version from composer.

The text should display "Happy Birthday 😀"
![test](https://cloud.githubusercontent.com/assets/1554289/20855540/eecceef2-b8b2-11e6-942a-26d8f31a9652.png)

Is there something else that needs to be done to enable the display of full emojis with colors?

Edit: Using GD it shows the image above. Using imagick along with the OpenSansEmoji shows the following:
![test2](https://cloud.githubusercontent.com/assets/1554289/20855648/aea3621e-b8b4-11e6-8e01-661fb60be058.png)

**Comment by david-ridgeonnet** [comment]
Take a look here: http://stackoverflow.com/questions/32391005/php-function-imagettftext-to-write-text-with-smileys

Apparently GD library doesn't support emojis as they require 4 byte UTF8
