### ISSUE TITLE
resize image with arabic name

### ISSUE THREAD

**Issue by m-alinasab** [Intervention/image#646]
hi .

i want resize ( regenerate ) all image and make new size .
but my file name is arabic : 
example : 
https://net-tours.net/uploads/tours/1000تور-استانبول.jpg

error Exception : 
Image source not readable

please help to regenerate image file .

thanks .

**Comment by olivervogel** [comment]
Intervention Image works with arabic filenames. I just tested this locally:

```php
$img = Image::make('1000تور-استانبول.jpg')->fit(500);
```

Maybe the probleme here is, that the image library can't read the file via HTTP. I suggest to use a dedicated library like [Guzzle](http://docs.guzzlephp.org/en/latest/) to read the file and pass it to Intervention Image afterwards.

See https://github.com/Intervention/image/issues/438.

**Comment by m-alinasab** [comment]
thanks but my image name is tour-istanbul1000.jpg no problem and working !
but if set arabic or persian character : 
error Exception :
Image source not readable
