### ISSUE TITLE
Dependency Injection for hashed url or params

### ISSUE THREAD

**Issue by fabiopenagoli** [Intervention/image#648]
I use Intervention Image since months and I'm very happy. Thanks!

It would be wonderful having the possibility to make custom templates for params and hashed urls.
For example:

1. GET /{route}/{template-name}/{hashed-image-url}[.ext]
2. in a class I could decrypt the hashed-image-url to get the real image filename and some params (like dimensions requested etc.)
3. pass these params to the Intervention Image application to serve the cached image

Is it possible?
If not, can you tell us some suggestions to start this implementation by ourselves?

Thanks so much!

**Comment by olivervogel** [comment]
Of course it is possible. You can use Intervention Image, but you have to write your own url processing engine.

The concept of Intervention Image's [URL based image manipulation](http://image.intervention.io/use/url) is to store image dimension and manipulation options in the template class and not in the url.
