### ISSUE TITLE
url manipulation problem 

### ISSUE THREAD

**Issue by M0H3N** [Intervention/image#653]
Hi
Im using Laravel 5.3 , intervention/image 2.3 and intervention/imagecache 2.3 on windows 10.
this is my imagecache.php content : 
```
<?php

return array(

    'route' => 'images',
    
    'paths' => array(
    
       public_path('uploads'),
    ),
   
    'templates' => array(
        'small' => 'Intervention\Image\Templates\Small',
        'medium' => 'Intervention\Image\Templates\Medium',
        'large' => 'Intervention\Image\Templates\Large',
    ),
   
    'lifetime' => 43200,

);

```
and I have a test.jpeg file in "public\uploads" path.
but http://localhost:8000/images/small/test.jpeg just sends  404 error . 

I checked the config but no idea about that what is the problem ?

**Comment by M0H3N** [comment]
the problem was in my routes
I fixed it

**Comment by laravelish** [comment]
@M0H3N how did you fixed it i have the same issue

**Comment by laravelish** [comment]
i had this in my conf file

     location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }
removing it fixed it
