### ISSUE TITLE
intervention image fails on image with resolution higher then 1500x1300 on Apache

### ISSUE THREAD

**Issue by nermion** [Intervention/image#655]
When I upload the image and then try to resize it if the image is above 1500x1300 for example 1500x1500 resize fails and server responds with 500 code. This happens on only on apache server, same code on nginx server does not have this problem. Image in question is about 200 kb and it's png image.

**Comment by marcoapferegrino** [comment]
Hi, what was the solution here ? I have same problem. Thanks

**Comment by iwebnaut** [comment]
solution is to install nginx, try laragon.com for local development, for production you should not use apache.

**Comment by marcoapferegrino** [comment]
I already fix it givin more memory to resize bigger images because the server just have allowed a small portion. Thanks for your anwer

**Comment by marcoapferegrino** [comment]
I use 
ini_set('memory_limit','50M') in this way the server has enough memory to resize a big image. You can change the number of memory.

**Comment by iwebnaut** [comment]
great! :)
