### ISSUE TITLE
URL based image manipulation using GET

### ISSUE THREAD

**Issue by shinokada** [Intervention/image#656]
I am using on Laravel 5.3.

Is there any way I can use like `http://myweb.dev/imagecache/custom/article_box_1.jpg?w=100&h=100`

```
<?php
namespace App\Intervention;

use Intervention\Image\Image;
use Intervention\Image\Filters\FilterInterface;
use Request;

class Custom implements FilterInterface
{
    public function applyFilter(Image $image)
    {
        $width = Request::get('w');
        $height = (Request::get('h')) ? Request::get('h') : null ;
        return $image->fit($width, $height);
    }
}
```

**Comment by hengsoheak** [comment]
I'm facing this problem too
http://stackoverflow.com/questions/42364200/unable-to-init-from-given-url-in-intervention-image-2-3

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/558 or https://github.com/Intervention/image/issues/438.

**Comment by hengsoheak** [comment]
So mean that 
http://image.intervention.io/use/url is allow only it url?
