### ISSUE TITLE
crop picture and the selected area is not same.

### ISSUE THREAD

**Issue by csi0n** [Intervention/image#660]
When I cut out of the picture(use image->crop(w,h,x,y)), if is picture is normal, but if is a larger version(>600kb), cut out the pictures and I'm the selected area is not the same.

**Comment by juukie** [comment]
Please share a gist of your code so others can reproduce your error and help solving it.

**Comment by csi0n** [comment]
I find it is my problem, I was the picture in the page zoom, lead to
intercept out areas have also been corresponding scaling.
