### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kasperbisgaard** [Intervention/image#666]
Hi, I'm having issues using the Intervention Image library. It works on my localhost, but when i try using it on my server, it throws a 500 Internal Server Error. I suspect that I am missing some kind of php module or something, but i'm not sure. (It's an amazon EC2 server) 
It's failing on this line:
`$image = Image::make($file)->encode('jpg', 90);`
$file is a base64 encoded image file. It's throwing a 500, but no error message of any kind.

**Comment by briedis** [comment]
Well, check the server logs. You should be able to get a full strack trace of what exactly is failing. This error is vary vague. Maybe you don't even have Imagick or GD enabled...
