### ISSUE TITLE
 NotReadableException in Decoder.php line 46:

### ISSUE THREAD

**Issue by ezekel** [Intervention/image#669]
@olivervogel 

I have image from my mobile phone, when I tried to upload in our web server using Laravel, it threw error

```NotReadableException in Decoder.php line 46:```
```Unable to read image from file ```

this is my code

```
       $filename = $request->upimg->getClientOriginalName();
        $image = $request->upimg->getRealPath();
        $path =public_path() . '/userimg/';
        $fimage = Image::make($image)->resize(48, null,true);
        $fimage->save($path . $filename);
```

But when i open the image in the paint and save as . I can upload in the server, but I don't want my users to open in paint and do save as in order to upload their profile pic.

Thank you in advance.

**Comment by olivervogel** [comment]
Please provide a link to a not working image.

**Comment by andrew-za** [comment]
Same here - any image I have on my phone..

**Comment by matthewnessworthy** [comment]
are you correctly encoding the post data? e.g., `<form enctype="multipart/form-data">`

**Comment by LechuuuS** [comment]
I also have the same problem

Link to image: [https://drive.google.com/file/d/0B8XyZGhUQfVsRVQ5MEZ2cmtZZVU/view?usp=sharing](url)

**Comment by JOHN-MAINA** [comment]
In my case, random image were were not working first thought it was memory issues but it wasn't, it worked after the following lines before reading image data with any intervention image function

`ini_set ('gd.jpeg_ignore_warning', 1);
 error_reporting(E_ALL & ~E_NOTICE);`

**Comment by LechuuuS** [comment]
JOHN-MAINA, thank you for the solution, actually after adding this configuration it works perfectly. Regards :)

**Comment by Mr-Anonymous** [comment]
Hi @JOHN-MAINA Thank you for sharing your solution. I am stuck on the same problem and it is very odd. Like you pointed out, the `unable to read image from file` error happens only randomly and I am unable to reproduce that error. however i can see from laravel error log that this error is happening to some users who are using android chrome and even firefox on windows 7. So my question to your post, did you add that `ini_set()` and `error_reporting()` code 1 line before `$img = Image::make($file);` code in my controller?

Do you know why this line of code fixes the issue? It appears the line of code is related to error reporting, but why does that make the `Image::make($file);` work properly?

Its very odd, I have seen many posts on the same issue but with no concrete solution. Hope you can share a little bit more info on this please...

**Comment by JOHN-MAINA** [comment]
@Mr-Anonymous
Added it before
It turns off error reporting during runtime caused by JPEG images

**Comment by nfreear** [comment]
Hi All,

In case it's useful to anyone ...

I've just seen the same exception on a Redhat Linux production server, which I wasn't seeing on our approval server (on the face of it, identical installations / configurations ...)

When I enabled the Laravel debug-bar, I was able to see the underlying `ImagickException`:

> no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/504
/var/www/.../vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php#28
> ImagickException

I was also able to see on a `phpinfo();` web-page, under the "_imagick_" section:

> ImageMagick number of supported formats:  0

_(It should be a non-zero number!)_

I think the cause was an automated upgrade of the _imagick_ libraries ... The solution was to re-start the `php-fpm` service.

I hope this helps.

Nick

**Comment by olivervogel** [comment]
Please note that not all image formats are always included in the PHP image extensions. It is therefore possible, that the GD library is installed but is configured without Jpeg support or Imagick is available without Webp support for example.

You can view the supported image formats with [gd_info()](https://www.php.net/manual/de/function.gd-info.php) or [Imagick::queryFormats()](https://www.php.net/manual/de/imagick.queryformats)

It may then be necessary to configure the respective support for the corresponding image format.
