### ISSUE TITLE
memory error on publish artisan cmd laravel 5.4.8 ap

### ISSUE THREAD

**Issue by mubashirsiddique** [Intervention/image#681]
I am installing Image intervention via composer 
after placing servicesprovider and alias
- When I run publish artisan command it give me memory error as follows:

`fatal error: allowed memory size of 134217728 bytes exhausted`

I increased the memory in ph.ini : memory_limit = 128M to 512M but fatal error is the same. Tried to check other packages if they are producing it. It comes out to be "Intervention/Image" doing so on my Laravel 5.4.8 app I am recently making.

**Comment by jigsthegreat** [comment]
same problem with Laravel 5.4.10. Can anyone help?

**Comment by matthewnessworthy** [comment]
please include the output of the cli command `php -i | grep memory_limit`
