### ISSUE TITLE
Can't install Intervention on Ubuntu (Unenexpected Token ILLEGAL)

### ISSUE THREAD

**Issue by vikaskumar2299** [Intervention/image#682]
I installed composer and then Intervention as directed in installation guide. But when I tried to run the following code, I got following error:

> use Intervention\Image\ImageManager;
>     ^^^^^^^^^^^^^
> SyntaxError: Unexpected token ILLEGAL

Here's my code:

```
require ('vendor/autoload.php');
use Intervention\Image\ImageManager;
```

Composer.json:

```
{
    "require": {
        "intervention/image": "^2.3"
    }
}
```

**Comment by matthewnessworthy** [comment]
@vikaskumar2299 that looks oddly like a JS error, can you include more of the code please

**Comment by vikaskumar2299** [comment]
Thank you for looking into this but now the problem is solved. Actually I saved the file as .js instead of .php

**Comment by matthewnessworthy** [comment]
@olivervogel please close
