### ISSUE TITLE
Slow upload image

### ISSUE THREAD

**Issue by congkevin** [Intervention/image#686]
When changing user profile picture, I only need small size image. but user will upload a large size image from their phone.
I have written code below.
$img = Image::make('public/foo.jpg')->resize(320, 240)->insert('public/watermark.png');

My question:
This code upload the full size image to server and then do the resize and save?
If so, in order to speed up upload, can i resize the image on client side then save into server?

**Comment by olivervogel** [comment]
Intervention Image is written in PHP and PHP is server-side only.
