### ISSUE TITLE
Command (insert) is not available for driver (Gd)

### ISSUE THREAD

**Issue by umutyerebakmaz** [Intervention/image#690]
**GD Version => 2.1.1-dev**
**imagick module version => 3.1.2**
**PHP Version 5.5.9-1ubuntu4.21**

Image::make('uploads/products/'.$filename)->fit(440, 585)->insert('uploads/watermark.png','center',0,0)->save('uploads/products/'.$filename, 100);

Laravel 5.2 throw this error message:  Command (insert) is not available for driver (Gd)

**Comment by okansahin** [comment]
@umutyerebakmaz https://github.com/Intervention/image/issues/570

**Comment by umutyerebakmaz** [comment]
Yes true
