### ISSUE TITLE
Method save does not exist.

### ISSUE THREAD

**Issue by johnef** [Intervention/image#691]
public function store(Request $request)
    {
        $slider = new Slider();

        $slider->header = $request->header;
        $slider->paragraph = $request->paragraph;

        if ($request->hasFile('image')) {
            $slider = $request->file('image');
            $filename = time() . '.' . $slider->getClientOriginalExtension();
            Image::make($slider)->resize(1920, 1008)->save(public_path('images/homeSlider/' . $filename));
            $slider->image = $filename;
        }

        $slider->save();

        \Session::flash('sliderSuccess', 'Slider has been successfully uploaded');
        return \Redirect::to('admin/slider/create');
    }

**Comment by matthewnessworthy** [comment]
@johnef you're overwriting the `$slider` object with `$request->file('image')`, after that it's no longer a model/ORM object

try:
```
$slider->header = $request->header;
$slider->paragraph = $request->paragraph;

if ($request->hasFile('image')) {
    $image = $request->file('image');
    $filename = time() . '.' . $image->getClientOriginalExtension();
    Image::make($image)->resize(1920, 1008)->save(public_path('images/homeSlider/' . $filename));
    $slider->image = $filename;
}

$slider->save();

\Session::flash('sliderSuccess', 'Slider has been successfully uploaded');
return \Redirect::to('admin/slider/create');
```

**Comment by matthewnessworthy** [comment]
@olivervogel please close
