### ISSUE TITLE
laravel giving 500 error code 2 times

### ISSUE THREAD

**Issue by hamzaali00001** [Intervention/image#699]
When using laravel it gives **response code 500 two times**. But when I refresh it third times it works. There are no error logs in laravel. GD class is active and also there are no code errors because the third time I refresh that it gives me the image. Any solution to this

**Comment by gfabrizi** [comment]
This is happening to me too.
Laravel V5.4.23, PHP 7.0.x and 7.1.6
I see in the web server log (nginx) a few 500 codes for images accessed with imagecache url manipulation named routes.

**Comment by hamzaali00001** [comment]
Well, I had already solved it. One easy way is to go to your php.ini file and increase the memory limit available for a process and then restart the web server. But I think you will be using it in one route. So it would be better to use ini_set and set it to about 512. It will work fine.
