### ISSUE TITLE
Intervention imagick works in terminal but not in browser

### ISSUE THREAD

**Issue by vikaskumar2299** [Intervention/image#700]
I quite don't understand what's going wrong. I've installed Intervention from as guided here

Then I created the following .php file and started my localhost Apache server and tested the results and it worked!

Here's the code:

test.php
```

<?php
require 'vendor/autoload.php';
use Intervention\Image\ImageManagerStatic as Image;
Image::configure(array('driver' => 'gd'));
$image = Image::make('ar.jpg');
$path = 'public/images/photoh.png';
$image->save($path);
?>
```
But when I run the same file using php test.php in Ubuntu terminal, I get the following error:

GD Library extension not available with this PHP installation.

When I checked the phpinfo(), I saw gd being listed there with version 2.1.0

This is not the real issue, but still I would like to know what can be wrong and how can I solve it.

Then comes the real problem. I installed Imagick separately using following command:

sudo apt-get install php-imagick

This installed Imagick 6.8 on my system (I checked this using convert -version)

Then I added following to php.ini file:

**extension=imagick.so**

And then for testing, I changed the driver to 'imagick' in test.php and executed it using php in terminal and it worked fine.

But I want it to work on browser, like GD, but IT DIDN'T.

It showed the similar error that GD showed on terminal:

ImageMagick module not available with this PHP installation.

So it seems like ImageMagick is installed but something is missing. Is there something I can do?

Ubuntu: 16.04 LTS 
PHP: 5.6

**Comment by matthewnessworthy** [comment]
Have you restarted the apache service?

**Comment by vikaskumar2299** [comment]
Yes I did many times. Still working in terminal but not in browser. Only GD works in browser.

**Comment by matthewnessworthy** [comment]
perhaps compare the config files that have been loaded

`php -i` in the cli
and `<?php phpinfo(); ?>` in an apache/browser accessed file

pay special attention to:
```
Configuration File (php.ini) Path
Loaded Configuration File	
Scan this dir for additional .ini files	
Additional .ini files parsed	
```

also, ensure the `Configure Command` contains something like `'--with-gd`

**Comment by vikaskumar2299** [comment]
Sorry I couldn't find anything special. I don't have much understanding about this.

**Comment by vikaskumar2299** [comment]
@matthewnessworthy I think I got why it isn't working. When I run the same file in terminal, the imagick works, as I told before. When I checked the phpinfo() log in terminal, I saw PHP 7.1 and imagick listed there. Same file shows PHP 5.6 and no imagick listed in browser. So I think it's working in terminal because of PHP 7.1. So all I would need to remove PHP 7.1 (I tried but it didn't work.) And similarly tried to install imagick for PHP 5 using commands listed  [here](https://www.theshell.guru/install-imagemagick-ubuntu-16-04/) but it showed that "'php5-imagick' has no installation candidate" again maybe because of Ubuntu 16.04. What do you say?

**Comment by vikaskumar2299** [comment]
The problem is solved now. Actually I was using XAMPP and it was using a different php.ini file. I removed it and installed apache server from terminal and then install imagemagick and imagick again and it runs fine now.
