### ISSUE TITLE
Trying to resize dramatic ratios runs out of memory

### ISSUE THREAD

**Issue by jackmcdade** [Intervention/image#701]
We've been seeing issues where if an image has a dramatic aspect ratio (much taller than it is wide, or vise vera - e.g. `800x45` or `2x300` it plain runs out of memory:

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 71020001 bytes) in /Users/mark/work/support-site-2/statamic/vendor/intervention/image/src/Intervention/Image/Gd/Commands/ResizeCommand.php:56 Stack trace: #0 {main}
```

Is there a way to prevent that from happening?

**Comment by holtkamp** [comment]
Does this also happen when using the Imagick driver?

**Comment by woei66** [comment]
> Does this also happen when using the Imagick driver?

I did the test and I change gd to imagick and no this problem

**Comment by olivervogel** [comment]
Resizing or scaling still results in error with GD driver in version 3 of Intervention Image:

```php
$image = ImageManager::gd()
    ->read('images/tall.png') // 2 x 3000 px
    ->scale(height: 300);
```

> Fatal error: Uncaught ValueError: imagecreatetruecolor(): Argument #1 ($width) must be greater than 0

This is due to the fact that the internally used algorithm downsamples to sizes smaller than 1 pixel at high aspect ratios, which is not technically possible in image output.

**Comment by olivervogel** [comment]
Fixed in https://github.com/Intervention/image/commit/66b28952384a7e6e5918fbd2238689fcd4677574
