### ISSUE TITLE
Hose intervention support with Khmer Unicode?

### ISSUE THREAD

**Issue by hengsoheak** [Intervention/image#702]
I'm testing to create watermark by using Intervention images 

But it is not work properly please check the images below

The text which i used to create watermark " ប្រទេសកម្ពុជា " and the result is not better so I'm try to used any PHP method to decode or can create this job better.

![2017-03_27](https://cloud.githubusercontent.com/assets/812528/24055731/d084751e-0b73-11e7-8e26-a360b8893f30.jpg)

**Comment by limsocheat** [comment]
@hengsoheak did you find solution?

**Comment by olivervogel** [comment]
I think this is a duplicate of https://github.com/Intervention/image/issues/939
