### ISSUE TITLE
save() API: Furthermore the image will always be saved in RGB color mode without an embeded color profile

### ISSUE THREAD

**Issue by tecnologias-prograf** [Intervention/image#704]
Hi.
How can I preserve the CMYK color mode in a jpg file using the save/response function (using the imagick driver).
The attached files are the correct one (exported with Adobe Illustrator) and the incorrect one (saved with Image Intervention).
Thanks in advance

![correct_color](https://cloud.githubusercontent.com/assets/7958192/24306867/ba2aca52-1087-11e7-9d7e-fae25a11a51a.jpg)
![incorrect_color](https://cloud.githubusercontent.com/assets/7958192/24306868/ba329296-1087-11e7-8505-a2d1e39c5254.jpg)

**Comment by tecnologias-prograf** [comment]
both file appears to be the same, but aren't. I attached a zip file instead.

[color files.zip](https://github.com/Intervention/image/files/868788/color.files.zip)

**Comment by viniciusalonso** [comment]
Hey there,

I made this today. You should get the image from upload and use the color space using the `Imagick` class from PHP to save the image in CMYK mode. 


```php
public function generateCmykImage($originalImage)
  $cmykImage = new \Imagick($originalImage->getRealPath());
  $cmykImage->setImageColorspace(\Imagick::COLORSPACE_CMYK);
   $cmykImage->writeImage($originalImage->getRealPath());

  return $cmykImage;
}
```


I hope that helped :)

**Comment by saaiful** [comment]
To save CMYK Image i edited the Decoder.php's line 23 
`$core->setImageType(defined('\Imagick::COLORSPACE_CMYK') ? \Imagick::COLORSPACE_CMYK : \Imagick::COLORSPACE_CMYK);`
It works but, it converts all image into CMYK. For my case I'm only working with CMYK.

**Comment by olivervogel** [comment]
Version 3 of Intervention Image supports [colorspaces](https://image.intervention.io/v3/basics/colors#colorspaces) as well as [supports color profiles](https://image.intervention.io/v3/basics/colors#color-profiles) with the Imagick driver.

Unfortunately, it is still not possible to interpret color profiles with the GD library and therefore also not with Intervention Image and the driver for this library
