### ISSUE TITLE
is_file(): File name is longer than the maximum allowed path length on this platform

### ISSUE THREAD

**Issue by denmasyarikin** [Intervention/image#708]
Hi,

I have a method just for check is given value imagable, the method is like this

```php
    /**
     * check is string imagable
     *
     * @param string $string
     * @return bool
     */
    protected function isImagable($string)
    {
        try {
            ImageManagerStatic::make($string);
            return true;
        } catch (Exception $e) {
            return false;
        }
    }
```
I just realize that if i give the base64 encoded value, it's always return `false`, when i print the error message is `is_file(): File name is longer than the maximum allowed path length on this platform...`
Then I looking for possible reason for this error, so I'v found in `AbstractDecoder` class method `init` the sequence of `isFilePath` first checking then `isBase64`

I think `isFilePath` checking should be in the last, at lease `isBase64` is the first then `isFilePath`

My Project runing in `Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.4.38-std-1 x86_64 )`

**Comment by dietercoopman** [comment]
Hi,

have you found a solution for this problem , we encounter the same problem

thx

**Comment by denmasyarikin** [comment]
Hi,

yes, i was forked this repo and sent pull request for this problem, and still no response until now,
so for while I just direct my dependency to our forked [repo](https://github.com/flipboxstudio/image).

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/flipboxstudio/image"
        }
    ],
    "require": {
        "intervention/image": "dev-master",
    }
}
```

**Comment by dietercoopman** [comment]
The solution for my problem is quiet easy , ik did Image::make(file_get_contents($fullpath)); , but the file_get_contents is not needed , removed it and that did the job

**Comment by grayse7en** [comment]
the problem belongs to `Intervention\Image\ImageCache::isFile()` method.
`is_file()` that used in this method, can't handle names with more than system filename length. so error occurred! I think this a core php problem. btw my solution is below:
```php
if (strlen($value) < 255) {
    return is_file($value);
}else return false;
```
