### ISSUE TITLE
Fatal error: Class 'Image' not found

### ISSUE THREAD

**Issue by flihub** [Intervention/image#710]
installed with composer and 

// working 
require 'vendor/autoload.php';
use Intervention\Image\ImageManager;
$manager = new ImageManager();

// Static Example not working
require 'vendor/autoload.php';
use Intervention\Image\ImageManagerStatic as Image;
Image::configure();

Fatal error: Class 'Image' not found in C:\Wamp\www\

windows 10 
Wampserver 3.0.6 64 bit x64 – Apache 2.4.23 – PHP 5.6.25

**Comment by olivervogel** [comment]
Try:

```php
require 'vendor/autoload.php';
use Intervention\Image\ImageManagerStatic as Image;
\Image::configure();
```
