### ISSUE TITLE
Want to add text watermark in tile format

### ISSUE THREAD

**Issue by pramod-kumar-czone** [Intervention/image#711]
Hello support,

I want to add user given text(watermark) in tile form on an image.

i am using below code. but its not working it put a single line with angle i given, where as i want text to be repeated until it reaches end of the image, i hope you understand what i mean.

 $img = Image::make(storage_path('app'.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.$media->file_path));
                // use callback to define details
                $width = $img->width();
                $height = $img->height();

                $data = $img->text($watermark, 15, 25, function($font) {
                            $font->file(public_path('frontend/fonts/Xerox Serif Wide.ttf'));
                            $font->size(36);
                            $font->color(array(0,0,0, 0.3));
                            $font->align('center');
                            $font->valign('top');
                            $font->angle(45);
                        })

Thanks

**Comment by tomtomsen** [comment]
I think you need a loop which places the text on different positions, like:
```php
    for($i = 15, $j = 25; $i < $width && $j < $height; $i += 40, $j += 40) {
        $data = $img->text($watermark, $i, $j, function($font) {
            $font->file(public_path('frontend/fonts/Xerox Serif Wide.ttf'));
            $font->size(36);
            $font->color(array(255,0,0, 0.3));
            $font->align('center');
            $font->valign('top');
            $font->angle(45);
        });
    }
```
hope this helps.

**Comment by olivervogel** [comment]
I would split this into two steps. 

1. Create the watermark by writing text onto an transparent background
2. Use this watermark image as a parameter to call `fill()` and place it all over the target image
