### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by jagroop** [Intervention/image#714]
Hi, I am simply trying to resize and image, everything is working fine but don't know why sometimes I get rotated (90 deg) images.

```php
$height = 500;
$width = 500;

$img = Image::make('uploads/user00012.jpg');
$img->resize($height, $width);
$img->save('uploads/thumbnail_user00012.jpg');
```

Am I doing something wrong?

Thanks

**Comment by olivervogel** [comment]
Some photos have include Exif data to adjust the orientation.

Try applying [orientate()](http://image.intervention.io/api/orientate).
