### ISSUE TITLE
How to make intervention work with laravel storage

### ISSUE THREAD

**Issue by yelnyaface** [Intervention/image#716]
How to make intervention work with laravel storage?

all the code I saw on the web like:
```
$img = Image::make($request->file('avatar'));
Storage::put('path/to/file.jpg', $img);
```
or

```
$img = Image::make($request->file('avatar'));
Storage::put('path/to/file.jpg', $img->stream());
```
never work, the laravel storage EXPECTS a UploadFile type
so how does that even work?

**Comment by tehwave** [comment]
Save the file to storage first, then adjust it with Image. When you save the adjusted file, it will overwrite.

**Comment by olivervogel** [comment]
Try this:

```php
$img = Image::make($request->file('avatar'));
Storage::put('path/to/file.jpg', $img->encode('jpg'));
```

http://image.intervention.io/api/encode
