### ISSUE TITLE
Rotate and crop commands give different result on different drivers

### ISSUE THREAD

**Issue by snewer** [Intervention/image#723]
With GD works as it sholud:

> $imageManager = new ImageManager(['driver' => 'GD']);
$image = $imageManager->make(file_get_contents('link to image'));
$image->rotate(45, '#FFFFFF');
$image->crop($image->width(), $image->height(), 0, 0);
header('content-type: image/jpeg');
echo $image->encode('jpeg', 100);

Imagick`s cropping changes images size:

> $imageManager = new ImageManager(['driver' => 'Imagick']);
$image = $imageManager->make(file_get_contents('link to image'));
$image->rotate(45, '#FFFFFF');
$image->crop($image->width(), $image->height(), 0, 0);
header('content-type: image/jpeg');
echo $image->encode('jpeg', 100);

**Comment by snewer** [comment]
This fix resolves the problem:
`$image->getCore()->setImagePage($image->width(), $image->height(), 0, 0);`
(putting after crop command)

**Comment by olivervogel** [comment]
Issue should be fixed as of v3.3
