### ISSUE TITLE
Image source not readable

### ISSUE THREAD

**Issue by mustafaabduljalil** [Intervention/image#725]
NotReadableException in AbstractDecoder.php line 339:
Image source not readable

Please i need help i did everything in doc right at my app but still not working 
thanks,

**Comment by Matoo125** [comment]
are you sure your source is readable by web server? You probably have some permission problem

**Comment by mustafaabduljalil** [comment]
Yes i'm sure i use laravel and i did dd for source and it's write

**Comment by Matoo125** [comment]
you should put here your code (you can check in whoops which line of your code is causing it) .. not sure what is dd doing. You should also write what OS you use if you want to receive some specific suggestions. The file has to be readable by server, not just you as user.

**Comment by Megachill** [comment]
For a lot of people the problem is always in php.ini - just look at max_upload etc and you'll see. Just check your php.ini and I am sure you find the issue. I myself used to make the mistake looking everywhere but the place where the actual issue is.

**Comment by Faks** [comment]
intervention is very sensitive with wrong code to find out that i had to kill many hours on debug.
personal advice don't try to optimize code use from orginal website that is deployed and start from it i hoped.

**Comment by bahman2216** [comment]
I have same problem. What is image source exactly? It doesnt explain in document. I put my images in storage and also in public folder, But all time get error.

**Comment by aroozzak** [comment]
have you tried check to check upload_max_filesize in your php.ini  ?
