### ISSUE TITLE
NotReadableException Unable to read image from file on live server

### ISSUE THREAD

**Issue by chizzycrusty** [Intervention/image#749]
Hi, I'm not able to upload any image on my live server as I always get this error:

> NotReadableException
Unable to read image from file

I'm using gd driver and everything is working well on local.
Here is my code for the upload on a post:

```
$image = $request->file('image');

if($image)
        {
            Image::configure(array('driver' => 'gd'));

            $filename  = $user->role . '-' . $user->id . '-' . time() . '.jpg';

            $path = public_path('uploads/posts/' . $filename);

            $filepath = 'uploads/posts/' . $filename;

            Image::make($image)->resize(800, 600, function ($constraint) {
                $constraint->aspectRatio();
            })->save($path);

            $post->image = $filepath;
        }
```

I tried changing to imagick driver but I always get a timeout when I try to upload an image, tried to change php.ini too but didn't work.

**Comment by olivervogel** [comment]
Sorry, can't debug live server issue.
