### ISSUE TITLE
cannont install

### ISSUE THREAD

**Issue by aveshnaik007** [Intervention/image#754]
Can't install with laravel 5.4.27 

![error](https://user-images.githubusercontent.com/12998604/27789537-a635565c-600a-11e7-989d-205c297b4bd3.jpg)

**Comment by dhensby** [comment]
I'm not sure that's got anything to do with this module as it's not got any explicit laravel dependencies.

It looks like there's a version mismatch with your framework vs events requirements. Either be less strict with your dependency requirements (use `~` infront of the version numbers) or try to use the `--no-update` flag with your require call.

You can double check if this is an issue with this module by seeing if a `composer update` executes successfully without making any changes

**Comment by olivervogel** [comment]
I think this is a local issue and has nothing to do with Intervention Image itself.
