### ISSUE TITLE
PNG Corrupt with libgd3 (GD v-2.2.4-2)

### ISSUE THREAD

**Issue by Stunext** [Intervention/image#756]
Recently I updated my ubuntu server and one of the packages updated was libgd; since then, all png images that I encode to jpg are corrupted with glitches in the transparent part of the images, I had to switch to imagemagick to solve the problem.

Original file:
![student](https://user-images.githubusercontent.com/11985549/28127746-9f32e1ec-66fb-11e7-827b-491f6835679e.png)

Corrupted file:
![imagen_corrupta](https://user-images.githubusercontent.com/11985549/28127915-0a340e1c-66fc-11e7-8a02-e6f75bea2e31.jpg)

Same with all png files I've tried.

**Comment by mikzero** [comment]
Same thing to me too, to fix the problem I set the drives on imagick.
`Array ('driver' => 'imagick')`
Now works.

**Comment by snapey** [comment]
I have the same issue.  Works fine locally. On Ubuntu server, PNG image has corrupted background when converted to jpg.
