### ISSUE TITLE
Exif info ignored when loading from stream

### ISSUE THREAD

**Issue by eduardoarandah** [Intervention/image#764]
When using Image:make() with a stream instead of a file path, exif info is ignored. 

This makes orientate() impossible, some images appear with wrong rotation.

This is an example in Laravel 5.4. 
The second example loads image with the Storage facade 

```
// this works OK
$img = Image::make($file_path_here);   
print_r($img->exif());

```

```
// this doesn't work
$img = Image::make(Storage::disk('local')->get('example.jpg'));   
print_r($img->exif());
```

**Comment by Petah** [comment]
I am having the same issue with URLs.
