### ISSUE TITLE
Does this work with text font

### ISSUE THREAD

**Issue by zanjs** [Intervention/image#765]
## driver use imagickis not work

```php
 $img->text('你好', 100, 100, function($font) {
        $font->file('ab.ttf');
        $font->size(76);
        $font->color('#000');
        $font->align('center');
    });
```

![font](https://user-images.githubusercontent.com/12947276/29358426-98b10fa6-82ad-11e7-98d9-f091c9513489.png)

## driver use gd is ok 

![font2](https://user-images.githubusercontent.com/12947276/29359628-ff99f080-82b1-11e7-8b1e-c1009e5161ba.png)

**Comment by zotopteam** [comment]
我遇到同样的情况，但是我发现是字体的缘故，换了个字体就ok了
