### ISSUE TITLE
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data

### ISSUE THREAD

**Issue by saeedvz** [Intervention/image#766]
I got this error some times and i don't know why this error happens.

Full error message 

`exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data
' in /home/project/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:28
Stack trace:
#0 {main}`

can any one help me about this problem?

**Comment by saeedvaziry** [comment]
any solution?

**Comment by moppo24** [comment]
@saeedvaziry : have you found a solution to this problem ?

**Comment by saeedvaziry** [comment]
@moppo24 Unfortunately no :-(

**Comment by olivervogel** [comment]
Might be a bug in PHP 7. See: https://bugs.php.net/bug.php?id=73986
