### ISSUE TITLE
Laravel 4 version?

### ISSUE THREAD

**Issue by danwoodbury** [Intervention/image#769]
I am currently working on an old project and trying to use this package but I am getting the error `Call to undefined function Intervention\Image\config()` at `vendor/intervention/imagecache/src/Intervention/Image/ImageCache.php:72`

I am assuming this is a version issue but which version should I be using for Laravel 4? 

Thanks

**Comment by laravelish** [comment]
why not upgrading to laravel 5.*

**Comment by huglester** [comment]
why not use 1.6 branch? 
https://github.com/Intervention/image/tree/1.6
