### ISSUE TITLE
[5.5] Alias of 'image' conflict

### ISSUE THREAD

**Issue by lucasff** [Intervention/image#770]
We have an alias in our `config/app.php` for our `Image` model.
Intervention tries to set an alias with the same name and we have problems.
For some reason, on Laravel 5.4 application alias was overriding the set one through the ServiceProvider.

**Comment by dels07** [comment]
You can change your alias to another (ex: Intervention) in config/app.php, and update your code to use Intervention instead of Image (I also have Image as model)

**Comment by lucasff** [comment]
@dels07 that's exactly why I'm doing, but somehow the provider now overwrite my custom config, meaning that my model Image is broken everywhere.

**Comment by ce-brex** [comment]
Laravel 5.5 uses auto-discovery to add servoce providers and aliases.  I think the auto-discovery of the Image alias in Intervention's composer.json is causing this.  In your composer.json, you can add the following to disable auto-discovery for Intervention (you will have to manually add the service provider for Intervention.

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "intervention/image"
        ]
    }
},
````

See https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518 for some more info.
