### ISSUE TITLE
laravel 5.5 use it error Internal GD font () not available. Use only 1-5.

### ISSUE THREAD

**Issue by ForceLorda** [Intervention/image#771]
i composer mews/captcha and it requires Intervention/image.

formerly i used it normal,but today i study laravel5.5,when i composer it,and error haappend

Intervention \ Image \ Exception \ NotSupportedException
Internal GD font () not available. Use only 1-5.

1 dont know how to solve it,i google for nothing.
please help me!!

**Comment by echolevan** [comment]
问题原因：laravel 5.5 中 Filesystem::files 不再返回绝对路径。 
目前解决方案：
# vendor/mews/captcha/src/Captcha.php 218 行添加代码：
$this->fonts = array_map(function($file) {
    return $file->getPathname();
}, $this->fonts);

**Comment by qloog** [comment]
@echolevan  👍
