### ISSUE TITLE
Intervention Cache uses file storage instead of Redis [Lumen 5.5]

### ISSUE THREAD

**Issue by Drakota** [Intervention/image#774]
Hi, I've set Redis in my .env like this
```
CACHE_DRIVER=redis
```
And call the Image Cache like this
```
$img = Image::cache(function($image) use ($upload) {
    $image->make($upload->image);
});
return Image::make($img)->response('jpg');
```
But for some reason, the image still gets cached in Vendor/Intervention/imagecache/storage/cache. Why?

Thanks for helping.

**Comment by kfeng0806** [comment]
I am also facing this problem, any solution?
