### ISSUE TITLE
Laravel 5.2 : Upload multiple image

### ISSUE THREAD

**Issue by johnef** [Intervention/image#780]
I am using intervention/image 2.4 with laravel 5.2 I need to upload multiple image and resize them

Here is what I try

```
if ( $request->hasFile( 'gImg' ) ) {
            $gImgs = $request->gImg;
            foreach ( $gImgs as $gImg ) {

                $filename = time() . '.' . $gImg->getClientOriginalExtension();
                Image::make( $gImg )->resize( 1890, 1358 )->save( 'images/decoration/' . $filename );
                Image::make( $gImg )->fit( 646, 250 )->save( 'images/decoration/thumbs-' . $filename );
                $dcoImg                = new DecorationGallery();
                $dcoImg->image         = $filename;
                $dcoImg->decoration_id = $insertedId;
                $dcoImg->save();
            }
        }
```

I was able to upload and resize my images but **Got duplicated images** say I am uploading this three images 0.png, 1.png, 2.png

but this is how the images inserted in database

```
id=>1 -- 0.png
id=>2 -- 0.png
id=>3 -- 1.png
```

so the id for each image inserted in the database correct but the image name it self gets duplicated

can anybody help please

**Comment by Metrevelli** [comment]
This happens because you use time() method to name a file and maybe it uploads two images in a same time... try to declare variable and increase it each time in foreach loop and use it instead of time() or just add it to time(). It should fix a problem.
