### ISSUE TITLE
Allow encoding of progressive JPGs

### ISSUE THREAD

**Issue by cviebrock** [Intervention/image#782]
I'm guessing this is more of a limitation of what Imagick can do, but I was reading these articles:

* https://cloudinary.com/blog/progressive_jpegs_and_green_martians
* https://hodapple.com/blag/posts/2011-11-24-obscure-features-of-jpeg.html

and am wondering if this package could allow me to specifiy a custom scan script for encoding a progressive JPG?

**Comment by olivervogel** [comment]
Encoding of progressive Jpeg images is supported as of version `3.6.0`.

See documenation:
https://image.intervention.io/v3/basics/image-output#encoding-jpeg-format
