### ISSUE TITLE
how to save text on image in laravel 5.5

### ISSUE THREAD

**Issue by robertnicjoo** [Intervention/image#783]
Hello,

I have issue to get text on images while upload, this is my store function to save image how should i call text method in this?

```
if ($request->hasFile('image')) {
        $image = $request->file('image');
        $filename = 'food' . '-' . time() . '.' . $image->getClientOriginalExtension();
        $location = public_path('images/');
        $request->file('image')->move($location, $filename);

        $food->image = $filename;
      }
```

thanks.

**Comment by robertnicjoo** [comment]
anyone?

**Comment by matthib** [comment]
Well, I guess if you have registered the `Image` facade in Laravel you need to create a new image instance from the stored image file write the text to it and then save it, after you have stored the image.

```
$image = \Image::make($location . $filename);

$image->text('The text');

$image->save($location . $filename);
```
