### ISSUE TITLE
Unable to find file ().

### ISSUE THREAD

**Issue by robertnicjoo** [Intervention/image#787]
Hi,

I'm facing this error in L5.5 `Unable to find file ().` and seems there is no solution for it!
PS: I face this issue only when I try to use resize for my photos otherwise it's working.

I even tried this https://github.com/Intervention/image/issues/773 this no luck.

here is my code:

```php
if ($request->hasFile('image')) {
        $image = $request->file('image');
        $filename = 'food' . '-' . time() . '.' . $image->getClientOriginalExtension();
        $location = public_path('images/');
        Image::make($image)->resize('800','400')->save($location.$filename);

        $food->image = $filename;
      }
```

here is my topic that what ways I tried so far, https://stackoverflow.com/questions/46518596/intervention-image-exception-notreadableexception-unable-to-find-file

any idea?

**Comment by olivervogel** [comment]
What's the content of `$image`?

**Comment by robertnicjoo** [comment]
@olivervogel an image! Jpeg/Jpg/Png

```php
'image' =>'sometimes|image',
```

**Comment by olivervogel** [comment]
Could you `var_dump` the variable and post the content here?

**Comment by vijayrana-me** [comment]
I am facing the same issue. 
`
(1/1) NotReadableException Unable to find file ().
--
`

What are the possible solutions? Any Idea?

**Comment by mandrysn** [comment]
any answers pls??

**Comment by mdsabbirweb** [comment]
Try this code 


$location = "assets/images/brand";
$file = $request->image;
$filename =uniqid().time().'.'.$file->getClientOriginalExtension();
$image = Image::make(file_get_contents($file))->resize('600','600')->save($location.'/'.$filename);
