### ISSUE TITLE
Call to undefined function finfo_buffer()

### ISSUE THREAD

**Issue by KikoPalomares** [Intervention/image#79]
I updated by composer and now I get this error:
![capture](https://f.cloud.github.com/assets/6002391/2058347/d38874c0-8b6c-11e3-89b4-9716765a7f27.PNG)
What happened? o:

**Comment by danielfowler** [comment]
I'm also having this issue on my Statamic-built site.

```Fatal error: Call to undefined function Intervention\Image\finfo_buffer() in /home/fowler7/public_html/grco/_app/vendor/Intervention/Image/Image.php on line 1802````

Mac OS X 10.10.1
Statamic 1.9.2
PHP 5.4.35
