### ISSUE TITLE
Command (getRealPath) is not available for driver (Gd)

### ISSUE THREAD

**Issue by loooping-old** [Intervention/image#793]
Hi there,
Laravel 5.4
PHP 7 | With GD

I Try
$resized = Image::make($imagem)->resize(100, 100); 
AND
$resized = Image::make($imagem->getRealPath())->resize(100, 100);

Get this error
Command (getRealPath) is not available for driver (Gd).

**Comment by boyet007** [comment]
any solution for this question?

**Comment by sumonst21** [comment]
@boyet007 take a look the stackoverflow answer: https://stackoverflow.com/a/50900128/5400737
