### ISSUE TITLE
Write text to image inside the borders of the image with a padding

### ISSUE THREAD

**Issue by matboehm** [Intervention/image#794]
I am currently using Laravel 5.5 and I am trying to write to an image while staying inside the boundaries of the image and also applying a certain padding.

![intervention-image](https://user-images.githubusercontent.com/12625174/31850593-1ae44fd0-b655-11e7-840a-39546cf6a6bc.png)

Just like this I would like to write the text into a specified "box" (the red rectangle) inside of the image (the orange rectangle) and make sure it doesn't run outside of this "box".

Is that possible with this library?

**Comment by olivervogel** [comment]
See https://github.com/Intervention/image/issues/143
