### ISSUE TITLE
can't save image

### ISSUE THREAD

**Issue by iMohammadd** [Intervention/image#797]
hi
i have problem with uploading
my code:
```php
if($request->hasFile('logo')) {
            $logo_name = $web->subdomain .'.' . $request->file('logo')->extension();
            $web->logo = $request->file('logo')->storeAs(
                'upload/logo', $logo_name
            );

            $logo = Image::make($request->file('logo'))->resize(256, null, function ($const) {
                $const->aspectRatio();
            })->save('upload/logo/256/'. $logo_name);
        }
```

i get this error

> NotWritableException in Image.php line 143: Can't write image data to path (upload/logo/256/aleki.jpeg)

**Comment by onhernandes** [comment]
Seems like permission problem. Did you check the folder's permission for writing?

**Comment by argb** [comment]
I had the same problem, even I have given  the permission. But I found the reason in the source code. If you don't have the directory(path), you can't save the file to disk.
I change part of the src code like bellow:

`$pathInfo = pathinfo($path);
        $data = $this->encode($pathInfo['extension'], $quality);
        if(!\File::exists($pathInfo['dirname'])){
            \File::makeDirectory($pathInfo['dirname']);
        }`

the original code is 
`/**
     * Saves encoded image in filesystem
     *
     * @param  string  $path
     * @param  integer $quality
     * @return \Intervention\Image\Image
     */
    public function save($path = null, $quality = null)
    {
        $path = is_null($path) ? $this->basePath() : $path;

        if (is_null($path)) {
            throw new Exception\NotWritableException(
                "Can't write to undefined path."
            );
        }

        $data = $this->encode(pathinfo($path, PATHINFO_EXTENSION), $quality);
        $saved = @file_put_contents($path, $data);

        if ($saved === false) {
            throw new Exception\NotWritableException(
                "Can't write image data to path ({$path})"
            );
        }

        // set new file info
        $this->setFileInfoFromPath($path);

        return $this;
    }`
Maybe this is a good suggestion. :)
