### ISSUE TITLE
Driver (and Decoder/Encoder) discarded/ignored at load

### ISSUE THREAD

**Issue by mindplay-dk** [Intervention/image#798]
The Imagick and GD Decoder implementations both discard the current Driver instance at load:

https://github.com/Intervention/image/blob/a54d1e9e6af2815c5ec24972d1d9209c677ce452/src/Intervention/Image/Imagick/Decoder.php#L68

https://github.com/Intervention/image/blob/a54d1e9e6af2815c5ec24972d1d9209c677ce452/src/Intervention/Image/Gd/Decoder.php#L86

Per [this issue](https://github.com/Intervention/image/issues/707), I need to use a custom Decoder - but it turns out, the Driver/Decoder/Encoder instances, which you have to create up-front and inject via the ImageManager constructor, aren't used at all - they simply get discarded (and the whole driver architecture gets reinitialized) every time you load an image.

**Comment by olivervogel** [comment]
This issue should be resolved as of version 3.
