### ISSUE TITLE
Get dominant color

### ISSUE THREAD

**Issue by federico77** [Intervention/image#80]
I know it is a very specific request but I believe it would be a great addition to Intervention: adding a method to find the image dominant color.

There is a great port from the js algorithm here: https://github.com/ksubileau/color-thief-php

I would have forked myself if I was good enough to blend these two tools. :)

**Comment by JackPoint** [comment]
Whats the progress on this?

**Comment by willrowe** [comment]
In the past I've used a function on a filter like the following:
```php
/**
 * Averages the colors in the image.
 * @param  \Intervention\Image\Image $image The source image.
 * @return int The color average.
 */
private function getColorAverage(Image $image)
{
    $image = clone $image;
    // Reduce to single color and then sample
    $color = $image->limitColors(1)->pickColor(0, 0);
    $image->destroy();

    return $color;
}
```

**Comment by JackPoint** [comment]
Thanks, ill try that one!

**Comment by andrefelipe** [comment]
Just sharing, this is a great palette / color extractor library: https://github.com/thephpleague/color-extractor

**Comment by cmnstmntmn** [comment]
@olivervogel any update on this?

**Comment by olivervogel** [comment]
I think something like this is better off in a separate package. Intervention Image is already bloated.
