### ISSUE TITLE
Converting CMYK to RGB, still having profile data after save

### ISSUE THREAD

**Issue by urshofer** [Intervention/image#802]
Uploaded CMYK images (tested with jpeg) will keep their profile, although saved as RGB. This creates large jpeg files.

Example code snippet:

          $image = $manager->make(***sourcefile***);
          $width = 800;
          $height = null;
          $image->resize($width,$height, function ($constraint) {
            $constraint->aspectRatio();
          });
          $image->save(***destinationfile***);

This are the file specs of the original:

<img width="284" alt="bildschirmfoto 2017-11-15 um 11 31 48" src="https://user-images.githubusercontent.com/116976/32831430-97a63496-c9f8-11e7-90ef-cca8ef88c7b7.png">

And here's the scaled version, still having the ISO Coated Profile:

<img width="304" alt="bildschirmfoto 2017-11-15 um 11 32 15" src="https://user-images.githubusercontent.com/116976/32831443-a7773a6e-c9f8-11e7-8f45-4e3faeafc938.png">

In my case, the tiny 350 pixel jpeg file has a size of nearly **2 megabytes**.

Running `PHP 7.1.11` with imagick enabled and `Intervention/Image v. 2.4.1`:

    imagick module => enabled
    imagick module version => 3.4.3
    imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator
    Imagick compiled with ImageMagick version => ImageMagick 6.7.7-10 2016-11-29 Q16 http://www.imagemagick.org
    Imagick using ImageMagick library version => ImageMagick 6.7.7-10 2016-06-01 Q16 http://www.imagemagick.org
    ImageMagick copyright => Copyright (C) 1999-2012 ImageMagick Studio LLC
    ImageMagick release date => 2016-06-01
    ImageMagick number of supported formats:  => 213
    ImageMagick supported formats => 3FR, A, AAI, AI, ART, ARW, AVI, AVS, B, BGR, BGRA, BIE, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FITS, FRACTAL, FTS, G, G3, GIF, GIF87, GRADIENT, GRAY, GROUP4, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, ICB, ICO, ICON, INFO, INLINE, IPL, ISOBRL, J2C, J2K, JBG, JBIG, JNG, JP2, JPC, JPEG, JPG, JPX, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MAT, MATTE, MEF, MIFF, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG24, PNG32, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RGB, RGBA, RGBO, RLA, RLE, SCR, SCT, SFW, SGI, SHTML, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UIL, UYVY, VDA, VICAR, VID, VIFF, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YCbCr, YCbCrA, YUV

**Comment by olivervogel** [comment]
Intervention Image Version 3 supports color profiles with Imagick driver and can remove not wanted color profiles with the [removeProfile() method](https://image.intervention.io/v3/basics/meta-information#color-profiles).
