### ISSUE TITLE
How to use text() add text on image like the position of insert()?

### ISSUE THREAD

**Issue by zotopteam** [Intervention/image#803]
i want to add text on image, it only has  x and y , but i want use like image insert ,use the position

```
    top-left (default)
    top
    top-right
    left
    center
    right
    bottom-left
    bottom
    bottom-right
```

when i use the align && valign

```
$font->align('left');  //left, right or center. 
$font->valign('top');    //top, bottom or middle.
```

but it is set text alignment relative to given basepoint, how to align with the image like the insert()?

Need help,Thanks!

**Comment by jason-engage** [comment]
You don't need to do it this way. Instead use GD to create an image with the text, and then insert the image.

Here's some code that works for me. I'm using Imagick for the main image, but must use GD in order to create the image from text and get the size.

    $font = new \Intervention\Image\Gd\Font(urldecode($data['text_value']));
    $font->valign('top');
    $font->color('#'.$data['text_color']);
    $font->file('./../app/fonts/'.$data['text_font'].'.ttf');
    $font->size($data['text_size']);
    $size = $font->getBoxSize();

    $gdmanager = new ImageManager(array('driver' => 'gd'));

    $image_text = $gdmanager->canvas( $size['width'], $size['height']);

    $font->applyToImage($image_text);

    $text_watermark = $manager->make($image_text->encode('data-url'));
    $image->insert( $text_watermark->response('png'), getPositionName($data['text_position']), $data['text_padding'], $data['text_padding'] ); //this is the main image created earlier using make
