### ISSUE TITLE
I just want to output an image without saving it to server

### ISSUE THREAD

**Issue by jonny77** [Intervention/image#805]
just like a verify code ?

**Comment by TechKat** [comment]
`Image::make($_FILES['file'])->response();`

**Comment by jonny77** [comment]
include_once VENDOR_DIR.'autoload.php';
$manager = new ImageManager(array('driver' => 'gd'));
 $manager->make('./Upload/ofview/thd_f.jpg')->resize(300, 200)->response();
doesn't work at all.

**Comment by TechKat** [comment]
@jonny77 You're using ./ at the beginning. "./" is considered as "current directory".

You should ideally use the full path. /path/to/Upload/ofview/thd_f.jpg

**Comment by jonny77** [comment]
Actually  the image file path is right.  When i use  file_exists('./Upload/ofview/thd_f.jpg') ; it returns  true

**Comment by TechKat** [comment]
Yes, but you're using composer, which uses the vendor folder.

The Image class will be loaded from vendor/intervention/image/src, by doing "./", it will think the image is in vendor/intervention/image/src/./

Try the full path.

**Comment by jonny77** [comment]
Ok,thanks a lot , i will try it again
