### ISSUE TITLE
Rotate a rectangle

### ISSUE THREAD

**Issue by ronan-paul** [Intervention/image#806]
Hello,

I need to draw a rectangle as a background for a text. It works well, but I also need to rotate the rectangle but I can't find a way to do that. 

I searched into the abstractshape class, but there is no method for this. 

Thank you for your help. 

Regards

**Comment by TechKat** [comment]
What's your current code?

**Comment by ronan-paul** [comment]
Here it is:
```php
$image->getImage()->rectangle($this->startX, $this->startY, $this->endX, $this->endY,
    function ($draw ) 
    {
        //background color and transparency
        $draw->background("rgba({$r},{$g},{$b},{$this->background_transparency})");
        //rotation: I wish I could add something like :
        //$draw->rotate($this->angle);
    }
);

```
