### ISSUE TITLE
adding Watermark

### ISSUE THREAD

**Issue by Hredoy** [Intervention/image#808]
How can I Add watermark when uploading

**Comment by vipinkundal** [comment]
You can use following code:

`
$image = Image::make($file->getRealPath());
`	
//if you want to resize your image
`$resized_image = $image->resize(null, 500, function($constraint)
{
$constraint->aspectRatio();
});`
//path for watermark 
`$watermark = Image::make(public_path('images/watermark.png'));
`

and then apply

`			$resized_image->insert($watermark, 'top-right', 10, 10);
`

**Comment by dipenparmar12** [comment]
we can also use inline method chaining 
```
        $image =
            Image::make($file)
                ->insert('waterMark_img.jpg')->save('Watermarked.jpeg')
```

**Comment by Eddys93** [comment]
Can I add this to the source code on my website?
