### ISSUE TITLE
sampling factor

### ISSUE THREAD

**Issue by serverfire** [Intervention/image#811]
hello.
How to apply sampling factor to my images?
convert INPUT.jpg -sampling-factor 4:2:0 -strip [-resize WxH] [-quality N] [-interlace JPEG] [-colorspace Gray/sRGB] OUTPUT.jpg

https://developers.google.com/speed/docs/insights/OptimizeImages

**Comment by bytestream** [comment]
Use imagick driver (https://www.php.net/manual/en/imagick.setsamplingfactors.php):
```php
$im->getCore()->setSamplingFactors(array('2x2', '1x1', '1x1'));
```

`2x2 1x1 1x1` is equivalent to `4:2:0`
