### ISSUE TITLE
aspectRatio don't work on digitalocean sever

### ISSUE THREAD

**Issue by argb** [Intervention/image#813]
`$ret = $image->resize($w, null, function (Constraint $constraint){
                $constraint->upsize();
                $constraint->aspectRatio();
            })->save(getCacheImageStoragePath($name));`
$newW = $ret->getWidth();

When i upload images, the codes above work well in my local computer, but don't work on digitalocean's server, I don't know why.
The new width is right. but the actual image file  saved is not right, the size even don't change.

And I save same image in a new directory, not in the temp uploading directory "/tmp/xxxx" , it also work well.
and even different image work different.
It's really weird problem.

**Comment by drstreet** [comment]
same problem in centos 7 + php 7.1.3 
GD & Imagemagick both ! 
work locally like charm

**Comment by olivervogel** [comment]
Not reproducible.
