### ISSUE TITLE
Doesn't Work With Laravel 5.5

### ISSUE THREAD

**Issue by MIMAXUZ** [Intervention/image#815]
After upgrading/Installing this package doesn't work,
After inputting it to $providers
Intervention\Image\ImageServiceProvider::class
and after run it
  Class 'Intervention\Image\ImageServiceProvider' not found
This bug displayed in Composer.How can I fixed it?

**Comment by alexcroox** [comment]
Same issue, have triple checked I added the alias correctly. No joy

**Comment by patriziotomato** [comment]
Maybe try to:
- Exclude library to perform a dump-autoload first
- Check auto-discovery settings for this library

**Comment by pkeogan** [comment]
You ever figure this out?
