### ISSUE TITLE
Unable to upload large size images

### ISSUE THREAD

**Issue by fazlul3003** [Intervention/image#823]
Hi Guys,

When uploading large size images, the error throws as "`Image source not readable`". This issue only happens for the large images, because I noticed when I tried to load the images from my mobile photo library the error throws, but in the desktop when I tried with medium size images it works fine.

I think the issue is with the mime type is different, when I tried with large images; the mime type shows as "application/octet-stream" , this mime typically contain in the large size images. I need my mobile users to upload their images from the mobile photo gallery, however this problem is driving me crazy.

Any help would be appreciated.

Thanks

**Comment by olivervogel** [comment]
I would like to ask you to update to the current version 3. If the problem still exists, this issue can be reopened.
