### ISSUE TITLE
Can't upload multi page tiff image

### ISSUE THREAD

**Issue by islam-mohammed** [Intervention/image#824]
@Intervention I have installed and enabled imagick on my server and enable it in my project image.php config file instead of gd. the issue happens when I try to upload multi page tiff file. it only upload the first page and excludes other pages!

my code is semple:

```
 $file = request()->file('RemoteFile');
 $img = Image::make(file_get_contents($file));
 $img_path = public_path() . '/storage/ . $file->hashName();
 $img ->save($img_path);
```

how to fix this issue

**Comment by olivervogel** [comment]
Sorry, but Intervention Image is currently limited to handling only the first page of multi-page tiff files. I suggest to use Imagick directly to process these images.
