### ISSUE TITLE
Cannot process large image, server return 500 error

### ISSUE THREAD

**Issue by blu94** [Intervention/image#826]
Inpect the error return empty page, here is my code:
```
$img = Image::make(public_path($name))
        ->resize(320, 240)
        ->save('/assets/', $file->getClientOriginalName());
```

![image](https://user-images.githubusercontent.com/16028996/36145277-d7b53188-10eb-11e8-91a1-e0d3673f7a13.png)
![image](https://user-images.githubusercontent.com/16028996/36145300-eb304d6a-10eb-11e8-8aff-3fa4ba73a930.png)
![image](https://user-images.githubusercontent.com/16028996/36145388-278ae81a-10ec-11e8-9d95-9ec0787475f4.png)

**Comment by umairm638** [comment]
I'm also getting same error. The strange thing is that it's working for 10mb sized image but giving error on 5mb sized image. 

    memory_limit=2048M
    $img = Image::make($originalFilePath);
    $img->resize(intval($width), intval($height), null,
                    function($constraint) {
                        $constraint->aspectRatio();
                    });
     $destinationPath   = public_path('app/photos/thumbnails');
     $photoName         = explode('photos/', $filename);
     $img->save($destinationPath.'/'.$photoName[1]);

Error occurring on Image::make;

**Comment by umairm638** [comment]
Following file is the one which is not uploading.

![aahhaaa](https://user-images.githubusercontent.com/24369007/36248153-4c92e6a4-1258-11e8-87ad-a0c0a446be2b.jpg)

**Comment by umairm638** [comment]
@blu94 have you figured out this issue?

**Comment by blu94** [comment]
@umairm638 i include this code, `ini_set('memory_limit', "2000M");`, enhancing the memory limit using php ways. It work in localhost, but i don't think this code will work on godaddy share hosting.

**Comment by neobie** [comment]
This is real problem. I use another image library with the same Image, and it works fine.

**Comment by SefaDedeoglu** [comment]
> This is real problem. I use another image library with the same Image, and it works fine.

which library?

**Comment by naufalshoeria5** [comment]
> This is real problem. I use another image library with the same Image, and it works fine.

what libraries are you using?

**Comment by neobie** [comment]
Sorry too long to recall. If not mistaken, gumlet php image resizer.

**Comment by sarik-k** [comment]
Increasing memory limit and switching from imagick driver to gd solved it for me.

**Comment by SefaDedeoglu** [comment]
> Increasing memory limit and switching from imagick driver to gd solved it for me.

Sorry too long to recall. Yes its the problem you can increae memory limit and timeout time and it will be fine

**Comment by danielthomascarr** [comment]
Hi, is this error coming up on live server or localhost? You need to increase the limits set in the php.ini file, this worked for me.

php.ini edits needed for server
max_execution_time = 360
max_input_time = 360
memory_limit = 2048M
extension=php_imagick

You can go as much higher but this works for some intense image manipulation that takes 3 minutes or more, also it can be a limit on the server limits so in my case I had to increase the amount of RAM used on Digital Ocean.
