### ISSUE TITLE
encode() is not working

### ISSUE THREAD

**Issue by mavinothkumar** [Intervention/image#831]
Hi 

Am on Laravel 5.5 with image type Imagick, even I have installed libwebp, WebP in my Ubuntu 16.04.

I would like to resize and change the extension of the file, so I made a even and listener to achieve it.
So created a listener HasUploadedImageListener and in handle() 

EventServiceProvider
`ImageWasUploaded::class => [
	        HasUploadedImageListener::class
        ]`

inside the handle()
`		$img = Image::make( $event->path() );
		$img->encode( 'jpg' );
		$img->resize( 720, null, function ( $constraint ) {
			$constraint->aspectRatio();
		} );
		$img->save();`

But its not saving to jpg but its resizing it to 720px. Even I tried to apply the encode into the vendor file ResizeController.php but nothing is working on encode().

Kindly suggestion me how to fix this.

**Comment by EligiusSantori** [comment]
Same problem. Version 2.4.2.

**Comment by livingos** [comment]
Same for me. Using imagick Laravel 5.8.
encode() does not seem to work.

```
$manager = new ImageManager(['driver' => 'imagick']);
$uploadImage = $manager->make($file);
$uploadImage = $uploadImage->encode('jpg', 100);
```

Mime still original such as tiff.

**Comment by andrewwindfall** [comment]
No progress on this huh?

```
$img = Image::make($upload); 
if($img->filesize() > 100000){
  $img->encode('jpg', 5);
}
$img->save($path);
```

Should result in a pretty low quality jpg but saves the same as without encode.

**Comment by davidparedes** [comment]
Same issue here with Laravel 6 and 2.5.1.

**Comment by cplewnia** [comment]
> 
> 
> Hi
> 
> Am on Laravel 5.5 with image type Imagick, even I have installed libwebp, WebP in my Ubuntu 16.04.
> 
> I would like to resize and change the extension of the file, so I made a even and listener to achieve it.
> So created a listener HasUploadedImageListener and in handle()
> 
> EventServiceProvider
> `ImageWasUploaded::class => [ HasUploadedImageListener::class ]`
> 
> inside the handle()
> ` $img = Image::make( $event->path() ); $img->encode( 'jpg' ); $img->resize( 720, null, function ( $constraint ) { $constraint->aspectRatio(); } ); $img->save();`
> 
> But its not saving to jpg but its resizing it to 720px. Even I tried to apply the encode into the vendor file ResizeController.php but nothing is working on encode().
> 
> Kindly suggestion me how to fix this.

I think the issue is that you actually do not save the encoded but the original image.

This should work:

```php
img = Image::make( $event->path() ); 
$encodedImage = $img->encode( 'jpg' ); 
$encodedImage->resize( 720, null, function ( $constraint ) { $constraint->aspectRatio(); } ); 
$encodedImage->save();
```

**Comment by garcons** [comment]
Same issue. Version 2.5.1 with Laravel 7.24.0.

I tryed bellow code and this worked.

```
$img = Image::make(storage_path("app/xxxxx.jpg"));
$img->save(storage_path("app/xxxxx.jpg"), 20);
```

The quality option of `encode()` was not work...

**Comment by kythuatwebso** [comment]
Same issue.

PHP code use this package
`
"name": "intervention/image",
"version": "2.5.1",
`

**Comment by salmanrajz** [comment]
still, issue? damn anyone, any luck?

**Comment by rlucan** [comment]
works without saving:
`$img = Image::make('some image');`
`Image::make((string)$img->encode('jpg', 75));`

**Comment by olivervogel** [comment]
This issue should be resolved as of version 3.
