### ISSUE TITLE
Add Support for libvips

### ISSUE THREAD

**Issue by johnvoncolln** [Intervention/image#836]
When processing files for avatars, iMagick is usually ok.  But for doing anything with large files, vips is superior in processing time and memory.

For instance, I have a need to retrieve resolution and image size from images.  for large images, imagick can take up to 20 seconds!  vips was milliseconds.  And then if you want to do anything like cropping or resizing, imagick has to be instantiated yet again!

**Comment by jarodium** [comment]
Similar thread #615 was started. A binding for php is out, but Intervention has yet to pick it up. Hopefully to a v3? xD

**Comment by johnvoncolln** [comment]
I've switched from Imagick to LibVips and it's really amazing the performance difference...

**Comment by jarodium** [comment]
Is there any news about integrating libvips into Intervention?

**Comment by vedmant** [comment]
Any plans to integrate libvips?

**Comment by christopherdarling** [comment]
+1 for vips integration

Not used the project yet, but found a project that has made a on this; https://github.com/osiemsiedem/intervention-image-vips-driver

**Comment by jarodium** [comment]
@christopherdarling yes but the project still hasn't implemented all commands. From what I've tested myself is working great.

**Comment by Lustmored** [comment]
Hi,

I have taken this under my radar and spent some time to implement missing commands. You can see the result in my fork:

https://github.com/Lustmored/intervention-image-vips-driver

I hope to get it merged into main package and then pursue upstreaming into intervention if there will be interest for that.

Any feedback would be very welcome :)

**Comment by timgws** [comment]
@Lustmored the fork looks fantastic. Have you been able to hit up @osiemsiedem to see if your changes could be merged into his original package?

I just had a quick look, and it appears that you have implemented many of the functions that he was waiting to complete.

Ping @olivervogel. Is it possible to have a look and see if there is anything missing that would stop this driver from being merged upstream? I am more then happy to help work on the code to get it merged in.

**Comment by Lustmored** [comment]
@timgws to be honest osiemsiedem wasn't very cooperative and expressed doubt in whole intervention library. I have indeed implemented all missing methods, but failed to implement drawing text in a nice way. It works, but results are kinda ugly and the code too. See for yourself:

https://github.com/osiemsiedem/intervention-image-vips-driver/pull/14

With this attitude and problems with implementing drawing text (which makes it unusable for me) I lost interest.

But if someone would like to help with drawing text I can commit some more time to this and migrate code from library to PR here. But surely I won't have time to fight with text problem again in foreseeable future.

**Comment by Lustmored** [comment]
> I'm happy to have a look and see what I can do to get the text looking a bit better.
> 
> To get a bit more of an idea, what version of the vips library and it's dependancies did you have installed? I have seen some issues rendering fonts with older versions of pango, which might have caused the problems you saw with php-fpm?

It was probably 8.10.0 at the time, installed from one of Gentoo overlays, so it's hard to tell what dependency versions were at the time.
