### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by mmergenthaler95** [Intervention/image#838]
Hi Guys, 

I'm not totaly sure if this is the right place for my Issue but really need some help with this package. 
Allways I tried to install the package I got following errors.

```

> Using version ^2.4 for intervention/image
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package fideloper/proxy (locked at 3.3.4, required as ~4.0) is satisfiable by fideloper/proxy[3.3.4] but these conflict with your requirements or minimum-stability.
>   Problem 2
>     - The requested package laravel/framework (locked at v5.5.21, required as 5.6.*) is satisfiable by laravel/framework[v5.5.21] but these conflict with your requirements or minimum-stability.
>   Problem 3
>     - laravelnews/laravel-twbs4 1.1.0 requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9] but these conflict with your requirements or minimum-stability.
>     - laravelnews/laravel-twbs4 1.1.0 requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9] but these conflict with your requirements or minimum-stability.
>     - laravelnews/laravel-twbs4 1.1.0 requires laravel/framework ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9] but these conflict with your requirements or minimum-stability.
>     - Installation request for laravelnews/laravel-twbs4 (locked at 1.1.0, required as ^1.1) -> satisfiable by laravelnews/laravel-twbs4[1.1.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content. 

```

That started since I've Updated to Laravel 5.6 before it worked excelent.
Can you help me please?

**Comment by roennow** [comment]
This is not because of the intervention package but as it says three different packages.

As it says in the upgrade guide for laravel change laravel/framework to 5.6.* and fideloper/proxy to ~4.0

And finally the laravelnews/laravel-twbs4 package doesn't support 5.6

**Comment by mmergenthaler95** [comment]
Actually I thaugt I've done this already. Now I've removed the complete node_modules Folder and reinstalled with the npm install command. This is my package.json
`
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.18",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-mobx": "^1.0.2",
    "babel-preset-stage-1": "^6.24.1",
    "bootstrap": "^4.0.0",
    "browser-sync": "^2.23.6",
    "browser-sync-webpack-plugin": "^2.0.1",
    "cross-env": "^5.1.4",
    "jquery": "^3.3.1",
    "laravel-mix": "^2.0.0",
    "lodash": "^4.17.5",
    "popper.js": "^1.14.0",
    "vue": "^2.5.15"
  },
  "dependencies": {
    "ajv-keywords": "^3.1.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "chart.js": "^2.7.2",
    "element-ui": "^2.2.1",
    "imagemagick": "^0.1.3",
    "mobx": "^4.0.0",
    "vue-lazyload": "^1.2.2",
    "vue-mobx": "^2.0.0",
    "vue-social-sharing": "^2.3.3",
    "vue-stash": "^2.0.1-beta",
    "vue-youtube-embed": "^2.1.3",
    "vuex": "^3.0.1",
    "vuex-forms": "0.0.7",
    "vuex-map-fields": "^1.1.2"
  }
}

`

and this is my composer.json

`
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0.0",
        "barryvdh/laravel-dompdf": "^0.8.1",
        "fideloper/proxy": "~4.0",
        "intervention/image": "^2.4.1",
        "laravel-notification-channels/facebook": "^0.0.1",
        "laravel-notification-channels/facebook-poster": "^1.1",
        "laravel-notification-channels/smsapi": "^0.3.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4.0",
        "maatwebsite/excel": "~2.1.0",
        "nesbot/carbon": "^1.22",
        "yajra/laravel-datatables": "1.0",
        "yajra/laravel-datatables-oracle": "~8.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
`

Does anyone see any mistakes ?
