### ISSUE TITLE
Resize image fail for some images

### ISSUE THREAD

**Issue by angde1990** [Intervention/image#841]
Hi,

I encountered a problem during resizing image where some images pass while some fail. My code are as below:

```
Image::make($image)
->resize(720, null, function($constraint)
{
    $constraint->aspectRatio();
    $constraint->upsize();
})            
->stream('jpg', 90);
```
I got the error Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method GuzzleHttp\Psr7\Stream::resize()

The failed image:
![fail7](https://user-images.githubusercontent.com/17272364/38718110-ed1a2104-3f1d-11e8-93bb-f59c2eed4063.jpg)

The passed image:
![pass1](https://user-images.githubusercontent.com/17272364/38718231-96ab3f50-3f1e-11e8-9b4c-a977c0c039fe.jpg)

Both images are taken using Samsung Galaxy S7 Edge

Laravel v5.5.31
Intervention Image 2.4.1
PHP 7.3.0-dev
GD version 2.1.0

**Comment by lakshmana** [comment]
hi, did you solve your problem? I also have similar problem.

thx

**Comment by angde1990** [comment]
I managed to resize the image if only I lower the size of the image or by setting a lower image quality. 

Weirdly this error is more likely to happens if the image is high in contrast.
