### ISSUE TITLE
Unable to init from given binary data.

### ISSUE THREAD

**Issue by REPTILEHAUS** [Intervention/image#842]
Not sure what the issue is but ive noticed a new site  is throwing this error on image uploads.

running nginx/1.13.3,  php fpm 7.2.3 and gd bundled (2.1.0 compatible)

running in a docker container if that matters

**Comment by vinayak25** [comment]
@ricardotulio I am also facing the same issue.

**Comment by panickz** [comment]
@ricardotulio Tambem aqui :P

**Comment by adriandrozdz** [comment]
I am also facing this.

I am uploading images as DataUrl base64 encoded and most images work fine but when I imported images from my iPhone to my MacbookPro and chose an image made with iPhone it generates this error. 

The strange thing is that I am able to encode and decode the same image using codebeautify.org and when I convert the image to base64 the site gives me the same result which I am trying to use to make an image using `Image::make()` - I hope you understand 

I am using Laradock as my local env with PHP71, GD and ImageMagic enabled as well as php exif extension.

**Comment by tsangaris** [comment]
Same issue here..

**Comment by jasperf** [comment]
I used 
```
###########################################################################
# GD Library:
###########################################################################
USER root

ARG INSTALL_GD=false

RUN if [ ${INSTALL_GD} = true ]; then \
    apt-get update && apt-get install -y \
		       libfreetype6-dev \
		       libjpeg62-turbo-dev \
		       libpng-dev \
	  && docker-php-ext-install -j$(nproc) iconv \
	  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	  && docker-php-ext-install -j$(nproc) gd \
;fi
```

as discussed at https://github.com/laradock/laradock/issues/1969 and I do see GD enabled with GIF, PNG and JPG:

![screen shot 2019-01-28 at 10 03 08 am](https://user-images.githubusercontent.com/344138/51812401-eec02080-22e3-11e9-827d-9f0254a352c8.png)
 but when I add gd as option in `config/image.php` uploading does not work.

**Comment by HSPDev** [comment]
I'm running PHP-FPM version `7.4` in Docker.
We were too facing this issue, in 2021, and @ricardotulio led me the right way.

However, you'll get an error on `7.4` using his Dockerfile, because they changed the argument naming.

```
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
```

**_PNG is baked in by default._**
No need to specify paths manually anymore either.

**Comment by olivervogel** [comment]
Here is a working example with support for all image formats from the development environment:

https://github.com/Intervention/image/blob/71bb0e3449bbbfdf47a0d0f2860af7e5e90428e6/Dockerfile#L3-L32
