### ISSUE TITLE
uses too much memory

### ISSUE THREAD

**Issue by nekooee** [Intervention/image#846]
my host limited memory_limit to 256M. and when I upload image 10M get error :

> Fatal error: Allowed memory size of 262144000 bytes exhausted (tried to allocate 5461 bytes) in mysite\vendor\intervention\image\src\Intervention\Image\Gd\Decoder.php on line 136

Unfortunately, it uses too much memory. 
How can I reduce the amount of memory usage?

my code:
 ```
 Image::make($file->getRealPath())
                    ->orientate() //Apply orientation from exif data
                    ->save($new_file_path);
```

**Comment by jarodium** [comment]
You should debug it with images with different sizes and memory. You will find it will work and when it doesn't, the memory trying to be allocated will be different. Image information must be read into memory before any operation is made and another memory allocation should be reserved for calculations of the output. If you try to use imagick you should not be getting memory issues, but it comes down to the image you are using. Using libvips as an optional backend should provide us developers using this lib a faster and memory issues free experience with images.

**Comment by AndisGrossteins** [comment]
There is a great way to avoid this memory exhaustion issue. [This article by Alvaro Trigo describes it and provides a function to allocate memory for image processing with PHP in a smart way](https://alvarotrigo.com/blog/allocate-memory-on-the-fly-PHP-image-resizing/). While the article talks about GD, the only GD function used in the code is `getimagesize()`, so it can be used in most PHP environments.

For completeness' sake, here is my tweaked version of that code I've been using on multiple projects for many years:
```php
/**
 * Dynamically allocate memory based on image dimensions, bit-depth and channels
 * Shamelessly stolen somewhere online years ago.
 * Probably from https://alvarotrigo.com/blog/allocate-memory-on-the-fly-PHP-image-resizing/
 *
 * @param string $filename Full path to a file supported by getimagesize() function
 * @param int $tweak_factor Multiplier for tweaking required memory. 1.8 seems fine. More info: http://php.net/imagecreatefromjpeg#76968
 * @param string $original_name Used purely for reporting actual file name instead of uploaded temp file (e.g. /tmp/RaNd0m.tmp)
 *
 * @return bool true on success or if no memory increase required, false if required memory amount is too large
 */
function setMemoryLimit($filename, $tweak_factor = 1.8, $original_name = null) {

	$maxMemoryUsage = 512 * 1024 * 1024; // 512MB
	$width = 0;
	$height = 0;
	$memory_limit = return_bytes(ini_get('memory_limit'));

	$memory_baseline_usage = memory_get_usage(true);

	// Getting the image info
	$info = @getimagesize($filename);
	if( empty($info) ) {
		throw new Exception( sprintf('ERROR: getimagesize("%s") returned: %s', $filename, print_r($info, true)) );
		return false;
	}

	!empty($original_name) ? $filename = $original_name : $original_name;

	$channels = isset($info['channels']) ? $info['channels'] : 3;
	$width = $info[0];
	$height = $info[1];

	if($info['mime'] == 'image/png') {
		$channels = 4;
	}

	if(!isset($info['bits'])) {
		$info['bits'] = 16;
	}
	$bytes_per_channel = ( ($info['bits'] / 8) * $channels );

	// Calculating the needed memory
	$new_limit = $memory_baseline_usage + ($width * $height * $bytes_per_channel * $tweak_factor + 1048576);

	if( $new_limit <= $memory_limit ) {
		return true;
	}

	/* We don't want to allocate an extremely large amount of memory
	so it's a good practice to define a limit and bail out if new limit is more than that */
	if ($new_limit > $maxMemoryUsage) {
		throw new Exception( sprintf( "Failed increasing memory limit to %dMB (max=%dMB) for file '%s' (%d x %d)", ceil( $new_limit / 1048576 ), ceil( $maxMemoryUsage / 1048576 ), $filename, $width, $height ) );
		return false;
	}

	$new_limit = ceil( $new_limit / 1048576 );

	// Updating the default value
	ini_set('memory_limit', $new_limit.'M');
	return true;
}
```

**Important:** This code should be called _before_ invoking any image processing code that loads the image into memory.

If the function throws an exception, it is safe to assume that the passed image is too big.
I've tested this code using [a specially crafted spark.png](https://www.bamsoftware.com/hacks/deflate.html) which is 225000*225000px and would require more than 47GB of memory to simply allocate its pixels in memory.

**Comment by jarodium** [comment]
I believe it would be best for intervention provide access to another library to edit images. Even allowing more memory to the script there will be performance bottlenecks. If huge amounts of memory are indeed needed, why not use an interface to libvips for example? This way, developers using Intervention can prepare the best handling method by looking at the image size... If GD, ImageMagick and Libvips are there on the system Intervention can ramp up it's game.

**Comment by nekooee** [comment]
@AndisGrossteins  This method only helps us determine the amount of memory dynamically. But the main problem is the impossibility of using large amounts of memory in most hosts. Usually the memory is limited to a maximum of 256MB. With this limit, you can only upload a photo with a maximum size of 2 to 3 MB. I agree with @jarodium . must be use another library.
