### ISSUE TITLE
TIFF loses gps exif data on resize()

### ISSUE THREAD

**Issue by kasparesky** [Intervention/image#849]
Hello,

as title describes, .tiff format images lose their gps exif tags on resize, .jpeg format images don't have this issue.
`$image_exif = $image->exif();` this returns an array with data, including [SectionsFound]["ANY_TAG, IFD0, EXIF, GPS"]
if I run the same line after calling resize(), it returns an array with data, but this time without "EXIF" & "GPS" tags, like so [SectionsFound]["ANY_TAG, IFD0"]

I'm using Imagick driver (ImageMagick 6.8.9-9)

any ideas?

thanks in advance

**Comment by olivervogel** [comment]
This no longer seems to be an issue with version 3.
