### ISSUE TITLE
Encoding format (tmp) is not supported

### ISSUE THREAD

**Issue by Moix1** [Intervention/image#852]
I'm trying to resize my form images in two sizes and got this error: ( Intervention \ Image \ Exception \ NotSupportedException
Encoding format (tmp) is not supported. ) 

And here are my codes (  
//resizing image for thumbnail
           $ModelmainPhoto = Image::make($mainPhoto)->resize(500,650)->save();
           $mainPhoto->move('uploads/models/mainPhoto',$mainPhotoName,$ModelmainPhoto); 

 //resizing image for large format
           $ModelLargemainPhoto = Image::make($mainPhoto)->resize(800,500)->save();
           $mainPhoto->move('uploads/models/mainPhoto',$mainPhotoName,$ModelLargemainPhoto);

)

Thanks

**Comment by blackfyre** [comment]
@Moix1 Did you find a solution in the end?

**Comment by olivervogel** [comment]
This problem should no longer occur in version 3 of Intervention Image.
