### ISSUE TITLE
TextCommand : 4th argument as Font instance.

### ISSUE THREAD

**Issue by CaptainFalcon92** [Intervention/image#855]
Hello 👋  !

I would like to suggest an optimisation of the `->text()` command.
The current usage as of right now :
```php
$image->text($content, $x, $y, function($font){
    $font->file('somefont.ttf');
    $font->size(24);
    $font->color('#fff');
    $font->align('center');
});
```

Currently, 4th arguments `\Closure $callback = null` has to be a Closure.
But, i am doing text writing in a loop and find very suboptimal (and also kinda counter intuitive) to setup a new Font instance for every loop turn.

So i would like to suggest allowing the 4th argument to be a Font instance.

```php
$font = new Intervention\Image\Imagick\Font():
$font->file('somefont.ttf');
$font->size(24);
$font->color('#fff');
$font->align('center');

foreach($whatever as $something) {
    $image->text($content, $x, $y, $font);
}
```

Although it's not required, it would still be a good optimisation to allow both Closure and Font instance.
However, i also think that should be allowed a Callable instead of a closure.
Closure are Callables so you shouldn't have to change much - and it will then allow something like this:
```php
protected function getMyFont($font){
    $font->file('somefont.ttf');
    $font->size(24);
    $font->color('#fff');
    $font->align('center');
}

// [...]
$image->text($content, $x, $y, [$this, 'getMyFont']);
```

Which is i admit only cleaner, but still enhances reusability.

Thank for reading. Have a good one !

**Comment by olivervogel** [comment]
This is possible as of version 3.
