### ISSUE TITLE
Blank page when a file is too large

### ISSUE THREAD

**Issue by mattgreen110** [Intervention/image#86]
I was unaware an image that I was trying to use was 1.4mb. I was using it in a route in Laravel and the page would come up completely blank with no kind of error reporting. Took me a minute to find out. Just FYI.

**Comment by eduardocruz** [comment]
I just got the same error, and landed here. Shouldn't this generate an exception or anything that provides any feedback to the developer? I even tried to catch an exception but it doesn't generate none. And it messes with the application workfflow with no reason.
