### ISSUE TITLE
Problem with fit then upsize an image of 1 pixel

### ISSUE THREAD

**Issue by raiika** [Intervention/image#861]
$image->fit(100, 200, function ($constraint) {
    $constraint->upsize();
});

an image of 1 pixel width and 1 pixel height will not be "fit" and stays square

**Comment by MKiselev** [comment]
@raiika

Why do yo need upsize 1px?

Maybe useful use for you would be create canvas instead image:
```
$background = $this->imageManager->canvas($backgroundWidth, $backgroundHeight, $backgroundColor);
```

For situations when image after fit smaller than needed width, i fix it with `widen()`, for example:
```
$background = $this->imageManager->make($path);
$background->fit($backgroundWidth, $backgroundHeight, function (Constraint $constraint) {
    $constraint->upsize();
});

// If image width smaller than needed width
if ($background->width() < $backgroundWidth) {
    $background->widen($backgroundWidth);
}
```

**Comment by olivervogel** [comment]
The statement `$constraint->upsize()` prevents any enlargement of the image dimensions. I assume that the original size is 1 x 1 pixel. This cannot be exceeded as long as the limit is set.
