### ISSUE TITLE
Get filezise after save() return the original size

### ISSUE THREAD

**Issue by brunoabcn** [Intervention/image#866]
Hi

I read an image:

$img = Image::make(public_path() . '/ft_' . $id . '_' . $images['path']);

The image already exists, then read with no problem, after that, I read his size and give me 378.56:
$size = $img->filesize() / 1000;

Then I want to reduce the quality until the file size is lower from 100 kbytes, I tried this but don't work:

`
while ($size > 100) {
    $img->save(public_path() . '/mr-photos/mr_' . $id . '_' . $images['path'], $quality)->encode('jpg');
    $img->filesize();
                                    dump('size: ' . $size);
                                    if ($size <= 100) {
                                        exit; 
                                    } else {
                                        dump('quality: ' . $quality);
                                        $quality--;
                                    }

                                    if ($quality < 60) {
                                        $size = 100;
                                        exit;
                                    }
                                };
`

The problem is that the $size never change, in the folder the image reduce it's size until have 26kb, but the $size variable never reduce. 

I tried too:
`$img->save(public_path() . '/mr-photos/mr_' . $id . '_' . $images['path'], $quality);
$img = Image::make(public_path() . '/mr-photos/mr_' . $id . '_' . $images['path']);
$size = $img->filesize() / 1000;`

but is wrong, because now the size still the original size but the image is damaged. Then I tried:

`                                    
$img = Image::make(public_path() . '/mr-photos/mr_' . $id . '_' . $images['path']);
$img->save(public_path() . '/mr-photos/mr_' . $id . '_' . $images['path'], $quality);
$size = $img->filesize() / 1000;
$img->destroy();`

Same error, I can't update the size variable and the image is damaged.

I hope you can help me...

Regards
Bruno

**Comment by tinyCoder32** [comment]
I have the same problem, getting the file size after save is returning the original one, even if I opened the file under another variable.

**Comment by jarodium** [comment]
Have you tried to clearstatcache after file save ?

**Comment by brunoabcn** [comment]
I tried almost everything, open with different variable, and everything I try obtain the same error.

**Comment by jarodium** [comment]
I can see some things that might not working.
1- clearstatcache() normally helps since it clears filemtime or filesize operations
2- Have you tried to download the image and validate it for corruption?
3- Have you tried to use php's native filesize functions?
4 - Another variable seems a bad idea if intervention is somehow caching or cloning the file reference ( from what I am reading and it's purely theoretical.)

**Comment by brunoabcn** [comment]
> I can see some things that might not working.
> 1- clearstatcache() normally helps since it clears filemtime or filesize operations
> 2- Have you tried to download the image and validate it for corruption?
> 3- Have you tried to use php's native filesize functions?
> 4 - Another variable seems a bad idea if intervention is somehow caching or cloning the file reference ( from what I am reading and it's purely theoretical.)

1. clearstatcache() tell me Command (clearstatcache) is not available for driver **(Gd)**
2. Yes if I download the image is not corrupted, is fine.
3. Yes I try it and return me the same filesize, the original filesize not the new.
4. Nothing works...

Thanks

**Comment by julienbornstein** [comment]
Same issue, fixed by calling clearstatcache(); after the save()
PHP doc : https://secure.php.net/manual/en/function.clearstatcache.php

```
$im = $manager->make($file_path);
dump([$im->filesize(), filesize($file_path)]);
$size = 200;
$im->resize($size, $size)->save();
clearstatcache();
dump([$im->filesize(), filesize($file_path)]);
```

result : 
```
array:2 [
  0 => 104516
  1 => 104516
]
array:2 [
  0 => 15131
  1 => 15131
]
```
