### ISSUE TITLE
response() does not support caching?

### ISSUE THREAD

**Issue by fzyzcjy** [Intervention/image#867]
Thank you for this wonderful package! I have a small question that, it seems that the `response()` method does not support caching. After examining the source code, I do not find things related to `eTag` or cache-control. Therefore, whenever the user accesses this url, he will *always* need to download the full image... I would appreciate it if the caching feature could be added. If needed, I may be able to make a pull request as well. Thanks!

**Comment by turtlegood** [comment]
Here is the code to support cache control which I use in other places:
https://gist.github.com/turtlegood/c98c73414cd7cd46ee8388e2868984cf

**Comment by olivervogel** [comment]
The integration of the option to build HTTP response was a mistake. The task of this library is image manipulation. Handling HTTP request or responses should be done by a dedicated library. For this reason, Intervention Image Version 3 no longer support `response()`.
