### ISSUE TITLE
Apple iPhone rotation is wrong with orientate

### ISSUE THREAD

**Issue by Chrissi2812** [Intervention/image#868]
I have two images both have a rotation value of **6**.
But the apple image is only orientated right if the exif data is ignored, and i don't perform the orientate. (Exactly the opposite of what is mentioned in #461 and #253)
That seems more like a fragile hack, because I simply check for `Make: Appel`

Is this a known bug or are the exif data corrupt? (example images below)

## Here are the relevant code parts:
```php
private function getImageManager(): ImageManager
{
    $imageManager = ImageManagerStatic::make($this->path);

    // Apple seems to have broken Exif Data
    if ($imageManager->exif('Make') === 'Apple') {
        return $imageManager;
    }
    return $imageManager->orientate();
}


private function _resize($size, $quality = self::quality)
{
    $this->imageManager->resize(
        $size,
        null,
        function (Constraint $constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        }
    );

    $this->imageManager->save($this->thumbPath, $quality);
}
```

## Image taken on iPhone 7
I don't know the exact condition under which this image was taken (I don't have an iPhone myself)
![apple](https://user-images.githubusercontent.com/6141652/43145340-74908a06-8f5f-11e8-9bec-14c59d74e169.jpg)

## Example 6 from [exif-orientation-examples](https://github.com/recurser/exif-orientation-examples)
This should be orientated right.
![example](https://user-images.githubusercontent.com/6141652/43145348-785a33b2-8f5f-11e8-933f-f4ed15588bb2.jpg)

Github seems to ignore Exif data therefore the images are displayed wrong. (Open in new Tab then its correct).

## Here is how Windows 10 displays the images:
But they both should be straight.
![image](https://user-images.githubusercontent.com/6141652/43145474-baa8b7e8-8f5f-11e8-9fbe-6bcd7057362c.png)

**Comment by Chrissi2812** [comment]
As it turns out iOS prior to version 12.X.X (don't know the exact version) seems to save images prerotated and store the rotation also in the exif data. 

As a workaround I currently am using this:

```php
if ($imageManager->exif('Make') === 'Apple' && version_compare($imageManager->exif('Software'), '12.0.0', '<')) {
    return $imageManager;
}
```

**Comment by olivervogel** [comment]
I am closing this issue as it is a bug in an older iOS version.
