### ISSUE TITLE
How can I change the direction of the text() to rtl 

### ISSUE THREAD

**Issue by mohamedshuaau** [Intervention/image#869]
This has been bugging me of how to change the direction to rtl. Is this possible?

**Comment by hossy13** [comment]
hi did u found solution?

**Comment by a-j-n** [comment]
i have the same problem here with Arabic for the position and text encoding

**Comment by armagedan** [comment]
Unfortunately no support still. I had to make my own extension for my language. Unfortunately it won’t work for arabic language as it is very specific to mine. I hope this get added

**Comment by MostafaRabia** [comment]
what about #630 ?
and `$font->align('right');`?

**Comment by olivervogel** [comment]
This library helps to solve this issue.
https://github.com/Johntaa/ar-php
