### ISSUE TITLE
Support SVG format

### ISSUE THREAD

**Issue by nitishrajuprety** [Intervention/image#870]
Recently I tried uploading SVG image on a Laravel project using this package but I got format not supported error. As SVG is starting to be commonly used in many web apps these days, it would be really helpful if the support is added on this package.

**Comment by olivervogel** [comment]
SVG is a difficult subject. Intervention Image is based on either the GD library or the Imagick extension. The GD library does not support SVG at all. With Imagick as driver it is possible to process SVG graphics, but I have noticed that this format is often not readable without display errors and is therefore not a reliable solution.

I decided to keep the focus of Intervention Image on pixel-based images for the time being.
