### ISSUE TITLE
Laravel 5.6 Error Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required 

### ISSUE THREAD

**Issue by btechgroup** [Intervention/image#871]
having issue with library

Laravel 5.6
Php 7.2

Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required 

'/var/www/html/v1.1/vendor/intervention/image/src/Intervention/Image/../../config/config.php' (include_path='.:/usr/share/php')

**Comment by owenmcateer** [comment]
I have the same issue. Did you find a fix? @btechgroup

**Comment by zzpwestlife** [comment]
I met the same problem. Did you find the solution?

**Comment by btechgroup** [comment]
> I met the same problem. Did you find the solution?

Please update the intervention library

**Comment by zzpwestlife** [comment]
@btechgroup  thanks.
