### ISSUE TITLE
is_url() not working for utf-8

### ISSUE THREAD

**Issue by kak-smko** [Intervention/image#875]
The FILTER_VALIDATE_URL filter seems to have some trouble validating non-ASCII URLs:
Its not work for url like this: `http://test/uploads/2018/07/تفاهم-نامه--800x450.jpg`

**Comment by olivervogel** [comment]
The integration of the option to read data directly via URLs was a mistake. The task of this library is image manipulation. Reading data via HTTP should be done by a corresponding client. For this reason, Intervention Image Version 3 does not support reading URLs.
