### ISSUE TITLE
Black image issue

### ISSUE THREAD

**Issue by PinalPatel160** [Intervention/image#877]
I've created webp image using image/intervention. It's working perfectly on my local server but it's not working in the live server(ubuntu 160.04). 
But when I try to open that image it shows a blank transparent image with correct Content-Type: image/webp and file-size.

Blank image return like this: https://imgur.com/a/CMx6tsU
I'm using following code to generate webp image from png/jpg:

$path = "path_of_original_png/jpg_image";
$webp_path= "path_to_save_webp_image";
$webp = Image::make($path);
$webp->save($webp_path, 75);

**Comment by widewhale** [comment]
Same issue

**local machine**: 
OSX 10.14
PHP 7.3.2
Imagick 3.4.3 
ImageMagick 7.0.7-35 Q16 x86_64
Image 2.4.2

**Server machine**:
CentOS Linux release 7.6.1810
PHP 7.1.26
Imagick 3.4.3
ImageMagick 6.7.8-9 2016-06-16 Q16
Image 2.4.2

**Comment by Kostyaval** [comment]
@PatelPinal1415160  I have the same issue

**Comment by PatelPinal1415160** [comment]
@Kostyaval I've not found the solution to this problem. So I'm switching to use a "libwebp". I'm using "cwebp" to encode/decode image into WEBP. It's a wonderful tool for WEBP format which is provided by Google.

[Reference link](https://developers.google.com/speed/webp/docs/using)

**Comment by aoderinde** [comment]
I still have the same problem - does anyone know how to fix this?
