### ISSUE TITLE
Missing requirement: ext-mbstring

### ISSUE THREAD

**Issue by willemwollebrants** [Intervention/image#882]
I'm on a fresh vm and I didn't install the mbstring extension yet. 
```bash
Call to undefined function Intervention\Image\mb_convert_case() in [...]/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php:105 
```
The dependency was introduced by PR #837 https://github.com/Intervention/image/commit/e82d274f786e3d4b866a59b173f42e716f0783eb#diff-91971e0c7772a60fab6fbe264d649d99

I think there are 3 options (all of which I'm more than willing to send a PR for :))
- add ext-mbstring as a requirement in composer.json
- check if mbstring is available before using the functions. If it's not available use standard php functions instead
- remove the code that causes the problem (= revert the PR essentially)

**Comment by vlakoff** [comment]
I can't decide between these options either :)

Maybe I'd rule out option 2, as it could introduce some surprises when changing environment.

**Comment by vlakoff** [comment]
I added a commit in my PR that may interest you. I'm using Symfony's [mbstring polyfill](https://github.com/symfony/polyfill-mbstring). This way we have the best of options 1 and 2 combined :)

Also, maybe the mbstring extension is not as widespread as I though, and requiring to recompile the server might irritate some people…

**Comment by olivervogel** [comment]
I decided to add mbstring as dependency for the next release of Version 3.
