### ISSUE TITLE
Access image inside s3 

### ISSUE THREAD

**Issue by ecomunicarte** [Intervention/image#883]
I have opened an issue for the same reason on imagecache repository, sorry for the duplicated, but i don't know which place is the correct one.
The issue is:  #https://github.com/Intervention/imagecache/issues/96

Using the package in Laravel, I need to access to images saved inside s3 cloud storage.

After view this, I have supposed that its possible:

#https://github.com/Intervention/imagecache/pull/89

Which new path I have to define inside imagecache.php config file? There, I have an array with my paths. I usually do and works fine:

url('imagec/medium'.$image_path)

I want be able to do the same with s3 images. What should I do?

Thanks in advance

**Comment by fixytech** [comment]
@ecomunicarte have you found any solution?

**Comment by dejavuejs** [comment]
why ain't this merged?
