### ISSUE TITLE
How to set background color for cropping outside the boundaries of the image?

### ISSUE THREAD

**Issue by wcactus** [Intervention/image#884]
Hello!
When I am using `crop` method with negative X and Y values I get an image with black areas at the left and top edges. I got the same effect for a number of JPEG and PNG images – background color is always black. Is it possible to set background color for cases when cropping area goes beyond the boundaries of the image?

**Comment by Cholowao** [comment]
I would create an empty "base image" with a background-color and insert the other image into this.
```
Image::canvas(100,100, '#b53717')->insert($img)->save('foo.jpg');```

**Comment by olivervogel** [comment]
This will be fixed in https://github.com/Intervention/image/pull/1254/commits/6308afbd3e3af910980efcb4c2d4f8f718f0fdf1 in Version 3.3 of Intervention Image.

Newly created areas of the modifier are then displayed in the blending color. This color can be specified in advance and is white by default.

```php
$image = ImageManager::gd()
    ->read('example.jpg')
    ->setBlendingColor('ff5500')
    ->crop(200, 900, 0, 0, 'top-center');
```
