### ISSUE TITLE
Filename gets dublicated and concatenated when having multiple files upload in Laravel

### ISSUE THREAD

**Issue by fredemagi** [Intervention/image#885]
When I try to upload multiple images using Laravel and Intervention, I face a rather annoying issue;

File 1 will be named test1.jpg, file 2 will be named test1.jpgtest2.jpg, etc.

I don't know why this is happening. My code is as follows:
```

foreach($request->images as $image)
        {
            $filename = str_random(40).".jpg";
            $file = Image::make($image)
                   ->orientate()
                   ->resize(800, null, function ($constraint) 
                   {
                        $constraint->aspectRatio();
                        $constraint->upsize();
                   })->save($path.=$filename); 

            //Insert image path into db.
            ModelImage::create(
                [
                    'filename' => $filename,
                    'user_id' => Auth::user()->id
                ]);
        }
```

In advance, thank you.

**Comment by websiteproduct** [comment]
@fredemagi Hello,
Check your input file name, is it `name="images[]"`?

**Comment by fredemagi** [comment]
Can't get it to work. I even tried with 
`$filename = null;`

and 
`$file->destroy();`.

Maybe a bug in the library?

**Comment by fredemagi** [comment]
Oka, by bad. The issue was the `$path.=$filename`, as I forgot to reset the path for each iteration.
