### ISSUE TITLE
HEIC formatt file is not supported

### ISSUE THREAD

**Issue by anil-kumar-pal** [Intervention/image#891]
It's throwing an exception:`NotSupportedException Encoding format (HEIC) is not supported`
When I tried to upload image file with format .heic

**Comment by Kryptonit3** [comment]
Any update on this yet?

**Comment by zachu90** [comment]
Any update on this ?

**Comment by tomswinkels** [comment]
?

**Comment by ambroisemaupate** [comment]
I’m testing HEIC and AVIF file format encoding (for converting from jpg/png to next-gen formats):

https://github.com/ambroisemaupate/image/commit/668b24e7e6d51bbb9498528a49cd18aba9ec660b

This requires to compile ImageMagick with AVIF and HEIC, which requires libheic… which requires [libaom](https://aomedia.googlesource.com/aom/), [libavif](https://github.com/AOMediaCodec/libavif/blob/master/.travis.yml), nasm, libde265… that’s not out-of-the-box for the moment :smile: 

Here is a great Dockerfile with all steps to compile Imagemagick on your local machine: https://github.com/dooman87/imagemagick-docker/blob/master/Dockerfile.buster

I won’t even try with GD.

I’ll submit a PR if I come to an interesting point.

**Comment by mfn** [comment]
> This requires to compile ImageMagick with AVIF and HEIC, which requires libheic… which requires [libaom](https://aomedia.googlesource.com/aom/), [libavif](https://github.com/AOMediaCodec/libavif/blob/master/.travis.yml), nasm, libde265… that’s not out-of-the-box for the moment 😄

Down the rabbit hole!

Wow! Thanks for the heads up and the details, much appreciated 🙇
