### ISSUE TITLE
Setting pixels to transparent

### ISSUE THREAD

**Issue by DieGeduld** [Intervention/image#896]
Is there a possibility to remove all pixeldata from an image and set them to transparent?

For Example we have an image with the dimensions 200x200 and I want to remove all pixels of the top left corner and set them to transparent.

The draw method doesn't work:

`$image->rectangle(0, 0, 100, 100, function ($draw) {
$draw->background([0,0,0,0]);
});`

Neither does the fill method:

`$image->fill([0,0,0,0], 100, 100);`

**Comment by olivervogel** [comment]
This is currently not possible. All colors applied to the image are calculated on all color channels relative to the existing values. Unfortunately, it is currently not possible to change a color channel directly.

The only way I can see is to use the `mask()` function of version 2 if Intervention Image and apply the alpha channel information to the image.
