### ISSUE TITLE
The Problem of resize and crop

### ISSUE THREAD

**Issue by varanty** [Intervention/image#897]
(PHP7.2 with extension GD2  Laravel5.6)
When I use resize  and crop Sometime hava a problem like the attach image.
sometime top  sometime bottom sometime right sometime left
![20180926103315](https://user-images.githubusercontent.com/40297343/46053974-a2b77080-c177-11e8-811c-a2ba5052c5b2.png)

**Comment by raiika** [comment]
Is your cropper (x,y,w,h) from front end give you good params ?
