### ISSUE TITLE
resize with respect to aspect ration

### ISSUE THREAD

**Issue by amirgee007** [Intervention/image#901]
Let's say a user uploads a file that is 3000x1500. I don't know the exact sizes we said for thumb/medium/large but let's say max 100 / 400 / 900.

In the case of an original being 3000x1500 the large should not be 900x900 but 900x450. Currently, i am resizing 900x900 so that is not good. The images get "sqeezed" and look weird. Now, as well lose the aspect ratios.

is there a way to resize dynamically depending upon image height width.

right now I m resizing 900*900
but when the image is 3000x1500 and I save it 900*900 it look like weird.

**Comment by raiika** [comment]
Do you know whag fit() does ?

**Comment by ITwrx** [comment]
@amirgee007 what i did was just compare width and height to determine orientation and base my manipulation on that.

```
$height = Image::make($image_file)->height();
$width = Image::make($image_file)->width();
```

**Comment by rafi73** [comment]
`$callback = function ($constraint) { $constraint->upsize(); };
        $imageResize->widen(1000, $callback)->heighten(1000, $callback);`
