### ISSUE TITLE
isUrl() in AbstractDecoder fails valid URLS

### ISSUE THREAD

**Issue by StyxOfDynamite** [Intervention/image#904]
Due to a PHP Bug, https://bugs.php.net/bug.php?id=64948

This check means you cannot instantiate an image from valid URL (that contains underscores in the hostname).

I realise this isn't a bug for you guys to fix, but wanted to draw attention to it as it could be the root cause of some problems where you throw the below for seemingly *valid* image URL's

```
throw new Exception\NotReadableException("Image source not readable");
```

**Comment by olivervogel** [comment]
The integration of the option to read data directly via URLs was a mistake. The task of this library is image manipulation. Reading data via HTTP should be done by a corresponding client. For this reason, Intervention Image Version 3 does not support reading URLs.
