### ISSUE TITLE
orientate() doesn't work with iPhone pictures?

### ISSUE THREAD

**Issue by Hillcow** [Intervention/image#906]
What I do:

```
Image::make($request->get('image'))
                        ->orientate()
                        ->resize(1920, null, function ($constraint) {
                            $constraint->aspectRatio();
                            $constraint->upsize();
                        })
                        ->save($img_path = public_path('img/posts/imgposts/' . $fileName), 90);
```

Unfortunately images from iPhones for example do not rotate properly. Upright images end up being landscape. I attached the image I am using for testing.

![img_2690](https://user-images.githubusercontent.com/20979750/47215208-e5e4b800-d3a0-11e8-9211-e04f20466cea.jpg)

Edit: Wow, github doesn't handle the picture properly either.

**Comment by Hillcow** [comment]
Thank you, but I use Laravel. I thought there must be a way to properly detect the orientation of an image?

**Comment by alfredobarron** [comment]
I have the same problem, any suggestion to solve?

**Comment by Chrissi2812** [comment]
I have a similar issue #868.

**Comment by bilalgodesto** [comment]
Any update on this issue?

**Comment by wvffle** [comment]
In my case, orientate worked well and `img` tags were okay but css background was not. Even if it was the same image. I removed EXIF tags before saving as in this comment https://github.com/Intervention/image/issues/542#issuecomment-219232968 and it works now

**Comment by FrittenKeeZ** [comment]
Using `setFileInfoFromPath($url)` (as mentioned in https://github.com/Intervention/image/issues/343#issuecomment-540485694) makes `orientate()` work correctly as well.

**Comment by Hillcow** [comment]
@FrittenKeeZ this works. Case closed.
