### ISSUE TITLE
Exif Command throws exception on PNG image

### ISSUE THREAD

**Issue by ivanrey** [Intervention/image#917]
When Exif Command tries to use exif_read_data with a PNG image in PHP 7.2 an exception is thrown instead of returning false. 

This has changed and is undocumented in PHP 7.2. Before it used to return false, now it throws and exception a thus fails to work with PNG images.

I tried using Imagick driver but it has a preferExtension option at object level that can not be set when using the OrientateCommand.

It would be great to either> be able to disable the preferExtension when calling OrientateCommand, or handle the exception in both drivers.

**Comment by caffeineinc** [comment]
See related pull request. https://github.com/Intervention/image/pull/927
