### ISSUE TITLE
Is it possible to add transparent overlay black shadow over image(tinted image)

### ISSUE THREAD

**Issue by xsaad67** [Intervention/image#922]
Hello thanks for the nice library . I just wanted to know how can I add a transparent black overlay shadow over image like I can do this in GD through this. 

            
```
                $img = imagecreatefromjpeg($toMask);
		$w = imagesx($img);
		$h = imagesy($img);
		imagesavealpha($img, true);
		$img2 = imagecreatetruecolor($w, $h);
		imagefill($img2, 0, 0, imagecolorallocatealpha($img, 86, 69, 1, 40));
		imagecopy($img, $img2, 0, 0, 0, 0, $w, $h);
		imagepng($img, public_path("images/new.png"));
		imagedestroy($img);
		imagedestroy($img2);
```
        

Is it possible in intervention to add transparent overlay shadow for a reference I'm adding CSS overlay shadow 
https://css-tricks.com/tinted-images-multiple-backgrounds/

**Comment by jorbascrumps** [comment]
I'm also interested in knowing if something like this is possible. @xsaad67, did you ever find a solution?

**Comment by xsaad67** [comment]
> I'm also interested in knowing if something like this is possible. @xsaad67, did you ever find a solution?

I used default GD like this 

               ```
$toMask = public_path('assets\img\london.jpg'); //Image you want to add mask
		$img = imagecreatefromjpeg($toMask);
		$w = imagesx($img);
		$h = imagesy($img);
		imagesavealpha($img, true);

		$img2 = imagecreatetruecolor($w, $h);
		imagefill($img2, 0, 0, imagecolorallocatealpha($img, 21, 20, 20, 60)); //Add transparent shadow
                
		imagecopy($img, $img2, 0, 0, 0, 0, $w, $h);

		imagepng($img, public_path("images/new.png"));

		header("Content-type: image/png");
		imagepng($img);
```

**Comment by xsaad67** [comment]
> I'm also interested in knowing if something like this is possible. @xsaad67, did you ever find a solution?

Nothing was find so I used the default GD :)
