### ISSUE TITLE
Different results between GD/ImageMagick for WebP conversion with scale

### ISSUE THREAD

**Issue by kendugu** [Intervention/image#923]
Consider the following source image:

**100x62 PNG with Transparent Background**
![brick - 100 x 62](https://user-images.githubusercontent.com/1407275/51283684-dffd7380-199d-11e9-89af-0db767d6e06f.png)

Doing a conversion to WebP and resizing produces different results in GD vs ImageMagick.

**GD**, resize to 100x100 and convert to WebP (correctly transparent):
![gd](https://user-images.githubusercontent.com/1407275/51283974-c3ae0680-199e-11e9-93b5-39c4e20b07ee.png)

**ImageMagick**, resize to 100x100 and convert to WebP (incorrect background):
![blue-small](https://user-images.githubusercontent.com/1407275/51284675-328c5f00-19a1-11e9-99ba-9254f3689504.png)

The background is actually white but that wouldn't be visible here so I set the default background color to red to illustrate the issue.

I found a solution but I'm not sure of any other consequences. Adding the following line:

```php
        $imagick->setImageBackgroundColor(new \ImagickPixel('transparent'));
```

...before line 81 of this block:

https://github.com/Intervention/image/blob/e82d274f786e3d4b866a59b173f42e716f0783eb/src/Intervention/Image/Imagick/Encoder.php#L80-L86

...produces the correct results for me.

Or see PR #924.

**Comment by olivervogel** [comment]
This issue seems to no longer occur in [version 3](https://image.intervention.io/v3).
