### ISSUE TITLE
Image :: make () can not read some resolutions

### ISSUE THREAD

**Issue by autogestor-miguel** [Intervention/image#928]
I am trying to read this image, 

![dsc_0933](https://user-images.githubusercontent.com/41120116/52588565-ee676f80-2e23-11e9-8ea5-64bacad945b5.jpg)

but it is giving error and does not return any information, dimensions of the image 5884x3923.

ps: when I use the native PHP function "imagecreatefromjpeg" I can create a new image from this

**Comment by msilvapor** [comment]
#655 this might help you
