### ISSUE TITLE
Uncaught Intervention\Image\Exception\NotSupportedException: Driver (GD) could not be instantiated

### ISSUE THREAD

**Issue by subbame** [Intervention/image#929]
GD Library and mbstring are already installed on our VPS Cpanel server but for some reason, I keep getting the following error.

`PHP Fatal error:  Uncaught Intervention\Image\Exception\NotSupportedException: Driver (GD) could not be instantiated. in /intervention/image/src/Intervention/Image/ImageManager.php:113`

GD Support: enabled
GD Version: bundled (2.1.0 compatible)
FreeType Support: enabled
FreeType Linkage: with freetype
FreeType Version: 2.4.11
GIF Read Support: enabled
GIF Create Support: enabled
JPEG Support: enabled
libJPEG Version: 6b
PNG Support: enabled
libPNG Version: 1.5.13
WBMP Support: enabled
XPM Support: enabled
libXpm Version: 30411
XBM Support: enabled
WebP Support: enabled

**Comment by bremg** [comment]
Got the same error. Extension is enabled

**Comment by stefanodalpos** [comment]
same error for me on Ubuntu 20.04

**Comment by olivervogel** [comment]
I suggest to try this with Intervention Image Version 3.

**Comment by Jocasz** [comment]
no idea, same problem
