### ISSUE TITLE
General question performance for a large set of images

### ISSUE THREAD

**Issue by davidbarrington** [Intervention/image#93]
Hello Oliver,

Currently a website I have developed is creating thumbnails for a large amount of images. 
I am investigating whether I can use Intervention behind a CDN such as Cloudfront. With image caching, is it feasible to use this library on a large scale, delivering 1,000,000s images on a busy site?

Many thanks for the great library,
David

**Comment by will666** [comment]
Checking on eventual CDN support, any updates?

**Comment by canfiax** [comment]
Interested in CDN support as well.
