### ISSUE TITLE
Option to add utf-8 characters on image 

### ISSUE THREAD

**Issue by Satendra-SR** [Intervention/image#939]
Can we have an option for utf-8 characters
May be something like **$font->encode('utf-8');**.

```
$img->text('foo', 0, 0, function($font) {
    $font->encode('utf-8');
});
```

Currently, it is not supporting these characters.

I have tested it with following fonts
1. Arial unicode ms
1. Devanagari
1. Noto_Sans

#### All the above fonts supports hindi language

This is the expected result In Indian (Hindi) language.
> इण्टरनेट पर हिन्दी के साधन

This is how it getting rendered
![image](https://user-images.githubusercontent.com/39792899/57011277-7d637700-6c1e-11e9-871f-5ce9a17d1110.png)

**Comment by abhishek-pokhriyal** [comment]
I faced the exact same issue. This is too frustrating and needs an urgent fix. Can anyone tell me what's going on here? Or if this is not the right place where should this be reported?

**Comment by samgan-khan** [comment]
me too facing the same issue, please provide a fix asap

**Comment by samgan-khan** [comment]
It seems like the language is supported but you have to select a font which supports both the languages.

**Comment by huseyinerbayat** [comment]
There are same problem in Turkish characters. For example, it's writing "&Uuml;" instead of 'Ü'

**Comment by huseyinerbayat** [comment]
> There are same problem in Turkish characters. For example, it's writing "Ü" instead of 'Ü'

This problem in my server. It's running in my localhost. Why can be?

**Comment by james090500** [comment]
I am going to +1 this issue. It would be nice to be able to use UTF-8 character.

As you can see I am missing UTF-8 characters below:

Original
![image](https://user-images.githubusercontent.com/20372645/81510974-de338e00-930d-11ea-96fb-e2b614deda48.png)

Using Intervention:
![image](https://user-images.githubusercontent.com/20372645/81510982-e5f33280-930d-11ea-8fee-f3431c7fd674.png)

**Comment by james090500** [comment]
I ended up with sort of a solution. I used `preg_match('/([^\x00-\x7F]+)/u', $msg)` to see if the character was unicode. If it was I used a different font to render. I recommend this font: https://fontlibrary.org/en/font/gnu-unifont

as you can see unicode blocks/symbols are rendering:
![image](https://user-images.githubusercontent.com/20372645/81752121-c3e1e780-94a8-11ea-85e8-432097119e20.png)

![image](https://user-images.githubusercontent.com/20372645/81752568-977a9b00-94a9-11ea-8cb2-ad75c0a57d65.png)

**Comment by codernik** [comment]
Hi Author,

Can we please find a solution for this issue?

**Comment by ankitsinghmyself** [comment]
same issue, any help

**Comment by olivervogel** [comment]
I have checked this again with the current version 3. Maybe someone can help me, as I can't see a problem at the moment.

As long as the font supports the character, the result is rendered correctly in my opinion.

```php
$text = "इण्टरनेट पर हिन्दी के साधन";
$image->text($text, 100, 100, function ($font) {
    $font->filename('./ArialUnicodeMS.ttf');
    $font->size(32);
});
```

#### Result Image
<img width="377" alt="Bildschirmfoto 2023-12-09 um 10 46 16" src="https://github.com/Intervention/image/assets/884642/75221c6e-3f08-4c30-9395-b2ab19c45446">
