### ISSUE TITLE
Laravel Intervention ImageServiceProvider not found

### ISSUE THREAD

**Issue by mwvitorino** [Intervention/image#941]
Locally the intervention works normal without presenting any problem, locally I use Laragon.

In my online environment, I can not use intervention, I get error of "Class 'Intervention\Image\ImageServiceProvider' not found".

My online environment
-- Composer version 1.8.5
-- Laravel version 5.8
-- PHP version 7.3.0
-- Fileinfo support enable
-- GD Support enabled / Version bundled (2.1.0 compatible)
-- No Imagick PHP extension installed

I followed exactly the installation instructions on the official website.

1. php composer.phar require intervention/image
2. Add config/app.php $providers: Intervention\Image\ImageServiceProvider::class
3. Add config/app.php $alias: 'Image' => Intervention\Image\Facades\Image::class

Below all returns:

```
[waservice@web7081 portal]$ php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"

In ProviderRepository.php line 208:
Class 'Intervention\Image\ImageServiceProvider' not found
```

```
[waservice@web7081 ~]$ php composer.phar dump-autoload
Generated autoload files containing 0 classes
```

```
[waservice@web7081 ~]$ php composer.phar dump-autoload -o
Generated optimized autoload files containing 156 classes
```

```
"require": {
   "php": "^7.1.3",
   "fideloper/proxy": "^4.0",
   "laravel/framework": "5.8.*",
   "laravel/tinker": "^1.0",
   "intervention/image": "dev-master"
},
```

```
[waservice@web7081 ~]$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

```
[waservice@web7081 ~]$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

```
[waservice@web7081 ~]$ php composer.phar require intervention/image
Using version ^2.4 for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by jessikuh** [comment]
I know this is almost a year old, but wondering if you were able to resolve this?

**Comment by AnosKh** [comment]
https://stackoverflow.com/questions/34475855/laravel-5-class-intervention-image-imageserviceprovider-not-found

**Comment by devibrahimov** [comment]
> I know this is almost a year old, but wondering if you were able to resolve this?

yes I'm)

**Comment by mwvitorino** [comment]
> I know this is almost a year old, but wondering if you were able to resolve this?

In my case, it was a grotesque mistake of attention.
My composer.phar was not inside the laravel project folder, but one level up.
I just moved the composer.phar to the laravel folder and installed it again.

Sorry bad eng.

**Comment by Mareteglitch** [comment]
how can someone add \vendor\intervention\image\src\Intervention\Image\ImageServiceProvider.php, mine is missing
