### ISSUE TITLE
Insert SVG failing

### ISSUE THREAD

**Issue by n8udd** [Intervention/image#942]
Firstly I'm using the `imagick` driver.

I am receiving an image from a form submission, and attempting to overlay some info also included in the form before outputting the result.

It is all working fine if I provide my icons as png, but when i try to use the `insert()` with a **.svg** file, the icon doesn't show in the export.

The following is the key parts of my code. As mentioned above, if I change `swim-white.svg` to `swim-white.png` the download works fine.

        $img = Image::make($request->file('fileName'))->orientate();
        $img->insert(public_path() . '/images/icons/swim-white.svg', 'top-left', 80, 295);
        $img->response('jpeg');

        $name = Carbon::now()->toDateTimeString() . '-download.jpeg';

        $headers = [
            'Content-Type' => 'image/jpeg',
            'Content-Disposition' => 'attachment; filename='. $name,
        ];

        return response()->stream(function() use ($img) {
            echo $img;
        }, 200, $headers);

Any idea if it's a limitation of imagick, or am I doing something wrong?

**Comment by olivervogel** [comment]
The SVG format has never been really supported by Intervention Image. The following formats are currently supported:

Since the Imagick can process SVG, it was possible to read files in this format, but Intervention Image focuses more on pixel-based images.
