### ISSUE TITLE
Does not create a directory when saving a file

### ISSUE THREAD

**Issue by dmitrach** [Intervention/image#944]
I get an error when I try to save a file in a non-existent directory.

**New filename**: /home/dios/public/files/image/2019-05-24/thumbnail/JDOM0IvWtFomoHLvRZ4go0Hd5_thumbnail_tiny.jpeg
**Existing path**: /home/dios/public/files/image/2019-05-24/
**Need to create the directory 'resize'**: /home/dios/public/files/image/2019-05-24/resize/

When saving, I have to use additional functions to create directories.

```
$dir = dirname($filename); 

if (! is_dir($dir)) {
       mkdir($dir, 0777, true);
}
```

**Comment by ITwrx** [comment]
yes, i don't think this is a bug. I believe that creating directories is "out of scope" for Intervention. Intervention is only for manipulating images. Manipulating the OS filesystem is up to the user and their framework or OS commands.

**Comment by olivervogel** [comment]
I can understand that automatically creating directories would be very convenient. However, I see the danger of unintentional creation of folders and that the file system becomes cluttered as a result. I prefer to create the folder structure manually.

Alternatively, packages that are specifically created for managing file systems can be used for this task.

#### Abstract example with imaginary filesystem package

```
$encoded = $image->toJpeg();
$filesystem->write('foo/bar/baz/example.jpg', (string) $encoded);
```
