### ISSUE TITLE
Memory error  when the image has big dimensions 

### ISSUE THREAD

**Issue by ahmadzissa** [Intervention/image#948]
Hello,  I have issue    that I get    "apache mmap() failed: [12] Cannot allocate memory"

the php ram is  768MB 

I tried to increase it to 2GB just for testing and it didn't help 

I have 32GB RAM on the server and only  10GB is being used. 

How can I fix this issue ?

It work on small images  but not on big ones  I will get 500 error and  the error above in apache log

**Comment by jarodium** [comment]
Have you tried to use PHP FCGI interface instead of PHP as an Apache Module?
