### ISSUE TITLE
text() vertical align should use font baseline

### ISSUE THREAD

**Issue by maciek-szn** [Intervention/image#949]
The text() function has a valign() option for a text vertical alignment with 'bottom' as a default value. However this doesn't use the font baseline, unlike the imagettftext() function. As a result, the text is positioned differently depending on the character height. Try:

- _aaa_
- _AAA_
- _ÓÓÓ_
- _yyy_

There should be an option to enable the default imagettftext() vertical alignment mechanism.

**Comment by wblommaert** [comment]
@diverpl Have you tried forcing the driver to imagick? This seemed to respect the font baseline in my case. 

I was experiencing a similar issue to yours where, if the line contained no characters with a higher height such as "b", "d", "l", "k", etc, it would not enforce the font baseline to create a proper line height.

**Comment by olivervogel** [comment]
This issue should be resolved as of version 3.
