### ISSUE TITLE
How to use cache image with S3 ?

### ISSUE THREAD

**Issue by hotgeart** [Intervention/image#953]
Hi,

I would like to use Digital Ocean Space (S3 compatible) to store my images. But I've no idea how to make them work with my current intervention setup for the image cache.

I use this at the moment:

`<img src="{{ asset('cache/big-avatar/up/photo/'.$user->avatar) }}" >`

How can I pass an external url ? ex: https://EXAMPLE.ams3.digitaloceanspaces.com/photo/2019/1.jpg

Thx

**Comment by B2rana** [comment]
Any solution for this?
