### ISSUE TITLE
creating my own config/image.php to use imagick actually uses GD when using Facade

### ISSUE THREAD

**Issue by glederer** [Intervention/image#955]
When using the Laravel integration, I create a config/image.php config file to specify that i want to use imagick and not GD. However if I use the Facade approach :

       $img = Image::make(public_path($background));

it will still use GD and not Imagick, but using dependency injection :

	public function __construct(ImageManager $imageManager)
	{
		$this->imageManager = $imageManager;
	}

     ...

     $img = $this->imageManager->make(public_path($background));

then it works fine and imagick is correctly used. There seems to be an integration problem

**Comment by olivervogel** [comment]
I would use a custom service provider for this.
