### ISSUE TITLE
Calculating textwidth

### ISSUE THREAD

**Issue by divdax** [Intervention/image#96]
It would be great to have a function to calculate the textwidth to create a dynamic image which depends on the textwidth.

**Comment by anosim** [comment]
$font = new \Intervention\Image\Font('foo');
$font->valign('top');
$size = $font->getBoxSize();
$image = new \Intervention\Image\Image(null, $size['width'], $size['height']);
$font->applyToImage($image);
$image->save('foo.png');

this is really awesome feature.

please can you tell me how can i use this with Laravel??

**Comment by nifus** [comment]
**imagettfbbox** will help you

**Comment by vinodjoshi** [comment]
How to integrate this in Laravel ?

**Comment by robindirksen1** [comment]
@vinodjoshi you can use it as:

```
$font = new \Intervention\Image\Gd\Font('foo');
$font->valign('top');
$size = $font->getBoxSize();
```
