### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by hutaoseven** [Intervention/image#961]
`echo \Intervention\Image\ImageManagerStatic::canvas(800, 600, '#FFF')->response();`

`vsersion >= 2.4.3`

![11111111](https://user-images.githubusercontent.com/7609067/61847798-8fcc1480-aede-11e9-98b3-5a5f3d930c62.png)

`version <= 2.4.2`

![image](https://user-images.githubusercontent.com/7609067/61849490-10d9da80-aee4-11e9-9c4e-69fe1f19c054.png)

**Comment by nimanima2011** [comment]
not work for me too!

`<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Intervention\Image\Facades\Image;


class GravatarController extends Controller
{
    public function getByID(Request $request, $userID)
    {
        $user = User::findOrFail($userID);

        if(isset($user->gravatar)):

        else:
            $gravatar = $this->createImage((isset($request->size) && !empty($request->size)) ? (intval($request->size)) : (600), $user->first_name);
            return $gravatar->response('png');
        endif;


    }


    public function createImage($size, $string = '')
    {
        define('IMAGE_SIZE', intval($size));
        $backgrounds = ['#F44336', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5', '#2196F3', '#03A9F4', '#00BCD4', '#009688', '#4CAF50', '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800', '#FF5722', '#795548', '#607D8B'];

        $img = Image::canvas(IMAGE_SIZE, IMAGE_SIZE, $backgrounds[rand(0, count($backgrounds) - 1)]);
        // use callback to define details
        $img->text(mb_substr(mb_strtoupper($string), 0, 1, 'UTF8'), IMAGE_SIZE / 2, IMAGE_SIZE / 2, function($font) {
            $font->file(public_path('clint\assets\webfonts\IranSansWebRegular\IRANSansWeb.ttf'));
            $font->size(IMAGE_SIZE);
            $font->color('#fff');
            $font->align('center');
            $font->valign('center');
            $font->angle(0);
        });

        $img->encode('png');

        return $img;

    }
}
`
