### ISSUE TITLE
Unable to read image from path

### ISSUE THREAD

**Issue by zhouwuxiang** [Intervention/image#962]
Unable to read image from path (/tmp/aliyunoss_download/7G4Bx7U7P3JzTnNq_2235490335.tiff). in /data/www/backbone/vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php

$core->readImage($path);
$core->setImageType(defined('\Imagick::IMGTYPE_TRUECOLORALPHA') ? \Imagick::IMGTYPE_TRUECOLORALPHA : \Imagick::IMGTYPE_TRUECOLORMATTE);
} catch (\ImagickException $e) {
throw new \Intervention\Image\Exception\NotReadableException("Unable to read image from path ({$path}).",0,$e);

**Comment by zhouwuxiang** [comment]
Imagick missing plugin?

**Comment by niming175** [comment]
> Unable to read image from path (/tmp/aliyunoss_download/7G4Bx7U7P3JzTnNq_2235490335.tiff). in /data/www/backbone/vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php
> 
> $core->readImage($path);
> $core->setImageType(defined('\Imagick::IMGTYPE_TRUECOLORALPHA') ? \Imagick::IMGTYPE_TRUECOLORALPHA : \Imagick::IMGTYPE_TRUECOLORMATTE);
> } catch (\ImagickException $e) {
> throw new \Intervention\Image\Exception\NotReadableException("Unable to read image from path ({$path}).",0,$e);

你的环境，安装的`imagick`插件可能没有安装图片格式支持，在终端输入`php --ri imagick`, 你会发现支持的格式是0
![image](https://user-images.githubusercontent.com/26159724/114155319-eea41c80-9953-11eb-8a35-9ff5b7742f62.png)

所以你安装图片格式或者格式支持就可以解决
> apk add --update imagemagick-dev imagemagick

or 
>apt-get install -y libmagickwand-dev imagemagick

**Comment by azenkovets** [comment]
Hi there
Where you able to solve it?

**Comment by projct1** [comment]
Have some problem. With GD-driver all is fine with same path to image.

**Comment by olivervogel** [comment]
Please note that not all image formats are always included in the PHP image extensions. It is therefore possible, that the GD library is installed but is configured without Jpeg support or Imagick is available without Tiff support for example.

Please check [gd_info()](https://www.php.net/manual/de/function.gd-info.php) or [Imagick::queryFormats()](https://www.php.net/manual/de/imagick.queryformats) to get a list of the supported image formats. 

It may be necessary to do some configuration for the appropriate image format support.

**Comment by deepvision7** [comment]
Same problem, but for large image only (dimensions): 5760x8640.
Works fine after resize.
`message: Unable to read image from path (/tmp/crm_QgzoxO).
file: /var/www/vhosts/legendcrm.dk/httpdocs/vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php
line: 29
trace: 
#0 /var/www/vhosts/legendcrm.dk/httpdocs/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(344): Intervention\Image\Imagick\Decoder->initFromPath()
`
