### ISSUE TITLE
How can I make a square pic to a circle one

### ISSUE THREAD

**Issue by satisfywithmylife** [Intervention/image#969]
as title describe, the api circle only can fill color, can not fill a pic into a circle

**Comment by KEINOS** [comment]
Do you mean something like this?

- https://en.wikipedia.org/wiki/Mask_(computing)#Image_masks

If so, use the [mask API](http://image.intervention.io/api/mask) with an alpha filled circle, maybe?

<details><summary></summary><div><br>

- Original Image (from [Wikimedia](https://en.wikipedia.org/wiki/Gorgeous_(owarai))):<br> ![sample](https://user-images.githubusercontent.com/11840938/66267302-25ced480-e86a-11e9-8a15-23890afcbfc1.png)
- Mask Image:<br> ![mask](https://user-images.githubusercontent.com/11840938/66267304-26676b00-e86a-11e9-8e5d-4cbf6cbab729.png)
- Result:<br> ![result](https://user-images.githubusercontent.com/11840938/66267303-26676b00-e86a-11e9-8c2f-943feef4ea3c.png)

```php
<?php
require 'vendor/autoload.php';

use Intervention\Image\ImageManagerStatic as Image;

$path_file_picture = './sample.png';
$path_file_mask    = './mask.png';
$path_file_result  = './result.png';

// Create image from given file path or URL.
$pic = Image::make($path_file_picture);

// Resize the image to a height of 200 and constrain aspect ratio (auto width)
$pic->resize(null, 200, function ($constraint) {
    $constraint->aspectRatio();
});

// Create blank white canvas with transparent alpha=0
$mask = Image::canvas($pic->width(), $pic->height(), 'rgba(255, 255, 255, 0)');

// Circle Size and position
$diameter = ($pic->height() > $pic->width()) ? $pic->width() : $pic->height();
$pos_x    = intdiv($pic->width(), 2);
$pos_y    = intdiv($pic->height(), 2);

// Draw black circle with transparent alpha=1
$mask->circle($diameter, $pos_x, $pos_y, function ($draw) {
    $draw->background('rgba(0, 0, 0, 1)');
});
$mask->save('mask.png');

// Masking with alpha channel
$pic->mask($mask, true);

// Save result
$pic->save($path_file_result);
```

</div></details>

**Comment by satisfywithmylife** [comment]
> Do you mean something like this?
> 
> * https://en.wikipedia.org/wiki/Mask_(computing)#Image_masks
> 
> If so, use the [mask API](http://image.intervention.io/api/mask), maybe?
> 
> Sample

**Comment by satisfywithmylife** [comment]
ok i have found the way just like blow:

$imageUrl = '123.png'; // size 40 * 40
$avatarImage = Image::make($imageUrl);
$avatarImage = $avatarImage->getCore();
$avatarImage->roundCorners(20, 20);

**Comment by KEINOS** [comment]
Oh, you meant something like `border-radius` in CSS! Sorry, I mistook your question.
 
Didn't know the `roundCorners()` method though. 👍
