### ISSUE TITLE
image colors changed after saving the image

### ISSUE THREAD

**Issue by dmitriykivkin** [Intervention/image#970]
For some jpg images(see attached 'initial image' file) colors being changed after performing
make -> save sequence. Example code:
```
    protected $imageManager;
    
    public function __construct(.....)
    {
        ....
        $this->imageManager = new ImageManager();
        ....
    }

   public function doSave(){
       $this->imageManager->make($imagePath)->save('/path/to/folder/image.jpg');
   }
```

After performing this operation(with both gd and imagick), it seems  like the image after processing is increased in color saturation(see attached 'result image' file). 
![RESULT_IMAGE](https://user-images.githubusercontent.com/23174952/64965071-ff3dff00-d8a4-11e9-86e4-e4b2ad4866aa.jpg)
![INITIAL_IMAGE](https://user-images.githubusercontent.com/23174952/64965072-ff3dff00-d8a4-11e9-8c2a-5cd1a87e535e.jpg)

**Comment by DanielGilB** [comment]
Intervention applies few parameters by default, like sharpen for example. You can setter this parameters to 0 if you dont want to apply them.

**Comment by mrdernst** [comment]
> Intervention applies few parameters by default, like sharpen for example. You can setter this parameters to 0 if you dont want to apply them.

I have the same problem as @dmitriykivkin.

@DanielGilB can you please give an example where to change these parameters?

**Comment by DanielGilB** [comment]
You can read doc to see all parameters and their default values.

An example is sharpen. Method accepts values between 0 and 100. Default: 10

```php
// create new Intervention Image
$img = Image::make('public/foo.jpg');

// sharpen image
$img->sharpen(15);
```

**Comment by motosha** [comment]
I have the same problem with the saturation 

it should look like this when i create thumbnails:
![sliced-tomato-pieces-in-saladb](https://user-images.githubusercontent.com/49786988/87416948-bc85aa00-c5cf-11ea-9ae2-8d2261969af2.jpg)

but i get this:

![sliced tomato pieces in salad - 640x427](https://user-images.githubusercontent.com/49786988/87417008-d626f180-c5cf-11ea-90fd-67e5116522cf.jpg)


does anyone know what i have to do so that the colors do not lose their saturation? 
If I set the sharpness to 0 it has no effect on the color

**Comment by dmitriykivkin** [comment]
@motosha in my case such an issue occurred only with images based on CMYK color model and after converting to RGB the problem is gone

**Comment by motosha** [comment]
Hello I'm glad that you answer, how is the situation in Venezuela are you
and your family doing well?
Just wanted to say that I understand your situation and I hope that
normality will return to your life soon.

The pictures are not in CMYK they are in RGB I guess the problem is to
target somewhere
here vendor\intervention\image\src\Intervention\Image\Gd\Commands

Best wishes
Salah

>

**Comment by motosha** [comment]
The pictures are not in CMYK they are in RGB

**Comment by motosha** [comment]
I found out that it has to do with the ICC color profiles, but still no
idea how to solve that.

Am Di., 14. Juli 2020 um 21:39 Uhr schrieb Salah Ait Mokhtar <
ontronix87@googlemail.com>:

> Hello I'm glad that you answer, how is the situation in Venezuela are you
> and your family doing well?
> Just wanted to say that I understand your situation and I hope that
> normality will return to your life soon.
>
> The pictures are not in CMYK they are in RGB I guess the problem is to
> target somewhere
> here vendor\intervention\image\src\Intervention\Image\Gd\Commands
>
> Best wishes
> Salah
>
>>

**Comment by defsrisars** [comment]
Hi, I have found out a way to prevent this problem.
Before I used "path" to make a object
for example:

`$image = Image::make($filePath);`

then I got same problem (color is changed)

and I try 

```
$fileContent = file_get_contents($filePath);
$image = Image::make($fileContent);
```

the color is not changed anymore.

I don't know is it be okay with you guys, but You can try it.

p.s I use imagick for driver.

**Comment by dontEatMe** [comment]
#1035 this?

**Comment by romancfischer** [comment]
Same problem here. Any solution?

**Comment by monirulislamccr** [comment]
Same problem, did not found any solution yet

**Comment by marispro** [comment]
> Same problem, did not found any solution yet

Solution is to use "imagick" driver instead of default "gd".

**Comment by olivervogel** [comment]
This seems to be an issue with Version 2 of Intervention Image ignoring color profiles.

Version 3 of Intervention Image [supports color profiles](https://image.intervention.io/v3/basics/colors#color-profiles). But only with the Imagick driver. Unfortunately, it is still not possible to interpret color profiles with the GD library and therefore also not with Intervention Image and the driver for this library.

See https://github.com/Intervention/image/issues/707#issuecomment-1870271306
