### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by DanielGilB** [Intervention/image#973]
Please can you add support to Laravel 6?

**Comment by Lucky-Loek** [comment]
Just curious, what should be supported? This package installs and works fine in Laravel 6, at least in my projects.

**Comment by kickdev** [comment]
You are idiot? Watch this:
https://github.com/Intervention/image/pull/974

**Comment by Lucky-Loek** [comment]
> 
> 
> You are idiot? Watch this:
> #974

Okay thanks for the name calling? Don't really get why that was necessary? As I said, I was just curious since I hadn't encountered any problems and the referenced issue didn't have any Laravel 6 title.

**Comment by nekooee** [comment]
when are you update the package for Laravel 6?

**Comment by pirupius** [comment]
@Lucky-Loek please read through the description. I have also updated the title so that it indicates Laravel 6. #974

**Comment by chescos** [comment]
@pirupius thanks for the pull request! Hope this gets merged soon :)

**Comment by kickdev** [comment]
@pirupius Do not pay attention to such people, he can only put dislikes with his twink

**Comment by olivervogel** [comment]
@kickdev Stop using insulting language!

**Comment by olivervogel** [comment]
Issue should be fixed in 2.5.1 (abbf18d5ab8367f96b3205ca3c89fb2fa598c69e).
