### ISSUE TITLE
How print specific area in image file

### ISSUE THREAD

**Issue by edolfuchs** [Intervention/image#980]
I want to get the specific content of an image. How do I do that?
Something like that?

$ img = Image::make ($ file);
$ img->getContent (400,400) // x, y coordinates

It's possible?

*example.png*

![Example](https://user-images.githubusercontent.com/12100777/67862030-245a9a00-fb00-11e9-904b-7eee066b05da.png)

**Comment by olivervogel** [comment]
I guess [crop()](http://image.intervention.io/api/crop) is what you are looking for.
