### ISSUE TITLE
 exif will disappear after editing

### ISSUE THREAD

**Issue by yoyomule** [Intervention/image#986]
Hello, I used the intervention to edit the image, such as clipping, adding watermark, etc., but after doing these operations, I found that the gps information in the exif will disappear. Is there any way to support the retention of gps information after editing? In addition, currently only the function of reading exif is provided, is it considered to support writing exif?
Thanks.

**Comment by schel4ok** [comment]
I am also interesting in this issue. After picture resize exif data disappears. I need to keep at least `exif('ImageDescription')`
