### ISSUE TITLE
Web site is not working

### ISSUE THREAD

**Issue by myfbone** [Intervention/image#992]
At this github page you refer to the website with documentation (https://image.intervention.io), but it's not working. If I go to https://image.intervention.io/ I will be redirected to login form at https://image.intervention.io/login. If I go to installation documentation I get 404 standard laravel page.

**Comment by fadjriaf** [comment]
Try to open this link (http://image.intervention.io/)
it works..

**Comment by myfbone** [comment]
It works, but it's strange behavior that https redirect to login route. I personally use https everywhere plugin for firefox and it this confused me. Maybe you should consider rework of this behavior. Good luck!
