### ISSUE TITLE
trim(): specify which colors to trim

### ISSUE THREAD

**Issue by rentalhost** [Intervention/image#993]
Currently the first parameter `$base` is a string that could be: `top-left` (default), `bottom-right` or `transparent` as the [doc: trim()](http://image.intervention.io/api/trim).

There some way to trim by color? In my case, I need trim transparent and/or white color, only. Eg.: `trim([ 'transparent', 'white', '#FF0000'])` to trim transparent, white and red. The problem is that first parameter is string.

**Comment by olivervogel** [comment]
The `trim()` function is part of Intervention Image 2, which has reached the end of life status. The successor version 3 unfortunately no longer supports this function.

The reasons for this can be found here: https://github.com/Intervention/image/issues/1239

However, your idea sounds interesting and will be considered in the event of a new integration of `trim()`.
