### ISSUE TITLE
text drop shadow

### ISSUE THREAD

**Issue by Hesesses** [Intervention/image#995]
Would be nice if you could add "drop shadow" effect on texts 👍

**Comment by Proloy-Bhaduri** [comment]
You can simply add shadow like this.......
<pre>
$y = 150;
$imtline = 'This is your text to be inserted';
 $imtimg->text($line, 303, $y+3, function($font){
        $font->file(__DIR__.'/imtfonts/proloybhaduri.ttf');
        $font->size(30);
        $font->color('#000');
        $font->align('center');
        $font->valign('top');
    });
    $imtimg->text($line, 300, $y, function($font){
        $font->file(__DIR__.'/imtfonts/proloybhaduri.ttf');
        $font->size(30);
        $font->color('#fdf6e3');
        $font->align('center');
        $font->valign('top');
    });

</pre>

**Comment by Proloy-Bhaduri** [comment]
You can simply add shadow like this.......
<pre>
$y = 150;
$imtline = 'This is your text to be inserted';
 $imtimg->text($imtline, 303, $y+3, function($font){
        $font->file(__DIR__.'/imtfonts/proloybhaduri.ttf');
        $font->size(30);
        $font->color('#000');
        $font->align('center');
        $font->valign('top');
    });
    $imtimg->text($imtline, 300, $y, function($font){
        $font->file(__DIR__.'/imtfonts/proloybhaduri.ttf');
        $font->size(30);
        $font->color('#fdf6e3');
        $font->align('center');
        $font->valign('top');
    });

</pre>

**Comment by olivervogel** [comment]
Sorry, this will not be part of this package.
