### ISSUE TITLE
Random rotated images or grey background image when I create a picture with other pictures

### ISSUE THREAD

**Issue by danielsum** [Intervention/image#997]
When launching a generation of a lot of A4 pictures. I have randomly some pictures with a grey background or a rotated images (I don't have any script that rotate a picture and the picture is good).

Does anybody have an idea of what might causing this kind of issue randomly ? And how I can fix this bug ?

Here is a sample of kind of manipulations I make : 

    $canva = ImageIntervention::make($imagePath);
    $image = ImageIntervention::make($image2Path);
    $image->crop($w, $h, $x, $y);
    $canva->insert($blockImage);
    $canva->save();

The script works 99% of the times but sometimes I have something like :

![Grey background](https://www.evernote.com/shard/s119/sh/f264f826-7b77-49be-a2b1-5cccc3279d24/7886e192016fbfbf300454f6888b7e15/res/70a29da1-7367-42bc-a0d3-4a84a7f059fa/skitch.png)

And here :

![Rotated picture](https://www.evernote.com/shard/s119/res/13d77999-f68a-4703-9142-a11e7012753d/skitch.png)

**Comment by danielsum** [comment]
Does anyone have this issue ? Here is an exemple of ghosting I have : 

https://www.evernote.com/l/AHfyZPgme3dJvqKxXMzDJ50keIbhkgFvv78

**Comment by nuvalis** [comment]
I have the same issue, does not always happen but has been more frequent lately.

![bbf0fdce-c221-4c03-b178-b8569163c818](https://github.com/Intervention/image/assets/4467675/a227f43e-b707-4614-8d07-7722aa5a2ae4)

Sometimes this is a URL not sure if it is download related or a memory issue.

``` 
public function processListImage(string|MyImage $image): MyImage
{
        if (is_string($image)) {
            $image = Image::make($image);
        }
        $padding = 80 * 2;
        $height = 510;
        $width = 550;

        $image->trim()->resize(
            $width - $padding,
            $height - $padding,
            function ($constraint) {
                $constraint->aspectRatio();
            }
        );

        $canvas = Image::canvas($width, $height, '#ffffff');
        return $canvas->insert($image, 'center');
}
```

**Comment by olivervogel** [comment]
Unfortunately, I can't say exactly how the problem occurs. However, I suspect it has something to do with the [memory settings](https://www.php.net/manual/en/ini.core.php#ini.sect.resource-limits) of the PHP installation. PHP eventually runs out of memory halfway through. However, this is just a guess.
