### ISSUE TITLE
image source not readable

### ISSUE THREAD

**Issue by nattive** [Intervention/image#998]
Please, guys, I'm yet to fish out the problem in my laravel 6 app.

Keeps saying image source not readable. I have followed all the solutions I find online to avail.

Please check and help me. Thanks 

https://stackoverflow.com/q/59622089/10535517

**Comment by AlvinQinwen** [comment]
I have the same problem

**Comment by nattive** [comment]
If you have access to your Terminal. Run 
`php artisan storage:link`

Or in your web.php, write a function that returns Artisan::call('storage:link')

Or `ln -s /path/to/laravel/storage/app/public`
